import React from 'react';
(globalThis as any).React=React;
import assert from 'node:assert/strict';
import {renderToStaticMarkup} from 'react-dom/server';
import App from '../src/App';
import {defaults} from '../src/content/defaults';
import {expandeer,datumSleutel} from '../src/agenda/model';
import type {AgendaBron} from '../src/content/types';
const series:AgendaBron={id:'series',soort:'activiteit',titel:'Inloopochtend',categorie:'Inloop',omschrijving:'',img:null,datum:'2026-10-01',begintijd:'10:00',eindtijd:'12:00',heleDag:false,herhaling:'wekelijks',overslaan:['2026-12-24','2026-12-31'],aanmelden:false};
const special:AgendaBron={...series,id:'special',titel:'Inloop met activiteit',herhaling:'eenmalig',datum:'2026-10-29',vervangtReeks:'series'};
const from=new Date(2026,9,1),to=new Date(2027,0,8);
const expanded=expandeer([series,special],from,to);
assert.equal(expanded.filter(x=>datumSleutel(x.start)==='2026-10-29').length,1);
assert.equal(expanded.find(x=>datumSleutel(x.start)==='2026-10-29')?.bronId,'special');
assert(expanded.some(x=>datumSleutel(x.start)==='2026-10-08'));
assert(expanded.every(x=>x.start.getDay()===4));
assert(!expanded.some(x=>['2026-12-24','2026-12-31'].includes(datumSleutel(x.start))));
assert.equal(expandeer([series],from,to).find(x=>datumSleutel(x.start)==='2026-10-29')?.bronId,'series');
assert.equal(expandeer([series,{...special,vervangtReeks:undefined}],from,to).filter(x=>datumSleutel(x.start)==='2026-10-29').length,2);
assert.equal(expandeer([{...series,herhaalTot:'2026-10-15'}],from,to).length,3);
assert(expandeer([{...series,datum:'2020-10-01',herhaling:'maandelijks'}],from,to).length>=3,'Long-running monthly series still works');
const render=(pad:string)=>renderToStaticMarkup(<App start={{pad,inhoud:{...defaults,pages:[{path:'/privacy',privacyFile:{asset:{_ref:'file-test-pdf'}}}]},voorbeeld:false,nu:from.getTime()}}/>);
assert.equal((render('/').match(/class="sponsor"/g)||[]).length,6);
assert.equal((render('/over-ons/onze-sponsors').match(/class="sponsor"/g)||[]).length,defaults.sponsoren.length);
const contact=render('/contact');assert(contact.includes('id="privacyverklaring"'));assert(contact.includes('90 dagen'));assert(contact.includes('test.pdf?dl=privacyverklaring-toon-over-leven.pdf'));assert.equal((contact.match(/<h1/g)||[]).length,1);
console.log('Six homepage logos/full sponsor list; full contact privacy and PDF; weekly dates, special replacements, cancellations, restoring regular dates, end date and long-running monthly recurrence passed. No submissions.');

const pics=[{klein:'a',breed:'a',ratio:1},{klein:'b',breed:'b',ratio:1},{klein:'c',breed:'c',ratio:1}];
const photoSeries={...series,img:pics[0],reeksFotos:pics.slice(1)} as AgendaBron;
const varied=expandeer([photoSeries],from,to);
assert.equal(new Set(varied.slice(0,3).map(e=>JSON.stringify(e.img))).size,3);
const later=expandeer([photoSeries],new Date(2026,9,15),to);
assert.deepEqual(later[0].img,varied.find(e=>datumSleutel(e.start)==='2026-10-15')?.img,'Photos stable across windows');
const cancelled=expandeer([{...photoSeries,overslaan:['2026-10-08']}],from,to);
assert.deepEqual(cancelled.find(e=>datumSleutel(e.start)==='2026-10-15')?.img,later[0].img,'Cancellation does not rotate remaining photos');
console.log('CMS series photo rotation stable across view windows, cancellations and daylight-saving changes.');
