/* GENERATED by scripts/i18n-strings.mjs. Do not hand-edit.
   it/housing.ts is a 1:1 structural mirror of en/housing.ts; only leaf strings
   differ. To change structure, change English and re-run the build. */
import type { SectionContent } from '../types';

export const housing: SectionContent = {
    title: 'Casa per expat nei Paesi Bassi',
    metaTitle: 'Casa per expat nei Paesi Bassi | E & I Expat Services',
    metaDescription: 'Assistenza personale per la casa agli expat nei Paesi Bassi: ricerca, visite, revisione del contratto di locazione e rapporti con il proprietario, con focus su Rotterdam e la regione portuale.',
    eyebrow: 'Casa',
    intro: [
      'Il mercato olandese degli affitti corre e premia chi è preparato. I buoni appartamenti vengono pubblicati la mattina e spariscono la sera, e i proprietari scelgono inquilini che rispondono in fretta con un fascicolo completo. È esattamente qui che entriamo noi. Teniamo d\'occhio il mercato per lei, reagiamo nel giro di ore e prepariamo il suo dossier così che, quando compare la casa giusta, lei sia il candidato a cui un proprietario dice di sì.',
      'Il nostro territorio è Rotterdam e la più ampia regione portuale, dal centro città fino a Europoort e alla Maasvlakte, anche se cerchiamo in tutti i Paesi Bassi. Non viene mai mandato in giro da solo con un elenco di link. Selezioniamo, partecipiamo alle visite con lei, leggiamo ogni contratto prima della firma e gestiamo il dialogo con il proprietario dal primo messaggio alla consegna delle chiavi.',
    ],
    image: '/images/canal-colour.jpg',
    imageAlt: 'Case colorate sul canale riflesse nell\'acqua di una città olandese',
    services: [
      {
        slug: 'housing-search-assistance-netherlands',
        menuLabel: 'Ricerca della casa',
        title: 'Assistenza nella ricerca della casa nei Paesi Bassi',
        metaTitle: 'Assistenza nella ricerca della casa nei Paesi Bassi | E & I Expat Services',
        metaDescription: 'Ricerca personale della casa per expat nei Paesi Bassi. Selezioniamo gli immobili, rispondiamo agli annunci nel giro di ore e prepariamo il suo fascicolo di locazione perché i proprietari la prendano sul serio.',
        eyebrow: 'Ricerca della casa',
        intro: [
          'Cercare un affitto nei Paesi Bassi dall\'estero è una gara che non si può vincere da soli. Gli annunci compaiono e spariscono in un giorno, le agenzie danno priorità ai fascicoli completi e molte belle case non vengono mai pubblicizzate. Conduciamo la ricerca per lei, sul posto, in olandese e con la rapidità che il mercato pretende.',
          'Lei ci dice come vuole vivere, il suo budget, il suo tragitto, se le serve un giardino per il cane o una scuola dietro l\'angolo. Traduciamo tutto questo in una ricerca mirata, filtriamo il rumore e le portiamo solo case che valgono il suo tempo. Le domande nel frattempo non aspettano gli orari d\'ufficio; ci raggiunge su una linea WhatsApp personale, giorno e notte.',
        ],
        cardText: 'Cerchiamo, selezioniamo e rispondiamo agli annunci prima che spariscano.',
        forWho: {
          title: 'A chi si rivolge',
          items: [
            'Professionisti che si trasferiscono nei Paesi Bassi e non possono cercare dall\'estero',
            'Famiglie che hanno bisogno della casa giusta nel bacino scolastico giusto, non di una casa qualsiasi',
            'Expat che cercano da settimane senza una sola offerta accettata',
            'Datori di lavoro che vogliono una risorsa già alloggiata prima della data di inizio',
          ],
        },
        included: {
          title: 'Cosa è incluso',
          blocks: [
            {
              title: 'Colloquio e profilo di ricerca',
              text: 'Una conversazione vera su come vive, poi un profilo di ricerca preciso che copre budget, quartieri, tragitto e requisiti irrinunciabili.',
            },
            {
              title: 'Ricerca attiva quotidiana',
              text: 'Monitoriamo ogni giorno le principali piattaforme e la nostra rete di agenzie locali e rispondiamo agli annunci compatibili nel giro di ore.',
            },
            {
              title: 'Preparazione del dossier di locazione',
              text: 'Raccogliamo buste paga, referenze e documenti che i proprietari olandesi si aspettano, nel formato in cui le agenzie vogliono vederli.',
            },
            {
              title: 'Selezione con pareri onesti',
              text: 'Per ogni casa candidata riceve il nostro parere schietto sulla strada, sull\'edificio, sul prezzo e sul proprietario, non una copia dell\'annuncio.',
            },
            {
              title: 'Assistenza su offerta e trattativa',
              text: 'Quando vuole una casa ci muoviamo subito: l\'offerta, le condizioni e i solleciti all\'agenzia li gestiamo noi per lei.',
            },
          ],
        },
        process: {
          title: 'Come funziona',
          steps: [
            {
              title: 'Colloquio iniziale',
              text: 'Mappiamo desideri, budget e tempi e concordiamo i quartieri adatti alla sua vita.',
            },
            {
              title: 'Ricerca e selezione',
              text: 'Cacciamo ogni giorno e le inviamo case che vale la pena visitare, con la nostra valutazione onesta allegata.',
            },
            {
              title: 'Visita e decisione',
              text: 'Organizziamo le visite, vi partecipiamo dove possibile e la aiutiamo a soppesare le opzioni in fretta.',
            },
            {
              title: 'Assicurarsi la casa',
              text: 'Presentiamo il suo fascicolo, negoziamo le condizioni e restiamo coinvolti finché le chiavi non sono in mano sua.',
            },
          ],
        },
        fees: {
          title: 'Onorario per una ricerca della casa',
          kind: 'fixed',
          amount: 'Investimento da 1.750 €',
          includes: [
            'Un profilo scritto e una selezione costruita su come vive davvero',
            'Accesso agli immobili tramite la nostra rete di agenzie, comprese case mai pubblicizzate',
            'Visite organizzate e svolte con lei o per suo conto',
            'Trattativa su affitto e condizioni, e contratto verificato prima della firma',
          ],
        },
        note: 'Su una cosa siamo espliciti: nessuna consulenza onesta può garantirle una casa specifica in questo mercato. Ciò che possiamo promettere è rapidità, un fascicolo completo e una solida rete locale, che è ciò che fa vincere le case. Il prezzo dipende dall\'area di ricerca e dai tempi e viene confermato durante il colloquio.',
        conditions: {
          title: 'Che cosa pretende il mercato olandese degli affitti',
          intro: 'È il mercato a decidere più del suo budget. Sono queste le condizioni su cui costruiamo il suo fascicolo.',
          items: [
            'La maggior parte dei proprietari richiede un reddito lordo pari a tre o quattro volte l\'affitto mensile, documentato da contratto e buste paga recenti.',
            'Senza una storia reddituale olandese, si aspetti che le vengano chiesti una dichiarazione del datore di lavoro, una garanzia bancaria o una cauzione più alta.',
            'Le cauzioni sono limitate a due mensilità di affitto base per i contratti firmati dal 1° luglio 2023.',
            'Il BSN non serve per firmare un contratto, ma serve per iscriversi a quell\'indirizzo, e l\'iscrizione sblocca quasi tutto il resto.',
            'Lavoriamo a Rotterdam, a Europoort e nella più ampia regione portuale. Oltre quel raggio lo diciamo invece di accettare l\'incarico.',
            'Agiamo per lei e mai per il proprietario, e non prendiamo provvigioni da nessuna delle due parti.',
          ],
        },
        details: {
          title: 'Come funziona davvero la ricerca',
          items: [
            {
              q: 'Quanto tempo ci vuole per trovare casa?',
              a: 'Nella regione di Rotterdam, da quattro a otto settimane è realistico nel segmento alto e arredato, e di più sotto i 1.500 euro al mese dove la concorrenza è più feroce. Gli immobili richiesti spariscono entro quarantotto ore, quindi la rapidità di risposta conta più dell\'ampiezza della ricerca.',
            },
            {
              q: 'Potete visitare gli immobili prima del mio arrivo?',
              a: 'Sì, e la maggior parte dei clienti inizia così. Partecipiamo per suo conto e le inviamo un verdetto scritto con video lo stesso giorno, sufficiente per decidere dall\'estero senza scommettere sulle fotografie.',
            },
            {
              q: 'Contratto a termine o a tempo indeterminato?',
              a: 'Dal 1° luglio 2024 la maggior parte delle nuove locazioni abitative deve essere a tempo indeterminato, con contratti a termine ammessi solo in situazioni definite, come l\'assenza temporanea del proprietario. La modifica gioca a suo favore, e verifichiamo a quale regime appartiene il suo contratto prima che firmi.',
            },
            {
              q: 'Arredato, non arredato o una via di mezzo?',
              a: 'Gli annunci olandesi distinguono kaal, a volte senza pavimenti né lampadari, gestoffeerd con pavimenti e tende, e gemeubileerd completamente arredato. La differenza può valere diverse migliaia di euro all\'arrivo, ed è il dettaglio che i nuovi arrivati si perdono più spesso in un annuncio.',
            },
          ],
        },
        faq: {
          title: 'Domande frequenti',
          items: [
            {
              q: 'Potete trovare case che accettino animali?',
              a: 'Sì, anche se restringe il campo. Molti proprietari olandesi sono titubanti sugli animali, quindi lo poniamo subito, puntiamo a proprietari pet-friendly e presentiamo il suo animale come si deve nel dossier invece di lasciare che emerga come sorpresa.',
            },
            {
              q: 'Potrò iscrivermi all\'anagrafe (BSN) nella casa che trovate?',
              a: 'Seguiamo solo case in cui l\'iscrizione al comune è consentita. L\'iscrizione è indispensabile per BSN, assicurazione sanitaria e conto bancario, quindi la verifichiamo con il proprietario prima che lei si impegni.',
            },
            {
              q: 'Conviene affittare arredato o non arredato?',
              a: 'L\'arredato costa di più al mese ma le permette di arrivare con due valigie. Il non arredato, che nei Paesi Bassi può significare senza pavimenti né lampadari, conviene per permanenze di diversi anni. La aiutiamo a fare i conti per la sua situazione.',
            },
          ],
        },
        cta: {
          title: 'Inizi oggi la sua ricerca della casa',
          text: 'Ci dica che casa sta cercando e le diremo onestamente che cosa è realistico, poi andremo a trovarla.',
          label: 'Inizia la mia ricerca',
        },
        form: 'relocation',
        image: '/images/housing-search.jpg?v=20260731',
        imageAlt: 'Consulente che presenta opzioni immobiliari a una coppia',
        image2: '/images/housing-interior.jpg?v=20260731',
        image2Alt: 'Soggiorno di un appartamento in una casa olandese sul canale',
      },
      {
        slug: 'housing-for-expats-rotterdam',
        menuLabel: 'Case per expat a Rotterdam',
        title: 'Case per expat a Rotterdam',
        metaTitle: 'Case per expat a Rotterdam | E & I Expat Services',
        metaDescription: 'Trovi casa a Rotterdam con uno specialista locale. Consigli sui quartieri, visite e assistenza contrattuale per expat che si trasferiscono a Rotterdam e nella regione portuale.',
        eyebrow: 'Rotterdam',
        intro: [
          'Rotterdam non è una città in cui scegliere il quartiere da lontano. Kralingen non somiglia per nulla a Katendrecht, Hillegersberg è un mondo diverso dal Kop van Zuid, e la scelta giusta dipende dal suo tragitto, dalla sua famiglia e da come le piace passare il sabato. Conosciamo personalmente queste strade e la abbiniamo alla parte di città in cui starà davvero bene.',
          'Rotterdam e il suo corridoio portuale fino a Europoort e alla Maasvlakte sono la nostra specialità; è la regione in cui viviamo, lavoriamo e abbiamo i rapporti più solidi con i proprietari. Quel peso locale conta in un mercato dove le case migliori vanno al fascicolo che arriva per primo con un nome affidabile alle spalle.',
        ],
        cardText: 'Conoscenza locale di ogni quartiere di Rotterdam e la rete per farla entrare.',
        forWho: {
          title: 'A chi si rivolge',
          items: [
            'Internazionali che iniziano a lavorare a Rotterdam o nell\'area portuale',
            'Famiglie che confrontano quartieri, scuole e tragitti',
            'Professionisti a Europoort o alla Maasvlakte che vogliono vivere bene restando vicini al lavoro',
            'Coppie che vogliono l\'energia della città senza pagare troppo per la strada sbagliata',
          ],
        },
        included: {
          title: 'Cosa è incluso',
          blocks: [
            {
              title: 'Abbinamento del quartiere',
              text: 'Un giro onesto fra le sue opzioni realistiche, da Kralingen e Blijdorp a Nesselande e ai comuni circostanti, abbinate al suo budget e al suo tragitto.',
            },
            {
              title: 'Ricerca mirata su Rotterdam',
              text: 'Monitoraggio quotidiano degli annunci di Rotterdam più contatto diretto con agenzie locali che spesso ci mostrano case prima che vadano online.',
            },
            {
              title: 'Visite con un locale al suo fianco',
              text: 'Fissiamo le visite e vi partecipiamo, e le facciamo notare ciò che un nuovo arrivato non può vedere: la strada dopo il tramonto, la piena del mercato del venerdì, la situazione dei vicini.',
            },
            {
              title: 'Gestione di fascicolo, offerta e contratto',
              text: 'Il suo dossier, la sua offerta e la revisione del contratto di locazione sono gestiti da noi, in olandese, alla velocità di Rotterdam.',
            },
          ],
        },
        process: {
          title: 'Come funziona',
          steps: [
            {
              title: 'Colloquio su Rotterdam',
              text: 'Parliamo del suo luogo di lavoro, del suo stile di vita e del budget e restringiamo la città ai quartieri adatti.',
            },
            {
              title: 'Cercare e visitare',
              text: 'Le portiamo un flusso di case realistiche e visitiamo insieme quelle promettenti.',
            },
            {
              title: 'Trasferirsi',
              text: 'Offerta, contratto e consegna sono gestiti per lei, verbale di sopralluogo del giorno delle chiavi compreso.',
            },
          ],
        },
        fees: {
          title: 'Quanto costa l\'assistenza per la casa a Rotterdam',
          kind: 'tailored',
          amount: 'Proposta su misura',
          amountNote: 'Rotterdam va dal singolo professionista che cerca un appartamento in città alla famiglia che ha bisogno di spazio, di un giardino e del percorso scolastico giusto. Dopo una prima conversazione riceve un preventivo fisso esattamente per l\'ambito che le serve.',
          includes: [
            'Un profilo di ricerca costruito su tragitto, budget e composizione del nucleo',
            'Consigli sui quartieri da chi conosce la città strada per strada',
            'Visite organizzate, accompagnate e valutate con onestà',
            'Revisione del contratto e consegna prima che firmi qualsiasi cosa',
          ],
        },
        conditions: {
          title: 'Prima di scegliere un quartiere',
          intro: 'Rotterdam premia chi sceglie l\'indirizzo attorno alla propria vita invece che attorno a una cartina.',
          items: [
            'Gli affitti del libero mercato partono di norma da circa 1.200 euro per un bilocale e 1.800 euro per un appartamento familiare, di più sul Kop van Zuid e in centro.',
            'L\'edilizia sociale è di fatto inaccessibile agli expat. Limiti di reddito e liste d\'attesa pluriennali la mettono fuori portata.',
            'L\'iscrizione all\'indirizzo è possibile solo dove il proprietario la consente, e alcuni proprietari di short-stay non lo fanno.',
            'I permessi di sosta sono rilasciati per nucleo familiare e per zona, e nei quartieri centrali la lista d\'attesa può durare mesi.',
            'Le case con etichetta energetica E, F o G comportano costi di gestione più alti e un affitto massimo consentito più basso secondo il sistema a punti.',
            'Copriamo Rotterdam e i comuni circostanti, fra cui Schiedam, Capelle, Barendrecht e il corridoio di Europoort.',
          ],
        },
        details: {
          title: 'Rotterdam, quartiere per quartiere',
          items: [
            {
              q: 'Dove vive la maggior parte dei professionisti internazionali?',
              a: 'Kralingen per spazio, verde e vicinanza alle scuole internazionali. Kop van Zuid e Wilhelminapier per la vista sul fiume e le nuove costruzioni. Centrum e Cool per muoversi a piedi. Hillegersberg per famiglie che vogliono un\'atmosfera di paese dentro la città. Quale sia giusto dipende molto più dal suo tragitto e dai suoi figli che da qualsiasi classifica.',
            },
            {
              q: 'Quanto dura il tragitto verso Europoort o la Maasvlakte?',
              a: 'Dal centro di Rotterdam, dai quarantacinque ai settanta minuti in auto a seconda del varco e del turno. Da Hoogvliet, Spijkenisse o Brielle scende a venti o trenta. Se lavora ai terminal, scegliere il quartiere prima di verificare il tragitto è l\'errore più costoso a disposizione.',
            },
            {
              q: 'Ci sono scuole internazionali nelle vicinanze?',
              a: 'Rotterdam ha diverse opzioni internazionali e bilingui, la maggior parte concentrate a Kralingen e nel sud della città, e i posti sono limitati. Le famiglie di norma devono scegliere prima la scuola e poi il quartiere, quindi lo pianifichiamo in quell\'ordine.',
            },
            {
              q: 'Conviene comprare invece di affittare?',
              a: 'A volte, ma raramente nel primo anno. Le banche olandesi vogliono una storia lavorativa e un permesso con un orizzonte ragionevole, e i costi di transazione rendono un acquisto da cui potrebbe uscire entro due anni un esperimento costoso. Le diremo onestamente quando comprare è la mossa migliore.',
            },
          ],
        },
        faq: {
          title: 'Domande frequenti',
          items: [
            {
              q: 'Quali quartieri di Rotterdam sono i migliori per famiglie expat?',
              a: 'Hillegersberg, Kralingen e i sobborghi con giardino vanno bene per spazio, parchi e scuole internazionali, mentre comuni come Capelle e Barendrecht offrono più casa per lo stesso denaro. La risposta giusta dipende dalla scelta della scuola e dal tragitto, ed è esattamente a questo che serve il colloquio.',
            },
            {
              q: 'Rotterdam è più economica di Amsterdam?',
              a: 'In generale sì, ottiene sensibilmente più spazio per lo stesso affitto. Ma Rotterdam si è stretta in fretta, e i quartieri più richiesti si muovono ormai alla stessa velocità della capitale. Anche qui contano la rapidità e un fascicolo completo.',
            },
            {
              q: 'Potete aiutarmi se lavoro al porto ma voglio vivere in città?',
              a: 'È una delle richieste che riceviamo più spesso. Pianifichiamo la ricerca attorno al suo tragitto reale, compresi gli orari dei turni, quando il traffico verso Europoort o la Maasvlakte si comporta in modo molto diverso.',
            },
          ],
        },
        cta: {
          title: 'Trovi il suo posto a Rotterdam',
          text: 'Ci racconti il suo trasferimento e le diremo dove in questa città è al suo posto, poi la aiuteremo a ottenere le chiavi.',
          label: 'Parla con un locale di Rotterdam',
        },
        form: 'relocation',
        image: '/images/rotterdam-housing.jpg?v=20260731',
        imageAlt: 'Palazzo residenziale sul lungofiume di Rotterdam al tramonto',
        image2: '/images/rotterdam-evening.jpg?v=20260731',
        image2Alt: 'Lo skyline di Rotterdam in serata',
      },
      {
        slug: 'viewing-assistance-netherlands',
        menuLabel: 'Assistenza alle visite',
        title: 'Assistenza alle visite nei Paesi Bassi',
        metaTitle: 'Assistenza alle visite nei Paesi Bassi | E & I Expat Services',
        metaDescription: 'Non può partecipare alle visite nei Paesi Bassi? Visitiamo le case per lei o con lei, con video-tour, valutazioni oneste e follow-up con l\'agenzia in giornata.',
        eyebrow: 'Visite',
        intro: [
          'Un annuncio le dice ciò che un proprietario vuole farle sapere. Una visita le dice la verità: il rumore del traffico nell\'ora di punta, l\'angolo umido dietro l\'armadio, l\'odore nella tromba delle scale. Quando è ancora all\'estero, o lavora tutto il giorno, partecipare alle visite è la parte più difficile di una ricerca di casa olandese, e saltarle è il modo in cui nascono gli errori costosi.',
          'Quindi ci andiamo noi. Johanna partecipa di persona alle visite, attraversa ogni stanza con occhio critico e la chiama dal soggiorno perché possa guardarsi intorno in diretta e fare domande sul momento. È la cosa più vicina a esserci di persona, sostenuta da chi ha visto centinaia di affitti olandesi e sa esattamente che cosa controllare.',
        ],
        cardText: 'Partecipiamo alle visite per lei o con lei e riferiamo ciò che l\'annuncio non dice.',
        forWho: {
          title: 'A chi si rivolge',
          items: [
            'Expat ancora all\'estero che non possono volare qui per una visita di martedì pomeriggio',
            'Professionisti impegnati che non possono lasciare il lavoro ogni volta che esce una casa',
            'Inquilini che vogliono un secondo paio di occhi esperti prima di impegnarsi',
            'Chiunque sia già rimasto scottato da foto più belle della realtà',
          ],
        },
        included: {
          title: 'Cosa è incluso',
          blocks: [
            {
              title: 'Fissaggio e conferma',
              text: 'Contattiamo l\'agenzia, assicuriamo in fretta uno slot e gestiamo ogni messaggio attorno all\'appuntamento in olandese.',
            },
            {
              title: 'Sopralluogo di persona',
              text: 'Controlliamo le cose che le costeranno soldi più avanti: umidità, ventilazione, isolamento, pressione dell\'acqua, stato di cucina e bagno e quadro elettrico.',
            },
            {
              title: 'Video-tour in diretta',
              text: 'Una videochiamata dall\'immobile così che veda ogni stanza in tempo reale e possa fare domande all\'agenzia tramite noi.',
            },
            {
              title: 'Verdetto scritto e onesto',
              text: 'Nel giro di poche ore riceve foto, appunti e una raccomandazione chiara: prendila, tratta, oppure lascia perdere.',
            },
            {
              title: 'Follow-up in giornata',
              text: 'Se vuole la casa, lo diciamo subito all\'agenzia e avviamo la sua candidatura prima del visitatore successivo.',
            },
          ],
        },
        process: {
          title: 'Come funziona',
          steps: [
            {
              title: 'Ci mandi l\'annuncio',
              text: 'Ci inoltri qualsiasi casa voglia far valutare, che l\'abbiamo trovata noi o lei.',
            },
            {
              title: 'La visitiamo',
              text: 'Partecipiamo, ispezioniamo e la videochiamiamo dall\'interno dell\'immobile.',
            },
            {
              title: 'Lei decide, noi agiamo',
              text: 'Con il nostro verdetto in mano decide, e noi gestiamo il follow-up con l\'agenzia lo stesso giorno.',
            },
          ],
        },
        fees: {
          title: 'Onorario per l\'assistenza alle visite',
          kind: 'fixed',
          amount: '295 € a visita',
          includes: [
            'Presenza alla visita, di persona, con le domande che un proprietario si aspetta',
            'Un verdetto scritto e onesto sull\'immobile, compreso ciò che noi non accetteremmo',
            'Verifiche su livello dell\'affitto, spese accessorie e sistema a punti',
            'Riscontro immediato così che possa decidere prima del candidato successivo',
          ],
        },
        note: 'L\'assistenza alle visite si può prenotare da sola o come parte di una ricerca completa della casa. Gli onorari dipendono dalla località e dalla frequenza e vengono confermati durante il colloquio.',
        conditions: {
          title: 'Come funziona l\'assistenza alle visite',
          intro: 'Un visitatore indipendente vale solo se è davvero indipendente. Sono queste le condizioni con cui lavoriamo.',
          items: [
            'Partecipiamo in tutta Rotterdam e nella regione portuale. Visite più lontane sono possibili su accordo, in base al tempo di viaggio.',
            'Gli annunci molto richiesti vengono spesso fissati entro ventiquattro ore, quindi ci mandi il link appena lo vede.',
            'Riferiamo ciò che vediamo. Negoziare l\'affitto è un servizio a parte, incluso nell\'assistenza su offerta e contratto.',
            'Un video-tour in diretta richiede un segnale mobile utilizzabile, che seminterrati e case sul canale dai muri spessi non sempre offrono.',
            'Non possiamo entrare senza la presenza dell\'agenzia o del proprietario, e alcune agenzie rifiutano del tutto le visite di terzi.',
            'Il nostro verdetto scritto è onesto. Se un immobile non fa per lei glielo diciamo, anche se ci costa il lavoro successivo.',
          ],
        },
        details: {
          title: 'Che cosa controlliamo che le fotografie nascondono',
          items: [
            {
              q: 'Che cosa ispezionate in concreto?',
              a: 'Umidità e ventilazione, qualità dei serramenti rispetto all\'etichetta energetica dichiarata, rumore da traffico, tram, vicini e vita notturna nell\'orario reale della giornata, pressione dell\'acqua, età e stato della caldaia, ricezione mobile e internet, spazi di deposito, parcheggio per le biciclette, e se l\'ingresso condominiale è curato o silenziosamente trascurato.',
            },
            {
              q: 'Potete visitare mentre sono ancora all\'estero?',
              a: 'Sì, e la maggior parte dei nostri clienti inizia così. Riceve un video-tour, fotografie delle cose che gli annunci non mostrano mai e un verdetto scritto lo stesso giorno, sufficiente per decidere con sicurezza da un altro continente.',
            },
            {
              q: 'Mi direte di non prenderla?',
              a: 'Spesso. Tutto il valore di un visitatore indipendente sta nel fatto che non abbiamo alcun interesse a farle firmare. Circa un terzo degli immobili che visitiamo riceve una chiara raccomandazione contraria.',
            },
            {
              q: 'Con quanta rapidità potete partecipare?',
              a: 'Di norma entro ventiquattro o quarantotto ore, e lo stesso giorno quando l\'immobile lo merita. In questo mercato una visita lenta è semplicemente un immobile perso.',
            },
          ],
        },
        faq: {
          title: 'Domande frequenti',
          items: [
            {
              q: 'Che cosa controllate che io mi perderei in video?',
              a: 'Le cose che una telecamera nasconde: odori, umidità, rumore, pressione dell\'acqua, come si sentono i vicini attraverso il muro e che aria si respira in strada. Leggiamo inoltre con occhio critico l\'etichetta energetica e le spese accessorie, che i nuovi arrivati tendono a trascurare.',
            },
            {
              q: 'Il proprietario mi consentirà di iscrivermi a quell\'indirizzo?',
              a: 'Lo chiediamo a ogni visita, mettendolo agli atti. Una casa in cui non ci si può iscrivere è inutile per il suo BSN e per l\'assicurazione, quindi la trattiamo come un elemento decisivo, salvo sua diversa indicazione.',
            },
            {
              q: 'L\'annuncio dice arredato. Che cosa dovrei aspettarmi alla visita?',
              a: 'Arredato nei Paesi Bassi va da pronto come un hotel a un divano spoglio e un materasso. Fotografiamo esattamente ciò che è incluso e facciamo confermare l\'inventario per iscritto prima che lei firmi qualsiasi cosa.',
            },
          ],
        },
        cta: {
          title: 'Non giudichi mai più una casa dalle sue foto',
          text: 'Ci mandi il prossimo annuncio che le colpisce l\'occhio e ci saremo dentro prima del fine settimana.',
          label: 'Prenota una visita',
        },
        form: 'relocation',
        image: '/images/viewing-couple.jpg',
        imageAlt: 'Agente immobiliare che mostra a una coppia un luminoso appartamento olandese',
        image2: '/images/housing-viewing.jpg',
        image2Alt: 'Visita a un appartamento con un consulente presente',
      },
      {
        slug: 'rental-contract-review-netherlands',
        menuLabel: 'Contratti di locazione',
        title: 'Revisione del contratto di locazione nei Paesi Bassi',
        metaTitle: 'Revisione del contratto di locazione nei Paesi Bassi | E & I Expat Services',
        metaDescription: 'Faccia esaminare il suo contratto di locazione olandese prima di firmare. Segnaliamo le clausole illegittime, verifichiamo cauzioni e spese accessorie e le spieghiamo i suoi diritti di inquilino in parole chiare.',
        eyebrow: 'Contratti',
        intro: [
          'I contratti di locazione olandesi sono scritti in linguaggio giuridico olandese, e certi proprietari contano sul fatto che gli expat non li leggano. Cauzioni sopra la soglia di legge, spese accessorie che coprono in silenzio ciò che non dovrebbero, contratti temporanei travestiti da permanenti, clausole penali che non reggerebbero mai davanti a un giudice. Dovrebbe sapere tutto questo prima di firmare, non dopo.',
          'Esaminiamo il suo contratto riga per riga e le diamo un riassunto in parole chiare di ciò a cui sta aderendo, di ciò che è standard, di ciò che è negoziabile e di ciò che semplicemente non è ammesso dal diritto olandese delle locazioni. La tutela dell\'inquilino nei Paesi Bassi è fra le più forti d\'Europa, ma solo per gli inquilini che conoscono i propri diritti.',
        ],
        cardText: 'Revisione del contratto riga per riga in parole chiare prima che firmi qualsiasi cosa.',
        forWho: {
          title: 'A chi si rivolge',
          items: [
            'Expat in procinto di firmare il primo contratto di locazione olandese',
            'Inquilini a cui vengono chiesti cauzioni, oneri o clausole inusuali',
            'Affittuari con contratti a termine incerti su che cosa succeda alla scadenza',
            'Chiunque venga messo sotto pressione dal proprietario per firmare oggi',
          ],
        },
        included: {
          title: 'Cosa è incluso',
          blocks: [
            {
              title: 'Revisione completa del contratto',
              text: 'Ogni clausola letta nell\'originale olandese, confrontata con il diritto delle locazioni vigente e riassunta per lei in un inglese chiaro.',
            },
            {
              title: 'Verifica di cauzione e costi',
              text: 'Verifichiamo cauzione, spese accessorie, oneri di agenzia e livello dell\'affitto rispetto a ciò che il diritto olandese consente davvero.',
            },
            {
              title: 'Tipo di contratto spiegato',
              text: 'A termine, a tempo indeterminato, clausola diplomatica: le spieghiamo esattamente che cosa significa il suo tipo di contratto per i suoi diritti di recesso e per quelli del proprietario.',
            },
            {
              title: 'Punti da negoziare',
              text: 'Un breve elenco di ciò su cui insistere e delle formule da usare, oppure lo solleviamo noi con il proprietario per lei.',
            },
          ],
        },
        process: {
          title: 'Come funziona',
          steps: [
            {
              title: 'Ci mandi la bozza',
              text: 'Ci invii il contratto via e-mail o WhatsApp nel momento in cui lo riceve.',
            },
            {
              title: 'Esaminiamo in fretta',
              text: 'Riceve rapidamente la nostra valutazione completa, perché sappiamo che in questo mercato i tempi per firmare sono stretti.',
            },
            {
              title: 'Firmi con sicurezza',
              text: 'Firma un contratto che capisce, con le clausole rischiose rimosse o rinegoziate.',
            },
          ],
        },
        fees: {
          title: 'Onorario per la revisione di un contratto di locazione',
          kind: 'fixed',
          amount: 'Investimento da 395 €',
          includes: [
            'Revisione completa del contratto e delle condizioni generali allegate',
            'L\'affitto verificato con il sistema a punti olandese finché la finestra per opporsi è aperta',
            'Clausola diplomatica, cauzione, spese accessorie e preavviso spiegati per iscritto',
            'Singoli punti rinegoziati per suo conto con il proprietario o l\'agenzia',
          ],
        },
        note: 'Esaminiamo i contratti come specialisti del trasferimento, non come studio legale. Per le controversie legali vere la mettiamo in contatto con avvocati esperti di locazioni della nostra rete professionale, costruita in anni di lavoro accanto ad ambasciate e consolati.',
        conditions: {
          title: 'Che cosa verifichiamo e che cosa non possiamo fare',
          intro: 'Il diritto olandese delle locazioni la tutela più di quanto la maggior parte dei nuovi arrivati immagini. Sapere quali tutele si applicano è tutto il gioco.',
          items: [
            'Le cauzioni sono limitate a due mensilità di affitto base per i contratti firmati dal 1° luglio 2023.',
            'Dal 1° luglio 2024 la maggior parte delle nuove locazioni abitative deve essere a tempo indeterminato, con contratti a termine ammessi solo in situazioni definite.',
            'Le spese accessorie devono essere specificate e conguagliate ogni anno sui costi effettivi. Un\'unica cifra forfettaria non è ammessa per la maggior parte delle locazioni.',
            'Gli oneri di agenzia non possono essere addebitati all\'inquilino quando l\'agente opera per il proprietario.',
            'Un affitto superiore al livello consentito dal sistema a punti può essere contestato alla Huurcommissie, nella maggior parte dei casi entro sei mesi dall\'inizio della locazione.',
            'Esaminiamo i contratti e le spieghiamo la sua posizione. Siamo consulenti di relocation, non uno studio legale, e per i procedimenti la indirizziamo a un avvocato olandese esperto di locazioni di cui ci fidiamo.',
          ],
        },
        details: {
          title: 'Clausole che costano care più avanti',
          items: [
            {
              q: 'Quali clausole guardate per prime?',
              a: 'Opzioni di recesso e clausole diplomatiche, chi paga le piccole riparazioni, se la cauzione è restituibile entro un termine definito, formule di indicizzazione che superano l\'inflazione, restrizioni all\'iscrizione anagrafica presso l\'indirizzo, stime delle spese accessorie fissate irrealisticamente basse e penali per recesso anticipato.',
            },
            {
              q: 'Posso iscrivermi all\'anagrafe a questo indirizzo?',
              a: 'È la clausola che conta di più e quella più spesso esclusa in silenzio. Senza iscrizione non c\'è BSN, né assicurazione sanitaria, né conto bancario, né corrispondenza sui permessi. Se il contratto lo vieta o tace, lo solleviamo prima che firmi e non dopo.',
            },
            {
              q: 'E se l\'affitto è troppo alto per l\'immobile?',
              a: 'Il sistema a punti olandese fissa un affitto massimo di legge per la maggior parte delle case in base a superficie, etichetta energetica, dotazioni e posizione. Dove l\'affitto lo supera, la Huurcommissie può ridurlo, di norma su istanza presentata entro sei mesi dall\'inizio della locazione. Lo segnaliamo durante la revisione, mentre la finestra è ancora aperta.',
            },
            {
              q: 'Quanto è rapida una revisione?',
              a: 'Normalmente entro un giorno lavorativo, e in giornata quando è sotto pressione per firmare. Un proprietario che insiste perché firmi entro un\'ora sta applicando una tattica, non descrivendo una scadenza.',
            },
          ],
        },
        faq: {
          title: 'Domande frequenti',
          items: [
            {
              q: 'Quanto può essere alta legalmente una cauzione?',
              a: 'Per la maggior parte dei contratti firmati oggi la cauzione è limitata al doppio dell\'affitto mensile base. Se un proprietario chiede di più, è un campanello d\'allarme che affronteremo prima che lei paghi un centesimo.',
            },
            {
              q: 'Il mio contratto vieta l\'iscrizione anagrafica all\'indirizzo. È consentito?',
              a: 'No. Se vi abita legittimamente, ha diritto a iscriversi al comune, e una clausola che lo vieta è un segnale d\'allarme sul proprietario. Lo trattiamo come una questione seria, poiché l\'iscrizione è alla base del suo BSN e della sua assicurazione.',
            },
            {
              q: 'Che cosa significa arredato per il mio contratto e il mio affitto?',
              a: 'L\'arredamento viene addebitato tramite le spese accessorie, che devono riflettere il valore reale di ciò che viene fornito. Verifichiamo che un divano vecchio non le costi un sovrapprezzo ogni mese e che l\'inventario corrisponda a ciò che c\'è davvero in casa.',
            },
          ],
        },
        cta: {
          title: 'Non lo firmi ancora',
          text: 'Ci mandi prima il contratto. Una revisione adesso costa meno di una clausola sbagliata poi.',
          label: 'Esamina il mio contratto',
        },
        form: 'relocation',
        image: '/images/rental-contract.jpg?v=20260731',
        imageAlt: 'Firma di un contratto di locazione olandese con una penna stilografica',
        image2: '/images/housing-interior.jpg?v=20260731',
        image2Alt: 'Soggiorno di un appartamento in una casa olandese sul canale',
      },
      {
        slug: 'temporary-housing-for-expats-netherlands',
        menuLabel: 'Alloggio temporaneo',
        title: 'Alloggio temporaneo per expat nei Paesi Bassi',
        metaTitle: 'Alloggio temporaneo per expat nei Paesi Bassi | E & I Expat Services',
        metaDescription: 'Alloggi short-stay e temporanei per expat nei Paesi Bassi. Una base comoda e registrabile per le sue prime settimane mentre troviamo la sua casa definitiva.',
        eyebrow: 'Alloggio temporaneo',
        intro: [
          'Quasi ogni trasferimento ha un vuoto: ha una data di inizio al lavoro ma non ancora una casa, oppure le sue cose sono su una nave mentre lei è già qui. L\'alloggio temporaneo colma quel vuoto, e farlo bene è la differenza fra arrivare stressati e arrivare sistemati.',
          'Organizziamo appartamenti short-stay e alloggi con servizi che siano davvero vivibili: arredati, allacciati, in un quartiere che le piacerà e, ove possibile, con la possibilità di iscriversi all\'anagrafe a quell\'indirizzo. E poiché gli arrivi raramente avvengono fra le nove e le cinque, la nostra linea WhatsApp personale resta aperta a qualsiasi ora, così un volo in ritardo o una cassetta portachiavi che non si apre non la lasciano mai a piedi.',
        ],
        cardText: 'Una base comoda e registrabile per le sue prime settimane mentre corre la ricerca vera.',
        forWho: {
          title: 'A chi si rivolge',
          items: [
            'Nuovi arrivati il cui lavoro inizia prima che finisca la ricerca della casa',
            'Famiglie che devono colmare il vuoto finché la casa definitiva non è pronta',
            'Professionisti con incarichi da due a dodici mesi',
            'Chiunque sia fra due case dopo una vendita, una ristrutturazione o la fine di un contratto',
          ],
        },
        included: {
          title: 'Cosa è incluso',
          blocks: [
            {
              title: 'Opzioni short-stay selezionate',
              text: 'Una selezione curata di appartamenti con servizi e case short-stay adatti al suo budget, alle sue date e al suo tragitto, non un elenco generico di prenotazioni.',
            },
            {
              title: 'Verifica sull\'iscrizione anagrafica',
              text: 'Dove le serve un BSN, diamo priorità agli indirizzi in cui l\'iscrizione al comune è consentita e lo facciamo confermare per iscritto.',
            },
            {
              title: 'Gestione di prenotazione e contratto',
              text: 'Negoziamo le condizioni, esaminiamo l\'accordo short-stay e ci assicuriamo che il preavviso corrisponda ai suoi tempi reali.',
            },
            {
              title: 'Consegna pronta all\'arrivo',
              text: 'Chiavi, utenze, internet e istruzioni della casa organizzati perché tutto funzioni dalla prima sera.',
            },
            {
              title: 'Ponte verso la casa definitiva',
              text: 'Il suo soggiorno temporaneo si innesta direttamente nella nostra ricerca della casa, così la caccia definitiva parte il giorno stesso in cui atterra.',
            },
          ],
        },
        process: {
          title: 'Come funziona',
          steps: [
            {
              title: 'Ci comunichi le date',
              text: 'Ci dica data di arrivo, numero di persone, budget e per quanto prevede di dover colmare il vuoto.',
            },
            {
              title: 'Scelga fra opzioni reali',
              text: 'Le inviamo una rosa di soluzioni disponibili e verificate, con note oneste su ciascuna.',
            },
            {
              title: 'Atterri e viva',
              text: 'Entra in una casa funzionante il primo giorno mentre noi proseguiamo con la ricerca di quella definitiva.',
            },
          ],
        },
        fees: {
          title: 'Quanto costa l\'assistenza per l\'alloggio temporaneo',
          kind: 'tailored',
          amount: 'Su richiesta',
          amountNote: 'L\'alloggio temporaneo dipende interamente da quanto le serve, per quante persone e con quanto preavviso. Riceve un preventivo fisso non appena conosciamo le date.',
          includes: [
            'Appartamenti con servizi e opzioni short-stay adatti alle sue date',
            'Condizioni verificate perché un soggiorno breve non blocchi la sua iscrizione al comune',
            'Coordinamento fra l\'indirizzo temporaneo e la ricerca definitiva',
            'Passaggio organizzato quando la casa definitiva è pronta',
          ],
        },
        conditions: {
          title: 'Lo short stay nella pratica',
          intro: 'Una base temporanea è un ponte, e i ponti vanno scelti con cura. Sono queste le condizioni che decidono se il suo funziona.',
          items: [
            'Gli affitti short-stay durano di norma da uno a sei mesi e costano più al mese di una locazione ordinaria, spesso dal trenta al cinquanta per cento in più.',
            'L\'iscrizione all\'indirizzo è possibile solo dove la consentono sia il proprietario sia il comune, e molti indirizzi short-stay non lo fanno.',
            'Senza iscrizione non c\'è BSN, il che ritarda assicurazione sanitaria, banca e in certi casi il pagamento dello stipendio.',
            'La maggior parte degli immobili short-stay è arredata con utenze e internet inclusi, ma pulizie e biancheria spesso no.',
            'Permanenze minime, condizioni di disdetta e cauzioni variano molto fra gli operatori e sono raramente negoziabili.',
            'Collochiamo i clienti solo in immobili che useremmo noi stessi, e rifiutiamo gli operatori dei cui contratti non ci fidiamo.',
          ],
        },
        details: {
          title: 'Usare bene il ponte',
          items: [
            {
              q: 'Posso iscrivermi a un indirizzo short-stay?',
              a: 'A volte, e cambia tutto. Filtriamo fin dall\'inizio gli immobili che consentono l\'iscrizione, perché una base che la permette fa partire BSN, assicurazione e stipendio dalla prima settimana invece che dal terzo mese. Dove l\'iscrizione è impossibile lo pianifichiamo deliberatamente invece di scoprirlo tardi.',
            },
            {
              q: 'Per quanto tempo dovrei prenotare?',
              a: 'Da sei a dieci settimane va bene per la maggior parte degli arrivi. Dà respiro alla ricerca definitiva senza pagare il sovrapprezzo short-stay più del necessario, e la maggior parte degli operatori proroga se la ricerca va per le lunghe.',
            },
            {
              q: 'Un hotel costa meno?',
              a: 'Sotto le tre settimane, spesso sì. Oltre, gli appartamenti short-stay vincono sia sul costo sia sulla salute mentale, in particolare per le famiglie. Il punto di svolta cade di norma attorno alla terza settimana.',
            },
            {
              q: 'E le cose che arrivano dall\'estero?',
              a: 'I contratti short-stay raramente includono un deposito. Coordiniamo la sua spedizione sull\'indirizzo definitivo anziché su quello temporaneo, e organizziamo un magazzino nella regione quando i tempi non coincidono.',
            },
          ],
        },
        faq: {
          title: 'Domande frequenti',
          items: [
            {
              q: 'Posso iscrivermi per il BSN a un indirizzo temporaneo?',
              a: 'In molti indirizzi short-stay sì, e lo trattiamo come filtro prioritario quando le serve l\'iscrizione per BSN, assicurazione o conto bancario. Confermiamo la politica sull\'iscrizione con ciascun operatore prima che prenoti.',
            },
            {
              q: 'L\'alloggio temporaneo è arredato?',
              a: 'Quasi sempre completamente arredato, biancheria, stoviglie, internet e utenze compresi in un unico prezzo. Quel sovrapprezzo è esattamente ciò per cui paga: entrare con una valigia e vivere normalmente già quella sera.',
            },
            {
              q: 'E se il mio animale arriva con me?',
              a: 'Gli short-stay che accettano animali esistono ma sono rari, quindi ce lo dica presto. Ci rivolgiamo direttamente agli operatori che accettano animali invece di scommettere su una casella spuntata di una piattaforma di prenotazione.',
            },
          ],
        },
        cta: {
          title: 'Colmi il vuoto con comodità',
          text: 'Ci dia la sua data di arrivo e ci assicureremo che dietro ci sia una casa calda e funzionante ad aspettarla.',
          label: 'Organizza la mia casa temporanea',
        },
        form: 'relocation',
        image: '/images/housing-interior.jpg?v=20260731',
        imageAlt: 'Soggiorno di un appartamento in una casa olandese sul canale',
        image2: '/images/entrepreneur-housing.jpg',
        image2Alt: 'Appartamento luminoso e arredato pronto per un nuovo arrivo',
      },
      {
        slug: 'landlord-communication-support-netherlands',
        menuLabel: 'Rapporti con il proprietario',
        title: 'Assistenza nei rapporti con il proprietario nei Paesi Bassi',
        metaTitle: 'Assistenza nei rapporti con il proprietario nei Paesi Bassi | E & I Expat Services',
        metaDescription: 'Gestiamo la comunicazione con il suo proprietario olandese: riparazioni, cauzioni, sopralluoghi e controversie, in olandese e con i suoi interessi al primo posto.',
        eyebrow: 'Rapporti con il proprietario',
        intro: [
          'Affittare in un paese straniero non finisce con la firma. La caldaia si rompe a gennaio, la restituzione della cauzione cade nel silenzio, il proprietario annuncia un sopralluogo con due giorni di preavviso, e all\'improvviso sta trattando in una lingua che non parla con regole che non conosce. La maggior parte degli inquilini semplicemente cede. Lei non dovrebbe doverlo fare.',
          'Diventiamo la sua voce verso il proprietario o l\'amministratore. Scriviamo e telefoniamo in olandese, sappiamo che cosa un proprietario è obbligato a riparare ed entro quali tempi, e teniamo traccia scritta di ogni scambio. Fermi dove serve, sempre cortesi, perché lei lì ci deve comunque vivere.',
        ],
        cardText: 'La sua voce verso il proprietario: riparazioni, cauzioni e controversie gestite in olandese.',
        forWho: {
          title: 'A chi si rivolge',
          items: [
            'Inquilini le cui richieste di riparazione vengono ignorate',
            'Expat che lottano per una cauzione che avrebbe dovuto essere restituita',
            'Affittuari alle prese con aumenti di affitto o addebiti che non capiscono',
            'Chiunque voglia che i contatti ordinari con il proprietario siano gestiti in modo professionale',
          ],
        },
        included: {
          title: 'Cosa è incluso',
          blocks: [
            {
              title: 'Monitoraggio di riparazioni e manutenzione',
              text: 'Segnaliamo i difetti nel modo corretto, richiamiamo gli obblighi di manutenzione di legge del proprietario e manteniamo la pressione finché il lavoro non è fatto.',
            },
            {
              title: 'Recupero della cauzione',
              text: 'Assistenza al sopralluogo di uscita, un fascicolo di riconsegna documentato e solleciti strutturati perché la cauzione torni per intero e nei tempi.',
            },
            {
              title: 'Controversie su affitto e costi',
              text: 'Valutiamo aumenti di affitto e conguagli annuali delle spese accessorie rispetto alle regole e ci opponiamo per suo conto quando i conti non tornano.',
            },
            {
              title: 'Corrispondenza continuativa',
              text: 'Lettere, e-mail e telefonate con il proprietario o l\'agenzia gestite in olandese, con lei in copia in inglese chiaro a ogni passaggio.',
            },
          ],
        },
        process: {
          title: 'Come funziona',
          steps: [
            {
              title: 'Ci spieghi la situazione',
              text: 'Ci mandi lo storico: il contratto, i messaggi, le foto. Valutiamo come sta messo.',
            },
            {
              title: 'Prendiamo noi i contatti',
              text: 'Dal messaggio successivo in poi il proprietario sente noi, con il tono giusto e i riferimenti giuridici giusti.',
            },
            {
              title: 'Soluzione e documentazione',
              text: 'Portiamo la questione a un esito e le consegniamo un fascicolo documentato su cui potrà contare in seguito se servirà.',
            },
          ],
        },
        fees: {
          title: 'Quanto costa l\'assistenza nei rapporti con il proprietario',
          kind: 'tailored',
          amount: 'Proposta su misura',
          amountNote: 'Alcuni clienti hanno bisogno che si risponda a una sola lettera difficile, altri di un intero anno di locazione gestito in olandese per loro conto. Riceve un preventivo per l\'ambito che le serve.',
          includes: [
            'Corrispondenza con il suo proprietario o la sua agenzia, in olandese, per suo conto',
            'Riparazioni, spese accessorie e controversie sulla cauzione prese in carico e portate a termine',
            'La sua posizione verificata rispetto al diritto olandese delle locazioni prima che scriviamo',
            'Ricorso alla Huurcommissie preparato dove è giustificato',
          ],
        },
        note: 'Per le questioni che appartengono davvero alla commissione per gli affitti o a un tribunale, prepariamo il suo fascicolo e la indirizziamo a un avvocato specializzato in locazioni. Non ci paga mai per fare ciò che dovrebbe fare un avvocato.',
        conditions: {
          title: 'Che cosa possiamo e che cosa non possiamo fare',
          intro: 'La maggior parte delle controversie di locazione si vince scrivendo la cosa giusta nella lingua giusta al momento giusto. È questo il lavoro.',
          items: [
            'Corrispondiamo con proprietari e agenzie in olandese, a suo nome, con lei in copia su tutto ciò che esce.',
            'Le riparazioni che riguardano sicurezza, riscaldamento o acqua vanno prima segnalate al proprietario. Un proprietario che poi non interviene può essere portato davanti alla Huurcommissie.',
            'Le cauzioni vanno restituite entro un termine ragionevole dopo il sopralluogo finale, e ogni trattenuta deve essere dettagliata e documentata.',
            'La normale usura non può essere trattenuta dalla cauzione. I danni effettivi sì.',
            'Per le controversie su livello dell\'affitto, spese accessorie e manutenzione, la Huurcommissie è di norma molto più rapida ed economica di un tribunale.',
            'Non siamo uno studio legale. Dove una controversia richiede un procedimento giudiziario passiamo la mano a un avvocato olandese esperto di locazioni e restiamo come suoi interpreti.',
          ],
        },
        details: {
          title: 'Le controversie che gestiamo più spesso',
          items: [
            {
              q: 'Il mio proprietario trattiene la cauzione.',
              a: 'La controversia più comune e di norma la più vincibile. Chiediamo un prospetto dettagliato con prove, separiamo la normale usura dai danni effettivi, confrontiamo il verbale d\'ingresso con quello d\'uscita e diamo un termine formale in olandese. La maggior parte delle cauzioni torna a quel punto, senza alcun procedimento.',
            },
            {
              q: 'Le riparazioni vengono ignorate.',
              a: 'Segnaliamo in modo formale e per iscritto, il che fa partire i termini sul piano giuridico e non su quello dei rapporti personali. Se non succede nulla, la Huurcommissie può disporre una riduzione temporanea dell\'affitto fino all\'esecuzione della riparazione, e la sola prospettiva di norma fa comparire un idraulico.',
            },
            {
              q: 'Le mie spese accessorie sono aumentate senza spiegazioni.',
              a: 'I proprietari devono fornire un conguaglio annuale che mostri i costi effettivi rispetto a quanto ha pagato. Lo richiediamo, lo confrontiamo con le letture dei contatori e contestiamo le voci che non possono essere documentate.',
            },
            {
              q: 'Devo andarmene prima.',
              a: 'La maggior parte dei contratti a tempo indeterminato consente all\'inquilino di recedere con un mese di preavviso, qualunque cosa le dicano sulla porta. Verifichiamo la clausola, notifichiamo il recesso correttamente e gestiamo il sopralluogo finale così che la cauzione torni intatta.',
            },
          ],
        },
        faq: {
          title: 'Domande frequenti',
          items: [
            {
              q: 'Il mio proprietario non vuole registrare i difetti dell\'immobile. E adesso?',
              a: 'I difetti vanno segnalati per iscritto con foto e un termine ragionevole. Redigiamo quella comunicazione per lei in olandese e, se il proprietario resta in silenzio, procediamo lungo la via prevista dalla legge, un passo documentato alla volta.',
            },
            {
              q: 'Per quanto tempo un proprietario può trattenere la mia cauzione dopo il trasloco?',
              a: 'Una cauzione va di norma liquidata entro poche settimane dal sopralluogo finale, con eventuali trattenute dettagliate e motivate. Le trattenute generiche per normale usura non reggono, e le contestiamo.',
            },
            {
              q: 'Il mio proprietario può impedirmi di tenere un animale?',
              a: 'Un divieto generalizzato non è automaticamente applicabile; molto dipende dal contratto, dal tipo di casa e dal disturbo effettivo. Prima di dare via un animale o di firmare qualcosa, ci lasci leggere che cosa dice davvero il suo contratto.',
            },
          ],
        },
        cta: {
          title: 'Smetta di temere la conversazione con il proprietario',
          text: 'Ci inoltri l\'ultimo messaggio a cui non sapeva come rispondere. Da lì in poi ci pensiamo noi.',
          label: 'Passa a noi la pratica',
        },
        form: 'relocation',
        image: '/images/landlord-communication.jpg?v=20260731',
        imageAlt: 'Consulente e proprietario che si stringono la mano in un appartamento',
        image2: '/images/housing-viewing.jpg?v=20260731',
        image2Alt: 'Visita a un appartamento con un consulente presente',
      },
    ],
    cta: {
      title: 'Ci lasci trovare la sua casa nei Paesi Bassi',
      text: 'Ci dica come vuole vivere e penseremo noi al mercato, alle visite, al contratto e al proprietario. Lei deve solo scegliere la casa.',
      label: 'Inizia la mia ricerca della casa',
    },
  };
