/* GENERATED by scripts/i18n-strings.mjs. Do not hand-edit.
   it/immigration.ts is a 1:1 structural mirror of en/immigration.ts; only leaf strings
   differ. To change structure, change English and re-run the build. */
import type { SectionContent } from '../types';

export const immigration: SectionContent = {
    title: 'Servizi di immigrazione per expat',
    metaTitle: 'Servizi di immigrazione per expat nei Paesi Bassi | E & I',
    metaDescription: 'Servizi di immigrazione concreti e seguiti di persona per expat nei Paesi Bassi. Visti per lavoratori altamente qualificati, per partner, startup e DAFT, gestiti con lei, non per un numero di pratica.',
    eyebrow: 'Immigrazione',
    intro: [
      'Un visto olandese non è un modulo. È il momento in cui la sua nuova vita inizia nei tempi previsti oppure resta in un cassetto dell\'IND. Gestiamo il lato immigrazione del suo trasferimento come andrebbe gestito: in modo pratico, personale e con qualcuno che ha accompagnato centinaia di famiglie attraverso esattamente queste porte. Essendo l\'unica consulenza boutique per expat nei Paesi Bassi, seguiamo pochi clienti e diamo a ciascuno attenzione vera.',
      'Ogni pratica inizia con un colloquio onesto. Le diciamo quale permesso si adatta davvero alla sua situazione, che cosa chiederà l\'IND e che cosa le togliamo dalle spalle. Da quel momento ha un solo referente, un solo piano e nessuna sorpresa.',
    ],
    image: '/images/canal-evening.jpg',
    imageAlt: 'Ponti sui canali di Amsterdam illuminati al crepuscolo',
    cta: {
      title: 'Non sa quale visto sia adatto alla sua situazione?',
      text: 'Ci dica da dove arriva e perché. Le diremo, senza giri di parole, quale percorso ha senso e che cosa comporta.',
      label: 'Inizi con un colloquio',
    },
    services: [
      {
        slug: 'highly-skilled-migrant-visa-netherlands',
        menuLabel: 'Lavoratore altamente qualificato',
        title: 'Visto per lavoratori altamente qualificati nei Paesi Bassi',
        metaTitle: 'Visto per lavoratori altamente qualificati nei Paesi Bassi | Guida personale',
        metaDescription: 'Si trasferisce nei Paesi Bassi come lavoratore altamente qualificato? Ci coordiniamo con il suo datore di lavoro, prepariamo la domanda all\'IND e accompagniamo la sua famiglia passo dopo passo.',
        eyebrow: 'Visto di lavoro',
        intro: [
          'Il percorso per lavoratori altamente qualificati è la via più rapida e lineare perché un professionista internazionale possa lavorare nei Paesi Bassi. Il suo datore di lavoro deve essere uno sponsor riconosciuto dall\'IND, la sua retribuzione deve raggiungere la soglia IND in vigore per la sua fascia d\'età e le pratiche devono essere corrette già la prima volta.',
          'È qui che entriamo noi. Ci coordiniamo direttamente con le risorse umane del suo datore di lavoro, prepariamo lei e la sua famiglia a ogni appuntamento e restiamo raggiungibili sulla nostra linea WhatsApp personale attiva 24 ore su 24, ogni volta che sorge una domanda, in qualunque fuso orario.',
        ],
        cardText: 'La via di lavoro più rapida verso i Paesi Bassi, coordinata fra lei, il suo datore di lavoro e l\'IND.',
        explainer: {
          title: 'Che cos\'è il permesso per lavoratori altamente qualificati?',
          text: [
            'Il permesso per lavoratori altamente qualificati, kennismigrant in olandese, è la via con cui i Paesi Bassi fanno entrare rapidamente professionisti esperti. Non si valuta la sua qualifica professionale né il suo titolo di studio. Si valuta una cosa sola: se un datore di lavoro olandese riconosciuto dall\'IND come sponsor le paga una retribuzione superiore a una soglia stabilita.',
            'Poiché il riconoscimento è in capo al datore di lavoro, la procedura è rapida e non c\'è alcun esame del mercato del lavoro. Il permesso è legato a quel datore di lavoro: è dunque il contratto, non la persona, ad ancorare il suo soggiorno nei Paesi Bassi.',
          ],
        },
        forWho: {
          title: 'A chi si rivolge',
          items: [
            'Professionisti con un\'offerta di lavoro da un\'azienda olandese',
            'Dipendenti trasferiti in una sede nei Paesi Bassi',
            'Partner e figli che si spostano insieme al richiedente principale',
            'Uffici del personale che trasferiscono per la prima volta una risorsa internazionale',
          ],
        },
        included: {
          title: 'Di che cosa ci occupiamo',
          blocks: [
            {
              title: 'Verifica dei requisiti e della retribuzione',
              text: 'Prima di depositare qualsiasi cosa verifichiamo che il suo datore di lavoro sia uno sponsor riconosciuto e che l\'offerta raggiunga la soglia retributiva IND in vigore, che viene indicizzata ogni anno.',
            },
            {
              title: 'Coordinamento con il suo datore di lavoro',
              text: 'È lo sponsor a presentare formalmente la domanda. Prepariamo il fascicolo con le risorse umane, sollecitiamo ciò che manca e teniamo entrambe le parti su un unico calendario.',
            },
            {
              title: 'Domande per la famiglia',
              text: 'Il suo partner e i suoi figli presentano domanda insieme a lei. Raggruppiamo le domande così che tutta la famiglia arrivi con i permessi giusti nello stesso momento.',
            },
            {
              title: 'Assistenza sui documenti',
              text: 'Gli atti di nascita e di matrimonio spesso richiedono legalizzazione o apostille dal suo paese d\'origine. Le diciamo esattamente quale timbro serve e da quale autorità, prima che parta.',
            },
            {
              title: 'Appuntamenti all\'arrivo',
              text: 'Biometria, ritiro del permesso, iscrizione in comune e BSN. Li fissiamo nell\'ordine giusto e la accompagniamo.',
            },
          ],
        },
        process: {
          title: 'Come funziona',
          steps: [
            {
              title: 'Colloquio iniziale',
              text: 'Esaminiamo la sua offerta, la sua cittadinanza e la sua situazione familiare, poi tracciamo il percorso e i tempi esatti.',
            },
            {
              title: 'Preparazione del fascicolo',
              text: 'Raccogliamo i documenti con lei e con il suo datore di lavoro e presentiamo tramite lo sponsor.',
            },
            {
              title: 'Decisione e MVV',
              text: 'A seconda della sua cittadinanza dovrà ritirare un visto d\'ingresso presso l\'ambasciata olandese prima di partire. La prepariamo a quell\'appuntamento.',
            },
            {
              title: 'Atterraggio',
              text: 'Nei suoi primi giorni completiamo l\'iscrizione, il ritiro del permesso e gli aspetti pratici essenziali.',
            },
          ],
        },
        fees: {
          title: 'Onorario per una domanda come lavoratore altamente qualificato',
          kind: 'fixed',
          amount: 'Investimento da 1.295 €',
          includes: [
            'Verifica della soglia retributiva applicabile alla sua età e alla sua situazione',
            'Il fascicolo completo preparato e depositato tramite il suo sponsor riconosciuto',
            'Coordinamento con le risorse umane del suo datore di lavoro perché contratto e data di inizio coincidano',
            'Riscontro a ogni richiesta dell\'IND fino all\'emissione della decisione',
          ],
        },
        note: 'Molti lavoratori altamente qualificati rientrano nell\'agevolazione del 30%, un vantaggio fiscale olandese per i dipendenti in arrivo. Le condizioni cambiano di frequente, quindi la segnaliamo durante il colloquio e la mettiamo in contatto con un consulente fiscale invece di promettere numeri.',
        conditions: {
          title: 'Che cosa richiede l\'IND',
          intro: 'Questo percorso passa dal suo datore di lavoro più che da lei. Sono queste condizioni a decidere il fascicolo prima ancora che venga aperto.',
          items: [
            'Il suo datore di lavoro deve essere uno sponsor riconosciuto dall\'IND. Senza quel riconoscimento la via è chiusa, qualunque sia la retribuzione.',
            'Retribuzione lorda mensile da 5.942 euro se ha 30 anni o più, e da 4.357 euro se ha meno di 30 anni (2026, esclusa l\'indennità di ferie dell\'8 per cento).',
            'Una soglia ridotta di 3.122 euro si applica nell\'anno successivo a un anno di orientamento olandese o a un titolo di studio olandese.',
            'La retribuzione va versata mensilmente su un conto bancario olandese. Bonus, indennità e budget spese non concorrono alla soglia.',
            'L\'agevolazione del 30 per cento si calcola sopra la soglia e non può mai essere usata per raggiungerla.',
            'Le soglie sono indicizzate ogni 1° gennaio e si valutano sui valori in vigore al momento del deposito della domanda.',
          ],
        },
        details: {
          title: 'Dettagli che vale la pena conoscere',
          items: [
            {
              q: 'E se il mio datore di lavoro non è uno sponsor riconosciuto?',
              a: 'Il riconoscimento richiede settimane che una data di inizio raramente concede. Quando un datore di lavoro non è riconosciuto valutiamo la Carta Blu UE, che non prevede il requisito dello sponsor, oppure avviamo la domanda di riconoscimento in parallelo al suo fascicolo se l\'azienda intende assumere ancora dall\'estero.',
            },
            {
              q: 'Quanto è rapida la decisione nella pratica?',
              a: 'Gli sponsor riconosciuti hanno un termine di legge di novanta giorni e i fascicoli completi vengono spesso decisi in due o quattro settimane. Il ritardo su questo percorso è quasi sempre un documento legalizzato mancante, non l\'IND.',
            },
            {
              q: 'Che cosa succede se cambio lavoro?',
              a: 'Il permesso è legato al suo datore di lavoro. Anche il nuovo datore deve essere uno sponsor riconosciuto e deve presentare una nuova domanda, e lei non può iniziare prima dell\'approvazione. Gestiamo il passaggio in modo che non si crei alcun buco nel suo soggiorno.',
            },
            {
              q: 'Mi serve anche un MVV oltre al permesso?',
              a: 'Alla maggior parte dei cittadini extra UE sì, e li richiediamo entrambi in un\'unica procedura combinata. I cittadini di Stati Uniti, Canada, Giappone, Australia, Nuova Zelanda, Corea del Sud e Regno Unito ne sono esentati e viaggiano con il solo permesso.',
            },
          ],
        },
        faq: {
          title: 'Domande che sentiamo spesso',
          items: [
            {
              q: 'Il mio partner può lavorare nei Paesi Bassi?',
              a: 'Sì. I partner dei lavoratori altamente qualificati ricevono un permesso di soggiorno con libero accesso al mercato del lavoro. Non serve alcun permesso di lavoro separato.',
            },
            {
              q: 'Quanto tempo richiede la domanda?',
              a: 'Le domande presentate tramite uno sponsor riconosciuto seguono la corsia più veloce dell\'IND e nella pratica la maggior parte dei casi si muove rapidamente. Confermiamo tempi e diritti IND aggiornati durante il colloquio, invece di citare numeri destinati a invecchiare.',
            },
            {
              q: 'Devo parlare olandese?',
              a: 'No. Per questo permesso non esiste alcun requisito linguistico, e la vita quotidiana nelle comunità internazionali attorno a Rotterdam e all\'Aia si svolge senza problemi in inglese.',
            },
            {
              q: 'Il mio partner può lavorare nei Paesi Bassi?',
              a: 'Sì. I partner dei lavoratori altamente qualificati ricevono un permesso con libero accesso al mercato del lavoro, il che significa nessun permesso di lavoro separato e nessuno sponsor. I figli rientrano nella stessa domanda familiare.',
            },
          ],
        },
        cta: {
          title: 'Ha un\'offerta da un datore di lavoro olandese?',
          text: 'Ci mandi i dati essenziali e in una sola conversazione le diremo se la strada è libera e che cosa succede dopo.',
          label: 'Verifica i miei requisiti',
        },
        form: 'immigration',
        image: '/images/hsm-visa.jpg?v=20260731',
        imageAlt: 'Professionista internazionale nell\'atrio di un ufficio olandese',
        image2: '/images/employer-immigration.jpg',
        image2Alt: 'Due professionisti internazionali in conversazione fuori da un ufficio olandese',
      },
      {
        slug: 'eu-blue-card-netherlands',
        menuLabel: 'Carta Blu UE',
        title: 'Carta Blu UE nei Paesi Bassi',
        metaTitle: 'Carta Blu UE nei Paesi Bassi | Assistenza alla domanda per expat',
        metaDescription: 'Richieda la Carta Blu UE nei Paesi Bassi con una guida personale. Riconoscimento del titolo di studio, coordinamento con il datore di lavoro e un permesso che accompagna la sua carriera europea.',
        eyebrow: 'Visto di lavoro',
        intro: [
          'La Carta Blu UE è il permesso di lavoro europeo per professionisti con istruzione superiore, e la versione olandese è diventata davvero interessante. Le dà il diritto di vivere e lavorare nei Paesi Bassi e costruisce diritti di mobilità in tutta l\'UE che un permesso nazionale non offre.',
          'La nostra reputazione è nata nel mondo delle ambasciate, e i fascicoli per la Carta Blu premiano esattamente quel tipo di precisione: un titolo valutato correttamente, un contratto conforme e un deposito impeccabile. Ci assicuriamo che il suo li abbia tutti e tre.',
        ],
        cardText: 'Il permesso di lavoro europeo per professionisti con istruzione superiore, con mobilità in tutta l\'UE.',
        explainer: {
          title: 'Che cos\'è la Carta Blu UE?',
          text: [
            'La Carta Blu UE è un permesso europeo di soggiorno e lavoro per professionisti laureati. Mentre il permesso olandese per lavoratori altamente qualificati guarda solo alla retribuzione e a uno sponsor riconosciuto, la Carta Blu chiede anche un percorso di istruzione superiore completato e in cambio conferisce diritti che si estendono oltre i Paesi Bassi.',
            'È questa la differenza vera. Una Carta Blu costruisce mobilità all\'interno dell\'Unione europea e apre allo status di soggiornante di lungo periodo UE, cosa che il permesso nazionale non fa. È la scelta migliore quando i Paesi Bassi sono un capitolo e non l\'intero libro.',
          ],
        },
        forWho: {
          title: 'È questo il suo percorso?',
          items: [
            'Professionisti con una laurea e un\'offerta di lavoro olandese',
            'Specialisti che potrebbero spostarsi fra paesi UE nel corso della carriera',
            'Dipendenti il cui datore di lavoro non è uno sponsor riconosciuto dall\'IND',
            'Professionisti IT esperti che possono qualificarsi in base all\'esperienza',
          ],
        },
        included: {
          title: 'Come la gestiamo',
          blocks: [
            {
              title: 'Confronto fra percorsi',
              text: 'Mettiamo a confronto la Carta Blu con il permesso per lavoratori altamente qualificati per il suo caso specifico, perché per alcuni profili uno dei due è nettamente migliore dell\'altro.',
            },
            {
              title: 'Valutazione del titolo di studio',
              text: 'I titoli esteri di norma necessitano di riconoscimento nei Paesi Bassi. Seguiamo la valutazione delle credenziali perché la sua qualifica venga accettata senza rimpalli.',
            },
            {
              title: 'Esame di retribuzione e contratto',
              text: 'Il suo contratto deve soddisfare la soglia retributiva IND in vigore e i requisiti di durata. Lo esaminiamo prima del deposito, non dopo un rigetto.',
            },
            {
              title: 'Gestione della domanda',
              text: 'Prepariamo e gestiamo l\'intera domanda all\'IND insieme al suo datore di lavoro e la monitoriamo fino all\'arrivo della decisione.',
            },
          ],
        },
        process: {
          title: 'Il suo percorso, passo dopo passo',
          steps: [
            {
              title: 'Valutazione',
              text: 'Verifichiamo titolo di studio, offerta e retribuzione rispetto alle condizioni vigenti della Carta Blu.',
            },
            {
              title: 'Riconoscimento e fascicolo',
              text: 'La valutazione del diploma viene avviata mentre in parallelo costruiamo il fascicolo della domanda.',
            },
            {
              title: 'Deposito e arrivo',
              text: 'Dopo l\'approvazione pianifichiamo il suo ingresso, l\'iscrizione e i primi appuntamenti nell\'ordine giusto.',
            },
          ],
        },
        fees: {
          title: 'Onorario per una domanda di Carta Blu UE',
          kind: 'fixed',
          amount: 'Investimento da 1.295 €',
          includes: [
            'Titolo di studio e retribuzione verificati rispetto ai criteri della Carta Blu prima che lei si impegni',
            'Valutazione del diploma organizzata dove l\'IND la richiede',
            'Domanda preparata e depositata, compresa la parte del fascicolo che spetta al datore di lavoro',
            'Monitoraggio fino alla decisione, comprese eventuali richieste di documenti aggiuntivi',
          ],
        },
        conditions: {
          title: 'Condizioni della Carta Blu',
          intro: 'La Carta Blu si decide su tre elementi: la sua qualifica, il suo contratto e la sua retribuzione. Ecco dove sono fissate le linee.',
          items: [
            'Un percorso di istruzione superiore completato di almeno tre anni, oppure, per i ruoli ICT, almeno tre anni di esperienza pertinente maturata negli ultimi sette.',
            'Retribuzione lorda mensile da 5.942 euro, oppure 4.754 euro con il criterio ridotto per neolaureati e professioni carenti (2026, esclusa l\'indennità di ferie).',
            'Un contratto di lavoro o un\'offerta vincolante di durata almeno semestrale.',
            'I diplomi esteri devono essere valutati da IDW o Nuffic. Le qualifiche olandesi non necessitano di valutazione.',
            'Il suo datore di lavoro non deve essere uno sponsor riconosciuto, ed è questo il vantaggio pratico rispetto al permesso per lavoratori altamente qualificati.',
            'Le soglie sono indicizzate il 1° gennaio e si applicano alla data di deposito, non alla data del contratto.',
          ],
        },
        details: {
          title: 'La Carta Blu nella pratica',
          items: [
            {
              q: 'Come funziona davvero la mobilità UE?',
              a: 'Dopo dodici mesi di soggiorno regolare come titolare di Carta Blu può trasferirsi in un altro Stato membro con una procedura abbreviata, e gli anni trascorsi in Stati membri diversi si sommano ai fini dello status di soggiornante di lungo periodo UE. Un permesso olandese per lavoratori altamente qualificati non le dà nulla di tutto questo.',
            },
            {
              q: 'Carta Blu o lavoratore altamente qualificato?',
              a: 'Se il suo datore di lavoro è uno sponsor riconosciuto e lei intende costruire la carriera nei Paesi Bassi, il permesso per lavoratori altamente qualificati è di norma più rapido e più semplice. Se il datore non è riconosciuto, o se la sua carriera si muoverà probabilmente in Europa, la Carta Blu è lo strumento più solido. Riceve il confronto per iscritto prima di impegnarsi.',
            },
            {
              q: 'Posso qualificarmi con l\'esperienza invece che con la laurea?',
              a: 'Solo nell\'ICT. Manager e specialisti delle tecnologie dell\'informazione e della comunicazione possono qualificarsi con almeno tre anni di esperienza pertinente maturata nei sette anni precedenti la domanda. Ogni altra professione richiede il titolo di studio.',
            },
            {
              q: 'Quanto dura la valutazione del diploma?',
              a: 'IDW restituisce di norma una valutazione in circa quattro settimane, di più quando un istituto è lento a confermare l\'autenticità. La avviamo in parallelo al resto del fascicolo, così non diventa mai il collo di bottiglia.',
            },
            {
              q: 'A che cosa porta la Carta Blu?',
              a: 'Una volta maturati cinque anni di soggiorno regolare nell\'UE, di cui almeno due nei Paesi Bassi, può chiedere qui lo status di soggiornante di lungo periodo UE. Questo accumulo attraverso i confini è esclusivo di questo permesso.',
            },
          ],
        },
        faq: {
          title: 'Domande pratiche',
          items: [
            {
              q: 'Quale retribuzione mi serve per la Carta Blu UE?',
              a: 'La soglia è fissata dall\'IND e adeguata ogni anno, con un livello più basso per i neolaureati. Verifichiamo la sua offerta rispetto ai valori in vigore durante il colloquio, invece di pubblicare numeri destinati a scadere.',
            },
            {
              q: 'Carta Blu o lavoratore altamente qualificato, quale è meglio?',
              a: 'Dipende. Il percorso per lavoratori altamente qualificati è spesso più rapido se il suo datore di lavoro è uno sponsor riconosciuto. La Carta Blu vince sulla mobilità UE e non richiede sponsor. Consigliamo caso per caso, onestamente.',
            },
            {
              q: 'Posso portare la mia famiglia?',
              a: 'Sì. Il suo partner e i suoi figli possono presentare domanda con lei, e il suo partner può lavorare nei Paesi Bassi senza un permesso di lavoro separato.',
            },
            {
              q: 'L\'agevolazione del 30 per cento conta ai fini della soglia retributiva?',
              a: 'No. L\'IND verifica la retribuzione lorda prima dell\'applicazione dell\'agevolazione. Un contratto che raggiunge la soglia solo conteggiando l\'agevolazione viene rigettato, ed è uno dei motivi più frequenti per cui un fascicolo Carta Blu fallisce.',
            },
          ],
        },
        cta: {
          title: 'Sta costruendo una carriera europea?',
          text: 'Ci mandi i dati del suo titolo di studio e della sua offerta. Le diremo se la Carta Blu è la sua via più solida verso i Paesi Bassi.',
          label: 'Chiedi informazioni sulla Carta Blu',
        },
        form: 'immigration',
        image: '/images/eu-blue-card.jpg?v=20260731',
        imageAlt: 'Due professionisti internazionali senior in discussione',
        image2: '/images/hsm-visa.jpg?v=20260731',
        image2Alt: 'Professionista internazionale nell\'atrio di un ufficio olandese',
      },
      {
        slug: 'orientation-year-visa-netherlands',
        menuLabel: 'Visto anno di orientamento',
        title: 'Visto anno di orientamento nei Paesi Bassi',
        metaTitle: 'Visto anno di orientamento nei Paesi Bassi | Zoekjaar per neolaureati',
        metaDescription: 'Neolaureato o dottore di ricerca? Il visto olandese per l\'anno di orientamento le dà dodici mesi per vivere e lavorare liberamente nei Paesi Bassi. Gestiamo la domanda e il suo arrivo.',
        eyebrow: 'Visto per neolaureati',
        intro: [
          'L\'anno di orientamento, lo zoekjaar, è uno dei permessi più generosi d\'Europa. Se si è laureato di recente in un istituto olandese o in un\'università internazionale di alta classifica, le dà dodici mesi per vivere nei Paesi Bassi e lavorare per qualsiasi datore di lavoro, senza bisogno di sponsor.',
          'La domanda in sé è lineare se fatta bene, quindi il nostro valore vero è ciò che viene dopo: trasformare quell\'anno in una carriera e in una casa. Accompagniamo i neolaureati dal primo modulo al primo appartamento e restiamo vicini mentre trovano il proprio equilibrio.',
        ],
        cardText: 'Dodici mesi per vivere e lavorare liberamente nei Paesi Bassi dopo la laurea.',
        explainer: {
          title: 'Che cos\'è l\'anno di orientamento?',
          text: [
            'L\'anno di orientamento, zoekjaar in olandese, è un permesso di soggiorno di un anno che consente a neolaureati e ricercatori di cercare lavoro nei Paesi Bassi senza che un datore di lavoro debba prima sponsorizzarli. Durante quell\'anno può lavorare liberamente e nessun datore di lavoro ha bisogno di un permesso di lavoro per lei.',
            'Esiste per risolvere un circolo vizioso: i datori di lavoro vogliono qualcuno che possa iniziare subito, e i permessi di norma richiedono un datore di lavoro. L\'anno di orientamento rompe quel blocco e porta con sé, subito dopo, una soglia retributiva più bassa se passa a un permesso per lavoratori altamente qualificati.',
          ],
        },
        forWho: {
          title: 'Chi ha i requisiti',
          items: [
            'Laureati di università e hogescholen olandesi, entro tre anni dalla laurea',
            'Laureati di università internazionali di alta classifica',
            'Dottori di ricerca e ricercatori che hanno concluso di recente nei Paesi Bassi o all\'estero',
            'Ex titolari dell\'anno di orientamento che passano ora a un permesso di lavoro',
          ],
        },
        included: {
          title: 'Che cosa facciamo per lei',
          blocks: [
            {
              title: 'Verifica dei requisiti',
              text: 'Verifichiamo il suo titolo, la sua data di conseguimento e la posizione in classifica della sua università rispetto ai requisiti IND prima che spenda un euro per la domanda.',
            },
            {
              title: 'Gestione completa della domanda',
              text: 'Questo permesso lo richiede lei stesso, senza un datore di lavoro. Prepariamo il fascicolo, lo depositiamo e lo seguiamo perché nulla si areni.',
            },
            {
              title: 'Pratiche sul titolo di studio',
              text: 'I titoli esteri richiedono le copie autenticate giuste e, in certi casi, la legalizzazione. Le diciamo con precisione che cosa portare.',
            },
            {
              title: 'Assistenza all\'arrivo',
              text: 'Iscrizione in comune, BSN, assicurazione sanitaria e una stanza o un appartamento in un mercato spietato con i nuovi arrivati. Sappiamo dove cercare e chi chiamare.',
            },
            {
              title: 'Il passo successivo',
              text: 'Quando trova un lavoro, i datori possono assumerla con una soglia retributiva ridotta. Gestiamo il passaggio al permesso per lavoratori altamente qualificati quando arriva il momento.',
            },
          ],
        },
        process: {
          title: 'Come funziona',
          steps: [
            {
              title: 'Verifica',
              text: 'Una conversazione per confermare che ha i requisiti e per pianificare i tempi del trasferimento.',
            },
            {
              title: 'Domanda',
              text: 'Prepariamo e depositiamo la domanda all\'IND e la teniamo aggiornata a ogni cambio di stato.',
            },
            {
              title: 'Arrivo e sistemazione',
              text: 'Organizziamo iscrizione ed essenziali così che possa dedicare l\'anno alla carriera e non alla burocrazia.',
            },
          ],
        },
        fees: {
          title: 'Onorario per l\'anno di orientamento',
          kind: 'tailored',
          amount: 'Su richiesta',
          amountNote: 'L\'anno di orientamento è una procedura breve e ciò che le serve da noi dipende dal fatto che presenti domanda dall\'interno o dall\'esterno dei Paesi Bassi. Dopo una breve verifica del suo titolo e dei suoi tempi riceve un preventivo a prezzo fisso.',
          includes: [
            'Verifica se il suo titolo e la sua data di laurea danno ancora diritto',
            'Domanda preparata e depositata presso l\'IND',
            'Accompagnamento al passaggio verso un permesso di lavoro prima che l\'anno scada',
          ],
        },
        note: 'La finestra di tre anni dopo la laurea è rigida e le classifiche cambiano ogni anno. Se è al limite, ci contatti prima di dare per scontato di essere fuori. Le domande raramente rispettano gli orari d\'ufficio, ed è per questo che i clienti ci raggiungono su una linea WhatsApp personale giorno e notte.',
        conditions: {
          title: 'Chi ha diritto allo zoekjaar',
          intro: 'L\'anno di orientamento è generoso una volta che si è dentro, e severo su chi può entrare. La finestra è la parte che sfugge alle persone.',
          items: [
            'Deve presentare domanda entro tre anni dalla laurea, dal conseguimento del dottorato o dalla conclusione della ricerca.',
            'I laureati di programmi olandesi accreditati di bachelor, master e dottorato si qualificano con il solo titolo olandese.',
            'I laureati internazionali hanno bisogno di un titolo di un\'università fra le prime 200 di una classifica mondiale riconosciuta.',
            'Il permesso dura dodici mesi, non è prorogabile e può essere concesso una sola volta.',
            'Può lavorare come dipendente o come autonomo per tutto l\'anno senza permesso di lavoro e senza soglia retributiva.',
            'Nell\'anno successivo si applica il criterio ridotto per lavoratori altamente qualificati di 3.122 euro (2026).',
          ],
        },
        details: {
          title: 'Far valere l\'anno',
          items: [
            {
              q: 'Che cosa mi rende più facile da assumere durante lo zoekjaar?',
              a: 'Ha libero accesso al mercato del lavoro olandese. Il suo datore di lavoro non ha bisogno di permesso di lavoro né di riconoscimento come sponsor e non paga alcun diritto all\'IND, il che elimina esattamente l\'obiezione che blocca gli altri candidati extra UE. Lo metta nella prima riga, perché la maggior parte dei datori olandesi non lo sa.',
            },
            {
              q: 'Che cosa succede alla fine dei dodici mesi?',
              a: 'Passa a un altro permesso, il più delle volte quello per lavoratori altamente qualificati con il criterio ridotto. Il passaggio va depositato prima della scadenza dell\'anno di orientamento, quindi iniziamo a prepararlo intorno al nono mese e non al dodicesimo.',
            },
            {
              q: 'Posso avviare un\'attività durante l\'anno?',
              a: 'Può iscriversi alla KvK e lavorare come autonomo per tutta la durata. Convertire in seguito su una base imprenditoriale stabile è una domanda separata con un proprio esame, quindi conviene pianificarlo dall\'inizio.',
            },
            {
              q: 'Il mio partner ottiene qualcosa?',
              a: 'Sì. Il suo partner può richiedere un permesso a carico per gli stessi dodici mesi e ha anch\'egli libero accesso al mercato del lavoro.',
            },
          ],
        },
        faq: {
          title: 'Domande frequenti',
          items: [
            {
              q: 'Posso lavorare durante l\'anno di orientamento?',
              a: 'Sì, pienamente e liberamente. Qualsiasi datore di lavoro può assumerla senza permesso di lavoro né sponsor per tutti i dodici mesi.',
            },
            {
              q: 'Mi serve un lavoro o un reddito per presentare domanda?',
              a: 'Non è richiesta alcuna offerta di lavoro. Deve però dimostrare di potersi mantenere, e le spieghiamo passo passo che cosa l\'IND accetta come prova.',
            },
            {
              q: 'Che cosa succede quando l\'anno finisce?',
              a: 'La maggior parte dei neolaureati passa a un permesso per lavoratori altamente qualificati tramite il nuovo datore di lavoro, con una soglia retributiva ridotta che rende più semplice assumerla. Pianifichiamo quella transizione ben prima del dodicesimo mese.',
            },
          ],
        },
        cta: {
          title: 'Il suo titolo di studio ha appena aperto una porta',
          text: 'Ci dica dove e quando si è laureato. Confermeremo i suoi requisiti e tracceremo il suo anno nei Paesi Bassi.',
          label: 'Verifica il mio anno di orientamento',
        },
        form: 'immigration',
        image: '/images/orientation-year.jpg?v=20260731',
        imageAlt: 'Neolaureata che cammina lungo un canale di Amsterdam in autunno',
        image2: '/images/consultation.jpg',
        image2Alt: 'Consulente e cliente discutono i passi successivi',
      },
      {
        slug: 'partner-visa-netherlands',
        menuLabel: 'Visto per partner',
        title: 'Visto per partner nei Paesi Bassi',
        metaTitle: 'Visto per partner nei Paesi Bassi | Porti a casa il suo partner',
        metaDescription: 'Porti il suo partner nei Paesi Bassi con serenità. Seguiamo l\'intera procedura del visto per partner, dai requisiti di reddito all\'esame di integrazione civica e all\'appuntamento in ambasciata.',
        eyebrow: 'Visto familiare',
        intro: [
          'Nessuna domanda pesa più di quella che porta la persona che ama sulla sua porta di casa. Il visto olandese per partner è del tutto ottenibile, ma non perdona i piccoli errori: un documento di reddito nel formato sbagliato, un\'iscrizione all\'esame mancata, un certificato senza il timbro giusto, e si perdono mesi.',
          'Trattiamo queste pratiche con la cura che meritano. Johanna accompagna personalmente i clienti agli appuntamenti, dallo sportello del comune all\'IND, così nessuno dei due si trova mai davanti a un funzionario senza essere preparato.',
        ],
        cardText: 'Accompagnamento attento e personale per portare il suo partner o coniuge nei Paesi Bassi.',
        explainer: {
          title: 'Che cos\'è un visto per partner?',
          text: [
            'Un visto per partner è un soggiorno concesso sulla base della vostra relazione e non del vostro lavoro. Uno di voi, la persona di riferimento, ha già il diritto di vivere nei Paesi Bassi. L\'altra chiede di raggiungerla. Il matrimonio non è richiesto, ma una relazione non matrimoniale deve essere dimostrata come duratura ed esclusiva.',
            'La procedura olandese verifica tre cose: che la relazione sia autentica, che la persona di riferimento abbia un reddito stabile e sufficiente e che gli atti di stato civile stranieri siano correttamente legalizzati e tradotti. La maggior parte dei rigetti nasce dal terzo punto, non dal primo.',
          ],
        },
        forWho: {
          title: 'Chi aiutiamo',
          items: [
            'Cittadini e residenti olandesi che portano un partner dall\'estero',
            'Expat già nei Paesi Bassi il cui partner arriverà più tardi',
            'Coppie sposate e non sposate, compresi partner di lunga data senza certificato di matrimonio',
            'Coppie che hanno già ricevuto un rigetto e questa volta vogliono farlo bene',
          ],
        },
        included: {
          title: 'Che cosa gestiamo insieme',
          blocks: [
            {
              title: 'Esame onesto dei requisiti',
              text: 'Valutiamo il reddito della persona di riferimento rispetto al requisito IND, le prove della relazione ed entrambe le cittadinanze prima di promettere qualsiasi cosa.',
            },
            {
              title: 'L\'MVV e l\'esame di integrazione',
              text: 'Molte cittadinanze devono superare l\'esame base di integrazione civica all\'estero e ritirare un visto d\'ingresso presso l\'ambasciata olandese. Pianifichiamo la preparazione all\'esame e l\'appuntamento stesso.',
            },
            {
              title: 'Legalizzazione dei documenti',
              text: 'Gli atti di nascita e di matrimonio vanno legalizzati o apostillati nel paese d\'origine. Individuiamo esattamente quali documenti richiedono quale trattamento.',
            },
            {
              title: 'Domanda e monitoraggio',
              text: 'Prepariamo e depositiamo l\'intera domanda e teniamo d\'occhio l\'IND fino all\'arrivo della decisione.',
            },
            {
              title: 'L\'arrivo come coppia',
              text: 'Iscrizione, BSN, assicurazione sanitaria e le prime settimane pratiche. Il suo partner dovrebbe arrivare a una vita, non a un elenco di cose da fare.',
            },
          ],
        },
        process: {
          title: 'Il percorso, passo dopo passo',
          steps: [
            {
              title: 'Colloquio in due',
              text: 'Parliamo con entrambi, esaminiamo reddito e documenti e fissiamo tempi realistici.',
            },
            {
              title: 'Preparazione all\'estero',
              text: 'Esame, legalizzazioni e logistica dell\'ambasciata nel paese del suo partner, coordinati da qui.',
            },
            {
              title: 'Deposito e decisione',
              text: 'La domanda arriva all\'IND. La seguiamo e gestiamo subito ogni richiesta aggiuntiva.',
            },
            {
              title: 'Di nuovo insieme',
              text: 'Il suo partner viaggia, si iscrive e riceve il permesso di soggiorno. Siamo lì per l\'atterraggio.',
            },
          ],
        },
        fees: {
          title: 'Onorario per una domanda di visto per partner',
          kind: 'fixed',
          amount: 'Investimento da 895 €',
          includes: [
            'Valutazione delle prove della relazione prima che venga depositato qualsiasi cosa',
            'Fascicoli della persona di riferimento e del richiedente costruiti insieme perché non possano contraddirsi',
            'Requisiti di legalizzazione e traduzione individuati per il suo paese d\'origine',
            'Domanda depositata e monitorata fino alla decisione',
          ],
        },
        conditions: {
          title: 'Che cosa deve essere vero',
          intro: 'Le domande per partner vengono rigettate molto più spesso sulle prove che sui requisiti. Queste sono le condizioni, e i punti in cui i fascicoli si perdono di solito.',
          items: [
            'La persona di riferimento nei Paesi Bassi deve guadagnare almeno 2.523,96 euro lordi al mese, indennità di ferie compresa (2026, rivisto due volte l\'anno).',
            'Quel reddito deve essere duraturo. Un contratto a tempo indeterminato lo soddisfa senz\'altro, uno a termine viene valutato su ciò che resta.',
            'La relazione deve essere esclusiva, di lunga durata e dimostrabile. Matrimonio, unione registrata e relazioni non matrimoniali documentate valgono tutti.',
            'Entrambi i partner devono avere almeno 21 anni.',
            'La maggior parte dei partner deve superare l\'esame base di integrazione civica all\'estero prima che possa essere rilasciato un MVV.',
            'Gli atti stranieri di nascita, matrimonio e stato libero richiedono di norma legalizzazione o apostille più una traduzione giurata.',
          ],
        },
        details: {
          title: 'I punti delicati che gestiamo',
          items: [
            {
              q: 'Che cosa si intende per reddito duraturo?',
              a: 'Un contratto a tempo indeterminato lo soddisfa senz\'altro. Con un contratto a termine l\'IND si chiede se il reddito ci sarà ancora nei dodici mesi successivi, e di norma basta un contratto con almeno un anno residuo oppure una storia lavorativa di tre anni. I lavoratori autonomi vengono valutati su tre anni di bilanci.',
            },
            {
              q: 'Non siamo sposati. È un problema per noi?',
              a: 'No, ma alza l\'asticella delle prove. Costruiamo un fascicolo sulla relazione: storia dell\'indirizzo comune, finanze condivise, viaggi, fotografie nel corso degli anni, tracce delle comunicazioni e dichiarazioni di chi vi conosce. È qui che si perdono le domande rigettate ed è qui che una preparazione attenta le vince.',
            },
            {
              q: 'Chi è esentato dall\'esame di integrazione all\'estero?',
              a: 'I cittadini di UE, SEE, Svizzera, Stati Uniti, Canada, Australia, Nuova Zelanda, Giappone, Corea del Sud e Regno Unito, fra alcuni altri, oltre a chi non può sostenerlo per motivi medici o possiede un titolo di studio olandese o belga. Tutti gli altri sostengono l\'esame presso un\'ambasciata olandese.',
            },
            {
              q: 'Ci è già stato rigettato. Si può rimediare?',
              a: 'Spesso sì. Un rigetto non è una preclusione definitiva, ma il secondo fascicolo deve rispondere esattamente al motivo del primo rigetto invece di ripetere il primo tentativo. Ci mandi la lettera di decisione e avrà una lettura onesta su quale sia la via migliore, una nuova domanda o un\'opposizione formale.',
            },
          ],
        },
        faq: {
          title: 'Le coppie ci chiedono',
          items: [
            {
              q: 'Il mio partner può lavorare una volta arrivato?',
              a: 'Sì. Il permesso di soggiorno per partner comporta libero accesso al mercato del lavoro olandese, quindi può accettare qualsiasi impiego senza un permesso di lavoro separato.',
            },
            {
              q: 'Di quale reddito ho bisogno come persona di riferimento?',
              a: 'L\'IND richiede un reddito autonomo e duraturo a un livello che aggiorna due volte l\'anno. Verifichiamo la sua situazione esatta, compresi i contratti e il lavoro autonomo, durante il colloquio.',
            },
            {
              q: 'Non siamo sposati. È un problema?',
              a: 'No. I Paesi Bassi riconoscono le relazioni durature fra partner non sposati. Dovrà dimostrare la relazione, e la aiutiamo a costruire quel fascicolo in modo convincente.',
            },
          ],
        },
        cta: {
          title: 'Inizi la sua vita qui, insieme',
          text: 'Ci racconti di voi due. Le daremo un quadro chiaro e onesto del percorso e di quanto duri davvero l\'attesa.',
          label: 'Pianifica il nostro visto per partner',
        },
        form: 'immigration',
        image: '/images/partner-visa.jpg?v=20260731',
        imageAlt: 'Coppia a casa nel proprio appartamento olandese',
        image2: '/images/daft-couple.jpg',
        image2Alt: 'Coppia insieme su un canale olandese al tramonto',
      },
      {
        slug: 'family-reunification-netherlands',
        menuLabel: 'Visto per ricongiungimento familiare',
        title: 'Ricongiungimento familiare nei Paesi Bassi',
        metaTitle: 'Ricongiungimento familiare nei Paesi Bassi | Trasferitevi come una sola famiglia',
        metaDescription: 'Ricongiungimento familiare nei Paesi Bassi, gestito con calore e precisione. Permessi per coniugi e figli, ricerca della scuola e un atterraggio morbido per tutta la famiglia.',
        eyebrow: 'Visto familiare',
        intro: [
          'Un trasferimento riesce solo quando arriva bene tutta la famiglia. Il ricongiungimento familiare consente al coniuge e ai figli di raggiungerla nei Paesi Bassi, e farlo per bene significa unire permessi, certificati dal paese d\'origine e pianificazione scolastica in un\'unica operazione coordinata.',
          'Conduciamo quell\'operazione per famiglie attorno a Rotterdam, a Europoort e nella più ampia regione industriale, dove i professionisti internazionali arrivano con un contratto e le famiglie li seguono. È il nostro territorio, e determina tutto: dalle scuole che consigliamo agli sportelli comunali che conosciamo per nome.',
        ],
        cardText: 'Permessi per coniuge e figli, coordinati perché tutta la famiglia arrivi insieme.',
        explainer: {
          title: 'Che cos\'è il ricongiungimento familiare?',
          text: [
            'Il ricongiungimento familiare, gezinshereniging in olandese, è la via che porta partner e figli a vivere con chi ha già un titolo di soggiorno nei Paesi Bassi. È un unico quadro giuridico che copre l\'intero nucleo, non una procedura separata per ciascuna persona.',
            'L\'IND valuta la persona di riferimento tanto quanto i richiedenti: un reddito stabile pari o superiore alla soglia di legge, un alloggio adeguato e atti di stato civile del paese d\'origine che superino la legalizzazione. Per i minori valgono requisiti di prova propri, in materia di affidamento e consenso dei genitori.',
          ],
        },
        forWho: {
          title: 'Pensato per',
          items: [
            'Titolari di permesso di lavoro il cui coniuge e i cui figli sono ancora all\'estero',
            'Famiglie che si trasferiscono nei Paesi Bassi insieme al richiedente principale',
            'Genitori che portano con sé figli minori di una relazione precedente',
            'Datori di lavoro che organizzano il ricongiungimento familiare per uno specialista trasferito',
          ],
        },
        included: {
          title: 'Come portiamo qui una famiglia',
          blocks: [
            {
              title: 'Strategia del fascicolo familiare',
              text: 'Un piano per ogni componente: chi presenta domanda e quando, quali permessi si agganciano al suo e come si incastrano i tempi.',
            },
            {
              title: 'Certificati fatti bene',
              text: 'Atti di matrimonio e di nascita, documenti sull\'affidamento dove rilevanti, tutti legalizzati o apostillati correttamente già la prima volta.',
            },
            {
              title: 'Domande all\'IND per ciascun componente',
              text: 'Prepariamo e depositiamo le domande per il coniuge e per i figli e gestiamo ogni richiesta successiva.',
            },
            {
              title: 'Scuole e servizi per l\'infanzia',
              text: 'Scuole internazionali, bilingui o olandesi, scelte per i suoi figli e per il suo tragitto. Organizziamo visite e presentazioni prima del suo arrivo.',
            },
            {
              title: 'Un arrivo vero',
              text: 'Iscrizioni, numeri BSN per tutti, sanità e le piccole cose che fanno sembrare una casa una decisione ben presa.',
            },
          ],
        },
        process: {
          title: 'Da separati a insieme',
          steps: [
            {
              title: 'Colloquio familiare',
              text: 'Mappiamo cittadinanza, documenti ed esigenze di ogni componente in un\'unica conversazione.',
            },
            {
              title: 'Preparare e depositare',
              text: 'I certificati vengono legalizzati mentre in parallelo costruiamo e depositiamo le domande, risparmiando mesi.',
            },
            {
              title: 'Viaggio e sistemazione',
              text: 'Visti d\'ingresso, voli, iscrizioni e inizio della scuola, in sequenza perché nessuno debba aspettare nessun altro.',
            },
          ],
        },
        fees: {
          title: 'Onorario per una domanda di ricongiungimento familiare',
          kind: 'fixed',
          amount: 'Investimento da 1.195 €',
          includes: [
            'Requisiti di reddito e di persona di riferimento verificati sul suo contratto reale',
            'Un fascicolo coordinato per il suo partner e per ciascun figlio',
            'Requisiti di legalizzazione e traduzione giurata individuati paese per paese',
            'Domande depositate insieme e monitorate fino alla decisione',
          ],
        },
        note: 'Le domande per i figli dipendono da dettagli che i genitori raramente si aspettano, come il consenso del genitore che resta. Esponga l\'intera situazione familiare durante il colloquio così che nulla emerga tardi.',
        conditions: {
          title: 'Condizioni per il fascicolo familiare',
          intro: 'Una sola persona di riferimento regge l\'intera domanda familiare. Tutto ciò che segue viene verificato su quella persona e su documenti rilasciati in paesi che avete già lasciato.',
          items: [
            'Il titolare del permesso principale funge da persona di riferimento e deve avere un permesso di soggiorno valido su base non temporanea.',
            'Reddito di almeno 2.523,96 euro lordi al mese, indennità di ferie compresa, valutato come duraturo (dato 2026).',
            'I figli devono essere minorenni, non sposati e devono aver fatto parte della famiglia prima del trasferimento nei Paesi Bassi.',
            'Se un genitore resta all\'estero, serve il suo consenso scritto prima che un figlio possa trasferirsi.',
            'I certificati della maggior parte dei paesi richiedono legalizzazione o apostille e una traduzione giurata in olandese, inglese, francese o tedesco.',
            'Le domande depositate insieme a quella del richiedente principale vengono decise più rapidamente di quelle depositate in un secondo momento.',
          ],
        },
        details: {
          title: 'Come funzionano davvero i fascicoli familiari',
          items: [
            {
              q: 'Conviene presentare domanda insieme o seguire più tardi?',
              a: 'Insieme, ogni volta che è possibile. Una domanda familiare simultanea viene decisa insieme al fascicolo principale, si muove su un unico calendario ed evita un secondo esame del reddito. Seguire più tardi è del tutto praticabile, costa semplicemente una procedura in più e diversi mesi di separazione.',
            },
            {
              q: 'Quanto dura la legalizzazione?',
              a: 'Da due settimane a sei mesi a seconda del paese, perché in molti luoghi la catena passa dal ministero degli esteri locale e poi dall\'ambasciata olandese. È la causa di ritardo di gran lunga più frequente nei fascicoli familiari, ed è per questo che la avviamo prima di ogni altra cosa.',
            },
            {
              q: 'I nostri figli possono iniziare subito la scuola?',
              a: 'Sì. Nei Paesi Bassi i minori hanno sia il diritto sia l\'obbligo di frequentare la scuola a prescindere dallo stato del permesso, e le scuole internazionali e le classi per neoarrivati di norma li accolgono nel giro di settimane. Conduciamo la ricerca della scuola in parallelo al permesso, non dopo.',
            },
            {
              q: 'E se un figlio compie diciotto anni durante la procedura?',
              a: 'L\'IND valuta l\'età al momento del deposito, quindi un figlio che era minorenne quando la domanda è stata presentata non perde il diritto per aver compiuto gli anni mentre è pendente. È esattamente il motivo per cui depositiamo presto invece di depositare alla perfezione.',
            },
          ],
        },
        faq: {
          title: 'Che cosa vogliono sapere le famiglie',
          items: [
            {
              q: 'Il mio coniuge può lavorare nei Paesi Bassi?',
              a: 'Nella maggior parte dei casi sì. I coniugi dei lavoratori altamente qualificati e della maggior parte dei titolari di permesso ottengono libero accesso al mercato del lavoro fin dall\'arrivo.',
            },
            {
              q: 'I miei figli dovranno imparare l\'olandese?',
              a: 'Non necessariamente. Le regioni di Rotterdam e dell\'Aia hanno ottime scuole internazionali e bilingui. I bambini più piccoli spesso imparano l\'olandese in fretta nelle scuole locali, e noi consigliamo per ogni bambino, non per brochure.',
            },
            {
              q: 'Possiamo presentare domanda tutti insieme?',
              a: 'Sì, e di norma è quello che conviene fare. Le domande raggruppate tengono la famiglia su un unico calendario e su un unico momento decisionale. La strutturiamo così ogni volta che è possibile.',
            },
          ],
        },
        cta: {
          title: 'Porti tutti a casa',
          text: 'Ci dica chi si trasferisce e da dove. Progetteremo un unico piano che faccia arrivare tutta la sua famiglia insieme.',
          label: 'Pianifica il trasferimento della nostra famiglia',
        },
        form: 'immigration',
        image: '/images/family-reunification.jpg?v=20260731',
        imageAlt: 'Famiglia riunita in una luminosa casa a schiera olandese',
        image2: '/images/family-unpacking.jpg?v=20260731',
        image2Alt: 'Famiglia sistemata nel nuovo salotto olandese',
      },
      {
        slug: 'startup-visa-netherlands',
        menuLabel: 'Visto startup',
        title: 'Visto startup nei Paesi Bassi',
        metaTitle: 'Visto startup nei Paesi Bassi | Per imprenditori innovativi',
        metaDescription: 'Il visto startup nei Paesi Bassi dà ai fondatori extra UE un permesso di soggiorno di un anno per costruire un\'impresa innovativa con un facilitatore riconosciuto. Requisiti, procedura e onorari.',
        eyebrow: 'Visto per fondatori',
        intro: [
          'Il visto startup nei Paesi Bassi è pensato per imprenditori internazionali che vogliono sviluppare qui un\'impresa innovativa. Concede una fase di avvio di un anno in cui costruire l\'azienda al fianco di un facilitatore riconosciuto, dentro un ecosistema con accesso reale a investitori, incubatori e mercati internazionali.',
          'Seguiamo l\'intero arco, non solo il permesso: l\'abbinamento con il facilitatore, il piano di sviluppo che l\'IND vuole leggere e il lato pratico dell\'arrivo, dalla costituzione della società a un posto dove vivere.',
        ],
        cardText: 'Un permesso per fondatori di un anno per costruire la sua impresa innovativa nell\'ecosistema olandese.',
        explainer: {
          title: 'Che cos\'è il visto startup?',
          text: [
            'Il visto startup è un permesso di soggiorno di un anno per imprenditori che costruiscono un\'impresa innovativa nei Paesi Bassi. Esiste perché un\'azienda davvero nuova raramente ha, il primo giorno, il fatturato o la storia che il normale permesso per lavoratori autonomi richiede.',
            'Il suo tratto distintivo è il facilitatore: un mentore esperto riconosciuto dall\'agenzia olandese per l\'impresa che accompagna la sua azienda nel primo anno. Viene valutato sull\'innovazione del piano e su quella collaborazione, non sul fatturato. L\'anno è una pista di decollo verso il permesso per lavoratori autonomi, e preparare presto quel passo successivo è la differenza fra proseguire e ricominciare da capo.',
          ],
        },
        forWho: {
          title: 'Chi può richiedere il visto startup',
          items: [
            'Imprenditori extra UE che introducono un prodotto, un servizio o una tecnologia innovativa sul mercato olandese',
            'Fondatori pronti a lavorare con un facilitatore riconosciuto che offra mentorship durante la fase di avvio',
            'Team che hanno bisogno di una base di soggiorno per sviluppare l\'attività in territorio olandese',
            'Fondatori che pianificano il passaggio al permesso per lavoratori autonomi dopo il primo anno',
          ],
        },
        conditions: {
          title: 'Requisiti del visto startup',
          intro: 'L\'IND valuta l\'idea e il facilitatore valuta lei. Il richiedente deve dimostrare:',
          items: [
            'Un concetto imprenditoriale innovativo',
            'La collaborazione con un facilitatore di startup riconosciuto',
            'Un piano strutturato di sviluppo della startup',
            'Mezzi finanziari sufficienti per il primo anno',
            'Che il fondatore svolga un ruolo attivo nell\'impresa',
          ],
        },
        included: {
          title: 'Dove aggiungiamo valore',
          blocks: [
            {
              title: 'Verifica onesta di fattibilità',
              text: 'Le diciamo subito se il suo caso soddisfa i criteri di innovazione, e che cosa rafforzare in caso contrario, prima che impegni denaro o mesi.',
            },
            {
              title: 'Abbinamento con il facilitatore',
              text: 'Un facilitatore riconosciuto deve sostenere la sua domanda. La aiutiamo ad avvicinare quelli adatti al suo settore e alla sua fase e coordiniamo l\'accordo.',
            },
            {
              title: 'Preparazione del piano di startup',
              text: 'Aiutiamo a strutturare il piano di sviluppo richiesto, che descrive il suo ruolo, l\'innovazione e le tappe dell\'anno.',
            },
            {
              title: 'Gestione della domanda',
              text: 'Prepariamo il fascicolo per l\'IND, lo depositiamo e gestiamo ogni scambio con le autorità fino alla decisione.',
            },
            {
              title: 'Arrivo del fondatore',
              text: 'Iscrizione, BSN, casa e i primi colloqui con la KvK, così che l\'azienda e il fondatore abbiano entrambi un indirizzo.',
            },
          ],
        },
        process: {
          title: 'Il nostro metodo di lavoro',
          steps: [
            {
              title: 'Valutazione dei requisiti',
              text: 'Valutiamo se la sua idea imprenditoriale rientri fra le startup innovative secondo i criteri IND.',
            },
            {
              title: 'Coordinamento con il facilitatore',
              text: 'Assistiamo nella ricerca e nella collaborazione con i facilitatori riconosciuti e nella firma dell\'accordo.',
            },
            {
              title: 'Piano di startup',
              text: 'Aiutiamo a strutturare il piano di sviluppo su cui viene giudicata la domanda.',
            },
            {
              title: 'Domanda di permesso di soggiorno',
              text: 'Prepariamo e depositiamo la domanda di visto startup all\'IND, poi la monitoriamo.',
            },
          ],
        },
        fees: {
          title: 'Onorario per una domanda di visto startup',
          kind: 'fixed',
          amount: 'Investimento da 2.495 €',
          includes: [
            'Strategia di immigrazione e consulenza sui requisiti',
            'Supporto nella costruzione del piano su cui viene giudicata la domanda',
            'Selezione del facilitatore e coordinamento',
            'Domanda depositata presso l\'IND e monitorata fino alla decisione',
          ],
        },
        note: 'Il permesso startup dura un anno e non viene prorogato come tale. Il passo successivo previsto è il permesso per lavoratori autonomi, e iniziamo a preparare quel fascicolo molto prima che il suo anno finisca.',
        details: {
          title: 'Dettagli da leggere prima di presentare domanda',
          items: [
            {
              q: 'Che cosa si considera innovazione?',
              a: 'L\'innovazione può essere una nuova tecnologia, un modello di servizio innovativo o un nuovo metodo di produzione. Nella pratica l\'IND si chiede se il prodotto o il servizio sia davvero nuovo per i Paesi Bassi, e l\'avallo del suo facilitatore pesa realmente in quel giudizio.',
            },
            {
              q: 'Che cosa succede dopo l\'anno di startup?',
              a: 'Durante l\'anno sviluppa l\'attività e si prepara alla fase successiva. I fondatori chiedono poi il permesso di soggiorno per lavoratori autonomi per continuare a gestire l\'azienda nei Paesi Bassi, valutato sul valore economico dell\'impresa.',
            },
            {
              q: 'Che cosa fa concretamente il facilitatore?',
              a: 'Un facilitatore riconosciuto offre mentorship durante la fase di avvio: orientamento sul piano, sul mercato e sulle tappe. Il rapporto è una condizione formale del permesso, non un extra facoltativo, quindi l\'abbinamento conta più di quanto la maggior parte dei fondatori si aspetti.',
            },
          ],
        },
        faq: {
          title: 'Domande dei fondatori',
          items: [
            {
              q: 'Posso portare la mia famiglia con un visto startup?',
              a: 'Sì. Il suo partner e i suoi figli possono chiedere il soggiorno insieme a lei, e il suo partner è libero di lavorare mentre lei costruisce.',
            },
            {
              q: 'Serve un investimento minimo?',
              a: 'Per il visto startup non è richiesto alcun importo fisso di investimento. Deve però dimostrare mezzi sufficienti per vivere durante l\'anno, e la aiutiamo a documentarli.',
            },
            {
              q: 'Posso presentare domanda se la mia azienda opera già all\'estero?',
              a: 'Spesso sì, se l\'attività olandese è davvero nuova e innovativa per questo mercato. Lo valutiamo onestamente al colloquio invece di lasciarglielo scoprire in un rigetto.',
            },
          ],
        },
        cta: {
          title: 'Lanci la sua startup nei Paesi Bassi',
          text: 'Ci racconti la sua azienda in una riga. Le diremo se il visto startup è la sua via e chi dovrebbe facilitarla.',
          label: 'Parliamo della tua startup',
        },
        form: 'immigration',
        image: '/images/startup-visa.jpg?v=20260731',
        imageAlt: 'Fondatore in un ufficio loft affacciato sul lungofiume di Rotterdam',
        image2: '/images/startup-team.jpg',
        image2Alt: 'Team fondatore al lavoro insieme in un ufficio condiviso',
      },
      {
        slug: 'daft-visa-netherlands',
        menuLabel: 'Visto DAFT',
        title: 'Visto DAFT nei Paesi Bassi',
        metaTitle: 'Visto DAFT nei Paesi Bassi | Dutch American Friendship Treaty',
        metaDescription: 'Il visto DAFT nei Paesi Bassi consente ai cittadini statunitensi di vivere e lavorare qui come imprenditori con un investimento aziendale di 4.500 euro. Requisiti, metodo di lavoro e onorari.',
        eyebrow: 'Per cittadini statunitensi',
        intro: [
          'Il visto DAFT nei Paesi Bassi, concesso in forza del Dutch American Friendship Treaty, è la via d\'ingresso più accessibile per i cittadini statunitensi che vogliono gestire qui una propria attività. Grazie al trattato fra Paesi Bassi e Stati Uniti, gli imprenditori americani rientrano in condizioni più flessibili rispetto al normale permesso per imprenditori.',
          'È la via che usano più spesso liberi professionisti, consulenti e piccoli imprenditori. Accanto al fascicolo di immigrazione ci occupiamo del lato pratico dell\'arrivo: costituzione della società, casa e soggiorno per la famiglia che arriva con lei.',
        ],
        cardText: 'La via del trattato che permette agli americani di vivere e lavorare nei Paesi Bassi come imprenditori.',
        explainer: {
          title: 'Che cos\'è il permesso DAFT?',
          text: [
            'Il permesso DAFT deriva dal Dutch American Friendship Treaty, un accordo del 1956 che offre ai cittadini degli Stati Uniti una via al lavoro autonomo nei Paesi Bassi di rara accessibilità. È aperto ai soli americani ed è, con ampio margine, il permesso imprenditoriale più semplice del paese.',
            'Il trattato sostituisce il sistema a punti cui sono soggette le altre nazionalità con un\'unica verifica lineare: registrare una vera impresa olandese e mantenere un investimento minimo definito nel suo capitale. Non c\'è alcun requisito di innovazione, nessun facilitatore e nessuna valutazione del suo piano d\'impresa. È il mantenimento dell\'investimento a tenere in vita il permesso al rinnovo.',
          ],
        },
        forWho: {
          title: 'A chi si rivolge il visto DAFT',
          items: [
            'Liberi professionisti e consulenti americani che portano la loro attività in Europa',
            'Imprenditori statunitensi che aprono un\'impresa olandese',
            'Professionisti da remoto che riorganizzano il proprio lavoro come attività autonoma',
            'Coniugi e famiglie americane che si trasferiscono insieme al richiedente',
          ],
        },
        conditions: {
          title: 'Requisiti del visto DAFT',
          intro: 'Il trattato sostituisce la valutazione economica a punti del suo piano d\'impresa con una semplice verifica sull\'investimento. Il richiedente deve di norma:',
          items: [
            'Possedere la cittadinanza statunitense',
            'Registrare una società nei Paesi Bassi',
            'Investire almeno 4.500 euro nell\'impresa',
            'Iscriversi alla Camera di Commercio olandese (KvK)',
            'Mantenere l\'investimento aziendale richiesto',
          ],
        },
        included: {
          title: 'Il percorso DAFT completo',
          blocks: [
            {
              title: 'Consulenza sulla forma giuridica',
              text: 'Eenmanszaak o BV, e che cosa significa ciascuna per il suo requisito di investimento e per le imposte. Le spieghiamo i compromessi in parole chiare prima che scelga.',
            },
            {
              title: 'Registrazione dell\'impresa',
              text: 'Iscrizione alla KvK, conto bancario aziendale olandese e conferimento del capitale di 4.500 euro, documentato nel modo in cui l\'IND vuole vederlo.',
            },
            {
              title: 'Gestione della domanda all\'IND',
              text: 'Prepariamo e depositiamo la sua domanda di soggiorno in forza del trattato e gestiamo ogni scambio con l\'IND fino alla decisione.',
            },
            {
              title: 'Presentazione a un commercialista',
              text: 'Lo status DAFT va mantenuto al rinnovo, e la sua contabilità è la prova. La mettiamo in contatto con commercialisti che conoscono bene il trattato.',
            },
            {
              title: 'Ambientarsi come famiglia',
              text: 'Soggiorno per coniuge e figli, iscrizioni, sanità e casa, organizzati insieme all\'avvio dell\'attività.',
            },
          ],
        },
        process: {
          title: 'Il nostro metodo di lavoro',
          steps: [
            {
              title: 'Consulenza sull\'immigrazione',
              text: 'Valutiamo i suoi requisiti in forza del trattato DAFT e tracciamo il percorso attorno alla sua attività, alla sua famiglia e ai suoi tempi.',
            },
            {
              title: 'Avvio dell\'impresa',
              text: 'La guidiamo nella registrazione della società e negli adempimenti amministrativi che ne conseguono.',
            },
            {
              title: 'Investimento e documentazione',
              text: 'Ci assicuriamo che l\'investimento richiesto sia effettuato e documentato nel modo in cui l\'IND vuole vederlo.',
            },
            {
              title: 'Domanda di permesso di soggiorno',
              text: 'Prepariamo e depositiamo la domanda DAFT all\'IND e gestiamo ogni scambio fino alla decisione.',
            },
          ],
        },
        fees: {
          title: 'Onorario per una domanda DAFT',
          kind: 'fixed',
          amount: 'Investimento da 2.295 €',
          includes: [
            'Valutazione dei requisiti in forza del Dutch American Friendship Treaty',
            'Registrazione della società e investimento strutturati per superare la verifica del trattato',
            'Domanda di permesso di soggiorno preparata e depositata',
            'Consulenza sul mantenimento dell\'investimento nei rinnovi successivi',
          ],
        },
        note: 'Il permesso di soggiorno viene di norma concesso per due anni ed è rinnovabile. I 4.500 euro devono restare investiti nell\'impresa per tutto il tempo in cui mantiene lo status DAFT, perché i rinnovi guardano al suo bilancio.',
        details: {
          title: 'Dettagli da leggere prima di presentare domanda',
          items: [
            {
              q: 'Che cos\'è esattamente il permesso di soggiorno DAFT?',
              a: 'Consente ai cittadini statunitensi di vivere nei Paesi Bassi gestendo qui una propria impresa. A differenza del normale permesso di soggiorno per imprenditori, la via DAFT non richiede una valutazione economica a punti del piano d\'impresa. Il requisito principale è l\'investimento aziendale minimo.',
            },
            {
              q: 'Eenmanszaak o BV?',
              a: 'Entrambe possono soddisfare il trattato. L\'impresa individuale è più leggera ed economica da gestire; la BV limita la responsabilità e si adatta alla crescita e agli investitori. La scelta cambia il modo in cui si documenta l\'investimento e il modo in cui viene tassato, quindi consigliamo sui suoi numeri e non su una regola generale.',
            },
            {
              q: 'Che cosa significa in pratica mantenere l\'investimento?',
              a: 'Il capitale deve restare nell\'impresa, visibile in bilancio, e non essere prelevato una volta ottenuto il permesso. La sua contabilità è la prova al rinnovo, ed è per questo che presentiamo i clienti a commercialisti che conoscono bene il trattato.',
            },
          ],
        },
        faq: {
          title: 'Gli americani ci chiedono',
          items: [
            {
              q: 'Mia moglie può lavorare nei Paesi Bassi con il DAFT?',
              a: 'Sì. Il coniuge riceve un permesso di soggiorno con libero accesso al mercato del lavoro, quindi può accettare un impiego o avviare una propria attività.',
            },
            {
              q: 'Servono clienti o fatturato prima di presentare domanda?',
              a: 'All\'inizio non si applica alcuna soglia di fatturato. Servono l\'investimento, un\'impresa registrata e l\'intenzione di gestirla davvero. Al momento del rinnovo la contabilità dovrà mostrare un\'impresa viva.',
            },
            {
              q: 'Il DAFT porta al soggiorno permanente?',
              a: 'Può portarci. Dopo cinque anni di soggiorno regolare e continuativo si può di norma chiedere il soggiorno permanente o la naturalizzazione, nel rispetto dei requisiti di integrazione. Molti dei nostri clienti DAFT seguono quel percorso.',
            },
          ],
        },
        cta: {
          title: 'Si trasferisca nei Paesi Bassi con il trattato DAFT',
          text: 'Ci dica di che cosa si occupa. Tracceremo il suo percorso DAFT, dall\'investimento al permesso, in una sola conversazione.',
          label: 'Avvia il mio piano DAFT',
        },
        form: 'immigration',
        image: '/images/daft-visa.jpg?v=20260731',
        imageAlt: 'Fondatore americano al lavoro in uno studio di design nei Paesi Bassi',
        image2: '/images/daft-couple.jpg',
        image2Alt: 'Coppia americana che si ambienta in una città olandese',
      },
      {
        slug: 'business-schengen-visa-netherlands',
        menuLabel: 'Visto per affari',
        title: 'Visto Schengen per affari nei Paesi Bassi',
        metaTitle: 'Visto Schengen per affari nei Paesi Bassi | Assistenza per soggiorni brevi',
        metaDescription: 'Visti Schengen per affari di breve durata per i Paesi Bassi, preparati come si deve. Lettere di invito, fascicoli per l\'ambasciata e assistenza alle delegazioni in visita a partner olandesi.',
        eyebrow: 'Soggiorno breve',
        intro: [
          'Non ogni viaggio nei Paesi Bassi è un trasferimento. Si firmano accordi, si ispezionano porti, si costruiscono collaborazioni, e per molte cittadinanze tutto questo richiede un visto Schengen di breve durata: fino a 90 giorni entro un periodo di 180 giorni, per motivi di affari.',
          'Questi fascicoli si giocano tutto al consolato, ed è un mondo che conosciamo a fondo. La nostra reputazione è nata nel mondo delle ambasciate, il che significa che sappiamo che aspetto ha un fascicolo aziendale convincente visto dall\'altra parte del banco.',
        ],
        cardText: 'Visti di breve durata per riunioni, trattative e visite ai siti nei Paesi Bassi.',
        explainer: {
          title: 'Che cos\'è un visto per affari?',
          text: [
            'Un visto per affari è un visto Schengen di breve durata, di tipo C, per riunioni, trattative, congressi e visite ai siti. Consente fino a 90 giorni entro qualunque periodo di 180 giorni in tutta l\'area Schengen e non permette di assumere un impiego nei Paesi Bassi.',
            'I cittadini di molti paesi devono ottenerlo prima di partire; altri ne sono esentati per i soggiorni brevi. La domanda viene decisa dal consolato sulla base dell\'invito, della sua storia di viaggi, dell\'assicurazione e della prova che tornerà, ed è per questo che il fascicolo di supporto conta più del modulo.',
          ],
        },
        forWho: {
          title: 'Chi viaggia di solito',
          items: [
            'Dirigenti e specialisti in visita a partner o clienti olandesi',
            'Delegazioni che partecipano a trattative, fiere o ispezioni portuali e di impianto',
            'Aziende olandesi che invitano ospiti internazionali e hanno bisogno che le pratiche siano fatte bene',
            'Viaggiatori d\'affari abituali che vogliono visti per ingressi multipli impostati correttamente',
          ],
        },
        included: {
          title: 'Che cosa contiene un fascicolo solido',
          blocks: [
            {
              title: 'Scopo e invito',
              text: 'Una lettera di invito precisa dall\'azienda ospitante olandese, che indichi chi, perché e per quanto tempo. La redigiamo o la esaminiamo perché risponda alle domande del consolato prima che vengano poste.',
            },
            {
              title: 'Documentazione di supporto',
              text: 'Legami con il suo paese d\'origine, mezzi finanziari, assicurazione e programma di viaggio, raccolti in un fascicolo che risulti credibile al primo sguardo.',
            },
            {
              title: 'Strategia sull\'appuntamento',
              text: 'Il consolato giusto, il tipo di appuntamento giusto e la preparazione alle domande che potrebbero esserle poste allo sportello.',
            },
            {
              title: 'Assistenza al soggetto ospitante',
              text: 'Per le aziende olandesi che ricevono ospiti, gestiamo il lato dell\'invito: lettere, garanzie dove opportuno e calendarizzazione attorno alle date delle vostre riunioni.',
            },
          ],
        },
        process: {
          title: 'Dall\'invito all\'arrivo',
          steps: [
            {
              title: 'Ci informi',
              text: 'Chi viaggia, da dove e per che cosa. Confermiamo subito il tipo di visto corretto.',
            },
            {
              title: 'Costruire il fascicolo',
              text: 'Invito, prove e moduli si compongono in giorni, non in settimane.',
            },
            {
              title: 'Consolato e viaggio',
              text: 'Appuntamento prenotato, fascicolo depositato e la sua visita procede come previsto.',
            },
          ],
        },
        fees: {
          title: 'Onorario per una domanda di visto per affari',
          kind: 'fixed',
          amount: 'Investimento da 795 €',
          includes: [
            'Individuazione del tipo di visto adatto allo scopo e alla durata del suo viaggio',
            'Invito e documenti giustificativi preparati secondo lo standard consolare',
            'Appuntamento prenotato e fascicolo assemblato per il deposito',
            'Consulenza su assicurazione di viaggio e prova dei mezzi',
          ],
        },
        note: 'Un visto Schengen per affari consente riunioni e trattative, non un impiego. Se le sue visite stanno diventando lavoro regolare nei Paesi Bassi, ci parli di un permesso su base lavorativa prima che diventi un problema alla frontiera.',
        conditions: {
          title: 'Che cosa consente e che cosa non consente questo visto',
          intro: 'Qui i limiti contano più dei requisiti, perché usare questo visto per l\'attività sbagliata espone sia il viaggiatore sia l\'ospite olandese.',
          items: [
            'Un massimo di novanta giorni di soggiorno entro qualsiasi periodo di centottanta giorni in tutta l\'area Schengen.',
            'Riunioni, trattative, formazione, fiere e visite ai siti sono consentite. Il lavoro retribuito nei Paesi Bassi no.',
            'È richiesto un invito formale dall\'azienda ospitante olandese, e all\'ospite può essere chiesto di assumersi la responsabilità dei costi.',
            'È obbligatoria un\'assicurazione sanitaria di viaggio con copertura di almeno 30.000 euro, valida in tutta l\'area Schengen.',
            'Vanno forniti prova dell\'alloggio, del viaggio di ritorno e di mezzi sufficienti per il soggiorno.',
            'Depositi presso la rappresentanza olandese solo se i Paesi Bassi sono la sua destinazione principale, altrimenti la domanda spetta al paese in cui trascorre più tempo.',
          ],
        },
        details: {
          title: 'Ottenere una decisione più solida',
          items: [
            {
              q: 'Perché i visti per affari vengono rigettati?',
              a: 'Quasi sempre per uno di tre motivi: lo scopo del viaggio non risulta credibile dai documenti, il richiedente non riesce a dimostrare legami sufficienti con il proprio paese, oppure viaggi Schengen precedenti sono stati usati impropriamente. Tutti e tre sono problemi di fascicolo e tutti e tre si possono affrontare prima del deposito.',
            },
            {
              q: 'Come si ottiene un visto per ingressi multipli?',
              a: 'I visti per ingressi multipli da uno a cinque anni vanno a richiedenti con una storia di viaggi Schengen impeccabile e un rapporto d\'affari continuativo dimostrabile. Strutturiamo il fascicolo perché quella ricorrenza sia visibile nelle prove invece di essere chiesta come favore.',
            },
            {
              q: 'Con quanto anticipo conviene presentare domanda?',
              a: 'Le domande si possono depositare fino a sei mesi prima del viaggio e non oltre quindici giorni prima. Il vincolo vero è la disponibilità di appuntamenti al consolato, e nelle regioni affollate e in alta stagione gli slot possono essere a sei settimane di distanza. Ci dica la data per tempo.',
            },
            {
              q: 'Il nostro specialista deve lavorare in loco. È questo il visto giusto?',
              a: 'No. Installare impianti, realizzare un progetto o prestare servizi per un cliente olandese è lavoro, e richiede un permesso su base lavorativa o una notifica secondo le norme sui lavoratori distaccati. Usare un visto per affari espone la sua azienda e il suo dipendente. Le diremo quale strumento si applica davvero.',
            },
          ],
        },
        faq: {
          title: 'Prima di prenotare i voli',
          items: [
            {
              q: 'Con quanto anticipo dovremmo presentare domanda?',
              a: 'I tempi dei consolati variano molto per paese e per stagione. Come regola, cominci appena il viaggio è certo. Confermiamo la disponibilità attuale di appuntamenti al suo consolato quando ci contatta.',
            },
            {
              q: 'Posso visitare altri paesi Schengen con questo visto?',
              a: 'Sì. Un visto Schengen consente di viaggiare in tutta l\'area Schengen, ma la domanda va presentata tramite i Paesi Bassi quando sono la sua destinazione principale.',
            },
            {
              q: 'E se una domanda precedente è stata rigettata?',
              a: 'Un rigetto non è la fine. Analizziamo i motivi indicati, correggiamo i punti deboli del fascicolo e strutturiamo di conseguenza la nuova domanda.',
            },
          ],
        },
        cta: {
          title: 'Ha una riunione da organizzare nei Paesi Bassi?',
          text: 'Ci mandi le date del viaggio e lo scopo. Le diremo esattamente che cosa serve al fascicolo e con quanta rapidità può muoversi.',
          label: 'Organizza il mio visto per affari',
        },
        form: 'immigration',
        image: '/images/business-visa.jpg?v=20260731',
        imageAlt: 'Dirigente che arriva in auto alla sede centrale di un\'azienda olandese',
        image2: '/images/business-signing.jpg',
        image2Alt: 'Firma di documenti durante una riunione d\'affari',
      },
      {
        slug: 'residence-permit-netherlands',
        menuLabel: 'Permessi di soggiorno',
        title: 'Permesso di soggiorno nei Paesi Bassi per expat',
        metaTitle: 'Permesso di soggiorno nei Paesi Bassi per expat | Rinnovi e consulenza',
        metaDescription: 'I permessi di soggiorno nei Paesi Bassi spiegati e gestiti: prime domande, rinnovi, cambi di scopo e la strada verso il soggiorno permanente, con guida personale.',
        eyebrow: 'Soggiorno',
        intro: [
          'Ogni vita da expat nei Paesi Bassi poggia su un permesso di soggiorno, e il permesso stesso ha una vita: viene concesso, rinnovato, modificato quando cambia la sua situazione e infine trasformato in soggiorno permanente. Basta mancare una finestra di rinnovo o cambiare lavoro senza verificarne le conseguenze e anni di costruzione attenta possono vacillare.',
          'Facciamo da ufficio immigrazione a cui i nostri clienti non devono mai pensare. Teniamo d\'occhio le date, prepariamo i fascicoli e Johanna accompagna di persona i clienti agli appuntamenti con l\'IND, così una convocazione non sembra mai una minaccia.',
        ],
        cardText: 'Primi permessi, rinnovi, modifiche e la strada verso il soggiorno permanente, tutto sotto un unico tetto.',
        explainer: {
          title: 'Che cos\'è un permesso di soggiorno olandese?',
          text: [
            'Un permesso di soggiorno, verblijfsvergunning in olandese, è il documento che rende legittima la sua permanenza oltre i 90 giorni. Lo rilascia l\'IND, indica sempre uno scopo di soggiorno come lavoro, famiglia o studio, e i diritti che ne derivano seguono quello scopo e non la tessera in sé.',
            'I permessi sono temporanei o permanenti. Nel lungo periodo conta soprattutto quale scopo detiene e per quanto tempo, perché è il soggiorno regolare e ininterrotto ad aprire alla fine il soggiorno permanente e la naturalizzazione. Cambiare scopo è possibile, ma è il momento a decidere se gli anni maturati sopravvivono al cambio.',
          ],
        },
        forWho: {
          title: 'Quando chiamarci',
          items: [
            'Il suo permesso si avvicina alla scadenza',
            'La sua situazione è cambiata: nuovo datore di lavoro, nuova relazione, un divorzio, una nuova società',
            'Si avvicina ai cinque anni di soggiorno e desidera lo status permanente',
            'Ha un permesso ma non è sicuro di che cosa le consenta davvero di fare',
          ],
        },
        included: {
          title: 'I nostri servizi sul soggiorno',
          blocks: [
            {
              title: 'Check-up del permesso',
              text: 'Un esame del suo permesso attuale, delle sue condizioni e della sua scadenza, con un calendario chiaro di che cosa deve avvenire e quando.',
            },
            {
              title: 'Rinnovi senza drammi',
              text: 'Prepariamo le domande di rinnovo per tempo e in modo completo, così la continuità dei suoi diritti di soggiorno non è mai in discussione.',
            },
            {
              title: 'Cambio di scopo',
              text: 'Da neolaureato a dipendente, da partner a indipendente, da startup a lavoratore autonomo. Gestiamo il passaggio così che la nuova base sia assicurata prima che finisca la vecchia.',
            },
            {
              title: 'Soggiorno permanente e oltre',
              text: 'Dopo cinque anni di soggiorno regolare può avere diritto a un permesso permanente o al soggiorno di lungo periodo UE, di norma con un requisito di integrazione civica. Valutiamo se è pronto e costruiamo la domanda.',
            },
          ],
        },
        process: {
          title: 'Come lavoriamo',
          steps: [
            {
              title: 'Esame',
              text: 'Verifichiamo il suo status attuale e segnaliamo ogni data e condizione che conta.',
            },
            {
              title: 'Preparazione',
              text: 'La domanda giusta, assemblata in anticipo rispetto alla scadenza e con margine.',
            },
            {
              title: 'Messa in sicurezza',
              text: 'Deposito, monitoraggio e il suo nuovo permesso in mano, con la tappa successiva già in calendario.',
            },
          ],
        },
        fees: {
          title: 'Onorario per una domanda di permesso di soggiorno',
          kind: 'fixed',
          amount: 'Investimento da 895 €',
          includes: [
            'Individuazione del permesso adatto alla sua situazione e di quello che dura nel tempo',
            'Domanda preparata e depositata presso l\'IND',
            'Requisiti di documenti, legalizzazione e traduzione individuati in anticipo',
            'Monitoraggio fino alla decisione, e sui rinnovi dove rilevante',
          ],
        },
        note: 'Diritti e tempi di decisione variano per tipo di permesso e cambiano nel tempo, quindi confermiamo i valori IND aggiornati durante il colloquio invece di stamparli qui.',
        conditions: {
          title: 'Tempi e soglie',
          intro: 'Quasi tutti i problemi di permesso che ripariamo sono nati da una data passata in silenzio. Queste sono quelle che contano.',
          items: [
            'Depositi il rinnovo almeno tre mesi prima della scadenza. Il diritto di vivere e lavorare prosegue mentre un rinnovo tempestivo è pendente.',
            'Un cambio di datore di lavoro, di scopo o di relazione richiede una nuova domanda, e nella maggior parte dei casi non può iniziare la nuova attività prima dell\'approvazione.',
            'Il soggiorno permanente richiede cinque anni di soggiorno regolare ininterrotto su base non temporanea.',
            'I permessi per studio e per anno di orientamento non contano ai fini di quei cinque anni.',
            'L\'integrazione civica al livello A2, o un\'esenzione formale, è richiesta per il soggiorno permanente e per la naturalizzazione.',
            'Assenze superiori a sei mesi consecutivi, o a quattro mesi l\'anno nell\'arco del periodo, interrompono la continuità.',
          ],
        },
        details: {
          title: 'Le domande che ci vengono poste più spesso',
          items: [
            {
              q: 'Soggiorno permanente o cittadinanza olandese?',
              a: 'Il soggiorno permanente le assicura il diritto di vivere e lavorare qui a tempo indeterminato e sopravvive a un cambio di lavoro. La cittadinanza aggiunge un passaporto olandese, la cittadinanza UE e il voto, richiede gli stessi cinque anni più l\'integrazione e di norma impone di rinunciare alla cittadinanza attuale. Molti clienti prendono prima il soggiorno permanente e decidono sulla naturalizzazione in seguito.',
            },
            {
              q: 'Il mio permesso scade a breve e non ho un nuovo lavoro.',
              a: 'I lavoratori altamente qualificati hanno tre mesi di ricerca dopo la fine del rapporto, durante i quali il soggiorno prosegue mentre trova un nuovo sponsor riconosciuto. Agisca dentro quella finestra. Una volta chiusa, la posizione diventa molto più difficile da riparare.',
            },
            {
              q: 'Sto divorziando. Perdo il soggiorno?',
              a: 'Non necessariamente. A seconda di da quanto tempo detiene un permesso a carico e delle sue circostanze personali, un cambio di scopo verso un soggiorno autonomo è spesso possibile. È una questione di tempi, e prima ci parla più vie restano aperte.',
            },
            {
              q: 'Posso avere anche lo status di soggiornante di lungo periodo UE?',
              a: 'Sì, ed è spesso la combinazione migliore. Il permesso di soggiornante di lungo periodo UE aggiunge diritti di mobilità verso altri Stati membri che il soggiorno permanente olandese non porta con sé, ed entrambi possono essere richiesti nello stesso momento.',
            },
          ],
        },
        faq: {
          title: 'Domande sul soggiorno',
          items: [
            {
              q: 'Quando dovrei avviare il rinnovo?',
              a: 'L\'IND consente di presentare domanda nei mesi precedenti la scadenza, e prima è quasi sempre meglio. Di norma iniziamo a preparare ben prima che la finestra si apra, così il giorno del deposito è una formalità.',
            },
            {
              q: 'Devo parlare olandese per il soggiorno permanente?',
              a: 'Di solito sì. Il soggiorno permanente richiede in genere il superamento degli esami di integrazione civica, con esenzioni in casi specifici. Valutiamo quali requisiti si applicano a lei e come prepararsi.',
            },
            {
              q: 'Che cosa succede al mio permesso se perdo il lavoro?',
              a: 'Dipende dal tipo di permesso. I lavoratori altamente qualificati, per esempio, hanno un periodo di ricerca per trovare un nuovo sponsor. La chiave è agire subito, quindi ci chiami la settimana in cui accade, non il mese dopo.',
            },
          ],
        },
        cta: {
          title: 'Mantenga il suo soggiorno solidissimo',
          text: 'Ci mandi una foto della sua tessera di soggiorno e la sua situazione in tre frasi. Le diremo che cosa richiede attenzione e quando.',
          label: 'Esamina il mio status di soggiorno',
        },
        form: 'immigration',
        image: '/images/immigration-documents.jpg?v=20260731',
        imageAlt: 'Cartella in pelle e penna stilografica su una scrivania',
        image2: '/images/immigration-desk.jpg?v=20260731',
        image2Alt: 'Consulente e cliente a un tavolo di consulenza riservata',
      },
    ],
    crossLinks: [
      {
        path: '/starting-a-business/employer-immigration-services-netherlands',
        label: 'Immigrazione per datori di lavoro',
        text: 'Per le aziende che assumono personale extra UE: domande di permesso, riconoscimento come sponsor presso l\'IND, distacco di lavoratori e riesame delle pratiche.',
      },
    ],
  };
