/* GENERATED by scripts/i18n-strings.mjs. Do not hand-edit.
   it/vip.ts is a 1:1 structural mirror of en/vip.ts; only leaf strings
   differ. To change structure, change English and re-run the build. */
import type { VipContent } from '../types';

export const vip: VipContent = {
    title: 'Servizi VIP di relocation',
    metaTitle: 'Pacchetti VIP di relocation e immigrazione nei Paesi Bassi | E & I',
    metaDescription: 'Pacchetti VIP di trasferimento per coppie, famiglie e imprese che si spostano nei Paesi Bassi. Immigrazione, casa, iscrizioni e ambientamento, orchestrati da una sola persona. Ogni pacchetto è quotato sulle sue esigenze.',
    eyebrow: 'Servizi VIP',
    intro: [
      'Artisti con date di tournée. Atleti fra una stagione e l\'altra. Dirigenti con un solo fine settimana libero e fondatori senza nemmeno quello. I nostri pacchetti VIP esistono per chi ha un calendario che non si piega, così a piegarsi sono i Paesi Bassi.',
      'Ogni pacchetto è seguito personalmente da Johanna: appuntamenti concentrati, porte aperte in anticipo e una linea attiva 24 ore su 24 a cui risponde chi conosce il suo fascicolo, non un centralino.',
    ],
    image: '/images/vip-hub.jpg?v=20260731',
    imageAlt: 'Addetto all\'accoglienza saluta una coppia che arriva in auto a un hotel sul canale',
    pricingNote: {
      title: 'Come si definisce il prezzo del VIP',
      text: [
        'Servizi su misura, costruiti sulle sue esigenze personali. Dopo una prima consulenza riceverà una proposta personalizzata basata sui suoi obiettivi, sulla situazione familiare e sul livello di assistenza che preferisce.',
        'Quella proposta è una cifra fissa per l\'ambito che concorderemo. Nessuna tariffa oraria, nessuna aggiunta a metà trasferimento e nessun costo per la consulenza da cui nasce.',
      ],
    },
    tailored: {
      text: 'Ogni pacchetto è un punto di partenza, non un menu fisso. Nella prima consulenza adattiamo l\'ambito alla sua situazione, aggiungendo ciò che le serve e togliendo ciò che non le serve.',
      label: 'Parliamo di un pacchetto su misura',
    },
    packages: [
      {
        slug: 'couple-relocation-immigration-package-netherlands',
        name: 'Pacchetto VIP Coppia',
        tagline: 'Due vite, un arrivo senza attriti.',
        metaTitle: 'Pacchetto di trasferimento e immigrazione per coppie nei Paesi Bassi | E & I',
        metaDescription: 'Pacchetto completo di trasferimento e immigrazione per coppie che si spostano nei Paesi Bassi: visto per partner, casa, BSN, assicurazione, conto bancario e ambientamento, con guida personale.',
        investment: 'Su misura',
        intro: [
          'Vi trasferite per una carriera, per un\'azienda o l\'uno per l\'altro, e nessuno dei due ha tempo di diventare esperto di burocrazia olandese. Il Pacchetto VIP Coppia mette entrambi i fascicoli in una sola mano e ordina ogni passaggio, così che visti, casa e iscrizioni arrivino nella sequenza giusta.',
        ],
        included: {
          title: 'Cosa è incluso',
          items: [
            {
              title: 'Assistenza per il visto per partner',
              text: 'Valutazione, preparazione e deposito del percorso per partner, allineato al permesso del partner che lavora.',
            },
            {
              title: 'Consulenza sull\'immigrazione',
              text: 'Una sola strategia per entrambi i fascicoli, così nessuna domanda resta in attesa dell\'altra.',
            },
            {
              title: 'Assistenza per la casa',
              text: 'Una selezione costruita sulla vostra vita, visite organizzate, contratto esaminato prima della firma.',
            },
            {
              title: 'Registrazione BSN',
              text: 'Appuntamenti in comune prenotati e affrontati insieme.',
            },
            {
              title: 'Consulenza sull\'assicurazione sanitaria',
              text: 'La polizza olandese giusta, scelta e attivata nei tempi.',
            },
            {
              title: 'Assistenza per il conto bancario',
              text: 'Un conto olandese aperto senza il solito circolo vizioso fra indirizzo e BSN.',
            },
            {
              title: 'Appuntamenti in comune',
              text: 'Ogni iscrizione programmata, preparata e accompagnata.',
            },
            {
              title: 'Assistenza all\'ambientamento',
              text: 'Utenze, internet, medico, dentista e le piccole cose che rendono vostra una città.',
            },
            {
              title: 'Assistenza via WhatsApp',
              text: 'Una linea diretta con Johanna, a qualsiasi ora, per entrambi.',
            },
          ],
        },
        forWho: {
          title: 'Pensato per',
          items: [
            'Coppie in cui un partner si trasferisce per lavoro e l\'altro ha bisogno di un titolo di soggiorno',
            'Coppie con doppia carriera che arrivano con permessi separati',
            'Partner che raggiungono chi già lavora nei Paesi Bassi',
          ],
        },
        process: {
          title: 'Come si svolge',
          steps: [
            {
              title: 'Consulenza',
              text: 'Una conversazione sulla vostra situazione, sui tempi e su ciò che non è negoziabile. Ricevete un preventivo fisso.',
            },
            {
              title: 'Preparazione',
              text: 'Entrambe le domande preparate in parallelo mentre selezioniamo le case.',
            },
            {
              title: 'Settimana dell\'arrivo',
              text: 'Iscrizioni, banca e assicurazione completate in pochi giorni, con noi al vostro fianco.',
            },
            {
              title: 'Ambientamento',
              text: 'Restiamo in linea finché l\'ultimo scatolone è aperto e l\'ultimo account funziona.',
            },
          ],
        },
        justification: {
          title: 'Perché le coppie lo scelgono',
          text: [
            'Gestito separatamente, il trasferimento di una coppia sono due fascicoli di immigrazione, una ricerca di casa in un mercato che si muove in giorni e un mese di appuntamenti in orari d\'ufficio che non avete. Gestito da noi, è un solo piano e una manciata di firme.',
          ],
        },
        faq: {
          title: 'Domande che pongono le coppie',
          items: [
            {
              q: 'Il mio partner può lavorare nei Paesi Bassi?',
              a: 'Con la maggior parte dei permessi per partner sì, con libero accesso al mercato del lavoro. Confermiamo la vostra situazione esatta durante la consulenza.',
            },
            {
              q: 'Dobbiamo essere sposati?',
              a: 'No. I Paesi Bassi riconoscono le relazioni durature per i percorsi riservati ai partner; vi consigliamo quali prove rendono convincente il fascicolo.',
            },
            {
              q: 'Quanto rapidamente possiamo essere registrati entrambi?',
              a: 'Con i documenti preparati prima dell\'arrivo, le iscrizioni principali si completano di norma entro la prima settimana.',
            },
          ],
        },
        cta: {
          title: 'Pianificate insieme il vostro arrivo',
          text: 'Diteci le vostre date e vi diremo esattamente che cosa è possibile.',
          label: 'Invia la tua richiesta VIP',
        },
        image: '/images/vip-couple.jpg?v=20260728',
        imageAlt: 'Coppia sul balcone di un attico con vista su Rotterdam al tramonto',
      },
      {
        slug: 'family-relocation-immigration-services-netherlands',
        name: 'Pacchetto VIP Famiglia',
        tagline: 'Tutta la famiglia, atterrata dolcemente.',
        metaTitle: 'Servizi di trasferimento e immigrazione per famiglie nei Paesi Bassi | E & I',
        metaDescription: 'Pacchetto di trasferimento familiare per i Paesi Bassi: immigrazione per ogni membro della famiglia, casa, ricerca della scuola, sanità, iscrizioni e orientamento nel quartiere, con guida personale.',
        investment: 'Su misura',
        badge: 'Il più richiesto',
        intro: [
          'Il trasferimento di una famiglia non è la versione ingrandita di quello di una persona, è un mestiere diverso. Anni scolastici che iniziano a date fisse, una casa che deve funzionare per tutti, quattro fascicoli all\'IND invece di uno. Questo pacchetto esiste perché azzeccare quella sequenza è ciò in cui siamo più bravi.',
        ],
        included: {
          title: 'Cosa è incluso',
          items: [
            {
              title: 'Consulenza sull\'immigrazione familiare',
              text: 'Il permesso di ogni familiare preparato e depositato come un\'unica domanda coordinata.',
            },
            {
              title: 'Assistenza per la casa',
              text: 'Case di misura familiare vicino alle scuole giuste, trovate e negoziate.',
            },
            {
              title: 'Ricerca della scuola',
              text: 'Scuole internazionali e olandesi a confronto, visite organizzate, iscrizione gestita prima che chiudano le liste.',
            },
            {
              title: 'Registrazione BSN per la famiglia',
              text: 'Una sola visita in comune per tutto il nucleo, preparata e accompagnata.',
            },
            {
              title: 'Orientamento sanitario',
              text: 'Assicurazione per ogni componente, un medico di famiglia e un dentista che accettano nuovi pazienti.',
            },
            {
              title: 'Appuntamenti in comune',
              text: 'Programmati intorno agli orari scolastici e alla vostra giornata di lavoro.',
            },
            {
              title: 'Assistenza all\'ambientamento',
              text: 'Dalle utenze alle società sportive, l\'infrastruttura della vita familiare messa in piedi.',
            },
            {
              title: 'Orientamento nel quartiere',
              text: 'Un\'introduzione guidata alla vostra zona: percorsi, parchi giochi, supermercati, vita del fine settimana.',
            },
            {
              title: 'Assistenza via WhatsApp',
              text: 'Una linea per entrambi i genitori, con risposta a qualsiasi ora.',
            },
          ],
        },
        forWho: {
          title: 'Pensato per',
          items: [
            'Famiglie che si trasferiscono per un incarico a Rotterdam o nella regione portuale',
            'Genitori che devono sistemare le scuole prima di ogni altra cosa',
            'Nuclei che arrivano per ricongiungimento familiare accanto a un permesso di lavoro',
          ],
        },
        process: {
          title: 'Come si svolge',
          steps: [
            {
              title: 'Consulenza',
              text: 'Mappiamo la famiglia: età, scuole, percorsi di visto, date. Ricevete un unico preventivo fisso.',
            },
            {
              title: 'Prima le scuole',
              text: 'L\'iscrizione parte subito, perché sono i posti a scuola a fissare i tempi di tutto il resto.',
            },
            {
              title: 'Casa e permessi',
              text: 'Ricerca della casa e pratiche di immigrazione procedono in parallelo.',
            },
            {
              title: 'Arrivo',
              text: 'Iscrizioni fatte in una sola visita, orientamento vissuto come famiglia, e noi restiamo raggiungibili.',
            },
          ],
        },
        justification: {
          title: 'Perché le famiglie lo scelgono',
          text: [
            'Il costo di un pacchetto famiglia si misura su un altro numero: il costo di un anno scolastico perso, di un affitto andato a chi ha offerto prima, o di un genitore che passa i primi tre mesi in coda invece che al lavoro e a casa. Le famiglie ci dicono che il pacchetto si è ripagato nelle prime due settimane.',
          ],
        },
        faq: {
          title: 'Domande che pongono le famiglie',
          items: [
            {
              q: 'Potete far entrare i nostri figli in una scuola internazionale?',
              a: 'Non possiamo creare posti che non esistono, ma sappiamo quali scuole hanno spazio, come funzionano davvero le loro liste e come presentare una domanda che si muova in fretta.',
            },
            {
              q: 'I nostri figli hanno bisogno di un permesso proprio?',
              a: 'Sì, ogni figlio ha bisogno di un permesso di soggiorno. Li prepariamo insieme al vostro, così la famiglia viene approvata come un tutt\'uno.',
            },
            {
              q: 'Quanto tempo prima che la famiglia si senta a casa?',
              a: 'Le pratiche richiedono giorni, una volta preparate. La sensazione richiede una stagione, ed è esattamente il periodo che copre la nostra assistenza all\'ambientamento.',
            },
          ],
        },
        cta: {
          title: 'Regalate alla vostra famiglia un atterraggio morbido',
          text: 'Raccontateci il vostro nucleo e le vostre date. Progetteremo l\'arrivo intorno all\'anno scolastico.',
          label: 'Invia la tua richiesta VIP',
        },
        image: '/images/vip-family.jpg?v=20260731',
        imageAlt: 'Famiglia che arriva a una villa olandese nella luce della sera',
      },
      {
        slug: 'business-relocation-immigration-services-netherlands',
        name: 'Pacchetto VIP Impresa',
        tagline: 'Fondare, iscrivere, vivere. In quest\'ordine, in fretta.',
        metaTitle: 'Servizi di trasferimento e immigrazione per imprese nei Paesi Bassi | E & I',
        metaDescription: 'Pacchetto di trasferimento aziendale per i Paesi Bassi: visto startup o DAFT, costituzione della società e iscrizione alla KvK, casa e ambientamento per fondatori e dirigenti, in un solo piano.',
        investment: 'Su misura',
        intro: [
          'Fondatori e dirigenti che si trasferiscono nei Paesi Bassi affrontano due burocrazie insieme: una per l\'azienda, una per la vita che le sta attorno. Questo pacchetto porta avanti entrambi i binari contemporaneamente, così l\'impresa opera mentre chi l\'ha fondata vive già bene, invece di fare la spola fra un hotel e una coda allo sportello.',
        ],
        included: {
          title: 'Cosa è incluso',
          items: [
            {
              title: 'Consulenza sul visto startup',
              text: 'Abbinamento del facilitatore, allineamento del business plan e deposito per il percorso startup olandese.',
            },
            {
              title: 'Assistenza per il visto DAFT',
              text: 'Per i cittadini statunitensi: il percorso del Dutch American Friendship Treaty, preparato dall\'inizio alla fine.',
            },
            {
              title: 'Costituzione della società',
              text: 'Forma giuridica, atto costitutivo e le decisioni pratiche che stanno in mezzo.',
            },
            {
              title: 'Assistenza per l\'iscrizione alla KvK',
              text: 'Iscrizione alla Camera di Commercio completata correttamente già la prima volta.',
            },
            {
              title: 'Assistenza per la casa',
              text: 'Una casa o un pied-à-terre in linea con la sua base operativa.',
            },
            {
              title: 'Trasferimento dell\'imprenditore',
              text: 'Il lato personale del trasferimento, ordinato intorno ai tempi dell\'azienda.',
            },
            {
              title: 'Registrazione BSN',
              text: 'Iscrizione in comune prenotata e accompagnata.',
            },
            {
              title: 'Assistenza all\'ambientamento',
              text: 'Banca, assicurazioni e infrastruttura quotidiana per lei e per la sua famiglia.',
            },
            {
              title: 'Consulenza per l\'avvio dell\'attività',
              text: 'Presentazioni a commercialisti, notai e alla rete locale che le servirà davvero.',
            },
          ],
        },
        forWho: {
          title: 'Pensato per',
          items: [
            'Fondatori che entrano con il visto startup o con il trattato DAFT',
            'Dirigenti che si trasferiscono mentre costituiscono una società olandese',
            'Aziende che spostano insieme persone chiave e le loro famiglie',
          ],
        },
        process: {
          title: 'Come si svolge',
          steps: [
            {
              title: 'Consulenza',
              text: 'Piani aziendali e situazione personale sullo stesso tavolo. Riceve un preventivo fisso e una sequenza.',
            },
            {
              title: 'Due binari',
              text: 'Visto e costituzione della società procedono in parallelo, sbloccandosi a vicenda al momento giusto.',
            },
            {
              title: 'Atterraggio',
              text: 'KvK, BSN, banca e casa completati in una settimana di arrivo compressa.',
            },
            {
              title: 'Operatività',
              text: 'Lei manda avanti l\'azienda. Noi restiamo la persona da chiamare per qualsiasi cosa emerga.',
            },
          ],
        },
        justification: {
          title: 'Perché i fondatori lo scelgono',
          text: [
            'Nessun altro sul mercato mette insieme visto, costituzione, casa e famiglia in un unico incarico. Comporre lo stesso risultato con quattro fornitori diversi costa di più, richiede più tempo e lascia lei a fare il project manager. Qui il project manager è incluso.',
          ],
        },
        faq: {
          title: 'Domande che pongono i fondatori',
          items: [
            {
              q: 'Visto startup o DAFT, quale fa per me?',
              a: 'Il DAFT è riservato ai cittadini statunitensi e richiede un investimento contenuto; il visto startup richiede un facilitatore riconosciuto. Valutiamo entrambi rispetto ai suoi piani già nella prima conversazione.',
            },
            {
              q: 'Posso iscrivere una società prima di avere un indirizzo?',
              a: 'L\'ordine fra indirizzo, BSN e KvK è esattamente il tipo di trappola di sequenza per cui esistiamo. Organizziamo i passaggi in modo che nulla si blocchi.',
            },
            {
              q: 'Lavorate con team in trasferimento?',
              a: 'Sì. Per trasferimenti aziendali di più dipendenti e delle loro famiglie costruiamo un programma unico; ci chieda le condizioni per le aziende.',
            },
          ],
        },
        cta: {
          title: 'Sposti il fondatore, non solo l\'azienda',
          text: 'Ci racconti i suoi piani e la sua finestra temporale. Le risponderemo con una sequenza e un preventivo fisso.',
          label: 'Invia la tua richiesta VIP',
        },
        image: '/images/vip-business.jpg?v=20260731',
        imageAlt: 'Dirigente che lavora sul sedile posteriore di un\'auto con autista',
      },
      {
        slug: 'vip-relocation-concierge',
        name: 'VIP Relocation Concierge',
        tagline: 'Per vite che non si fermano per traslocare.',
        metaTitle: 'VIP Relocation Concierge nei Paesi Bassi | E & I',
        metaDescription: 'Trasferimento concierge completo nei Paesi Bassi per artisti, atleti e dirigenti: una sola visita preparata, ogni appuntamento allineato, giornate con autista e assistenza personale 24 ore su 24.',
        investment: 'Su misura',
        intro: [
          'Un artista fra due date di tournée. Un atleta ingaggiato a stagione in corso. Un dirigente il cui calendario è già pianificato per l\'anno prossimo. Il livello concierge comprime un trasferimento nel tempo che lei ha davvero, a volte un solo fine settimana, e gestisce tutto ciò che è possibile gestire senza di lei.',
          'Lei ci dice le date in cui può essere nei Paesi Bassi. Noi coreografiamo il resto attorno a quelle.',
        ],
        included: {
          title: 'Cosa è incluso',
          items: [
            {
              title: 'Una visita preparata',
              text: 'Ogni appuntamento che per legge richiede la sua presenza, allineato in un\'unica trasferta: IND, comune, banca, visite agli immobili.',
            },
            {
              title: 'La casa prima dell\'atterraggio',
              text: 'Una selezione curata, visitata prima in video, così la sua visita conferma invece di cercare.',
            },
            {
              title: 'Giornate con autista',
              text: 'Prelievo in aeroporto e autista per tutta la durata della visita.',
            },
            {
              title: 'Immigrazione, gestita in silenzio',
              text: 'Domande preparate, depositate e sollecitate mentre lei è altrove.',
            },
            {
              title: 'Famiglia inclusa',
              text: 'Partner, figli, scuole e organizzazione del personale, coperti dove serve.',
            },
            {
              title: 'Discrezione',
              text: 'Un modo di lavorare ereditato dal mondo delle ambasciate. Il suo trasferimento resta affare suo.',
            },
            {
              title: 'Linea 24 ore su 24',
              text: 'Johanna, direttamente, in qualunque fuso orario si trovi.',
            },
          ],
        },
        forWho: {
          title: 'Pensato per',
          items: [
            'Artisti e interpreti che si trasferiscono fra tournée e produzioni',
            'Atleti e staff che si spostano a stagione in corso',
            'Dirigenti e personaggi pubblici che hanno bisogno di rapidità e discrezione in egual misura',
          ],
        },
        process: {
          title: 'Come si svolge',
          steps: [
            {
              title: 'Una conversazione riservata',
              text: 'La sua situazione, i suoi vincoli, le sue date. Progettiamo la visita e la quotiamo a prezzo fisso.',
            },
            {
              title: 'Tutto preparato',
              text: 'Documenti, depositi, selezioni e appuntamenti organizzati mentre lei continua la sua vita.',
            },
            {
              title: 'La visita',
              text: 'Un soggiorno coreografato, di norma due o tre giorni, con autista e Johanna sempre presenti.',
            },
            {
              title: 'Dopo la visita',
              text: 'Completiamo il resto, ritiriamo le chiavi dove consentito e restiamo reperibili mentre lei arriva per restare.',
            },
          ],
        },
        justification: {
          title: 'Che cosa sta comprando davvero',
          text: [
            'Questo livello viene quotato su una verità semplice: il suo tempo è la risorsa più scarsa del trasferimento. Ogni ora che togliamo dal suo lato del tavolo è un\'ora sul palco, in campo o in consiglio di amministrazione. Questo è lo scambio, ed è ciò attorno a cui è costruita la proposta.',
          ],
        },
        faq: {
          title: 'Domande che pongono i clienti',
          items: [
            {
              q: 'Si può davvero fare tutto in una sola visita?',
              a: 'Quasi tutto. La legge olandese richiede la sua presenza fisica per un piccolo gruppo di appuntamenti; concentriamo esattamente quelli nella sua visita e assorbiamo il resto.',
            },
            {
              q: 'Quanto è discreto il processo?',
              a: 'Del tutto. Nessun elenco di clienti, nessun caso studio con nomi e, dove è utile, lavoriamo tramite il suo management o il suo family office.',
            },
            {
              q: 'E se le mie date cambiano?',
              a: 'I programmi costruiti attorno ad artisti e atleti nascono per essere ricostruiti. Rifacciamo la coreografia e teniamo in movimento le pratiche.',
            },
          ],
        },
        cta: {
          title: 'Ci dica la sua finestra',
          text: 'Ci dia le date che ha. Le mostreremo che cosa può accadere al loro interno.',
          label: 'Invia una richiesta riservata',
        },
        image: '/images/vip-concierge.jpg?v=20260728',
        imageAlt: 'Jet privato con auto in attesa all\'alba',
      },
    ],
    cta: {
      title: 'Non sa quale pacchetto faccia al caso suo?',
      text: 'Una conversazione basta per progettare quello giusto. Ogni pacchetto inizia dallo stesso passo, una consulenza personale.',
      label: 'Prenota una consulenza',
    },
  };
