import { chromium } from 'playwright';
import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
const MIME={'.html':'text/html','.css':'text/css','.js':'text/javascript','.jpg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml','.mp4':'video/mp4','.xml':'text/xml','.txt':'text/plain','.png':'image/png','.woff2':'font/woff2','.json':'application/json'};
const srv=http.createServer((req,res)=>{let p=decodeURIComponent(req.url.split('?')[0]);if(p.endsWith('/'))p+='index.html';const f=path.join('site',p);if(!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);return res.end('x');}res.writeHead(200,{'Content-Type':MIME[path.extname(f)]||'application/octet-stream'});fs.createReadStream(f).pipe(res);});
await new Promise(r=>srv.listen(8902,r));
const b=await chromium.launch(); const ctx=await b.newContext({viewport:{width:1440,height:940}}); const page=await ctx.newPage();
page.on('console',m=>console.log('[console]',m.type(),m.text().slice(0,300)));
page.on('pageerror',e=>console.log('[pageerror]',String(e).slice(0,300)));
page.on('requestfailed',r=>console.log('[failed]',r.url().slice(0,120),r.failure()?.errorText));
page.on('response',r=>{ if(/mapbox/.test(r.url())) console.log('[resp]',r.status(),r.url().slice(0,110)); });
await page.goto('http://127.0.0.1:8902/',{waitUntil:'load'});
await page.evaluate(()=>document.getElementById('werkgebied').scrollIntoView());
await page.waitForTimeout(6000);
console.log('mapboxgl?', await page.evaluate(()=>typeof window.mapboxgl));
console.log('supported?', await page.evaluate(()=>window.mapboxgl? mapboxgl.supported():null));
console.log('canvas', await page.evaluate(()=>{const c=document.querySelector('#map canvas'); return c? c.width+'x'+c.height : 'none';}));
console.log('markers', await page.evaluate(()=>document.querySelectorAll('.map-pin').length));
console.log('fallback', await page.evaluate(()=>!!document.getElementById('mapFallback')));
await page.locator('#werkgebied').screenshot({path:'work/map-dbg.png'});
await b.close(); srv.close();
