import { webkit, devices } from 'playwright';
import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
const MIME={'.html':'text/html','.css':'text/css','.js':'text/javascript','.jpg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml','.png':'image/png','.mp4':'video/mp4'};
const srv=http.createServer((q,s)=>{let p=decodeURIComponent(q.url.split('?')[0]);if(p.endsWith('/'))p+='index.html';const f=path.join('site',p);if(!fs.existsSync(f)||fs.statSync(f).isDirectory()){s.writeHead(404);return s.end('x')}s.writeHead(200,{'Content-Type':MIME[path.extname(f)]||'application/octet-stream'});fs.createReadStream(f).pipe(s)});
await new Promise(r=>srv.listen(8904,r));
fs.mkdirSync('work/shots',{recursive:true});
const b=await webkit.launch();
const ctx=await b.newContext({...devices['iPhone 13']}); const pg=await ctx.newPage();
await pg.goto('http://127.0.0.1:8904/',{waitUntil:'load'});
await pg.waitForTimeout(900);
await pg.screenshot({path:'work/shots/fix-hero.png'});
await pg.locator('#voorna').scrollIntoViewIfNeeded();
await pg.waitForTimeout(3000);
await pg.screenshot({path:'work/shots/fix-voorna.png'});
const ctx2=await b.newContext({viewport:{width:1440,height:900}}); const pg2=await ctx2.newPage();
await pg2.goto('http://127.0.0.1:8904/',{waitUntil:'load'});
await pg2.waitForTimeout(900);
await pg2.screenshot({path:'work/shots/fix-hero-d.png'});
await b.close(); srv.close();
