/* GENERATED by scripts/i18n-strings.mjs. Do not hand-edit.
   pt/core.ts is a 1:1 structural mirror of en/core.ts; only leaf strings
   differ. To change structure, change English and re-run the build. */
import type { CoreContent } from '../types';

export const core: CoreContent = {
    ui: {
      skipToContent: 'Ir para o conteúdo',
      nav: {
        home: 'Início',
        immigration: 'Imigração',
        housing: 'Habitação',
        relocation: 'Relocalização',
        business: 'Abrir uma empresa',
        vip: 'Serviços VIP',
        guides: 'Guias',
        about: 'Sobre nós',
        contact: 'Contacto',
      },
      cta: {
        whatsapp: 'WhatsApp',
        whatsappLong: 'Escreva-nos no WhatsApp',
        consultation: 'Marque uma consulta',
        startRelocation: 'Comece a sua mudança',
        readMore: 'Saber mais',
        allServices: 'Todos os serviços',
        backTo: 'Voltar a',
        send: 'Enviar pedido',
        sending: 'A enviar…',
        explore: 'Explorar',
      },
      langBanner: {
        prompt: 'Prefere consultar este site em {lang}?',
        switch: 'Mudar',
        dismiss: 'Não, obrigado',
      },
      form: {
        firstName: 'First name',
        lastName: 'Last name',
        email: 'Email address',
        phone: 'Phone / WhatsApp',
        optional: 'optional',
        successTitle: 'Thank you, your inquiry has been sent',
        successBody: 'Johanna will personally review your situation and reply within one business day, usually much sooner. For anything urgent, message us on WhatsApp.',
        errorTitle: 'Something went wrong',
        errorBody: 'Your inquiry could not be sent. Please try again, or message us on WhatsApp.',
        consent: 'By sending this form you agree to our privacy policy.',
        nextSteps: 'After you send this form, Johanna personally reviews your situation and replies within one business day with an honest assessment of whether and how we can help. If your request falls outside our services or region, we tell you straight away.',
      },
      footer: {
        tagline: 'Uma consultoria boutique de relocalização para profissionais e famílias internacionais que se instalam em Roterdão, no Europoort e na região portuária envolvente.',
        services: 'Serviços',
        company: 'Empresa',
        contactHeading: 'Contacto',
        legalHeading: 'Informação legal',
        kvkLabel: 'KvK',
        rightsReserved: 'Todos os direitos reservados.',
        builtBy: 'Site por',
        disclaimer: 'A E & I é uma consultoria independente de relocalização e imigração. Não somos um organismo público e não temos qualquer ligação ao IND, ao Governo dos Países Baixos nem a qualquer embaixada ou consulado. As decisões sobre vistos, autorizações de residência e naturalização cabem exclusivamente às autoridades competentes.',
      },
      misc: {
        from: 'Investimento a partir de',
        whatsIncluded: 'O que está incluído',
        otherServices: 'Outros serviços',
        relatedGuides: 'Guias relacionados',
        conditions: 'Requisitos',
        investment: 'Investimento',
        feesDisclaimer: 'Os valores de investimento indicados correspondem apenas aos nossos honorários profissionais e servem de orientação. Taxas públicas (incluindo as taxas do IND), IVA, custos de legalização e apostila, traduções ajuramentadas, emolumentos consulares e despesas de terceiros não estão incluídos, salvo indicação expressa na proposta.',
      },
    },
    home: {
      metaTitle: 'Serviços boutique de relocalização e imigração nos Países Baixos | E & I',
      metaDescription: 'Uma consultoria boutique de relocalização para profissionais, famílias e empresários internacionais que se instalam em Roterdão, no Europoort e na região portuária envolvente. Habitação, escolas, registos, imigração e pacotes VIP.',
      hero: {
        h1: 'Serviços boutique de relocalização e imigração nos Países Baixos',
        sub: 'Uma consultoria privada de relocalização para profissionais, famílias e empresários internacionais que se instalam em Roterdão, no Europoort e na região portuária envolvente. A imigração está incluída, nunca é a história toda.',
        ctaPrimary: 'Marque uma consulta',
        ctaWhatsapp: 'Escreva-nos no WhatsApp',
        ctaSecondary: 'Comece a sua mudança',
        trust: 'Acompanhamento pessoal da Johanna, disponível 24 horas por dia',
      },
      paths: {
        heading: 'Como podemos ajudá-lo a chegar?',
        sub: 'Relocalização, habitação, apoio VIP e imigração, tratados por uma única consultoria. Escolha a sua porta de entrada e uma pessoa saberá o seu nome desde a primeira mensagem até ao dia em que se sentir em casa.',
        items: [
          {
            key: 'immigration',
            title: 'Serviços de imigração',
            text: 'Vistos e autorizações para profissionais, cônjuges, famílias e fundadores. Preparados com rigor, acompanhados pessoalmente, dos requisitos à aprovação.',
            label: 'Explorar imigração',
            path: '/immigration',
            image: '/images/path-immigration.jpg?v=20260731',
            imageAlt: 'Consultora em conversa com um cliente internacional',
          },
          {
            key: 'relocation',
            title: 'Relocalização e habitação',
            text: 'Pacotes completos de relocalização ou serviços avulso: procura de casa, escolas, BSN, seguro e tudo o que fica pelo meio.',
            label: 'Explorar relocalização',
            path: '/relocation',
            image: '/images/path-relocation.jpg?v=20260731',
            imageAlt: 'Família a chegar a uma casa neerlandesa junto ao canal',
          },
          {
            key: 'vip',
            title: 'Relocalização VIP',
            text: 'Para artistas, atletas, quadros de direção e visitas de fim de semana. Toda a mudança orquestrada em torno de uma única visita, com todas as portas já abertas.',
            label: 'Explorar serviços VIP',
            path: '/vip-services',
            image: '/images/path-vip.jpg?v=20260731',
            imageAlt: 'Motorista a abrir a porta de um carro com o skyline de Roterdão ao fundo',
          },
        ],
      },
      mostRequested: {
        heading: 'Serviços mais procurados',
        sub: 'As oito coisas que os expatriados nos pedem primeiro.',
        items: [
          {
            label: 'Visto de trabalhador altamente qualificado',
            path: '/immigration/highly-skilled-migrant-visa-netherlands',
          },
          {
            label: 'Apoio na procura de habitação',
            path: '/housing/housing-search-assistance-netherlands',
          },
          {
            label: 'Visto de cônjuge nos Países Baixos',
            path: '/immigration/partner-visa-netherlands',
          },
          {
            label: 'Registo BSN',
            path: '/relocation/bsn-registration-netherlands',
          },
          {
            label: 'Visto startup nos Países Baixos',
            path: '/immigration/startup-visa-netherlands',
          },
          {
            label: 'Procura de escola',
            path: '/relocation/school-search-netherlands',
          },
          {
            label: 'Pacote completo de relocalização',
            path: '/vip-services',
          },
          {
            label: 'Serviços de relocalização em Roterdão',
            path: '/relocation/relocation-services-rotterdam',
          },
        ],
      },
      vipBlock: {
        eyebrow: 'Serviços VIP de relocalização',
        heading: 'Chegue como está habituado a chegar',
        text: [
          'Há clientes que não podem dedicar seis semanas a papelada. Chegam para um fim de semana, assinam, registam-se e partem enquanto nós tratamos do resto. Os nossos pacotes VIP comprimem uma relocalização inteira num programa construído à sua medida: marcações alinhadas numa única visita, casas pré-selecionadas antes de aterrar, um carro à espera em Schiphol.',
          'Casais, famílias e empresas têm cada um o seu pacote, e o nível concierge é escrito em torno do que a sua vida exigir.',
        ],
        label: 'Descobrir a relocalização VIP',
      },
      immigrationBlock: {
        eyebrow: 'Imigração para expatriados',
        heading: 'A autorização certa, preparada da forma certa',
        text: [
          'A imigração neerlandesa recompensa a preparação. Avaliamos que via se ajusta realmente à sua situação, preparamos o pedido tal como o IND o quer ver e acompanhamo-lo às marcações que contam.',
        ],
        label: 'Todos os serviços de imigração',
        links: [
          {
            label: 'Trabalhador altamente qualificado',
            path: '/immigration/highly-skilled-migrant-visa-netherlands',
          },
          {
            label: 'Cartão Azul UE',
            path: '/immigration/eu-blue-card-netherlands',
          },
          {
            label: 'Visto de cônjuge',
            path: '/immigration/partner-visa-netherlands',
          },
          {
            label: 'Visto startup',
            path: '/immigration/startup-visa-netherlands',
          },
          {
            label: 'Visto DAFT',
            path: '/immigration/daft-visa-netherlands',
          },
          {
            label: 'Autorizações de residência',
            path: '/immigration/residence-permit-netherlands',
          },
        ],
      },
      housingBlock: {
        eyebrow: 'Habitação e instalação',
        heading: 'Uma casa, não apenas uma morada',
        text: [
          'O mercado de arrendamento neerlandês move-se em dias, não em semanas. Procuramos, vamos às visitas consigo ou por si, revemos cada cláusula do contrato antes de assinar e continuamos a ser o ponto de contacto do seu senhorio muito depois de as chaves serem suas.',
        ],
        label: 'Todos os serviços de habitação',
        links: [
          {
            label: 'Procura de habitação',
            path: '/housing/housing-search-assistance-netherlands',
          },
          {
            label: 'Habitação para expatriados em Roterdão',
            path: '/housing/housing-for-expats-rotterdam',
          },
          {
            label: 'Apoio nas visitas',
            path: '/housing/viewing-assistance-netherlands',
          },
          {
            label: 'Alojamento temporário',
            path: '/housing/temporary-housing-for-expats-netherlands',
          },
        ],
      },
      businessBlock: {
        eyebrow: 'Abrir uma empresa',
        heading: 'Funde a sua empresa onde o mundo atraca',
        text: [
          'Visto startup, tratado DAFT, registo na KvK, uma morada, uma casa, uma escola para os seus filhos. A maioria das firmas trata de uma destas coisas. Nós tratamos da sequência, porque um fundador não se muda por etapas, um fundador muda uma vida.',
        ],
        label: 'Serviços para empresas',
      },
      portBlock: {
        eyebrow: 'Portos, docas e offshore',
        heading: 'O especialista do porto de Roterdão',
        text: [
          'O maior porto da Europa não aparece nas brochuras de relocalização e, no entanto, dezenas de milhares de profissionais internacionais constroem ali a sua carreira. Somos a única consultoria boutique especializada em Roterdão, na região a sul, no Europoort e na Maasvlakte, e trabalhamos diariamente com as empresas portuárias, offshore, de navegação e de engenharia que trazem pessoas para cá.',
        ],
        label: 'Serviços para expatriados na indústria',
        areas: [
          {
            title: 'Roterdão',
            text: 'Viver entre arranha-céus, escolas internacionais e a cidade que mais depressa muda nos Países Baixos.',
          },
          {
            title: 'Europoort e Maasvlakte',
            text: 'Relocalização concreta para profissionais do porto, do offshore e das refinarias e para as suas famílias.',
          },
          {
            title: 'A sul de Roterdão',
            text: 'Vilas tranquilas como Brielle, Rozenburg e Hellevoetsluis, a minutos dos terminais e a um mundo de distância deles.',
          },
        ],
        advantages: [
          {
            title: 'Conhecimento local',
            text: 'Conhecemos rua a rua os bairros, as escolas, os senhorios e os trajetos desta região.',
          },
          {
            title: 'Apoio rápido e pessoal',
            text: 'Estamos perto, por isso podemos estar numa visita, num balcão da câmara ou numa urgência com pouquíssima antecedência.',
          },
          {
            title: 'Uma rede consolidada',
            text: 'Agências, câmaras municipais, escolas e empregadores internacionais da região já nos conhecem.',
          },
          {
            title: 'Apoio depois da chegada',
            text: 'A relação não termina com as chaves. Continuamos a ser o ponto de contacto muito depois de se instalar.',
          },
        ],
        links: [
          {
            label: 'Expatriados no Europoort',
            path: '/industrial-expat-services/europoort-relocation-services-netherlands',
          },
          {
            label: 'Expatriados na Maasvlakte',
            path: '/industrial-expat-services/maasvlakte-expat-relocation-netherlands',
          },
          {
            label: 'Profissionais offshore',
            path: '/industrial-expat-services/offshore-expat-services-netherlands',
          },
          {
            label: 'Profissionais de logística',
            path: '/industrial-expat-services/relocation-for-logistics-professionals-netherlands',
          },
        ],
      },
      familyBlock: {
        eyebrow: 'Relocalização familiar',
        heading: 'Mudar uma família é outra disciplina',
        text: [
          'Anos letivos que começam em datas fixas, vários processos no IND em vez de um só, e uma casa que tem de servir a todos. Coordenamos a chegada de toda a família, imigração incluída, num único plano e com uma só direção.',
        ],
        label: 'Serviços de relocalização familiar',
        path: '/relocation/family-relocation-netherlands',
        image: '/images/family-unpacking.jpg?v=20260731',
        imageAlt: 'Família instalada na sua nova sala de estar neerlandesa',
        links: [
          {
            label: 'Pacote VIP Família',
            path: '/vip-services/family-relocation-immigration-services-netherlands',
          },
          {
            label: 'Procura de escola',
            path: '/relocation/school-search-netherlands',
          },
          {
            label: 'Reagrupamento familiar',
            path: '/immigration/family-reunification-netherlands',
          },
        ],
      },
      whyBoutique: {
        eyebrow: 'Porquê boutique',
        heading: 'Uma consultoria. Uma pessoa. O seu nome.',
        text: [
          'As grandes empresas de relocalização atribuem-lhe um número de processo. Uma consultoria boutique atribui-lhe uma pessoa. A Johanna construiu a sua reputação no mundo das embaixadas, onde discrição e rigor não são qualidades, são a descrição de funções.',
          'Não somos uma empresa de relocalização de volume que oferece todos os serviços imagináveis. Fazemos relocalização, habitação, apoio VIP e imigração para uma só região, através de uma só empresa, e fazemo-los até ao fim.',
        ],
        points: [
          {
            title: 'Vamos consigo',
            text: 'À câmara municipal, ao IND, ao banco e à visita ao imóvel. Nunca lhe entregam uma lista de tarefas e lhe desejam boa sorte.',
          },
          {
            title: '24 horas por dia, pessoalmente',
            text: 'Uma linha de WhatsApp, atendida por quem trata do seu processo. De dia ou de noite, na primeira semana ou no primeiro ano.',
          },
          {
            title: 'A única do género',
            text: 'Os Países Baixos têm empresas de mobilidade corporativa e têm balcões de vistos. Têm exatamente um concierge boutique para expatriados.',
          },
          {
            title: 'Pacotes construídos à medida de vidas',
            text: 'Casal, família, empresa ou concierge completo. Cada pacote cobre toda a chegada, não uma fatia dela.',
          },
        ],
        stats: [
          {
            value: 'Desde 2016',
            label: 'A acompanhar chegadas aos Países Baixos',
          },
          {
            value: '1200+',
            label: 'Expatriados e famílias apoiados',
          },
          {
            value: '98%',
            label: 'Índice de satisfação dos clientes',
          },
          {
            value: '24/7',
            label: 'Apoio pessoal por WhatsApp',
          },
        ],
      },
      reviews: {
        eyebrow: 'Histórias de clientes',
        heading: 'Chegadas de que nos orgulhamos',
        sub: 'Clientes reais, percursos reais para os Países Baixos.',
        items: [
          {
            quote: 'Graças à E & I, o nosso reagrupamento familiar foi um processo sem stress. Ficou tudo perfeitamente tratado.',
            name: 'Anna',
            route: 'Da Rússia para os Países Baixos',
            tags: [
              'Relocalização',
              'Visto',
              'Autorização de trabalho',
              'Apoio na habitação',
              'Família',
            ],
          },
          {
            quote: 'A Johanna esteve connosco 24 horas por dia nos primeiros dias. Um serviço verdadeiramente único!',
            name: 'Chinedu',
            route: 'Da Nigéria para os Países Baixos',
            tags: [
              'Relocalização',
              'Visto',
              'Negócios',
              'Startup',
              'Integração',
            ],
          },
        ],
      },
      whatsappCta: {
        heading: 'Uma mensagem. Do resto tratamos nós.',
        text: 'Diga-nos onde está e onde precisa de estar. Vai falar com a Johanna, não com um chatbot.',
        label: 'Escreva-nos no WhatsApp',
      },
      contactBlock: {
        eyebrow: 'Vamos começar a conversa',
        heading: 'Conte-nos a sua mudança',
        text: 'Bastam algumas linhas. Respondemos no prazo de um dia útil.',
      },
    },
    about: {
      metaTitle: 'Sobre a E & I | Consultoria boutique de expatriados e relocalização nos Países Baixos',
      metaDescription: 'A E & I é a única consultoria boutique de relocalização e imigração para expatriados nos Países Baixos. Acompanhamento pessoal da Johanna, do visto à casa até ao dia em que se sentir em casa.',
      eyebrow: 'Sobre a E & I',
      title: 'A boutique por trás de mil chegadas',
      intro: [
        'A E & I: Expat, Relocation and Immigration Services The Netherlands nasceu de uma observação simples feita dentro do mundo das embaixadas: quem melhor muda de país é quem é acompanhado pessoalmente. Não gerido como processo. Acompanhado.',
        'Hoje a Johanna e a sua rede acompanham profissionais, casais, famílias e fundadores até aos Países Baixos, com uma especialização que mais ninguém reivindica: Roterdão, o Europoort e a região industrial em torno do maior porto da Europa.',
      ],
      image: '/images/about-joanna.jpg',
      imageAlt: 'Johanna, fundadora da E & I, no seu escritório',
      approach: {
        heading: 'A nossa abordagem pessoal à relocalização',
        text: [
          'Cada cliente tem um único interlocutor que conhece todo o processo. Quando a câmara municipal o quer presencialmente, estamos na cadeira ao seu lado. Quando um senhorio telefona, respondemos em neerlandês. Quando acontece algo às onze da noite na sua primeira semana, na linha de WhatsApp está a mesma pessoa que o foi buscar ao aeroporto.',
          'Esta forma de trabalhar não é escalável a milhares de clientes por ano. E é precisamente esse o ponto.',
        ],
      },
      history: {
        heading: 'Em atividade desde 2016',
        text: [
          'A E & I foi fundada em 2016 e desde então acompanha quem chega aos Países Baixos. Uma década numa só região é a razão pela qual sabemos que câmara municipal pede que documento, que senhorios sequer consideram um candidato cujo contrato começa no mês seguinte e quanto tempo demora realmente o IND no mês em que apresenta o pedido.',
          'Significa também que as relações são reais. Agentes, notários, secretarias de escolas e funcionários que atendem porque reconhecem o nome. É a vantagem silenciosa que uma firma não pode comprar e que uma recém-chegada não consegue imitar.',
        ],
      },
      boutique: {
        heading: 'Porquê trabalhar com uma consultoria boutique',
        text: [
          'As empresas de mobilidade corporativa são feitas para o volume: portais, tickets, níveis de serviço. Uma boutique é feita para o resultado. Recebe o discernimento de quem acompanhou centenas de clientes através do IND, a rapidez de uma equipa que conhece todos os balcões da região e a discrição que exige uma reputação construída entre diplomatas.',
        ],
        points: [
          {
            title: 'Raízes no mundo das embaixadas',
            text: 'Rigor e discrição aprendidos onde o erro não é opção.',
          },
          {
            title: 'Uma região que mais ninguém serve',
            text: 'Roterdão, o Europoort e a Maasvlakte, conhecidos rua a rua.',
          },
          {
            title: 'Imigração e relocalização numa só mão',
            text: 'A autorização, a casa e a vida à sua volta, ordenadas por uma só equipa.',
          },
        ],
      },
      families: {
        heading: 'Apoio a expatriados e famílias',
        text: [
          'Metade de uma relocalização bem-sucedida nada tem a ver com papelada. Escolas que servem os seus filhos, um bairro que serve os seus serões, um médico, um ginásio, um caminho para o trabalho. O nosso apoio à instalação trata disso com a mesma seriedade que o visto, porque é isso que decide se uma mudança resulta.',
        ],
      },
      reviews: {
        heading: 'Avaliações e experiências de clientes',
        sub: 'O que dizem os clientes sobre chegar com a E & I.',
      },
      cta: {
        title: 'Conheça-nos antes de decidir',
        text: 'Uma conversa diz-lhe exatamente em que ponto está.',
        label: 'Marque uma consulta',
      },
    },
    contact: {
      metaTitle: 'Contactar a E & I | Apoio a relocalização e imigração nos Países Baixos',
      metaDescription: 'Marque uma consulta de relocalização, escreva-nos no WhatsApp ou envie um pedido de imigração, relocalização ou VIP. Resposta pessoal no prazo de um dia útil.',
      eyebrow: 'Contacto',
      title: 'Comece a sua mudança',
      intro: [
        'Escolha o percurso adequado à sua situação e escreva-nos algumas linhas. O seu pedido chega diretamente à Johanna e terá uma resposta pessoal no prazo de um dia útil.',
      ],
      tabs: [
        {
          key: 'immigration',
          label: 'Imigração',
          text: 'Vistos, autorizações e pedidos ao IND.',
        },
        {
          key: 'relocation',
          label: 'Relocalização e habitação',
          text: 'Pacotes, habitação, escolas e instalação.',
        },
        {
          key: 'vip',
          label: 'VIP',
          text: 'Relocalizações concierge e visitas relâmpago.',
        },
      ],
      whatsapp: {
        heading: 'Apoio à relocalização por WhatsApp',
        text: 'A forma mais rápida de nos contactar e o canal que os nossos clientes continuam a usar muito depois de chegarem.',
        label: 'Escreva-nos no WhatsApp',
      },
      emergency: {
        heading: 'Apoio urgente à relocalização',
        text: 'Prazo amanhã, casa que caiu por terra, marcação que não pode falhar? Escreva-nos no WhatsApp com a palavra URGENTE e respondemos de imediato, de dia ou de noite.',
      },
      details: {
        heading: 'Dados',
      },
      formCopy: {
        immigration: {
          heading: 'Pedido de imigração e relocalização',
          text: 'Diga-nos a sua nacionalidade e a via que tem em mente. Não sabe que visto lhe serve? Diga-o, essa avaliação é exatamente o que fazemos.',
          service: 'De que serviço precisa?',
          serviceOptions: [
            'Visto de trabalhador altamente qualificado',
            'Cartão Azul UE',
            'Visto de ano de orientação',
            'Visto de cônjuge',
            'Reagrupamento familiar',
            'Visto startup',
            'Visto DAFT',
            'Visto Schengen de negócios',
            'Autorização de residência',
            'Ainda não tenho a certeza',
          ],
          nationality: 'Nacionalidade',
          currentLocation: 'País de residência atual',
          status: 'Situação atual de residência',
          statusOptions: [
            'Fora da UE, ainda sem autorização neerlandesa',
            'Já nos Países Baixos com visto ou autorização',
            'Cidadão da UE ou do EEE',
            'Outra situação ou não sei',
          ],
          timeline: 'Quando pensa mudar-se?',
          timelineOptions: [
            'O mais depressa possível',
            'Dentro de 3 meses',
            'De 3 a 6 meses',
            'Estou a explorar opções',
          ],
          message: 'A sua situação',
          messagePlaceholder: 'Por exemplo: cidadão dos EUA, com proposta para um cargo em Roterdão a começar em março, com cônjuge e dois filhos.',
        },
        relocation: {
          heading: 'Pedido de relocalização e habitação',
          text: 'De um serviço avulso a um pacote completo. Diga-nos como deve ser a sua chegada.',
          service: 'De que precisa?',
          serviceOptions: [
            'Pacote completo de relocalização',
            'Procura de habitação',
            'Procura de escola',
            'BSN e registos',
            'Apoio à instalação',
            'Alojamento temporário',
            'Relocalização na região industrial',
            'Outra coisa',
          ],
          movingFrom: 'Vem de',
          household: 'Quem se muda?',
          householdOptions: [
            'Só eu',
            'Eu e o meu cônjuge',
            'A minha família com filhos',
            'Colaboradores da minha empresa',
            'Outra situação',
          ],
          timeline: 'Quando chega?',
          timelineOptions: [
            'O mais depressa possível',
            'Dentro de 3 meses',
            'De 3 a 6 meses',
            'Estou a explorar opções',
          ],
          message: 'A sua mudança',
          messagePlaceholder: 'Por exemplo: família de quatro pessoas a mudar-se de Zurique no verão, precisamos de casa perto de uma escola internacional.',
        },
        vip: {
          heading: 'Pedido de relocalização VIP',
          text: 'Discreto, rápido e construído em torno da sua agenda. Diga-nos as datas e desenhamos a visita.',
          package: 'Que pacote lhe interessa?',
          packageOptions: [
            'Pacote VIP Casal',
            'Pacote VIP Família',
            'Pacote VIP Empresa',
            'VIP Relocation Concierge',
            'Ainda não tenho a certeza',
          ],
          preferredContact: 'Contacto preferido',
          preferredContactOptions: [
            'WhatsApp',
            'Telefone',
            'E-mail',
          ],
          arrival: 'Chegada prevista',
          movingFrom: 'Vem de',
          message: 'A sua relocalização',
          messagePlaceholder: 'Por exemplo: mudança de Los Angeles em outubro, disponível para uma visita de preparação em setembro.',
        },
      },
    },
    privacy: {
      metaTitle: 'Política de privacidade | E & I Expat & Immigration Services',
      title: 'Política de privacidade',
      intro: [
        'A E & I: Expat, Relocation and Immigration Services The Netherlands trata dados pessoais apenas para responder ao seu pedido e para prestar os serviços de relocalização e imigração que nos confiar.',
      ],
      sections: [
        {
          heading: 'Que dados recolhemos',
          paragraphs: [
            'Quando nos contacta, recebemos os dados que decide partilhar: o seu nome, os seus contactos e a descrição da sua situação. Para clientes ativos tratamos ainda os documentos necessários aos pedidos, sempre com o seu conhecimento.',
          ],
        },
        {
          heading: 'Como os usamos',
          paragraphs: [
            'Os seus dados servem para lhe responder, para preparar e gerir o seu processo de relocalização ou imigração, e para mais nenhum fim. Não vendemos dados e não os usamos para publicidade.',
          ],
        },
        {
          heading: 'Conservação e os seus direitos',
          paragraphs: [
            'Os dados do pedido são conservados apenas durante o tempo necessário para o servir. Pode solicitar a qualquer momento o acesso, a retificação ou a eliminação dos seus dados através dos contactos abaixo.',
          ],
        },
        {
          heading: 'Contacto',
          paragraphs: [
            'E & I: Expat, Relocation and Immigration Services The Netherlands, Laan van Zuid Hoorn 70, Rijswijk. KvK 65768922.',
          ],
        },
      ],
    },
    notFound: {
      title: 'Esta página mudou-se',
      text: 'A página que procura não existe ou o seu endereço mudou. Deixe-nos mostrar-lhe o caminho de volta.',
      label: 'Voltar à página inicial',
    },
  };
