/* GENERATED by scripts/i18n-strings.mjs. Do not hand-edit.
   pt/immigration.ts is a 1:1 structural mirror of en/immigration.ts; only leaf strings
   differ. To change structure, change English and re-run the build. */
import type { SectionContent } from '../types';

export const immigration: SectionContent = {
    title: 'Serviços de imigração para expatriados',
    metaTitle: 'Serviços de imigração para expatriados nos Países Baixos | E & I',
    metaDescription: 'Serviços de imigração práticos e com acompanhamento pessoal para expatriados nos Países Baixos. Vistos de trabalhador altamente qualificado, de cônjuge, startup e DAFT, tratados consigo e não para um número de processo.',
    eyebrow: 'Imigração',
    intro: [
      'Um visto neerlandês não é um formulário. É o momento em que a sua nova vida ou começa a tempo ou fica numa gaveta do IND. Tratamos o lado da imigração da sua mudança como deve ser tratado: de forma prática, pessoal e com alguém que já levou centenas de famílias por estas mesmas portas. Sendo a única consultoria boutique para expatriados nos Países Baixos, aceitamos poucos clientes e damos a cada um atenção verdadeira.',
      'Cada processo começa com uma avaliação honesta. Dizemos-lhe que autorização se ajusta realmente à sua situação, o que o IND vai pedir e o que lhe tiramos das mãos. A partir daí tem um interlocutor, um plano e nenhuma surpresa.',
    ],
    image: '/images/canal-evening.jpg',
    imageAlt: 'Pontes sobre os canais de Amesterdão iluminadas ao anoitecer',
    cta: {
      title: 'Não sabe que visto se ajusta à sua situação?',
      text: 'Diga-nos de onde vem e porquê. Dir-lhe-emos, sem rodeios, que via faz sentido e o que implica.',
      label: 'Comece com uma avaliação',
    },
    services: [
      {
        slug: 'highly-skilled-migrant-visa-netherlands',
        menuLabel: 'Trabalhador altamente qualificado',
        title: 'Visto de trabalhador altamente qualificado nos Países Baixos',
        metaTitle: 'Visto de trabalhador altamente qualificado nos Países Baixos | Acompanhamento pessoal',
        metaDescription: 'Vai mudar-se para os Países Baixos como trabalhador altamente qualificado? Coordenamos com o seu empregador, preparamos o pedido ao IND e acompanhamos a sua família em cada passo.',
        eyebrow: 'Visto de trabalho',
        intro: [
          'A via do trabalhador altamente qualificado é a forma mais rápida e limpa de um profissional internacional trabalhar nos Países Baixos. O seu empregador tem de ser um patrocinador reconhecido pelo IND, o seu salário tem de atingir o limiar do IND em vigor para o seu escalão etário, e a papelada tem de estar certa logo à primeira.',
          'É aí que entramos. Coordenamos diretamente com os recursos humanos do seu empregador, preparamos o senhor e a sua família para cada marcação e continuamos contactáveis na nossa linha pessoal de WhatsApp 24 horas por dia, sempre que surja uma dúvida, em qualquer fuso horário.',
        ],
        cardText: 'A via de trabalho mais rápida para os Países Baixos, coordenada entre si, o seu empregador e o IND.',
        explainer: {
          title: 'O que é a autorização de trabalhador altamente qualificado?',
          text: [
            'A autorização de trabalhador altamente qualificado, kennismigrant em neerlandês, é a via pela qual os Países Baixos trazem depressa profissionais experientes. Não é avaliada pelo seu cargo nem pelo seu diploma. É avaliada por uma coisa: se um empregador neerlandês reconhecido pelo IND como patrocinador lhe paga um salário acima de um limiar fixado.',
            'Como o reconhecimento recai sobre o empregador, o procedimento é rápido e não há teste ao mercado de trabalho. A autorização está ligada a esse empregador, pelo que é o contrato, e não a pessoa, que ancora a sua residência nos Países Baixos.',
          ],
        },
        forWho: {
          title: 'A quem se dirige',
          items: [
            'Profissionais com uma proposta de trabalho de uma empresa neerlandesa',
            'Colaboradores transferidos para um escritório nos Países Baixos',
            'Cônjuges e filhos que se mudam com o requerente principal',
            'Equipas de recursos humanos que transferem pela primeira vez uma contratação internacional',
          ],
        },
        included: {
          title: 'Do que tratamos',
          blocks: [
            {
              title: 'Verificação de requisitos e salário',
              text: 'Antes de entregar seja o que for, confirmamos que o seu empregador é patrocinador reconhecido e que a proposta atinge o limiar salarial do IND em vigor, que é indexado todos os anos.',
            },
            {
              title: 'Coordenação com o seu empregador',
              text: 'É o patrocinador que apresenta formalmente o pedido. Preparamos o processo com os recursos humanos, insistimos no que falta e mantemos ambos os lados num só calendário.',
            },
            {
              title: 'Pedidos para a família',
              text: 'O seu cônjuge e os seus filhos apresentam pedido consigo. Agrupamos os pedidos para que toda a família chegue com as autorizações certas ao mesmo tempo.',
            },
            {
              title: 'Apoio nos documentos',
              text: 'Certidões de nascimento e de casamento precisam muitas vezes de legalização ou apostila do seu país de origem. Dizemos-lhe exatamente que selo, de que autoridade, antes de viajar.',
            },
            {
              title: 'Marcações à chegada',
              text: 'Biometria, levantamento da autorização, registo na câmara municipal e BSN. Agendamo-los pela ordem certa e vamos consigo.',
            },
          ],
        },
        process: {
          title: 'Como funciona',
          steps: [
            {
              title: 'Avaliação inicial',
              text: 'Analisamos a sua proposta, a sua nacionalidade e a sua situação familiar e traçamos a via e os prazos exatos.',
            },
            {
              title: 'Preparação do processo',
              text: 'Reunimos os documentos consigo e com o seu empregador e entregamos através do patrocinador.',
            },
            {
              title: 'Decisão e MVV',
              text: 'Consoante a sua nacionalidade, levanta um visto de entrada na embaixada neerlandesa antes de viajar. Preparamo-lo para essa marcação.',
            },
            {
              title: 'Aterragem',
              text: 'Nos primeiros dias concluímos o registo, o levantamento da autorização e o essencial prático.',
            },
          ],
        },
        fees: {
          title: 'Honorários por um pedido de trabalhador altamente qualificado',
          kind: 'fixed',
          amount: 'Investimento a partir de 1.295 €',
          includes: [
            'Verificação do limiar salarial aplicável à sua idade e à sua situação',
            'O processo completo preparado e entregue através do seu patrocinador reconhecido',
            'Coordenação com os recursos humanos do seu empregador para que contrato e data de início coincidam',
            'Resposta a cada pedido do IND até à emissão da decisão',
          ],
        },
        note: 'Muitos trabalhadores altamente qualificados têm direito ao regime dos 30%, um benefício fiscal neerlandês para colaboradores vindos do estrangeiro. As condições mudam com frequência, por isso sinalizamo-lo na avaliação inicial e pomo-lo em contacto com um consultor fiscal em vez de prometer números.',
        conditions: {
          title: 'O que o IND exige',
          intro: 'Esta via passa pelo seu empregador mais do que por si. São estas condições que decidem o processo antes sequer de ser aberto.',
          items: [
            'O seu empregador tem de ser patrocinador reconhecido pelo IND. Sem esse reconhecimento a via está fechada, seja qual for o salário.',
            'Salário mensal bruto a partir de 5.942 euros se tiver 30 anos ou mais, e a partir de 4.357 euros se tiver menos de 30 (2026, excluindo o subsídio de férias de 8 por cento).',
            'Aplica-se um limiar reduzido de 3.122 euros no ano seguinte a um ano de orientação neerlandês ou a um diploma neerlandês.',
            'O salário tem de ser pago mensalmente numa conta bancária neerlandesa. Prémios, subsídios e verbas de despesas não contam para o limiar.',
            'O regime dos 30 por cento é calculado acima do limiar e nunca pode ser usado para o atingir.',
            'Os limiares são indexados a 1 de janeiro e avaliados pelos valores em vigor na data de entrega do pedido.',
          ],
        },
        details: {
          title: 'Pormenores que vale a pena conhecer',
          items: [
            {
              q: 'E se o meu empregador não for patrocinador reconhecido?',
              a: 'O reconhecimento leva semanas que uma data de início raramente tem. Quando um empregador não é reconhecido, olhamos para o Cartão Azul UE, que não exige patrocínio, ou tratamos do pedido de reconhecimento em paralelo com o seu processo se a empresa tencionar voltar a contratar no estrangeiro.',
            },
            {
              q: 'Na prática, quão rápida é a decisão?',
              a: 'Os patrocinadores reconhecidos têm um prazo legal de decisão de noventa dias, e processos completos são frequentemente decididos em duas a quatro semanas. O atraso nesta via é quase sempre um documento legalizado em falta, não o IND.',
            },
            {
              q: 'O que acontece quando mudo de emprego?',
              a: 'A sua autorização está ligada ao seu empregador. O novo empregador também tem de ser patrocinador reconhecido e tem de apresentar um novo pedido, e não pode começar antes da aprovação. Gerimos a transição para que não haja qualquer interrupção na sua residência.',
            },
            {
              q: 'Preciso de MVV além da autorização?',
              a: 'A maioria dos cidadãos de fora da UE precisa, e pedimos ambos num procedimento combinado. Os nacionais dos Estados Unidos, Canadá, Japão, Austrália, Nova Zelândia, Coreia do Sul e Reino Unido estão isentos e viajam apenas com a autorização.',
            },
          ],
        },
        faq: {
          title: 'Perguntas que ouvimos com frequência',
          items: [
            {
              q: 'O meu cônjuge pode trabalhar nos Países Baixos?',
              a: 'Sim. Os cônjuges de trabalhadores altamente qualificados recebem uma autorização de residência com livre acesso ao mercado de trabalho. Não é necessária uma autorização de trabalho separada.',
            },
            {
              q: 'Quanto tempo demora o pedido?',
              a: 'Os pedidos feitos através de um patrocinador reconhecido seguem a via rápida do IND e, na prática, a maioria dos casos avança depressa. Confirmamos prazos e taxas atuais do IND durante a avaliação inicial, em vez de citar números que envelhecem.',
            },
            {
              q: 'Preciso de falar neerlandês?',
              a: 'Não. Não existe qualquer requisito linguístico para esta autorização, e a vida quotidiana nas comunidades internacionais de Roterdão e Haia corre bem em inglês.',
            },
            {
              q: 'O meu cônjuge pode trabalhar nos Países Baixos?',
              a: 'Sim. Os cônjuges de trabalhadores altamente qualificados recebem uma autorização com livre acesso ao mercado de trabalho, o que significa que não é preciso autorização de trabalho separada nem patrocínio do empregador. Os filhos são incluídos no mesmo pedido familiar.',
            },
          ],
        },
        cta: {
          title: 'Tem uma proposta de um empregador neerlandês?',
          text: 'Envie-nos o essencial e, numa só conversa, dir-lhe-emos se a via está livre e o que acontece a seguir.',
          label: 'Verificar os meus requisitos',
        },
        form: 'immigration',
        image: '/images/hsm-visa.jpg?v=20260731',
        imageAlt: 'Profissional internacional no átrio de um escritório neerlandês',
        image2: '/images/employer-immigration.jpg',
        image2Alt: 'Dois profissionais internacionais em conversa à porta de um escritório neerlandês',
      },
      {
        slug: 'eu-blue-card-netherlands',
        menuLabel: 'Cartão Azul UE',
        title: 'Cartão Azul UE nos Países Baixos',
        metaTitle: 'Cartão Azul UE nos Países Baixos | Apoio ao pedido para expatriados',
        metaDescription: 'Peça o Cartão Azul UE nos Países Baixos com acompanhamento pessoal. Reconhecimento do diploma, coordenação com o empregador e uma autorização que acompanha a sua carreira europeia.',
        eyebrow: 'Visto de trabalho',
        intro: [
          'O Cartão Azul UE é a autorização de trabalho europeia para profissionais com formação superior, e a versão neerlandesa tornou-se genuinamente atrativa. Dá-lhe o direito de viver e trabalhar nos Países Baixos e constrói direitos de mobilidade na UE que uma autorização nacional não confere.',
          'A nossa reputação nasceu no mundo das embaixadas, e os processos de Cartão Azul recompensam exatamente esse rigor: um diploma corretamente avaliado, um contrato conforme e uma entrega impecável. Garantimos que o seu tem as três coisas.',
        ],
        cardText: 'A autorização de trabalho europeia para profissionais com formação superior, com mobilidade na UE.',
        explainer: {
          title: 'O que é o Cartão Azul UE?',
          text: [
            'O Cartão Azul UE é uma autorização europeia de residência e trabalho para profissionais com formação universitária. Enquanto a autorização neerlandesa de trabalhador altamente qualificado só olha para o salário e para um patrocinador reconhecido, o Cartão Azul exige ainda um percurso de ensino superior concluído e, em troca, confere direitos que vão além dos Países Baixos.',
            'É essa a diferença real. Um Cartão Azul constrói mobilidade dentro da União Europeia e caminho para o estatuto de residente de longa duração UE, coisa que a autorização nacional não faz. É a melhor escolha quando os Países Baixos são um capítulo e não o livro inteiro.',
          ],
        },
        forWho: {
          title: 'É esta a sua via?',
          items: [
            'Profissionais com licenciatura e uma proposta de trabalho neerlandesa',
            'Especialistas que podem circular entre países da UE ao longo da carreira',
            'Colaboradores cujo empregador não é patrocinador reconhecido pelo IND',
            'Profissionais de TI experientes que podem qualificar-se pela experiência',
          ],
        },
        included: {
          title: 'Como o tratamos',
          blocks: [
            {
              title: 'Comparação de vias',
              text: 'Comparamos o Cartão Azul com a autorização de trabalhador altamente qualificado para o seu caso concreto, porque para alguns perfis uma é claramente melhor do que a outra.',
            },
            {
              title: 'Avaliação do diploma',
              text: 'Os diplomas estrangeiros precisam normalmente de reconhecimento nos Países Baixos. Acompanhamos a avaliação das credenciais para que a sua qualificação seja aceite sem idas e vindas.',
            },
            {
              title: 'Revisão de salário e contrato',
              text: 'O seu contrato tem de cumprir o limiar salarial do IND em vigor e os requisitos de duração. Revemo-lo antes da entrega, não depois de uma recusa.',
            },
            {
              title: 'Gestão do pedido',
              text: 'Preparamos e gerimos todo o pedido ao IND com o seu empregador e acompanhamo-lo até sair a decisão.',
            },
          ],
        },
        process: {
          title: 'A sua via, passo a passo',
          steps: [
            {
              title: 'Avaliação',
              text: 'Verificamos o seu diploma, a proposta e o salário face às condições em vigor do Cartão Azul.',
            },
            {
              title: 'Reconhecimento e processo',
              text: 'A avaliação do diploma é lançada enquanto construímos o processo em paralelo.',
            },
            {
              title: 'Entrega e chegada',
              text: 'Após a aprovação, planeamos a sua entrada, o registo e as primeiras marcações pela ordem certa.',
            },
          ],
        },
        fees: {
          title: 'Honorários por um pedido de Cartão Azul UE',
          kind: 'fixed',
          amount: 'Investimento a partir de 1.295 €',
          includes: [
            'Qualificação e salário testados face aos critérios do Cartão Azul antes de se comprometer',
            'Avaliação do diploma tratada onde o IND a exige',
            'Pedido preparado e entregue, incluindo a parte do processo que cabe ao empregador',
            'Acompanhamento até à decisão, incluindo qualquer pedido de documentos adicionais',
          ],
        },
        conditions: {
          title: 'Condições do Cartão Azul',
          intro: 'O Cartão Azul decide-se em três pontos: a sua qualificação, o seu contrato e o seu salário. É aqui que estão as linhas.',
          items: [
            'Um percurso de ensino superior concluído de pelo menos três anos, ou, para funções de TIC, pelo menos três anos de experiência relevante obtida nos últimos sete.',
            'Salário mensal bruto a partir de 5.942 euros, ou 4.754 euros no critério reduzido para recém-licenciados e profissões carenciadas (2026, excluindo subsídio de férias).',
            'Um contrato de trabalho ou uma proposta vinculativa com duração mínima de seis meses.',
            'Os diplomas estrangeiros têm de ser avaliados pelo IDW ou pela Nuffic. As qualificações neerlandesas não precisam de avaliação.',
            'O seu empregador não precisa de ser patrocinador reconhecido, e é essa a vantagem prática face à autorização de trabalhador altamente qualificado.',
            'Os limiares são indexados a 1 de janeiro e aplicados à data de entrega, não à data do contrato.',
          ],
        },
        details: {
          title: 'O Cartão Azul na prática',
          items: [
            {
              q: 'Como funciona realmente a mobilidade na UE?',
              a: 'Após doze meses de residência legal como titular de Cartão Azul pode mudar-se para outro Estado-Membro por um procedimento abreviado, e os anos passados em diferentes Estados-Membros somam-se para efeitos do estatuto de residente de longa duração UE. Uma autorização neerlandesa de trabalhador altamente qualificado não lhe dá nada disto.',
            },
            {
              q: 'Cartão Azul ou trabalhador altamente qualificado?',
              a: 'Se o seu empregador é patrocinador reconhecido e tenciona construir a carreira nos Países Baixos, a autorização de trabalhador altamente qualificado é normalmente mais rápida e simples. Se o empregador não é reconhecido, ou se a sua carreira tende a circular pela Europa, o Cartão Azul é o instrumento mais forte. Recebe a comparação por escrito antes de se comprometer.',
            },
            {
              q: 'Posso qualificar-me pela experiência em vez do diploma?',
              a: 'Apenas nas TIC. Gestores e especialistas de tecnologias de informação e comunicação podem qualificar-se com pelo menos três anos de experiência relevante obtida nos sete anos anteriores ao pedido. Todas as outras profissões precisam do diploma.',
            },
            {
              q: 'Quanto tempo demora a avaliação do diploma?',
              a: 'O IDW devolve normalmente uma avaliação em cerca de quatro semanas, mais tempo quando a instituição demora a confirmar a autenticidade. Lançamo-la em paralelo com o resto do processo para que nunca se torne o estrangulamento.',
            },
            {
              q: 'A que conduz o Cartão Azul?',
              a: 'Assim que tiver cinco anos de residência legal na UE, dos quais pelo menos dois nos Países Baixos, pode pedir aqui o estatuto de residente de longa duração UE. Essa acumulação transfronteiriça é exclusiva desta autorização.',
            },
          ],
        },
        faq: {
          title: 'Perguntas práticas',
          items: [
            {
              q: 'Que salário preciso para o Cartão Azul UE?',
              a: 'O limiar é fixado pelo IND e ajustado todos os anos, com um nível mais baixo para recém-licenciados. Verificamos a sua proposta face aos valores em vigor durante a avaliação, em vez de publicar números que caducam.',
            },
            {
              q: 'Cartão Azul ou trabalhador altamente qualificado, qual é melhor?',
              a: 'Depende. A via do trabalhador altamente qualificado é muitas vezes mais rápida se o seu empregador for patrocinador reconhecido. O Cartão Azul ganha na mobilidade na UE e não exige patrocínio. Aconselhamos caso a caso, com honestidade.',
            },
            {
              q: 'Posso trazer a minha família?',
              a: 'Sim. O seu cônjuge e os seus filhos podem apresentar pedido consigo, e o seu cônjuge pode trabalhar nos Países Baixos sem autorização de trabalho separada.',
            },
            {
              q: 'O regime dos 30 por cento conta para o limiar salarial?',
              a: 'Não. O IND avalia o seu salário bruto antes de aplicado o regime. Um contrato que só atinge o limiar contando o regime é recusado, e esta é uma das razões mais frequentes para um processo de Cartão Azul falhar.',
            },
          ],
        },
        cta: {
          title: 'Está a construir uma carreira europeia?',
          text: 'Envie-nos os dados do seu diploma e da sua proposta. Dir-lhe-emos se o Cartão Azul é a sua via mais forte para os Países Baixos.',
          label: 'Perguntar sobre o Cartão Azul',
        },
        form: 'immigration',
        image: '/images/eu-blue-card.jpg?v=20260731',
        imageAlt: 'Dois profissionais internacionais seniores em discussão',
        image2: '/images/hsm-visa.jpg?v=20260731',
        image2Alt: 'Profissional internacional no átrio de um escritório neerlandês',
      },
      {
        slug: 'orientation-year-visa-netherlands',
        menuLabel: 'Visto de ano de orientação',
        title: 'Visto de ano de orientação nos Países Baixos',
        metaTitle: 'Visto de ano de orientação nos Países Baixos | Zoekjaar para licenciados',
        metaDescription: 'Recém-licenciado ou doutorado? O visto neerlandês de ano de orientação dá-lhe doze meses para viver e trabalhar livremente nos Países Baixos. Tratamos do pedido e da sua chegada.',
        eyebrow: 'Visto para licenciados',
        intro: [
          'O ano de orientação, o zoekjaar, é uma das autorizações mais generosas da Europa. Se concluiu recentemente um curso numa instituição neerlandesa ou numa universidade internacional de topo, dá-lhe doze meses para viver nos Países Baixos e trabalhar para qualquer empregador, sem necessidade de patrocínio.',
          'O pedido em si é simples quando bem feito, por isso o nosso valor real está no que vem depois: transformar esse ano numa carreira e numa casa. Acompanhamos os recém-licenciados do primeiro formulário ao primeiro apartamento e ficamos por perto enquanto encontram o seu equilíbrio.',
        ],
        cardText: 'Doze meses para viver e trabalhar livremente nos Países Baixos depois do curso.',
        explainer: {
          title: 'O que é o ano de orientação?',
          text: [
            'O ano de orientação, zoekjaar em neerlandês, é uma autorização de residência de um ano que permite a recém-licenciados e investigadores procurar trabalho nos Países Baixos sem que um empregador os patrocine primeiro. Durante esse ano pode trabalhar livremente, sem que nenhum empregador precise de autorização de trabalho.',
            'Existe para resolver um problema circular: os empregadores querem alguém que possa começar, e as autorizações costumam exigir um empregador. O ano de orientação quebra esse bloqueio e traz depois um limiar salarial mais baixo se transitar para uma autorização de trabalhador altamente qualificado.',
          ],
        },
        forWho: {
          title: 'Quem reúne condições',
          items: [
            'Licenciados por universidades e hogescholen neerlandesas, até três anos após a conclusão',
            'Licenciados por universidades internacionais de topo',
            'Doutorados e investigadores que concluíram recentemente nos Países Baixos ou no estrangeiro',
            'Antigos titulares do ano de orientação que transitam agora para uma autorização de trabalho',
          ],
        },
        included: {
          title: 'O que fazemos por si',
          blocks: [
            {
              title: 'Verificação de requisitos',
              text: 'Confirmamos o seu diploma, a data de conclusão e a posição da sua universidade nos rankings face aos requisitos do IND antes de gastar um euro no pedido.',
            },
            {
              title: 'Gestão completa do pedido',
              text: 'Esta autorização é pedida por si, sem empregador. Preparamos o processo, entregamo-lo e acompanhamo-lo para que nada encalhe.',
            },
            {
              title: 'Papelada do diploma',
              text: 'Os diplomas estrangeiros precisam das cópias autenticadas certas e, nalguns casos, de legalização. Dizemos-lhe com precisão o que levar.',
            },
            {
              title: 'Apoio à chegada',
              text: 'Registo na câmara municipal, BSN, seguro de saúde e um quarto ou apartamento num mercado brutal para recém-chegados. Sabemos onde procurar e a quem ligar.',
            },
            {
              title: 'O passo seguinte',
              text: 'Quando encontrar emprego, os empregadores podem contratá-lo com um limiar salarial reduzido. Gerimos a transição para a autorização de trabalhador altamente qualificado quando chegar o momento.',
            },
          ],
        },
        process: {
          title: 'Como funciona',
          steps: [
            {
              title: 'Verificação',
              text: 'Uma conversa para confirmar que reúne condições e para planear os prazos da sua mudança.',
            },
            {
              title: 'Pedido',
              text: 'Preparamos e entregamos o pedido ao IND e mantemo-lo informado a cada mudança de estado.',
            },
            {
              title: 'Chegar e instalar-se',
              text: 'Organizamos o registo e o essencial para que possa dedicar o ano à carreira e não à burocracia.',
            },
          ],
        },
        fees: {
          title: 'Honorários pelo ano de orientação',
          kind: 'tailored',
          amount: 'Sob consulta',
          amountNote: 'O ano de orientação é um procedimento curto e o que precisa de nós depende de apresentar o pedido a partir dos Países Baixos ou do estrangeiro. Após uma breve avaliação do seu diploma e dos seus prazos, recebe um orçamento fixo.',
          includes: [
            'Verificação de se o seu diploma e a data de conclusão ainda dão direito',
            'Pedido preparado e entregue ao IND',
            'Acompanhamento na transição para uma autorização de trabalho antes de o ano terminar',
          ],
        },
        note: 'A janela de três anos após a conclusão do curso é rígida, e as listas de rankings mudam todos os anos. Se estiver no limite, contacte-nos antes de assumir que está fora. As dúvidas raramente respeitam o horário de expediente, e é por isso que os clientes nos contactam numa linha pessoal de WhatsApp de dia e de noite.',
        conditions: {
          title: 'Quem tem direito ao zoekjaar',
          intro: 'O ano de orientação é generoso depois de lá estar dentro e rigoroso quanto a quem entra. A janela é a parte que escapa às pessoas.',
          items: [
            'Tem de apresentar o pedido no prazo de três anos após concluir o curso, obter o doutoramento ou terminar a investigação.',
            'Os licenciados de programas neerlandeses acreditados de licenciatura, mestrado e doutoramento qualificam-se apenas com o diploma neerlandês.',
            'Os licenciados internacionais precisam de um diploma de uma universidade entre as 200 melhores de um ranking mundial reconhecido.',
            'A autorização dura doze meses, não é prorrogável e só pode ser concedida uma vez.',
            'Pode trabalhar por conta de outrem ou por conta própria durante todo o ano, sem autorização de trabalho e sem limiar salarial.',
            'No ano seguinte aplica-se o critério reduzido de trabalhador altamente qualificado de 3.122 euros (2026).',
          ],
        },
        details: {
          title: 'Aproveitar o ano',
          items: [
            {
              q: 'O que me torna mais fácil de contratar durante o zoekjaar?',
              a: 'Tem livre acesso ao mercado de trabalho neerlandês. O seu empregador não precisa de autorização de trabalho, nem de patrocínio, e não paga qualquer taxa ao IND, o que elimina exatamente a objeção que bloqueia os outros candidatos de fora da UE. Ponha isso na primeira linha, porque a maioria dos empregadores neerlandeses não sabe.',
            },
            {
              q: 'O que acontece no fim dos doze meses?',
              a: 'Transita para outra autorização, normalmente a de trabalhador altamente qualificado no critério reduzido. A transição tem de ser entregue antes de o ano de orientação expirar, por isso começamos a prepará-la por volta do nono mês e não do décimo segundo.',
            },
            {
              q: 'Posso criar uma empresa durante o ano?',
              a: 'Pode inscrever-se na KvK e trabalhar por conta própria durante todo o período. Converter depois para uma base empresarial permanente é um pedido separado com o seu próprio teste, por isso vale a pena planeá-lo desde o início.',
            },
            {
              q: 'O meu cônjuge recebe alguma coisa?',
              a: 'Sim. O seu cônjuge pode pedir uma autorização de familiar para os mesmos doze meses e tem também livre acesso ao mercado de trabalho.',
            },
          ],
        },
        faq: {
          title: 'Perguntas frequentes',
          items: [
            {
              q: 'Posso trabalhar durante o ano de orientação?',
              a: 'Sim, plenamente e sem restrições. Qualquer empregador o pode contratar sem autorização de trabalho nem patrocínio durante os doze meses.',
            },
            {
              q: 'Preciso de emprego ou rendimento para apresentar o pedido?',
              a: 'Não é exigida qualquer proposta de trabalho. Precisa de demonstrar que se consegue sustentar, e explicamos-lhe passo a passo o que o IND aceita como prova.',
            },
            {
              q: 'O que acontece quando o ano termina?',
              a: 'A maioria dos licenciados transita para uma autorização de trabalhador altamente qualificado através do novo empregador, com um limiar salarial reduzido que facilita a contratação. Planeamos essa transição muito antes do décimo segundo mês.',
            },
          ],
        },
        cta: {
          title: 'O seu diploma acabou de abrir uma porta',
          text: 'Diga-nos onde e quando concluiu o curso. Confirmamos os seus requisitos e esboçamos o seu ano nos Países Baixos.',
          label: 'Verificar o meu ano de orientação',
        },
        form: 'immigration',
        image: '/images/orientation-year.jpg?v=20260731',
        imageAlt: 'Recém-licenciada a caminhar junto a um canal de Amesterdão no outono',
        image2: '/images/consultation.jpg',
        image2Alt: 'Consultora e cliente a discutir os passos seguintes',
      },
      {
        slug: 'partner-visa-netherlands',
        menuLabel: 'Visto de cônjuge',
        title: 'Visto de Cônjuge nos Países Baixos',
        metaTitle: 'Visto de Cônjuge nos Países Baixos | Traga Quem Ama',
        metaDescription: 'Traga o seu companheiro para os Países Baixos com confiança. Acompanhamos todo o processo do visto de cônjuge, dos requisitos de rendimento ao exame de integração cívica e à marcação na embaixada.',
        eyebrow: 'Visto de família',
        intro: [
          'Nenhum processo pesa tanto como aquele que traz a pessoa que ama até à sua porta. O visto de cônjuge neerlandês é perfeitamente exequível, mas não perdoa pequenos erros: um comprovativo de rendimentos no formato errado, uma inscrição no exame que ficou por fazer, uma certidão sem o selo correto, e perde meses.',
          'Tratamos estes casos com o cuidado que merecem. A Johanna acompanha pessoalmente os clientes às marcações, do balcão da câmara municipal ao IND, para que nenhum dos dois se sente alguma vez diante de um funcionário sem preparação.',
        ],
        cardText: 'Acompanhamento cuidadoso e pessoal para trazer o seu companheiro ou cônjuge para os Países Baixos.',
        explainer: {
          title: 'O que é um visto de cônjuge?',
          text: [
            'Um visto de cônjuge é uma residência concedida com base na relação e não no emprego. Um dos dois, o garante, já tem o direito de viver nos Países Baixos. O outro candidata-se para se juntar a ele. O casamento não é obrigatório, mas uma relação não formalizada tem de ser comprovada como duradoura e exclusiva.',
            'O procedimento neerlandês avalia três coisas: que a relação é genuína, que o garante aufere um rendimento estável e suficiente e que os documentos de registo civil emitidos no estrangeiro estão devidamente legalizados e traduzidos. A maioria das recusas nasce do terceiro ponto, não do primeiro.',
          ],
        },
        forWho: {
          title: 'Quem acompanhamos',
          items: [
            'Cidadãos e residentes neerlandeses que trazem um companheiro do estrangeiro',
            'Expatriados já nos Países Baixos cujo companheiro chega mais tarde',
            'Casais casados e não casados, incluindo companheiros de longa data sem certidão de casamento',
            'Casais que já receberam uma recusa e querem fazer as coisas bem desta vez',
          ],
        },
        included: {
          title: 'O que tratamos em conjunto',
          blocks: [
            {
              title: 'Análise honesta de elegibilidade',
              text: 'Avaliamos o rendimento do garante face à exigência do IND, as provas da relação e as duas nacionalidades antes de prometer o que quer que seja.',
            },
            {
              title: 'O MVV e o exame de integração',
              text: 'Muitas nacionalidades têm de passar o exame básico de integração cívica no estrangeiro e levantar um visto de entrada na embaixada neerlandesa. Planeamos a preparação para o exame e a própria marcação.',
            },
            {
              title: 'Legalização de documentos',
              text: 'As certidões de nascimento e de casamento têm de ser legalizadas ou apostiladas no país de origem. Mapeamos exatamente que documentos precisam de que tratamento.',
            },
            {
              title: 'Pedido e acompanhamento',
              text: 'Preparamos e submetemos o processo completo e mantemos a pressão junto do IND até chegar a decisão.',
            },
            {
              title: 'A chegada enquanto casal',
              text: 'Registo, BSN, seguro de saúde e as primeiras semanas práticas. O seu companheiro deve chegar a uma vida, não a uma lista de tarefas.',
            },
          ],
        },
        process: {
          title: 'O percurso, passo a passo',
          steps: [
            {
              title: 'Primeira conversa a dois',
              text: 'Falamos com os dois, analisamos rendimentos e documentos e definimos um calendário realista.',
            },
            {
              title: 'Preparação no estrangeiro',
              text: 'Exame, legalizações e logística da embaixada no país do seu companheiro, coordenados a partir daqui.',
            },
            {
              title: 'Submissão e decisão',
              text: 'O processo segue para o IND. Acompanhamo-lo e respondemos de imediato a qualquer pedido adicional.',
            },
            {
              title: 'Reunidos',
              text: 'O seu companheiro viaja, faz o registo e recebe a autorização de residência. Estamos presentes na aterragem.',
            },
          ],
        },
        fees: {
          title: 'Honorários para um pedido de visto de cônjuge',
          kind: 'fixed',
          amount: 'Investimento a partir de €895',
          includes: [
            'Avaliação das provas da relação antes de qualquer submissão',
            'Processos do garante e do requerente preparados em conjunto para que não se contradigam',
            'Requisitos de legalização e tradução mapeados para o seu país de origem',
            'Pedido submetido e acompanhado até à decisão',
          ],
        },
        conditions: {
          title: 'O que tem de se verificar',
          intro: 'Os pedidos de cônjuge são recusados por falta de prova muito mais vezes do que por falta de elegibilidade. Estas são as condições, e os pontos onde os processos costumam perder-se.',
          items: [
            'O garante nos Países Baixos tem de auferir pelo menos 2.523,96 euros brutos por mês, incluindo subsídio de férias (2026, revisto duas vezes por ano).',
            'Esse rendimento tem de ser duradouro. Um contrato sem termo cumpre o requisito de imediato; um contrato a termo é avaliado pelo tempo que ainda falta cumprir.',
            'A relação tem de ser exclusiva, duradoura e demonstrável. Casamento, união registada e relações não formalizadas devidamente documentadas são todos aceites.',
            'Ambos os companheiros têm de ter, no mínimo, 21 anos.',
            'A maioria dos companheiros tem de passar o exame básico de integração cívica no estrangeiro antes de poder ser emitido um MVV.',
            'As certidões estrangeiras de nascimento, de casamento e de estado civil precisam normalmente de legalização ou apostila, mais uma tradução ajuramentada.',
          ],
        },
        details: {
          title: 'Os pontos sensíveis que tratamos',
          items: [
            {
              q: 'O que conta como rendimento duradouro?',
              a: 'Um contrato sem termo cumpre o requisito de imediato. Com um contrato a termo, o IND pergunta se o rendimento se mantém nos próximos doze meses, e um contrato com pelo menos um ano por cumprir, ou um histórico de três anos de trabalho, costuma bastar. Os garantes que trabalham por conta própria são avaliados com base em três anos de contas.',
            },
            {
              q: 'Não somos casados. Isso conta contra nós?',
              a: 'Não, mas eleva a fasquia da prova. Construímos um dossiê da relação: histórico de morada comum, finanças partilhadas, viagens, fotografias ao longo dos anos, registos de comunicação e declarações de quem os conhece. É aqui que os pedidos recusados se perdem, e é aqui que a preparação cuidada os ganha.',
            },
            {
              q: 'Quem está isento do exame de integração no estrangeiro?',
              a: 'Os nacionais da UE, do EEE, da Suíça, dos Estados Unidos, do Canadá, da Austrália, da Nova Zelândia, do Japão, da Coreia do Sul e do Reino Unido, entre alguns outros, além dos requerentes que não o podem prestar por motivos médicos ou que possuem uma qualificação neerlandesa ou belga. Todos os restantes fazem o exame numa embaixada neerlandesa.',
            },
            {
              q: 'Já fomos recusados. Isso pode ser reparado?',
              a: 'Muitas vezes, sim. Uma recusa não é um impedimento permanente, mas o segundo processo tem de responder ao fundamento exato da primeira recusa em vez de repetir a primeira tentativa. Envie-nos a carta de decisão e receberá uma leitura honesta sobre se o melhor caminho é um novo pedido ou uma reclamação formal.',
            },
          ],
        },
        faq: {
          title: 'O que os casais nos perguntam',
          items: [
            {
              q: 'O meu companheiro pode trabalhar assim que chegar?',
              a: 'Sim. A autorização de residência de cônjuge dá acesso livre ao mercado de trabalho neerlandês, pelo que pode aceitar qualquer emprego sem uma autorização de trabalho separada.',
            },
            {
              q: 'De que rendimento preciso enquanto garante?',
              a: 'O IND exige um rendimento sustentável e autónomo, num valor que atualiza duas vezes por ano. Verificamos a sua situação exata, incluindo contratos e trabalho por conta própria, na primeira conversa.',
            },
            {
              q: 'Não somos casados. Isso é um problema?',
              a: 'Não. Os Países Baixos reconhecem relações duradouras entre companheiros não casados. Terá de comprovar a relação, e ajudamo-lo a construir esse dossiê de forma convincente.',
            },
          ],
        },
        cta: {
          title: 'Comecem aqui a vossa vida, juntos',
          text: 'Falem-nos sobre os dois. Terão um retrato claro e honesto do percurso e do tempo que a espera realmente demora.',
          label: 'Planear o nosso visto de cônjuge',
        },
        form: 'immigration',
        image: '/images/partner-visa.jpg?v=20260731',
        imageAlt: 'Casal em casa no seu apartamento neerlandês',
        image2: '/images/daft-couple.jpg',
        image2Alt: 'Casal junto a um canal neerlandês ao pôr do sol',
      },
      {
        slug: 'family-reunification-netherlands',
        menuLabel: 'Visto de relocalização familiar',
        title: 'Reagrupamento Familiar nos Países Baixos',
        metaTitle: 'Reagrupamento Familiar Países Baixos | Mudar em Família',
        metaDescription: 'Reagrupamento familiar nos Países Baixos, tratado com calor humano e precisão. Autorizações para cônjuges e filhos, procura de escola e uma aterragem suave para toda a família.',
        eyebrow: 'Visto de família',
        intro: [
          'Uma mudança só resulta quando a família inteira chega bem. O reagrupamento familiar permite que o seu cônjuge e os seus filhos se juntem a si nos Países Baixos, e fazê-lo como deve ser significa reunir autorizações, certidões do seu país de origem e o planeamento escolar numa única operação coordenada.',
          'Conduzimos essa operação para famílias em Rotterdam, Europoort e em toda a região industrial envolvente, onde profissionais internacionais chegam com contratos e as famílias seguem depois. É o nosso terreno, e isso influencia tudo, desde as escolas que recomendamos até aos balcões das câmaras municipais que conhecemos pelo nome.',
        ],
        cardText: 'Autorizações para o seu cônjuge e os seus filhos, coordenadas para que a família inteira aterre em conjunto.',
        explainer: {
          title: 'O que é o reagrupamento familiar?',
          text: [
            'O reagrupamento familiar, gezinshereniging em neerlandês, é a via que traz um companheiro e os filhos para viverem com alguém que já tem residência nos Países Baixos. É um único enquadramento legal que abrange todo o agregado, em vez de um procedimento separado por pessoa.',
            'O IND avalia o garante tanto como os requerentes: um rendimento estável igual ou superior ao limiar legal, habitação adequada e documentos de estado civil do país de origem que resistam à legalização. Os filhos têm requisitos de prova próprios em matéria de guarda e de consentimento parental.',
          ],
        },
        forWho: {
          title: 'Pensado para',
          items: [
            'Titulares de autorização de trabalho cujo cônjuge e filhos ainda estão no estrangeiro',
            'Famílias que se mudam para os Países Baixos ao mesmo tempo que o requerente principal',
            'Pais que trazem filhos menores de uma relação anterior',
            'Empregadores que organizam o reagrupamento familiar de um especialista relocalizado',
          ],
        },
        included: {
          title: 'Como trazemos uma família',
          blocks: [
            {
              title: 'Estratégia para o processo familiar',
              text: 'Um plano para cada membro da família: quem se candidata e quando, que autorizações dependem da sua e como os prazos encaixam uns nos outros.',
            },
            {
              title: 'Certidões feitas como deve ser',
              text: 'Certidões de casamento e de nascimento, documentos de guarda quando aplicável, tudo legalizado ou apostilado corretamente à primeira.',
            },
            {
              title: 'Pedidos ao IND para cada membro',
              text: 'Preparamos e submetemos os pedidos do seu cônjuge e dos seus filhos e gerimos todos os pedidos de informação subsequentes.',
            },
            {
              title: 'Escolas e acolhimento de crianças',
              text: 'Escolas internacionais, bilingues ou neerlandesas, escolhidas em função dos seus filhos e do seu trajeto diário. Marcamos visitas e apresentações antes de chegarem.',
            },
            {
              title: 'Uma aterragem a sério',
              text: 'Registos, números BSN para todos, cuidados de saúde e as pequenas coisas que fazem de uma casa uma decisão bem tomada.',
            },
          ],
        },
        process: {
          title: 'De separados a juntos',
          steps: [
            {
              title: 'Primeira conversa em família',
              text: 'Mapeamos a nacionalidade, os documentos e as necessidades de cada membro da família numa única conversa.',
            },
            {
              title: 'Preparar e submeter',
              text: 'As certidões são legalizadas enquanto construímos e submetemos os pedidos em paralelo, para poupar meses.',
            },
            {
              title: 'Viajar e instalar-se',
              text: 'Vistos de entrada, voos, registo e entrada na escola, sequenciados para que ninguém fique à espera de ninguém.',
            },
          ],
        },
        fees: {
          title: 'Honorários para um pedido de reagrupamento familiar',
          kind: 'fixed',
          amount: 'Investimento a partir de €1.195',
          includes: [
            'Requisitos de rendimento e de garante verificados face ao seu contrato real',
            'Um processo coordenado para o seu companheiro e para cada filho',
            'Requisitos de legalização de documentos e de tradução ajuramentada mapeados por país',
            'Pedidos submetidos em conjunto e acompanhados até à decisão',
          ],
        },
        note: 'Os pedidos relativos a filhos dependem de pormenores que os pais raramente antecipam, como o consentimento de um progenitor que fica no país de origem. Exponha toda a sua situação familiar na primeira conversa para que nada apareça tarde demais.',
        conditions: {
          title: 'Condições do processo familiar',
          intro: 'Um único garante sustenta todo o pedido familiar. Tudo o que se segue é avaliado em relação a essa pessoa e a documentos emitidos em países que já deixou.',
          items: [
            'O titular da autorização principal atua como garante e tem de possuir uma autorização de residência válida de natureza não temporária.',
            'Rendimento de, pelo menos, 2.523,96 euros brutos por mês, incluindo subsídio de férias, avaliado como duradouro (valor de 2026).',
            'Os filhos têm de ser menores, solteiros e ter pertencido ao agregado familiar antes da mudança para os Países Baixos.',
            'Quando um dos progenitores permanece no estrangeiro, é necessário o seu consentimento por escrito antes de a criança se poder mudar.',
            'As certidões da maioria dos países precisam de legalização ou apostila e de tradução ajuramentada para neerlandês, inglês, francês ou alemão.',
            'Os pedidos submetidos em conjunto com o requerente principal são decididos mais depressa do que os pedidos submetidos posteriormente.',
          ],
        },
        details: {
          title: 'Como decorrem realmente os processos familiares',
          items: [
            {
              q: 'Devemos candidatar-nos em conjunto ou seguir mais tarde?',
              a: 'Em conjunto sempre que for possível. Um pedido familiar simultâneo é decidido ao lado do processo principal, assenta num único calendário e evita um segundo teste de rendimentos. Seguir mais tarde é perfeitamente viável, custa apenas um procedimento adicional e vários meses separados.',
            },
            {
              q: 'Quanto tempo demora a legalização?',
              a: 'Entre duas semanas e seis meses, consoante o país, porque em muitos lugares a cadeia passa pelo ministério dos negócios estrangeiros local e depois pela embaixada neerlandesa. É a causa de atraso mais frequente nos processos familiares, e é por isso que começamos por aí, antes de tudo o resto.',
            },
            {
              q: 'Os nossos filhos podem começar a escola de imediato?',
              a: 'Sim. Nos Países Baixos, as crianças têm o direito e o dever de frequentar a escola, independentemente do estado da autorização, e as escolas internacionais e as turmas de acolhimento a recém-chegados costumam aceitá-las em poucas semanas. Fazemos a procura de escola em paralelo com a autorização, não depois dela.',
            },
            {
              q: 'E se um filho fizer dezoito anos durante o procedimento?',
              a: 'O IND avalia a idade no momento da submissão, pelo que um filho que era menor quando o pedido foi entregue não perde a elegibilidade por fazer anos enquanto o processo está pendente. É precisamente por isso que submetemos cedo em vez de submeter na perfeição.',
            },
          ],
        },
        faq: {
          title: 'O que as famílias querem saber',
          items: [
            {
              q: 'O meu cônjuge pode trabalhar nos Países Baixos?',
              a: 'Na maioria dos casos, sim. Os cônjuges de trabalhadores altamente qualificados e da maioria dos titulares de autorização recebem acesso livre ao mercado de trabalho à chegada.',
            },
            {
              q: 'Os meus filhos vão ter de aprender neerlandês?',
              a: 'Não necessariamente. As regiões de Rotterdam e de Haia têm boas escolas internacionais e bilingues. As crianças mais novas apanham muitas vezes o neerlandês depressa nas escolas locais, e aconselhamos criança a criança, não por brochura.',
            },
            {
              q: 'Podemos candidatar-nos todos ao mesmo tempo?',
              a: 'Sim, e normalmente é o que devem fazer. Os pedidos agrupados mantêm a família num único calendário e num único momento de decisão. Estruturamos assim sempre que é possível.',
            },
          ],
        },
        cta: {
          title: 'Traga toda a gente para casa',
          text: 'Diga-nos quem se muda e de onde. Desenhamos um único plano que faz aterrar toda a sua família em conjunto.',
          label: 'Planear a nossa mudança em família',
        },
        form: 'immigration',
        image: '/images/family-reunification.jpg?v=20260731',
        imageAlt: 'Família reunida numa casa neerlandesa luminosa',
        image2: '/images/family-unpacking.jpg?v=20260731',
        image2Alt: 'Família instalada na sua nova sala de estar neerlandesa',
      },
      {
        slug: 'startup-visa-netherlands',
        menuLabel: 'Visto para startups',
        title: 'Visto para Startups nos Países Baixos',
        metaTitle: 'Visto Startup nos Países Baixos | Empreendedores Inovadores',
        metaDescription: 'O visto para startups nos Países Baixos dá aos fundadores de fora da UE uma autorização de residência de um ano para construir uma empresa inovadora com um facilitador reconhecido. Requisitos, processo e honorários.',
        eyebrow: 'Visto para fundadores',
        intro: [
          'O visto para startups nos Países Baixos foi pensado para empreendedores internacionais que querem desenvolver aqui um negócio inovador. Concede uma fase inicial de um ano em que constrói a empresa ao lado de um facilitador de startups reconhecido, dentro de um ecossistema com acesso real a investidores, incubadoras e mercados internacionais.',
          'Acompanhamos todo o percurso, não apenas a autorização: a escolha do facilitador, o plano de startup que o IND quer ler e o lado prático da chegada, do registo da empresa a um sítio para viver.',
        ],
        cardText: 'Uma autorização de um ano para fundadores construírem a sua empresa inovadora no ecossistema neerlandês.',
        explainer: {
          title: 'O que é o visto para startups?',
          text: [
            'O visto para startups é uma autorização de residência de um ano para empreendedores que constroem um negócio inovador nos Países Baixos. Existe porque uma empresa verdadeiramente nova raramente tem, logo no primeiro dia, a faturação ou o historial que a autorização comum de trabalhador independente exige.',
            'A sua caraterística central é o facilitador: um mentor experiente aprovado pela agência empresarial neerlandesa que orienta a sua empresa ao longo do primeiro ano. É avaliado pela inovação do plano e por essa parceria, não pela faturação. O ano é uma pista de descolagem para a autorização de trabalhador independente, e preparar cedo esse passo seguinte é a diferença entre continuar e recomeçar.',
          ],
        },
        forWho: {
          title: 'Quem pode pedir o visto para startups',
          items: [
            'Empreendedores de fora da UE que introduzem um produto, serviço ou tecnologia inovadora no mercado neerlandês',
            'Fundadores dispostos a trabalhar com um facilitador reconhecido que presta mentoria durante a fase inicial',
            'Equipas que precisam de uma base de residência para desenvolver o negócio em solo neerlandês',
            'Fundadores que planeiam o passo para a autorização de empresário independente após o primeiro ano',
          ],
        },
        conditions: {
          title: 'Requisitos do visto para startups',
          intro: 'O IND avalia a ideia e o facilitador avalia-o a si. Os requerentes têm de demonstrar:',
          items: [
            'Um conceito de negócio inovador',
            'Cooperação com um facilitador de startups aprovado',
            'Um plano estruturado de desenvolvimento da startup',
            'Meios financeiros suficientes para o primeiro ano',
            'Que o fundador desempenha um papel ativo no negócio',
          ],
        },
        included: {
          title: 'Onde acrescentamos valor',
          blocks: [
            {
              title: 'Verificação honesta de viabilidade',
              text: 'Dizemos-lhe à partida se o seu caso cumpre os critérios de inovação e o que reforçar caso não cumpra, antes de comprometer dinheiro ou meses.',
            },
            {
              title: 'Escolha do facilitador',
              text: 'Um facilitador reconhecido tem de apoiar o seu pedido. Ajudamo-lo a abordar os que se adequam ao seu setor e à sua fase e coordenamos o acordo.',
            },
            {
              title: 'Preparação do plano de startup',
              text: 'Ajudamos a estruturar o plano de desenvolvimento exigido, que descreve o seu papel, a inovação e os marcos do ano.',
            },
            {
              title: 'Gestão do pedido',
              text: 'Preparamos o processo para o IND, submetemo-lo e gerimos todas as trocas com as autoridades até à decisão.',
            },
            {
              title: 'A chegada do fundador',
              text: 'Registo, BSN, habitação e as primeiras conversas com a KvK, para que a empresa e o fundador tenham ambos uma morada.',
            },
          ],
        },
        process: {
          title: 'O nosso método de trabalho',
          steps: [
            {
              title: 'Avaliação de elegibilidade',
              text: 'Avaliamos se a sua ideia de negócio se qualifica como startup inovadora à luz dos critérios do IND.',
            },
            {
              title: 'Coordenação com o facilitador',
              text: 'Ajudamos a encontrar facilitadores reconhecidos, a trabalhar com eles e a assinar o acordo.',
            },
            {
              title: 'Plano de startup',
              text: 'Ajudamos a estruturar o plano de desenvolvimento pelo qual o pedido é avaliado.',
            },
            {
              title: 'Pedido de autorização de residência',
              text: 'Preparamos e submetemos o pedido de visto para startups ao IND e depois acompanhamo-lo.',
            },
          ],
        },
        fees: {
          title: 'Honorários para um pedido de visto para startups',
          kind: 'fixed',
          amount: 'Investimento a partir de €2.495',
          includes: [
            'Consulta de estratégia de imigração e de elegibilidade',
            'Apoio na estruturação do plano pelo qual o pedido é avaliado',
            'Seleção e coordenação do facilitador',
            'Pedido submetido ao IND e acompanhado até à decisão',
          ],
        },
        note: 'A autorização de startup dura um ano e não é prorrogada enquanto tal. O passo seguinte previsto é a autorização de empresário independente, e começamos a preparar esse processo bastante antes de o seu ano terminar.',
        details: {
          title: 'Pormenores que vale a pena ler antes de se candidatar',
          items: [
            {
              q: 'O que conta como inovação?',
              a: 'A inovação pode significar nova tecnologia, um modelo de serviço inovador ou um novo método de produção. Na prática, o IND pergunta se o produto ou o serviço é genuinamente novo nos Países Baixos, e o parecer do seu facilitador tem peso real nessa apreciação.',
            },
            {
              q: 'O que acontece depois do ano de startup?',
              a: 'Durante esse ano desenvolve o negócio e prepara a fase seguinte. Os fundadores pedem então a autorização de residência de empresário independente para continuarem a operar a empresa nos Países Baixos, que é avaliada pelo valor económico do negócio.',
            },
            {
              q: 'O que faz na prática o facilitador?',
              a: 'Um facilitador reconhecido presta mentoria durante a fase inicial: orientação sobre o plano, o mercado e os marcos a atingir. A relação é uma condição formal da autorização, não um extra opcional, pelo que a escolha importa mais do que a maioria dos fundadores espera.',
            },
          ],
        },
        faq: {
          title: 'Perguntas de fundadores',
          items: [
            {
              q: 'Posso trazer a minha família com um visto para startups?',
              a: 'Sim. O seu companheiro e os seus filhos podem pedir residência consigo, e o seu companheiro pode trabalhar enquanto constrói a empresa.',
            },
            {
              q: 'É necessário um investimento mínimo?',
              a: 'Não é exigido qualquer montante fixo de investimento para o visto para startups. Tem de demonstrar meios suficientes para viver durante o ano, e ajudamo-lo a comprová-los.',
            },
            {
              q: 'Posso candidatar-me se a minha empresa já opera no estrangeiro?',
              a: 'Muitas vezes sim, desde que a atividade nos Países Baixos seja genuinamente nova e inovadora para este mercado. Avaliamos isso com honestidade na primeira conversa, em vez de o deixar descobrir numa recusa.',
            },
          ],
        },
        cta: {
          title: 'Lance a sua startup nos Países Baixos',
          text: 'Apresente-nos a sua empresa numa linha. Dizemos-lhe se o visto para startups é o seu caminho e quem o deve facilitar.',
          label: 'Fale connosco sobre a sua startup',
        },
        form: 'immigration',
        image: '/images/startup-visa.jpg?v=20260731',
        imageAlt: 'Fundador num escritório em loft com vista para a frente ribeirinha de Rotterdam',
        image2: '/images/startup-team.jpg',
        image2Alt: 'Equipa fundadora a trabalhar em conjunto num escritório partilhado',
      },
      {
        slug: 'daft-visa-netherlands',
        menuLabel: 'Visto DAFT',
        title: 'Visto DAFT nos Países Baixos',
        metaTitle: 'Visto DAFT Países Baixos | Dutch American Friendship Treaty',
        metaDescription: 'O visto DAFT permite aos cidadãos norte-americanos viver e trabalhar nos Países Baixos como empresários, com um investimento de 4.500 euros na empresa. Requisitos, método de trabalho e honorários.',
        eyebrow: 'Para cidadãos norte-americanos',
        intro: [
          'O visto DAFT, concedido ao abrigo do Dutch American Friendship Treaty, é a via de imigração mais acessível para cidadãos norte-americanos que pretendem gerir o seu próprio negócio nos Países Baixos. Graças ao tratado entre os Países Baixos e os Estados Unidos, os empresários americanos qualificam-se em condições mais flexíveis do que as da autorização de residência para empresários comum.',
          'É a via mais utilizada por freelancers, consultores e pequenos empresários. A par do processo de imigração, tratamos do lado prático da chegada: registo da empresa, habitação e residência para a família que o acompanha.',
        ],
        cardText: 'A via do tratado que permite aos americanos viver e trabalhar nos Países Baixos como empresários.',
        explainer: {
          title: 'O que é a autorização DAFT?',
          text: [
            'A autorização DAFT decorre do Dutch American Friendship Treaty, um acordo de 1956 que confere aos cidadãos dos Estados Unidos uma via singularmente acessível ao trabalho independente nos Países Baixos. Está aberta apenas a americanos e é, com larga margem, a autorização para empresários mais simples que o país oferece.',
            'O tratado substitui o sistema de pontos aplicado a outras nacionalidades por um critério simples: registar uma empresa neerlandesa verdadeira e manter um investimento mínimo definido no capital próprio dessa empresa. Não existe requisito de inovação, não é necessário um facilitador e o plano de negócios não é pontuado. É a manutenção do investimento que sustenta a autorização na renovação.',
          ],
        },
        forWho: {
          title: 'A quem se destina o visto DAFT',
          items: [
            'Freelancers e consultores americanos que trazem a sua atividade para a Europa',
            'Empresários norte-americanos que abrem uma empresa nos Países Baixos',
            'Profissionais em regime remoto que reestruturam a sua atividade como trabalho independente',
            'Cônjuges e famílias americanas que acompanham o requerente',
          ],
        },
        conditions: {
          title: 'Requisitos do visto DAFT',
          intro: 'O tratado substitui a avaliação económica por pontos do plano de negócios por um critério de investimento simples. Em regra, o requerente deve:',
          items: [
            'Ter nacionalidade norte-americana',
            'Registar uma empresa nos Países Baixos',
            'Investir pelo menos 4.500 euros na empresa',
            'Inscrever-se na Câmara de Comércio neerlandesa (KvK)',
            'Manter o investimento exigido na empresa',
          ],
        },
        included: {
          title: 'O percurso DAFT completo',
          blocks: [
            {
              title: 'Aconselhamento sobre a estrutura',
              text: 'Eenmanszaak ou BV, e o que cada uma implica para o seu requisito de investimento e para os impostos. Explicamos as vantagens e as desvantagens em linguagem clara antes de decidir.',
            },
            {
              title: 'Registo da empresa',
              text: 'Registo no KvK, a conta bancária empresarial neerlandesa e a aplicação de capital de 4.500 euros, documentada da forma que o IND exige.',
            },
            {
              title: 'Gestão do pedido junto do IND',
              text: 'Preparamos e submetemos o seu pedido de residência ao abrigo do tratado e gerimos toda a comunicação com o IND até à decisão.',
            },
            {
              title: 'Apresentação a um contabilista',
              text: 'O estatuto DAFT tem de ser mantido na renovação e a sua contabilidade é a prova disso. Colocamo-lo em contacto com contabilistas que conhecem bem o tratado.',
            },
            {
              title: 'Instalação em família',
              text: 'Residência para o seu cônjuge e filhos, registo, saúde e habitação, tratados em paralelo com a constituição da empresa.',
            },
          ],
        },
        process: {
          title: 'O nosso método de trabalho',
          steps: [
            {
              title: 'Consulta de imigração',
              text: 'Avaliamos a sua elegibilidade ao abrigo do tratado DAFT e desenhamos a via em torno do seu negócio, da sua família e dos seus prazos.',
            },
            {
              title: 'Constituição da empresa',
              text: 'Acompanhamo-lo no registo da empresa e nas obrigações administrativas que se lhe seguem.',
            },
            {
              title: 'Investimento e documentação',
              text: 'Garantimos que o investimento exigido é aplicado e documentado da forma que o IND exige.',
            },
            {
              title: 'Pedido de autorização de residência',
              text: 'Preparamos e submetemos o pedido DAFT ao IND e tratamos de toda a comunicação até à decisão.',
            },
          ],
        },
        fees: {
          title: 'Honorários para um pedido DAFT',
          kind: 'fixed',
          amount: 'Investimento a partir de €2.295',
          includes: [
            'Avaliação de elegibilidade ao abrigo do Dutch American Friendship Treaty',
            'Registo da empresa e estruturação do investimento para cumprir o critério do tratado',
            'Pedido de autorização de residência preparado e submetido',
            'Orientação sobre a manutenção do investimento nas renovações seguintes',
          ],
        },
        note: 'A autorização de residência é normalmente concedida por dois anos e pode ser prorrogada. Os 4.500 euros têm de permanecer investidos na empresa enquanto mantiver o estatuto DAFT, porque as renovações analisam o seu balanço.',
        details: {
          title: 'Pormenores que vale a pena ler antes de se candidatar',
          items: [
            {
              q: 'O que é exatamente a autorização de residência DAFT?',
              a: 'Permite aos cidadãos norte-americanos viver nos Países Baixos enquanto gerem aqui o seu próprio negócio. Ao contrário da autorização de residência para empresários comum, a via DAFT não exige uma avaliação económica por pontos do plano de negócios. O requisito principal é o investimento mínimo na empresa.',
            },
            {
              q: 'Eenmanszaak ou BV?',
              a: 'Ambas cumprem o tratado. Uma empresa em nome individual é mais leve e mais barata de gerir; uma BV limita a responsabilidade e adequa-se ao crescimento e à entrada de investidores. A escolha altera a forma como o investimento é comprovado e como é tributado, pelo que aconselhamos com base nos seus números e não numa regra geral.',
            },
            {
              q: 'O que significa manter o investimento na prática?',
              a: 'O capital tem de permanecer na empresa, visível no balanço, e não pode ser levantado depois de a autorização ser concedida. A sua contabilidade é a prova no momento da renovação, razão pela qual apresentamos os nossos clientes a contabilistas que conhecem bem o tratado.',
            },
          ],
        },
        faq: {
          title: 'Perguntas de clientes americanos',
          items: [
            {
              q: 'O meu cônjuge pode trabalhar nos Países Baixos ao abrigo do DAFT?',
              a: 'Sim. O seu cônjuge recebe uma autorização de residência com acesso livre ao mercado de trabalho, podendo aceitar um emprego ou criar o seu próprio negócio.',
            },
            {
              q: 'Preciso de clientes ou de receitas antes de me candidatar?',
              a: 'Não existe limiar de receitas no início. É necessário o investimento, uma empresa registada e a intenção de a gerir efetivamente. Na altura da renovação, as suas contas devem mostrar uma empresa com atividade real.',
            },
            {
              q: 'O DAFT conduz à residência permanente?',
              a: 'Pode conduzir. Após cinco anos de residência legal ininterrupta, em regra pode requerer a residência permanente ou a naturalização, sujeitas aos requisitos de integração. Muitos dos nossos clientes DAFT seguem esse caminho.',
            },
          ],
        },
        cta: {
          title: 'Mude-se para os Países Baixos ao abrigo do tratado DAFT',
          text: 'Diga-nos a que se dedica profissionalmente. Desenhamos a sua via DAFT, do investimento à autorização, numa só conversa.',
          label: 'Iniciar o meu plano DAFT',
        },
        form: 'immigration',
        image: '/images/daft-visa.jpg?v=20260731',
        imageAlt: 'Fundador americano a trabalhar num estúdio de design nos Países Baixos',
        image2: '/images/daft-couple.jpg',
        image2Alt: 'Casal americano a instalar-se numa cidade neerlandesa',
      },
      {
        slug: 'business-schengen-visa-netherlands',
        menuLabel: 'Visto de negócios',
        title: 'Visto Schengen de negócios para os Países Baixos',
        metaTitle: 'Visto Schengen de Negócios Países Baixos | Estada Curta',
        metaDescription: 'Vistos Schengen de negócios de curta duração para os Países Baixos, preparados com rigor. Cartas-convite, processos para a embaixada e apoio a delegações que visitam parceiros neerlandeses.',
        eyebrow: 'Estada curta',
        intro: [
          'Nem todas as viagens aos Países Baixos são uma mudança de vida. Assinam-se contratos, inspecionam-se portos, constroem-se parcerias, e para muitas nacionalidades isso exige um visto Schengen de curta duração: até 90 dias em cada período de 180 dias, para fins profissionais.',
          'Estes processos decidem-se no consulado, e esse é um mundo que conhecemos por dentro. A nossa reputação construiu-se no meio diplomático, o que significa que sabemos como é um processo de negócios convincente visto do outro lado do balcão.',
        ],
        cardText: 'Vistos de curta duração para reuniões, negociações e visitas a instalações nos Países Baixos.',
        explainer: {
          title: 'O que é um visto de negócios?',
          text: [
            'Um visto de negócios é um visto Schengen de curta duração, do tipo C, para reuniões, negociações, conferências e visitas a instalações. Permite até 90 dias em cada período de 180 dias no espaço Schengen e não autoriza o exercício de uma atividade laboral nos Países Baixos.',
            'Os nacionais de muitos países necessitam dele antes de viajar; outros estão isentos de visto para estadas curtas. O pedido é decidido pelo consulado com base na solidez do convite, no seu historial de viagens, no seguro e na prova de que regressará, razão pela qual o processo documental pesa mais do que o formulário.',
          ],
        },
        forWho: {
          title: 'Quem viaja habitualmente',
          items: [
            'Quadros e especialistas que visitam parceiros ou clientes neerlandeses',
            'Delegações que participam em negociações, feiras ou inspeções a portos e instalações',
            'Empresas neerlandesas que convidam visitantes internacionais e precisam da documentação bem feita',
            'Visitantes de negócios frequentes que pretendem vistos de entradas múltiplas bem estruturados',
          ],
        },
        included: {
          title: 'O que contém um processo sólido',
          blocks: [
            {
              title: 'Objetivo e convite',
              text: 'Uma carta-convite precisa da empresa anfitriã neerlandesa, indicando quem, porquê e por quanto tempo. Redigimo-la ou revemo-la para que responda às perguntas do consulado antes de serem feitas.',
            },
            {
              title: 'Documentação de suporte',
              text: 'Vínculos ao seu país de origem, meios financeiros, seguro e itinerário, reunidos num processo que se lê como credível à primeira vista.',
            },
            {
              title: 'Estratégia de marcação',
              text: 'O consulado certo, o tipo de marcação certo e preparação para as perguntas que lhe podem ser feitas ao balcão.',
            },
            {
              title: 'Apoio ao anfitrião',
              text: 'Para empresas neerlandesas que recebem visitantes, tratamos do lado do convite: cartas, garantias quando adequado e calendarização em função das datas das suas reuniões.',
            },
          ],
        },
        process: {
          title: 'Do convite à chegada',
          steps: [
            {
              title: 'Explique-nos o caso',
              text: 'Quem viaja, de onde e para quê. Confirmamos de imediato o tipo de visto correto.',
            },
            {
              title: 'Construção do processo',
              text: 'Convite, documentação e formulários ficam prontos em dias, não em semanas.',
            },
            {
              title: 'Consulado e viagem',
              text: 'Marcação feita, processo submetido e a sua visita decorre na data prevista.',
            },
          ],
        },
        fees: {
          title: 'Honorários para um pedido de visto de negócios',
          kind: 'fixed',
          amount: 'Investimento a partir de €795',
          includes: [
            'Avaliação do tipo de visto adequado ao objetivo e à duração da sua viagem',
            'Convite e documentos de suporte preparados segundo o padrão consular',
            'Marcação efetuada e processo reunido para submissão',
            'Orientação sobre seguro de viagem e prova de meios de subsistência',
          ],
        },
        note: 'Um visto Schengen de negócios permite reuniões e negociações, não trabalho. Se as suas visitas se estão a transformar em trabalho regular nos Países Baixos, fale connosco sobre uma autorização de residência para trabalho antes que isso se torne um problema na fronteira.',
        conditions: {
          title: 'O que este visto permite e o que não permite',
          intro: 'Aqui, os limites importam mais do que os requisitos, porque usar este visto para a atividade errada põe em risco tanto o viajante como o anfitrião neerlandês.',
          items: [
            'Um máximo de noventa dias de estada em cada período de cento e oitenta dias no espaço Schengen.',
            'São permitidas reuniões, negociações, formações, feiras e visitas a instalações. Trabalho remunerado nos Países Baixos não é permitido.',
            'É exigido um convite formal da empresa anfitriã neerlandesa, podendo ser pedido ao anfitrião que assuma a responsabilidade pelos custos.',
            'É obrigatório um seguro médico de viagem com cobertura mínima de 30.000 euros, válido em todo o espaço Schengen.',
            'Deve ser apresentada prova de alojamento, de viagem de regresso e de meios suficientes para a estada.',
            'Submeta o pedido na representação neerlandesa apenas se os Países Baixos forem o seu destino principal; caso contrário, o pedido cabe ao país onde permanecer mais tempo.',
          ],
        },
        details: {
          title: 'Como obter uma decisão mais favorável',
          items: [
            {
              q: 'Porque são recusados os vistos de negócios?',
              a: 'Quase sempre por uma de três razões: o objetivo da viagem não é credível à luz dos documentos, o requerente não demonstra vínculos suficientes ao país de origem, ou viagens Schengen anteriores foram usadas indevidamente. As três são problemas do processo e as três podem ser resolvidas antes da submissão.',
            },
            {
              q: 'Como se obtém um visto de entradas múltiplas?',
              a: 'Os vistos de entradas múltiplas de um a cinco anos são atribuídos a requerentes com um historial de viagens Schengen sem incidentes e uma relação comercial contínua demonstrável. Estruturamos o processo para que o padrão recorrente seja visível na documentação, em vez de ser pedido como um favor.',
            },
            {
              q: 'Com que antecedência devemos submeter o pedido?',
              a: 'Os pedidos podem ser submetidos até seis meses antes da viagem e, no máximo, quinze dias antes. A verdadeira limitação é a disponibilidade de marcações no consulado: em regiões muito procuradas e em época alta, as vagas podem estar a seis semanas de distância. Indique-nos a data com antecedência.',
            },
            {
              q: 'O nosso especialista precisa de trabalhar nas instalações. É este o visto certo?',
              a: 'Não. Instalar equipamento, executar um projeto ou prestar serviços a um cliente neerlandês é trabalho e exige uma autorização de residência para trabalho ou uma notificação ao abrigo das regras dos trabalhadores destacados. Usar um visto de negócios para esse fim expõe a sua empresa e o seu colaborador. Dir-lhe-emos qual é o instrumento que se aplica na realidade.',
            },
          ],
        },
        faq: {
          title: 'Antes de comprar os bilhetes de avião',
          items: [
            {
              q: 'Com que antecedência nos devemos candidatar?',
              a: 'Os prazos dos consulados variam muito consoante o país e a época. Em regra, comece assim que a viagem estiver confirmada. Confirmamos a disponibilidade atual de marcações no seu consulado quando nos contactar.',
            },
            {
              q: 'Posso visitar outros países Schengen com este visto?',
              a: 'Sim. Um visto Schengen permite viajar por todo o espaço Schengen, mas deve submeter o pedido através dos Países Baixos quando este for o seu destino principal.',
            },
            {
              q: 'E se um pedido anterior tiver sido recusado?',
              a: 'Uma recusa não é o fim. Analisamos os fundamentos indicados, corrigimos os pontos fracos do processo e estruturamos o novo pedido em conformidade.',
            },
          ],
        },
        cta: {
          title: 'Tem uma reunião nos Países Baixos para organizar?',
          text: 'Envie-nos as datas da viagem e o respetivo objetivo. Dir-lhe-emos exatamente o que o processo exige e com que rapidez pode avançar.',
          label: 'Tratar do meu visto de negócios',
        },
        form: 'immigration',
        image: '/images/business-visa.jpg?v=20260731',
        imageAlt: 'Executivo a chegar de carro à sede de uma empresa neerlandesa',
        image2: '/images/business-signing.jpg',
        image2Alt: 'Assinatura de documentos numa reunião de negócios',
      },
      {
        slug: 'residence-permit-netherlands',
        menuLabel: 'Autorizações de residência',
        title: 'Autorização de residência nos Países Baixos para expatriados',
        metaTitle: 'Autorização de Residência Países Baixos | Renovações e Apoio',
        metaDescription: 'Autorizações de residência nos Países Baixos explicadas e tratadas: primeiros pedidos, renovações, alterações de finalidade e o caminho para a residência permanente, com acompanhamento pessoal.',
        eyebrow: 'Residência',
        intro: [
          'Toda a vida de um expatriado nos Países Baixos assenta numa autorização de residência, e a própria autorização tem um percurso: é concedida, renovada, alterada quando a sua situação muda e, por fim, convertida em residência permanente. Basta perder um prazo de renovação ou mudar de emprego sem verificar as consequências para que anos de construção cuidadosa fiquem em risco.',
          'Somos o departamento de imigração em que os nossos clientes nunca têm de pensar. Controlamos as datas, preparamos os processos e a Johanna acompanha pessoalmente os clientes às marcações no IND, para que uma convocatória nunca pareça uma ameaça.',
        ],
        cardText: 'Primeiras autorizações, renovações, alterações e o caminho para a residência permanente, tudo no mesmo lugar.',
        explainer: {
          title: 'O que é uma autorização de residência neerlandesa?',
          text: [
            'Uma autorização de residência, verblijfsvergunning em neerlandês, é o documento que torna legal a sua permanência nos Países Baixos para além de 90 dias. É emitida pelo IND, indica sempre uma finalidade de residência, como trabalho, família ou estudo, e os direitos associados decorrem dessa finalidade e não do cartão em si.',
            'As autorizações são temporárias ou permanentes. O que mais importa a longo prazo é a finalidade de que dispõe e durante quanto tempo, porque é a residência legal ininterrupta que acaba por abrir a porta à residência permanente e à naturalização. Alterar a finalidade é possível, mas o momento em que o faz decide se os anos acumulados sobrevivem à mudança.',
          ],
        },
        forWho: {
          title: 'Quando nos deve contactar',
          items: [
            'A sua autorização está a aproximar-se da data de validade',
            'A sua situação mudou: novo empregador, nova relação, um divórcio, uma nova empresa',
            'Está a chegar aos cinco anos de residência e pretende o estatuto permanente',
            'Tem uma autorização, mas não sabe ao certo o que ela lhe permite fazer',
          ],
        },
        included: {
          title: 'Os nossos serviços de residência',
          blocks: [
            {
              title: 'Diagnóstico da autorização',
              text: 'Uma revisão da sua autorização atual, das respetivas condições e da data de validade, com um calendário claro do que tem de acontecer e quando.',
            },
            {
              title: 'Renovações sem sobressaltos',
              text: 'Preparamos os pedidos de renovação com antecedência e de forma completa, para que a continuidade dos seus direitos de residência nunca esteja em causa.',
            },
            {
              title: 'Alteração da finalidade',
              text: 'De recém-licenciado a trabalhador por conta de outrem, de parceiro dependente a residente autónomo, de startup a trabalhador independente. Gerimos a transição para que a nova base fique assegurada antes de a anterior terminar.',
            },
            {
              title: 'Residência permanente e o que vem depois',
              text: 'Após cinco anos de residência legal, pode reunir condições para uma autorização permanente ou para o estatuto de residente de longa duração da UE, normalmente com um requisito de integração cívica. Avaliamos se está preparado e construímos o pedido.',
            },
          ],
        },
        process: {
          title: 'Como trabalhamos',
          steps: [
            {
              title: 'Análise',
              text: 'Auditamos o seu estatuto atual e assinalamos todas as datas e condições que importam.',
            },
            {
              title: 'Preparação',
              text: 'O pedido certo, reunido bem antes do prazo, com margem de sobra.',
            },
            {
              title: 'Garantia',
              text: 'Submissão, acompanhamento e a sua nova autorização em mãos, com o marco seguinte já no calendário.',
            },
          ],
        },
        fees: {
          title: 'Honorários para um pedido de autorização de residência',
          kind: 'fixed',
          amount: 'Investimento a partir de €895',
          includes: [
            'Avaliação da autorização que se adequa à sua situação e da que se mantém a prazo',
            'Pedido preparado e submetido ao IND',
            'Requisitos de documentos, legalização e tradução identificados com antecedência',
            'Acompanhamento até à decisão, incluindo renovações quando aplicável',
          ],
        },
        note: 'As taxas e os prazos de decisão variam consoante o tipo de autorização e mudam ao longo do tempo, pelo que confirmamos os valores atuais do IND durante a sua consulta inicial, em vez de os fixar aqui.',
        conditions: {
          title: 'Prazos e limiares',
          intro: 'Quase todos os problemas de autorização que resolvemos começaram com uma data que passou despercebida. Estas são as que importam.',
          items: [
            'Submeta a renovação pelo menos três meses antes do termo de validade. O seu direito de viver e trabalhar mantém-se enquanto uma renovação atempada estiver pendente.',
            'Uma mudança de empregador, de finalidade ou de relação exige um novo pedido e, na maioria dos casos, não pode iniciar a nova atividade antes da aprovação.',
            'A residência permanente exige cinco anos de residência legal ininterrupta com base não temporária.',
            'As autorizações de estudo e as autorizações de ano de orientação não contam para esses cinco anos.',
            'A integração cívica ao nível A2, ou uma isenção formal, é exigida para a residência permanente e para a naturalização.',
            'Ausências superiores a seis meses consecutivos, ou superiores a quatro meses por ano ao longo do período, quebram a continuidade.',
          ],
        },
        details: {
          title: 'As perguntas que mais nos fazem',
          items: [
            {
              q: 'Residência permanente ou nacionalidade neerlandesa?',
              a: 'A residência permanente garante o seu direito de viver e trabalhar no país por tempo indeterminado e resiste a uma mudança de emprego. A nacionalidade acrescenta um passaporte neerlandês, a cidadania da UE e o direito de voto, exige os mesmos cinco anos mais a integração e, em regra, obriga a abdicar da nacionalidade atual. Muitos clientes optam primeiro pela residência permanente e decidem sobre a naturalização mais tarde.',
            },
            {
              q: 'A minha autorização caduca em breve e não tenho novo emprego.',
              a: 'Os trabalhadores altamente qualificados dispõem de um período de procura de três meses após o fim do contrato, durante o qual a residência se mantém enquanto encontra um novo patrocinador reconhecido. Aja dentro desse prazo. Depois de ele terminar, a situação torna-se muito mais difícil de corrigir.',
            },
            {
              q: 'Vou divorciar-me. Perco a minha residência?',
              a: 'Não necessariamente. Consoante o tempo durante o qual foi titular de uma autorização dependente e as suas circunstâncias pessoais, é muitas vezes possível alterar a finalidade para residência autónoma. É uma questão sensível ao tempo: quanto mais cedo falar connosco, mais vias permanecem abertas.',
            },
            {
              q: 'Posso também ter o estatuto de residente de longa duração da UE?',
              a: 'Sim, e é frequentemente a melhor combinação. A autorização de residente de longa duração da UE acrescenta direitos de mobilidade para outros Estados-Membros que a residência permanente neerlandesa não confere, e ambas podem ser requeridas em simultâneo.',
            },
          ],
        },
        faq: {
          title: 'Perguntas sobre residência',
          items: [
            {
              q: 'Quando devo iniciar a minha renovação?',
              a: 'O IND permite apresentar o pedido nos meses anteriores ao termo de validade, e mais cedo é quase sempre melhor. Começamos habitualmente a preparar bem antes de o prazo abrir, para que o dia da submissão seja uma formalidade.',
            },
            {
              q: 'Preciso de falar neerlandês para obter a residência permanente?',
              a: 'Em regra, sim. A residência permanente exige normalmente a aprovação nos exames de integração cívica, com isenções em casos específicos. Avaliamos quais os requisitos que se aplicam ao seu caso e como se deve preparar.',
            },
            {
              q: 'O que acontece à minha autorização se perder o emprego?',
              a: 'Depende do tipo de autorização. Os trabalhadores altamente qualificados, por exemplo, dispõem de um período de procura para encontrar um novo patrocinador. O essencial é agir de imediato, por isso contacte-nos na semana em que acontecer, não no mês seguinte.',
            },
          ],
        },
        cta: {
          title: 'Mantenha a sua residência inabalável',
          text: 'Envie-nos uma fotografia do seu cartão de residência e a sua situação em três frases. Dir-lhe-emos o que precisa de atenção e quando.',
          label: 'Analisar o meu estatuto de residência',
        },
        form: 'immigration',
        image: '/images/immigration-documents.jpg?v=20260731',
        imageAlt: 'Pasta de couro e caneta de tinta permanente sobre uma secretária',
        image2: '/images/immigration-desk.jpg?v=20260731',
        image2Alt: 'Consultora e cliente numa mesa de consulta privada',
      },
    ],
    crossLinks: [
      {
        path: '/starting-a-business/employer-immigration-services-netherlands',
        label: 'Imigração para empregadores',
        text: 'Para empresas que contratam pessoal de fora da UE: pedidos de autorização, reconhecimento como patrocinador junto do IND, destacamento de trabalhadores e revisão de processos.',
      },
    ],
  };
