/* GENERATED by scripts/i18n-strings.mjs. Do not hand-edit.
   pt/industrial.ts is a 1:1 structural mirror of en/industrial.ts; only leaf strings
   differ. To change structure, change English and re-run the build. */
import type { SectionContent } from '../types';

export const industrial: SectionContent = {
    title: 'Serviços para Expatriados no Setor Industrial',
    metaTitle: 'Serviços Expat Industriais Países Baixos | E & I Expat Services',
    metaDescription: 'Relocalização especializada para o cluster industrial do porto de Rotterdam: Europoort, Maasvlakte, profissionais offshore e de logística, tanto para empregadores como para trabalhadores.',
    eyebrow: 'Região industrial',
    intro: [
      'O porto de Rotterdam é o coração industrial da Europa, e o corredor que sai da cidade, passa por Europoort e chega à Maasvlakte emprega milhares de profissionais internacionais: engenheiros, equipas offshore, operadores de terminais, planeadores de logística. No entanto, quase todos os serviços de relocalização nos Países Baixos foram concebidos para quadros administrativos que aterram em Amsterdam. Ninguém se especializa nas pessoas que mantêm este porto a funcionar. Nós especializamo-nos, e somos os únicos.',
      'Conhecemos os terminais e as refinarias, os regimes de turnos e os contratos de prestação de serviços, as localidades onde as famílias do porto vivem de facto e os trajetos que tornam suportável começar às 6 da manhã. Quer seja um empregador que traz uma equipa, quer seja um profissional que chega sozinho, esta secção foi feita para o cluster industrial e para mais ninguém.',
    ],
    image: '/images/industrial-hub.jpg?v=20260728',
    imageAlt: 'Instalações industriais e terminais na zona portuária de Europoort',
    services: [
      {
        slug: 'europoort-relocation-services-netherlands',
        menuLabel: 'Expatriados em Europoort',
        title: 'Serviços de Relocalização em Europoort, Países Baixos',
        metaTitle: 'Relocalização Europoort Países Baixos | E & I Expat Services',
        metaDescription: 'Apoio à relocalização feito à medida de Europoort: habitação a uma distância realista, registos, seguros e instalação para profissionais da zona industrial do porto.',
        eyebrow: 'Europoort',
        intro: [
          'Europoort é um sítio onde se trabalha, não um sítio onde se vive, e esse simples facto quebra qualquer manual de relocalização convencional. As refinarias, os terminais de tanques e as fábricas químicas atraem aqui especialistas de todo o mundo, que depois descobrem que a casa mais sensata pode ficar em Spijkenisse, Brielle, Rozenburg ou já dentro de Rotterdam, cada uma com um trajeto muito diferente e uma vida muito diferente associada.',
          'Planeamos a sua relocalização em torno dessa realidade. A habitação é escolhida em função do seu portão de acesso e do início do turno, não de um raio de código postal. Registos, seguros e escolaridade seguem numa sequência coordenada e, quando uma marcação cai a meio dos seus turnos, acompanhamo-lo e resolvemos tudo numa única visita.',
        ],
        cardText: 'Relocalização planeada em torno do seu portão, do seu turno e de um trajeto que funciona.',
        forWho: {
          title: 'Para quem é',
          items: [
            'Engenheiros e técnicos que começam em fábricas e terminais de Europoort',
            'Prestadores de serviços em projetos e paragens de manutenção em refinarias',
            'Empregadores da zona portuária que relocalizam especialistas internacionais',
            'Famílias que acompanham o cônjuge para trabalho na indústria portuária',
          ],
        },
        included: {
          title: 'O que está incluído',
          blocks: [
            {
              title: 'Procura de casa a partir do trajeto',
              text: 'Selecionamos casas nas localidades que realmente funcionam para Europoort, testadas na A15 às suas horas de entrada reais, e tratamos das visitas e dos contratos.',
            },
            {
              title: 'Registos ajustados à sua escala',
              text: 'BSN e registo na câmara municipal planeados dentro do seu horário de turnos, preparados para que uma única marcação resolva tudo.',
            },
            {
              title: 'Seguros e questões salariais essenciais',
              text: 'Seguro de saúde neerlandês, seguro de responsabilidade civil e a papelada salarial prática tratados antes da sua primeira fatura ou do primeiro recibo de vencimento.',
            },
            {
              title: 'Apoio à chegada da família',
              text: 'Quando o cônjuge e os filhos chegam depois, alargamos o plano com escolas, acolhimento de crianças e orientação no bairro.',
            },
          ],
        },
        process: {
          title: 'Como funciona',
          steps: [
            {
              title: 'Levantamento do local de trabalho',
              text: 'Partimos do seu local, da sua escala e da duração do contrato, porque tudo o resto depende disso.',
            },
            {
              title: 'Casa e papelada em paralelo',
              text: 'A procura de casa decorre enquanto o seu processo de registo é preparado, para que nenhum espere pelo outro.',
            },
            {
              title: 'A trabalhar em poucas semanas',
              text: 'Começa a trabalhar registado, segurado e alojado, com apoio que continua depois do primeiro dia.',
            },
          ],
        },
        fees: {
          title: 'Quanto custa a relocalização para Europoort',
          kind: 'tailored',
          amount: 'Proposta à medida',
          amountNote: 'As colocações no porto diferem na duração, na rotação e no número de pessoas que chegam ao mesmo tempo. Recebe uma proposta construída em torno do contrato e da equipa.',
          includes: [
            'Habitação a uma distância viável do terminal ou da fábrica',
            'Processos de imigração para o trabalhador e, quando aplicável, para a família',
            'Todos os registos tratados em função dos regimes de turnos',
            'Um contacto que atende fora do horário de expediente, porque o porto também não o cumpre',
          ],
        },
        conditions: {
          title: 'O que trabalhar em Europoort significa para a sua mudança',
          intro: 'É o porto que define as condicionantes. Habitação, registo e vida familiar têm todos de se adaptar ao portão e à escala.',
          items: [
            'Os trajetos até Europoort demoram quarenta e cinco a setenta minutos a partir do centro de Rotterdam, e vinte a trinta a partir de Hoogvliet, Spijkenisse ou Brielle.',
            'Os regimes de turnos e de escalas tornam os transportes públicos impraticáveis para a maioria dos portões, pelo que o estacionamento e o carro costumam determinar a decisão sobre a habitação.',
            'O acesso ao local exige documentos de identificação e, para muitos prestadores de serviços, uma certificação de segurança válida como o VCA.',
            'Os prestadores de serviços e os trabalhadores destacados de outros Estados da UE estão sujeitos a regras de registo, seguro e processamento salarial diferentes das dos contratados diretos.',
            'O registo na sua morada continua a ser a porta de entrada para o BSN, o salário e o seguro, independentemente do que o seu empregador tenha combinado.',
            'Cobrimos especificamente a região portuária. Esta é a nossa própria zona, não um serviço nacional aplicado localmente.',
          ],
        },
        details: {
          title: 'Pontos práticos para profissionais do porto',
          items: [
            {
              q: 'Onde devo viver, na realidade?',
              a: 'Depende do seu portão e do seu turno, e a resposta honesta muitas vezes não é Rotterdam. Hoogvliet, Spijkenisse, Brielle e Rozenburg colocam-no a menos de meia hora da maioria dos terminais e custam bastante menos. Se o seu cônjuge trabalhar na cidade, o cálculo muda, e modelamos os dois cenários antes de se comprometer com uma morada.',
            },
            {
              q: 'Fui destacado para cá por um empregador estrangeiro. O que muda?',
              a: 'Quase tudo o que é administrativo. A sua segurança social pode manter-se no país de origem ao abrigo de um certificado A1, o seu empregador tem um dever de notificação nos Países Baixos, e a sua obrigação de seguro de saúde depende dessa estrutura e não da sua morada. Errar aqui produz prémios em duplicado ou ausência de cobertura, por isso analisamos este ponto em detalhe.',
            },
            {
              q: 'A minha família pode vir mais tarde?',
              a: 'Sim, e no trabalho por rotação e por turnos é muitas vezes a decisão certa. Planeamos a primeira fase em torno de si e a segunda em torno deles, para que as escolas e a habitação sejam escolhidas com a família presente, em vez de adivinhadas com antecedência.',
            },
            {
              q: 'Com que rapidez pode isto ser feito?',
              a: 'Com uma proposta de emprego em mãos e os documentos prontos, uma chegada funcional demora três a cinco semanas: base temporária, registo, BSN, seguro, banco e a procura de habitação permanente a decorrer em paralelo. Os documentos legalizados vindos do estrangeiro são a única coisa que atrasa o processo de forma sistemática.',
            },
          ],
        },
        faq: {
          title: 'Perguntas frequentes',
          items: [
            {
              q: 'As marcações podem ajustar-se a um horário de turnos rotativos?',
              a: 'Sim, é assim que trabalhamos aqui normalmente. Planeamos as marcações municipais e outras para os seus dias de folga ou entre turnos, preparamos tudo com antecedência e acompanhamo-lo para que uma única visita chegue.',
            },
            {
              q: 'O meu empregador pode ser faturado diretamente?',
              a: 'Certamente. Contratamos regularmente de forma direta com empregadores e agências da zona portuária, faturamos-lhes a relocalização e reportamos o progresso aos recursos humanos, enquanto o colaborador lida apenas connosco.',
            },
            {
              q: 'O meu contrato é de seis meses. Ainda vale a pena o apoio à relocalização?',
              a: 'Os contratos curtos são os que mais beneficiam, porque não há tempo a perder com erros. Tratamos de habitação temporária onde é possível registar-se, do procedimento correto de registo de curta duração e de um seguro que corresponde às suas datas reais.',
            },
          ],
        },
        cta: {
          title: 'A trabalhar em Europoort? Chegue bem.',
          text: 'Diga-nos o seu local e a data de início, e construímos o trajeto, a casa e a papelada à volta disso.',
          label: 'Planear a minha mudança para Europoort',
        },
        form: 'relocation',
        image: '/images/europoort.jpg?v=20260731',
        imageAlt: 'Infraestruturas de refinaria e terminais em Europoort, Rotterdam',
        image2: '/images/industrial-worker.jpg?v=20260731',
        image2Alt: 'Quadro superior do setor energético no porto de Rotterdam à hora dourada',
      },
      {
        slug: 'maasvlakte-expat-relocation-netherlands',
        menuLabel: 'Expatriados na Maasvlakte',
        title: 'Relocalização de Expatriados na Maasvlakte, Países Baixos',
        metaTitle: 'Relocalização Maasvlakte Países Baixos | E & I Expat Services',
        metaDescription: 'Relocalização para profissionais na Maasvlakte: habitação com um trajeto viável, registos rápidos e apoio pessoal no extremo do porto de Rotterdam.',
        eyebrow: 'Maasvlakte',
        intro: [
          'A Maasvlakte é a fronteira mais distante do porto de Rotterdam, quarenta quilómetros de terra conquistada ao mar onde se encontram os terminais de águas profundas, os gigantes dos contentores e as infraestruturas energéticas. O trabalho aqui é de nível mundial. O trajeto é o senão: a partir da morada errada, a viagem é brutal e as opções de transporte público são escassas. Escolha a sua localidade antes de escolher o lugar de estacionamento no local de trabalho, e a vida mantém-se boa.',
          'Relocalizamos profissionais da Maasvlakte com o trajeto como primeira decisão, e depois construímos tudo o resto por cima: registo, seguro, escolaridade, instalação. E como a vida no terminal não pára às cinco da tarde, leva consigo o nosso número pessoal de WhatsApp; as perguntas são respondidas quando surgem, não no dia útil seguinte.',
        ],
        cardText: 'Trabalhar num terminal de águas profundas merece uma morada que torne o trajeto sensato.',
        forWho: {
          title: 'Para quem é',
          items: [
            'Profissionais de terminais, energia e manutenção que começam na Maasvlakte',
            'Equipas internacionais que chegam para projetos de vários meses',
            'Empregadores na segunda Maasvlakte que relocalizam pessoal especializado',
            'Profissionais que ponderam viver perto de Voorne ou na cidade',
          ],
        },
        included: {
          title: 'O que está incluído',
          blocks: [
            {
              title: 'Modelação do trajeto',
              text: 'Antes de qualquer visita, mapeamos os tempos reais de porta a portão a partir das localidades candidatas, às suas horas de turno reais, incluindo as opções de transporte do próprio porto.',
            },
            {
              title: 'Procura de casa e contratos',
              text: 'Procura dirigida às comunidades que se ajustam, de Hellevoetsluis e Brielle até à própria Rotterdam, com visitas, análise do contrato e contacto com o senhorio tratados por nós.',
            },
            {
              title: 'Registo e seguro em ritmo acelerado',
              text: 'BSN, registo na câmara municipal e seguro de saúde neerlandês concluídos numa sequência apertada, alinhada com a sua data de início.',
            },
            {
              title: 'Instalação com apoio permanente',
              text: 'Banco, transportes, uma orientação local e ajuda contínua com aquilo que os primeiros meses trouxerem.',
            },
          ],
        },
        process: {
          title: 'Como funciona',
          steps: [
            {
              title: 'Levantamento do local e dos turnos',
              text: 'Terminal, escala e duração do contrato primeiro; são eles que definem todo o plano.',
            },
            {
              title: 'Escolha a sua base',
              text: 'Escolhe uma casa entre opções em que o trajeto está comprovado, não prometido.',
            },
            {
              title: 'Comece a trabalhar já instalado',
              text: 'Papelada feita, casa a funcionar e uma linha direta connosco para tudo o que vier a seguir.',
            },
          ],
        },
        fees: {
          title: 'Quanto custa a relocalização para a Maasvlakte',
          kind: 'tailored',
          amount: 'Proposta à medida',
          amountNote: 'As colocações na Maasvlakte vão de um único especialista num curto trabalho de comissionamento a uma equipa completa num contrato de vários anos. Recebe uma proposta para o âmbito real.',
          includes: [
            'Habitação que torna realista o trajeto até à Maasvlakte',
            'Imigração e autorizações tratadas em função do calendário do projeto',
            'Registos tratados sem retirar pessoas do local de trabalho',
            'Apoio para cônjuges e filhos que chegam mais tarde',
          ],
        },
        conditions: {
          title: 'Realidades da Maasvlakte',
          intro: 'A Maasvlakte 2 é o ponto mais distante do porto, e a distância é o único facto que molda todas as decisões à sua volta.',
          items: [
            'Os trajetos demoram sessenta a noventa minutos a partir do centro de Rotterdam, e trinta a quarenta e cinco a partir dos municípios ocidentais.',
            'Quase não existe habitação junto aos próprios terminais, pelo que todas as opções implicam um trajeto.',
            'O trabalho nos terminais de águas profundas assenta fortemente em turnos, incluindo noites e fins de semana, o que afeta tanto a escolha da habitação como o acolhimento das crianças.',
            'Alguns terminais dispõem de transporte do empregador, o que muda o cálculo por completo, por isso confirme-o antes de escolher uma morada.',
            'O acesso ao local exige identificação válida e, na maioria das funções de prestação de serviços, certificação de segurança em vigor.',
            'Registo, BSN, seguro e processamento salarial seguem as mesmas regras que em qualquer outro lado, e continuam a ser a porta de entrada para tudo.',
          ],
        },
        details: {
          title: 'Planear em torno do terminal',
          items: [
            {
              q: 'Que localidades funcionam melhor?',
              a: 'Brielle, Hellevoetsluis, Spijkenisse, Rozenburg e Oostvoorne colocam a maioria das pessoas a menos de quarenta e cinco minutos dos terminais, com mais espaço e rendas mais baixas do que a cidade. Brielle em particular agrada a famílias que preferem uma vila histórica a um subúrbio dormitório.',
            },
            {
              q: 'O meu empregador assegura transporte?',
              a: 'Vários terminais asseguram, e isso pode tornar uma morada distante perfeitamente viável ou uma morada próxima desnecessária. É a primeira pergunta que fazemos, porque a resposta reconfigura toda a procura de casa.',
            },
            {
              q: 'Como é que os turnos noturnos afetam a habitação?',
              a: 'Mais do que as pessoas esperam. Dormir durante uma manhã de semana é impossível num apartamento de paredes finas por cima de uma rua movimentada, e é a razão mais comum para o primeiro arrendamento correr mal. Verificamos o ruído à hora a que vai efetivamente dormir, e não à hora da visita.',
            },
            {
              q: 'E a vida familiar com uma escala rotativa?',
              a: 'Funciona, mas exige planeamento em vez de improviso. Escolas com prolongamento de horário, um cônjuge que possa conduzir e um bairro com algo para fazer a horas pouco habituais contam mais do que os metros quadrados. Construímos a procura em torno da escala e não em torno do anúncio.',
            },
          ],
        },
        faq: {
          title: 'Perguntas frequentes',
          items: [
            {
              q: 'Onde vivem normalmente os trabalhadores da Maasvlakte?',
              a: 'Muitos escolhem Voorne-Putten, localidades como Brielle, Hellevoetsluis e Spijkenisse, pela aproximação curta ao porto. Outros preferem Rotterdam pela vida urbana e conduzem no sentido contrário ao trânsito. Mostramos-lhe os dois compromissos com tempos de trajeto reais antes de decidir.',
            },
            {
              q: 'Faço turnos irregulares. Como tratamos das marcações?',
              a: 'Agendamos todas as marcações em função da sua escala, juntamos numa única deslocação tudo o que puder ser junto e preparamos os processos de forma tão completa que nenhuma marcação precisa de segunda tentativa.',
            },
            {
              q: 'O projeto dura nove meses. Qual é a solução de habitação certa?',
              a: 'Normalmente habitação temporária mobilada com registo municipal permitido, num contrato cujo período de aviso prévio coincide com o fim do projeto. Tratamos exatamente disso e, se o projeto for prolongado, renegociamos em vez de recomeçar.',
            },
          ],
        },
        cta: {
          title: 'Torne a Maasvlakte viável',
          text: 'Envie-nos o seu terminal e a data de início. Encontramos a casa que faz a distância desaparecer.',
          label: 'Tratar da minha mudança para a Maasvlakte',
        },
        form: 'relocation',
        image: '/images/maasvlakte.jpg?v=20260728',
        imageAlt: 'Terminais de contentores e gruas no porto de águas profundas da Maasvlakte',
        image2: '/images/industrial-worker.jpg?v=20260731',
        image2Alt: 'Quadro superior do setor energético no porto de Rotterdam à hora dourada',
      },
      {
        slug: 'offshore-expat-services-netherlands',
        menuLabel: 'Profissionais offshore',
        title: 'Serviços para Expatriados Offshore, Países Baixos',
        metaTitle: 'Serviços Offshore Países Baixos | E & I Expat Services',
        metaDescription: 'Relocalização e serviços de base em terra para profissionais offshore nos Países Baixos: habitação à prova de rotações, registos e um ponto de apoio à família enquanto está no mar.',
        eyebrow: 'Offshore',
        intro: [
          'A vida offshore funciona por rotações: semanas numa plataforma, num navio ou num parque eólico, depois semanas em casa. Esse ritmo torna uma base neerlandesa ao mesmo tempo essencial e invulgar. Precisa de habitação, registo e seguro como qualquer pessoa, mas está incontactável metade do tempo, a sua estrutura de rendimentos confunde os senhorios, e a sua família resolve sozinha todos os problemas práticos enquanto está no mar.',
          'Somos o ponto fixo em terra. Montamos corretamente a sua base neerlandesa entre rotações, marcando cada compromisso para as suas semanas em terra, e mantemo-nos disponíveis para a sua família enquanto está fora. Um cano rebentado, uma carta da câmara municipal, uma questão de escola: ligam-nos, fica resolvido, e só toma conhecimento quando já é um problema resolvido.',
        ],
        cardText: 'Uma base neerlandesa que funciona sem sobressaltos, esteja em terra ou no mar.',
        forWho: {
          title: 'Para quem é',
          items: [
            'Profissionais de energia offshore, eólicas e setor marítimo que fixam base nos Países Baixos',
            'Trabalhadores por rotação cuja papelada tem de caber nas semanas em terra',
            'Famílias que seguram as pontas durante as semanas offshore',
            'Agências de tripulação e empregadores que organizam bases neerlandesas para tripulações internacionais',
          ],
        },
        included: {
          title: 'O que está incluído',
          blocks: [
            {
              title: 'Planeamento à prova de rotações',
              text: 'Todos os registos, visitas e assinaturas agendados dentro das suas janelas em terra, preparados para que nada fique à espera de uma segunda rotação.',
            },
            {
              title: 'Habitação compatível com rendimentos offshore',
              text: 'Apresentamos o seu contrato e as suas diárias aos senhorios em termos que estes reconhecem, e visamos casas onde um perfil offshore é bem-vindo.',
            },
            {
              title: 'Registo e seguro',
              text: 'BSN, registo na câmara municipal e seguro de saúde tratados com atenção às particularidades transfronteiriças do emprego offshore.',
            },
            {
              title: 'Apoio em terra para a família',
              text: 'Enquanto está fora, a sua família tem a nossa linha direta para problemas práticos, desde questões com o senhorio a cartas oficiais.',
            },
          ],
        },
        process: {
          title: 'Como funciona',
          steps: [
            {
              title: 'Mapear a rotação',
              text: 'Partimos do seu calendário e construímos um plano de tarefas que cabe inteiramente na sua licença em terra.',
            },
            {
              title: 'Um período intensivo em terra',
              text: 'Habitação, registos e seguro concluídos num esforço concentrado enquanto está cá.',
            },
            {
              title: 'Regime estável',
              text: 'Parte para a rotação sabendo que a base está sólida e que alguém em terra está atento.',
            },
          ],
        },
        fees: {
          title: 'Quanto custa o apoio offshore',
          kind: 'tailored',
          amount: 'Proposta à medida',
          amountNote: 'Os calendários de rotação tornam o trabalho offshore diferente de qualquer outra relocalização. Recebe uma proposta construída em torno da sua rotação e da duração do contrato.',
          includes: [
            'Habitação adequada a uma rotação e não a um horário das nove às cinco',
            'Imigração tratada em função do tempo passado offshore',
            'Marcações agendadas dentro das suas semanas em terra',
            'Um ponto de contacto permanente enquanto está incontactável',
          ],
        },
        note: 'As situações fiscais e de segurança social offshore variam consoante o Estado de bandeira, o empregador e os dias trabalhados; assinalamos quando o seu caso exige um especialista em fiscalidade transfronteiriça e colocamo-lo em contacto com um da nossa rede.',
        conditions: {
          title: 'O que o trabalho por rotação altera',
          intro: 'Uma rotação offshore quebra a maior parte dos pressupostos em que assenta a administração neerlandesa. Estes são os que importam.',
          items: [
            'O registo numa morada neerlandesa continua a ser obrigatório se os Países Baixos forem a sua residência principal, qualquer que seja o seu padrão de rotação.',
            'Ausências prolongadas podem afetar o registo, o direito ao seguro de saúde e a continuidade necessária para a residência permanente.',
            'A segurança social pode ficar noutro país ao abrigo de um certificado A1, o que altera por completo a sua obrigação de seguro.',
            'Os senhorios avaliam os rendimentos por rotação de outra forma, e os padrões de pagamento irregulares precisam de ser explicados dentro do processo, e não depois dele.',
            'Os marítimos e os trabalhadores offshore podem estar sujeitos a regras fiscais e de segurança social específicas que não se aplicam ao pessoal em terra.',
            'Coordenamos o lado neerlandês. A fiscalidade e o processamento salarial transfronteiriços seguem para especialistas que lhe apresentamos.',
          ],
        },
        details: {
          title: 'Fazer uma rotação funcionar em terra',
          items: [
            {
              q: 'Pode tudo ser feito num único período em terra?',
              a: 'Normalmente sim, e é assim que planeamos. Marcações, visitas, registo, banco e seguro são comprimidos numa única semana intensiva em terra, em vez de espalhados por três rotações. Exige preparação do nosso lado e documentos prontos do seu.',
            },
            {
              q: 'O que acontece enquanto estou no mar?',
              a: 'Continuamos a ser a sua morada na prática: correspondência tratada, prazos vigiados, perguntas do senhorio respondidas, marcações alteradas. A sua família, se estiver cá, tem um número para ligar que não é internacional.',
            },
            {
              q: 'Como é que as ausências afetam a residência permanente?',
              a: 'A residência contínua é interrompida por ausências superiores a seis meses consecutivos, ou superiores a quatro meses por ano ao longo do período de qualificação. As rotações ficam normalmente bem dentro desses limites, mas vale a pena fazer as contas de forma deliberada se estiver a trabalhar para obter o estatuto permanente.',
            },
            {
              q: 'Que seguro se aplica ao meu caso?',
              a: 'Depende de onde o seu empregador está estabelecido, sob que bandeira navega e se existe um certificado A1. O offshore é a área onde mais frequentemente encontramos pessoas com seguro em duplicado ou sem seguro nenhum, por isso esclarecemos este ponto logo no levantamento inicial, em vez de assumirmos a resposta habitual.',
            },
          ],
        },
        faq: {
          title: 'Perguntas frequentes',
          items: [
            {
              q: 'É mesmo possível tratar de tudo durante uma única licença em terra?',
              a: 'Com preparação, normalmente sim. Recolhemos documentos e marcamos compromissos enquanto ainda está offshore, para que as suas semanas em terra sejam passadas a assinar e a instalar-se, e não à espera.',
            },
            {
              q: 'Os senhorios hesitam perante o meu contrato offshore. O que fazem quanto a isso?',
              a: 'Traduzimos a sua realidade laboral, diárias, contratos de rotação, estruturas de agências de tripulação, para um dossiê de arrendamento que se lê como o rendimento estável e elevado que efetivamente é, e respondemos pelo processo pessoalmente.',
            },
            {
              q: 'O meu empregador ou a agência de tripulação pode pagar isto diretamente?',
              a: 'Sim, a faturação direta ao empregador é habitual para nós, incluindo acordos-quadro para agências que baseiam tripulações nos Países Baixos com regularidade.',
            },
          ],
        },
        cta: {
          title: 'Tenha uma base em terra que se aguenta',
          text: 'Diga-nos as datas da sua próxima rotação e teremos o plano pronto antes de voltar a terra.',
          label: 'Montar a minha base',
        },
        form: 'relocation',
        image: '/images/industrial-worker.jpg?v=20260731',
        imageAlt: 'Quadro superior do setor energético no porto de Rotterdam à hora dourada',
        image2: '/images/industrial-hub.jpg',
        image2Alt: 'Cluster industrial portuário ao anoitecer',
      },
      {
        slug: 'relocation-for-logistics-professionals-netherlands',
        menuLabel: 'Profissionais de logística',
        title: 'Relocalização para Profissionais de Logística nos Países Baixos',
        metaTitle: 'Relocalização para Profissionais de Logística | E & I Expat Services',
        metaDescription: 'Relocalização para talento internacional de logística na região de Rotterdam: chegadas rápidas, planeamento adaptado aos turnos e habitação junto aos corredores de distribuição.',
        eyebrow: 'Logística',
        intro: [
          'A logística é a superpotência discreta dos Países Baixos e a região de Rotterdam é a sua sala de máquinas. Transitários, planeadores de terminal, gestores de cadeia de abastecimento e responsáveis de armazém chegam aqui de todo o mundo, quase sempre com pouca antecedência, porque nesta indústria uma vaga por preencher é carga parada. A sua relocalização tem de decorrer ao mesmo ritmo que o seu setor.',
          'É assim que a conduzimos. Prazos comprimidos, habitação junto aos corredores onde o trabalho realmente está, documentação sequenciada para cumprir a sua data de início e marcações que respeitam turnos que começam cedo e acabam tarde. A Johanna prepara cada passo e acompanha-o aos balcões que interessam, para que nada seja devolvido e nada tenha de se repetir.',
        ],
        cardText: 'Relocalização rápida e adaptada aos turnos para quem mantém a carga em movimento.',
        forWho: {
          title: 'Para quem é',
          items: [
            'Profissionais de cadeia de abastecimento e de transporte de mercadorias que entram em empresas da região de Rotterdam',
            'Colaboradores de armazém e de terminal que começam com pouca antecedência',
            'Empregadores de logística que relocalizam contratações internacionais, individualmente ou em grupo',
            'Profissionais que se mudam dentro da Europa e precisam de uma transição administrativa rápida',
          ],
        },
        included: {
          title: 'O que está incluído',
          blocks: [
            {
              title: 'Plano de chegada acelerado',
              text: 'Um calendário comprimido desde a carta de oferta até ao primeiro turno, com habitação, BSN e seguro sequenciados em função da sua data de início.',
            },
            {
              title: 'Habitação junto ao trabalho',
              text: 'Uma procura dirigida às zonas de distribuição, do corredor portuário ao eixo Ridderkerk e Barendrecht, com revisão do contrato incluída.',
            },
            {
              title: 'Registo sem visitas repetidas',
              text: 'Registo na câmara municipal e BSN preparados ao nível exigido para ficarem concluídos, planeados em torno da sua escala de turnos.',
            },
            {
              title: 'Relocalização de grupo para empregadores',
              text: 'Vai contratar vários profissionais internacionais? Conduzimos relocalizações em paralelo com um único ponto de contacto e relatórios consolidados para os recursos humanos.',
            },
          ],
        },
        process: {
          title: 'Como funciona',
          steps: [
            {
              title: 'Primeira reunião com a proposta na mão',
              text: 'Assim que o seu contrato é assinado, traçamos o caminho mais curto até um início com tudo já instalado.',
            },
            {
              title: 'Execução em paralelo',
              text: 'A habitação e a documentação avançam em simultâneo para que a data de início nunca derrape.',
            },
            {
              title: 'Primeiro turno, já instalado',
              text: 'Entra ao serviço com a morada, o número e o seguro já tratados.',
            },
          ],
        },
        fees: {
          title: 'Quanto custa a relocalização para profissionais de logística',
          kind: 'tailored',
          amount: 'Proposta à medida',
          amountNote: 'O âmbito depende de chegar sozinho ou com família e da rapidez com que a função começa. Recebe um orçamento fixo após a primeira conversa.',
          includes: [
            'Habitação junto aos terminais, armazéns ou corredor onde vai efetivamente trabalhar',
            'Via de imigração selecionada e submetida em função da sua data de início',
            'Registos, seguro e conta bancária tratados à chegada',
            'Apoio à família quando cônjuges e filhos acompanham',
          ],
        },
        conditions: {
          title: 'A rapidez e o que a limita',
          intro: 'A logística move-se depressa e as datas de início raramente esperam. Estas são as condicionantes que determinam a rapidez real de uma chegada.',
          items: [
            'Com os documentos prontos, uma chegada funcional demora três a cinco semanas: alojamento base, registo, BSN, seguro, conta bancária.',
            'As certidões de nascimento e de casamento legalizadas não podem ser obtidas depois de já estar aqui e são a causa mais frequente de atraso.',
            'A disponibilidade de marcações na câmara municipal varia com a época do ano e pode acrescentar uma a três semanas.',
            'Os horários por turnos e os centros de distribuição fora da cidade tornam quase sempre necessário um carro, o que afeta o orçamento para habitação.',
            'Os empregadores que contratam várias pessoas de uma vez podem agrupar registos e visitas a imóveis, o que comprime consideravelmente os prazos.',
            'No caso de contratações de fora da UE, o pedido de autorização tem de ser aprovado antes de o trabalho começar. Nenhuma instrução do empregador altera isso.',
          ],
        },
        details: {
          title: 'Chegar depressa sem cortar caminho',
          items: [
            {
              q: 'O que pode ser feito antes de eu chegar?',
              a: 'Mais do que a maioria das pessoas imagina. A verificação de documentos, a legalização, o processo de autorização, a marcação na câmara municipal, a seleção de imóveis e as visitas podem decorrer enquanto ainda está no estrangeiro, para que a primeira semana nos Países Baixos seja de execução e não de descoberta.',
            },
            {
              q: 'Vamos contratar um grupo. Isso ajuda?',
              a: 'Consideravelmente. Registos agrupados, um alojamento temporário partilhado e visitas coordenadas reduzem o custo e o tempo por pessoa, e ter uma só pessoa a acompanhar todo o grupo significa que os recursos humanos recebem uma visão única em vez de uma fila de problemas individuais.',
            },
            {
              q: 'Onde devem viver os profissionais de logística?',
              a: 'Perto do polo de distribuição e não perto do centro. As instalações do Waalhaven, do Botlek e do corredor A15 são mais bem servidas a partir de Hoogvliet, Spijkenisse, Barendrecht e Ridderkerk, e as rendas nessas zonas são sensivelmente mais baixas do que na própria Rotterdam.',
            },
            {
              q: 'Qual é o erro mais comum?',
              a: 'Começar a procura de habitação antes de a via de registo estar clara. Um imóvel que não permite registo bloqueia o BSN, que bloqueia o processamento salarial, o que significa que um recém-chegado trabalha seis semanas sem ser pago corretamente. Resolvemos sempre primeiro o registo.',
            },
          ],
        },
        faq: {
          title: 'Perguntas frequentes',
          items: [
            {
              q: 'A minha data de início é daqui a três semanas. É possível?',
              a: 'É apertado, mas é terreno conhecido. Com habitação temporária onde seja possível registar-se a servir de ponte e os documentos preparados antes de viajar, uma chegada em três semanas é realista; dizemos-lhe com honestidade, logo no primeiro dia, o que estará pronto e quando.',
            },
            {
              q: 'Trabalho à noite. Como se resolvem as marcações durante o dia?',
              a: 'Marcamo-las nos extremos do seu período de sono, agrupamo-las no menor número possível de deslocações e acompanhamo-lo a cada uma para que fique resolvida no momento.',
            },
            {
              q: 'Quem paga, o empregador ou eu?',
              a: 'Qualquer das opções funciona. Muitos empregadores de logística assumem a relocalização e faturamos diretamente à empresa; com a mesma frequência, são particulares a contratar-nos. O âmbito e o preço para a sua situação são confirmados na primeira reunião.',
            },
          ],
        },
        cta: {
          title: 'Comece a mover carga, não papelada',
          text: 'Envie-nos a data de início do seu contrato e construímos a chegada mais rápida e sem falhas até essa data.',
          label: 'Acelerar a minha mudança',
        },
        form: 'relocation',
        image: '/images/logistics-worker.jpg?v=20260731',
        imageAlt: 'Diretor de logística a observar o terminal portuário de Rotterdam',
        image2: '/images/europoort.jpg?v=20260731',
        image2Alt: 'O porto de Rotterdam à hora dourada',
      },
      {
        slug: 'rotterdam-industrial-expat-services',
        menuLabel: 'Trabalhadores internacionais em Rotterdam',
        title: 'Serviços para Expatriados no Setor Industrial de Rotterdam',
        metaTitle: 'Serviços para Expatriados Industriais Rotterdam | E & I Expat Services',
        metaDescription: 'Um único parceiro para trabalhadores internacionais em todo o polo industrial de Rotterdam: relocalização, registos, habitação e apoio à família, para empregadores e colaboradores.',
        eyebrow: 'Polo industrial',
        intro: [
          'Das docas da cidade aos terminais mais a ocidente, o polo industrial de Rotterdam é uma economia contínua de aço, energia, química e carga, servida por profissionais internacionais a todos os níveis, do operador de processo ao diretor de fábrica. Aqui, os empregadores disputam talento técnico escasso à escala mundial, e cada contratação que chega mal é uma contratação em risco de sair.',
          'Somos o parceiro de relocalização deste polo. Para os empregadores, um ponto de contacto único que retira toda a chegada da secretária dos recursos humanos, da coordenação do visto à entrega das chaves. Para os trabalhadores, um acompanhamento pessoal que compreende a vida industrial, respeita o trabalho por turnos e continua disponível depois de as caixas estarem desfeitas. É um nicho que mais ninguém serve, e servimo-lo a fundo.',
        ],
        cardText: 'O parceiro de relocalização de todo o polo industrial portuário, tanto para o empregador como para o colaborador.',
        forWho: {
          title: 'Para quem é',
          items: [
            'Empregadores industriais do polo portuário de Rotterdam que contratam no estrangeiro',
            'Profissionais técnicos que chegam para funções em fábrica, terminal ou manutenção',
            'Equipas de recursos humanos que querem a relocalização fora das suas mãos, mas sob o seu olhar',
            'Trabalhadores internacionais já cá residentes cuja documentação nunca foi tratada como devia',
          ],
        },
        included: {
          title: 'O que está incluído',
          blocks: [
            {
              title: 'Chegadas de colaboradores de ponta a ponta',
              text: 'Habitação, BSN, registo na câmara municipal, seguro e instalação entregues como um pacote coordenado por cada contratação.',
            },
            {
              title: 'Parceria com o empregador',
              text: 'Contacto fixo, âmbito claro por relocalização, faturação direta e relatórios de progresso que permitem aos recursos humanos responder a qualquer pergunta num só olhar.',
            },
            {
              title: 'Coordenação da imigração',
              text: 'Autorizações de trabalho e procedimentos de residência alinhados com o calendário da relocalização através dos nossos serviços de imigração, um só teto, um só plano.',
            },
            {
              title: 'Reparação de chegadas mal feitas',
              text: 'Para trabalhadores já no país com lacunas no registo, no seguro ou nos contratos, auditamos e corrigimos as bases.',
            },
            {
              title: 'Extensão à família',
              text: 'Cônjuges e filhos integrados no plano, com escolas, cuidados de saúde e orientação quando as famílias acompanham.',
            },
          ],
        },
        process: {
          title: 'Como funciona',
          steps: [
            {
              title: 'Definir a necessidade',
              text: 'Uma contratação ou um fluxo anual, definimos o âmbito, o calendário e o ritmo dos relatórios.',
            },
            {
              title: 'Fazer chegar cada trabalhador',
              text: 'Cada relocalização decorre no seu próprio percurso acompanhado, ajustado à função, à escala de turnos e à situação familiar.',
            },
            {
              title: 'Avaliar e repetir',
              text: 'Fazemos um balanço com o empregador depois de cada chegada, para que a seguinte corra ainda melhor.',
            },
          ],
        },
        fees: {
          title: 'Quanto custa o apoio à relocalização industrial',
          kind: 'tailored',
          amount: 'Proposta à medida',
          amountNote: 'Serviços concebidos à medida das suas necessidades pessoais. Após uma primeira consulta, recebe uma proposta personalizada com base nos seus objetivos, na sua situação familiar e no nível de acompanhamento que preferir.',
          includes: [
            'Um único plano que cobre a autorização, a casa e os registos',
            'Coordenação com o empregador para que a documentação não atrase uma data de início',
            'Apoio nas línguas que a sua equipa realmente fala',
            'Um único contacto para o trabalhador e para o seu departamento de recursos humanos',
          ],
        },
        conditions: {
          title: 'Como trabalhamos com o polo industrial',
          intro: 'Servimos os dois lados do polo industrial portuário, empregadores e trabalhadores, o que obriga a que as nossas condições sejam claras.',
          items: [
            'Abrangemos Rotterdam, Botlek, Europoort, Maasvlakte, Pernis e todo o corredor A15.',
            'Os empregadores podem contratar-nos por colaborador, por projeto ou através de um acordo-quadro para contratação contínua.',
            'As contratações de fora da UE necessitam de uma autorização aprovada antes de iniciarem funções e de um patrocinador reconhecido antes de se poder submeter o pedido.',
            'Os trabalhadores destacados por outras entidades da UE estão abrangidos por um regime de notificação distinto, com obrigações próprias.',
            'Cada colaborador que se relocaliza é registado individualmente, seja qual for a dimensão do grupo, e cada família necessita dos seus próprios documentos.',
            'Aceitamos trabalho de reparação em chegadas que já correram mal e dizemos com clareza o que pode e o que não pode ser corrigido.',
          ],
        },
        details: {
          title: 'Para empregadores do polo industrial',
          items: [
            {
              q: 'Podem assumir uma chegada que já falhou?',
              a: 'Sim, e fazemo-lo com regularidade. Moradas não registadas, BSN em falta, salários por pagar porque o processamento não pode correr, seguros que nunca foram feitos, uma família retida no estrangeiro por causa de um documento. É trabalho pouco glamoroso e é muitas vezes o mais valioso que fazemos.',
            },
            {
              q: 'Como funciona um acordo-quadro?',
              a: 'Um ponto de contacto único, níveis de serviço acordados por chegada, preço fixo por colaborador e uma visão única para os recursos humanos sobre todos os processos em curso. Para empregadores que contratam de forma contínua, elimina por completo a negociação a cada contratação.',
            },
            {
              q: 'Tratam da parte da imigração além da mudança?',
              a: 'Sim, e é por isso que as empresas nos contratam em vez de recorrerem a uma agência apenas de relocalização. Autorizações, patrocínio, registo, habitação e apoio à família ficam com uma só consultoria, para que nada caia no vazio entre dois fornecedores.',
            },
            {
              q: 'Como nos ajudam a reter as pessoas?',
              a: 'Fazendo com que os primeiros seis meses funcionem para a família e não apenas para o colaborador. A maioria das saídas precoces deste polo remonta a um cônjuge sem trabalho, a um filho que nunca se adaptou ou a uma situação de habitação que nunca pareceu certa, e cada uma dessas situações tem solução se alguém estiver atento a tempo.',
            },
          ],
        },
        faq: {
          title: 'Perguntas frequentes',
          items: [
            {
              q: 'Como funciona a faturação para empresas?',
              a: 'Por relocalização ou ao abrigo de um acordo-quadro, faturado diretamente à empresa com um âmbito claramente definido por colaborador. Os valores são confirmados numa conversa inicial sobre o perfil habitual das suas contratações.',
            },
            {
              q: 'As nossas pessoas trabalham por turnos em vários locais. Conseguem lidar com isso?',
              a: 'É o nosso pão de cada dia. As marcações são planeadas pessoa a pessoa em função da escala de turnos e do local, e acompanhamos cada trabalhador para que nenhuma ida a um balcão seja desperdiçada.',
            },
            {
              q: 'Muitos dos nossos contratos são de curta duração. O apoio à relocalização continua a compensar?',
              a: 'É nos contratos curtos que as chegadas mal feitas custam mais caro, em faltas à apresentação, saídas precoces e problemas salariais. Habitação temporária onde seja possível registar-se e uma via de registo correta dão a uma contratação de seis meses um início limpo e uma saída limpa.',
            },
          ],
        },
        cta: {
          title: 'Dê aos seus trabalhadores internacionais uma verdadeira chegada',
          text: 'Uma conversa sobre as suas contratações e a relocalização deixa de ser um problema dos recursos humanos.',
          label: 'Ser nosso parceiro',
        },
        form: 'relocation',
        image: '/images/rotterdam-industrial.jpg?v=20260731',
        imageAlt: 'Trabalhadores com coletes de alta visibilidade no porto, com a silhueta de Rotterdam ao fundo',
        image2: '/images/industrial-hub.jpg?v=20260731',
        image2Alt: 'Polo industrial portuário ao anoitecer',
      },
    ],
    cta: {
      title: 'A região portuária é a nossa especialidade',
      text: 'Europoort, Maasvlakte, offshore ou logística: diga-nos onde é o trabalho e nós tratamos de tudo à volta dele.',
      label: 'Fale com o especialista',
    },
  };
