/* GENERATED by scripts/i18n-strings.mjs. Do not hand-edit.
   pt/relocation.ts is a 1:1 structural mirror of en/relocation.ts; only leaf strings
   differ. To change structure, change English and re-run the build. */
import type { SectionContent } from '../types';

export const relocation: SectionContent = {
    title: 'Serviços de Relocalização nos Países Baixos',
    metaTitle: 'Relocalização nos Países Baixos | E & I Expat Services',
    metaDescription: 'Serviços de relocalização boutique nos Países Baixos. Um guia pessoal para o seu BSN, registo na câmara municipal, seguro de saúde, escolas e instalação, que o acompanha a todas as marcações.',
    eyebrow: 'Relocalização',
    intro: [
      'Mudar de país são mil pequenas tarefas disfarçadas de uma só grande tarefa. O BSN, a câmara municipal, o seguro, a escola, o banco, cada um com o seu balcão, os seus formulários e a sua própria ideia de um tempo de espera razoável. A maioria das empresas entrega-lhe uma lista de verificação. Somos a única consultoria boutique para expatriados nos Países Baixos e fazemos algo diferente: uma pessoa aprende o seu nome, a sua família e a sua situação, e depois simplesmente trata de tudo.',
      'Essa pessoa não gere a sua relocalização a partir de uma secretária. Marca as reuniões, prepara a documentação, vai consigo de carro à câmara municipal e senta-se ao seu lado no balcão. Desde o momento em que aterra até ao momento em que os Países Baixos são a sua casa, tem aqui alguém que já sabe a resposta à sua próxima pergunta.',
    ],
    image: '/images/family-arrival.jpg?v=20260731',
    imageAlt: 'Família internacional a chegar à sua casa neerlandesa junto ao canal',
    services: [
      {
        slug: 'bsn-registration-netherlands',
        menuLabel: 'Registo do BSN',
        title: 'Registo do BSN nos Países Baixos',
        metaTitle: 'Registo do BSN nos Países Baixos | E & I Expat Services',
        metaDescription: 'Obtenha o seu BSN de forma rápida e correta. Preparamos os seus documentos, marcamos a reunião e acompanhamo-lo ao balcão da câmara municipal.',
        eyebrow: 'BSN',
        intro: [
          'O BSN, o seu número de identificação civil neerlandês, é a chave que abre tudo o resto por cá: o seu salário, o seu seguro de saúde, a sua conta bancária, até o seu contrato de telemóvel. Enquanto não o tiver, está oficialmente em suspenso. É por isso que deve ser a primeira coisa a tratar depois de chegar, e a ser bem tratada logo à primeira.',
          'Preparamos a marcação, verificamos se as suas certidões de nascimento e apostilas serão aceites, e a Johanna acompanha-o pessoalmente ao balcão. Se o funcionário levantar uma questão sobre um documento estrangeiro, tem ao seu lado alguém que já ouviu essa pergunta uma centena de vezes e sabe a resposta.',
        ],
        cardText: 'O seu número de identificação civil tratado depressa, connosco ao seu lado no balcão.',
        explainer: {
          title: 'O que é o BSN?',
          text: [
            'O BSN, burgerservicenummer, é o seu número de identificação civil neerlandês. É o identificador único que o Estado, a sua entidade empregadora, o seu banco, a sua seguradora e o seu médico utilizam para o reconhecer, e quase nada na vida nos Países Baixos avança sem ele.',
            'Recebe-o ao efetuar o registo numa câmara municipal, e não através de um pedido separado. É por isso que o registo é a primeira tarefa prática após a chegada: não é possível pagar um salário, o seguro de saúde não pode começar e abrir uma conta bancária é difícil enquanto o número não existir.',
          ],
        },
        forWho: {
          title: 'Para quem é',
          items: [
            'Recém-chegados que precisam do BSN antes de poderem receber o primeiro salário',
            'Famílias que registam vários membros, incluindo crianças, numa só visita',
            'Expatriados cujos documentos estrangeiros precisam de apostilas ou traduções certificadas',
            'Quem tentou marcar uma reunião e esbarrou num muro de tempos de espera',
          ],
        },
        included: {
          title: 'O que está incluído',
          blocks: [
            {
              title: 'Verificação dos documentos antes de viajar',
              text: 'Analisamos antecipadamente as suas certidões de nascimento, a certidão de casamento e as legalizações, para que nada seja recusado ao balcão.',
            },
            {
              title: 'Estratégia de marcação',
              text: 'Sabemos que câmaras municipais e que balcões para expatriados têm as esperas mais curtas e marcamos o horário mais próximo que seja realista para a sua situação.',
            },
            {
              title: 'Acompanhamento pessoal',
              text: 'Vamos consigo à reunião, traduzimos quando for necessário e resolvemos as questões no momento.',
            },
            {
              title: 'Depois da reunião',
              text: 'Acompanhamos a confirmação, explicamos o seu extrato de registo e garantimos que o seu BSN chega corretamente à sua entidade empregadora e à sua seguradora.',
            },
          ],
        },
        process: {
          title: 'Como funciona',
          steps: [
            {
              title: 'Análise dos documentos',
              text: 'Envie-nos digitalizações dos seus documentos civis e dizemos-lhe exatamente o que precisa de apostila ou tradução.',
            },
            {
              title: 'Reunião marcada',
              text: 'Agendamos o seu registo no melhor balcão disponível para a sua morada e o seu calendário.',
            },
            {
              title: 'Dia do registo',
              text: 'Vamos juntos, concluímos o registo e saímos com tudo confirmado.',
            },
          ],
        },
        fees: {
          title: 'Honorários profissionais para o registo do BSN',
          kind: 'fixed',
          amount: 'Investimento a partir de €295',
          includes: [
            'Reunião na câmara municipal marcada no balcão certo e no momento certo',
            'Requisitos de documentos, legalização e tradução verificados antecipadamente',
            'Acompanhamento à reunião, com interpretação quando for necessário',
            'Seguimento até o número ser efetivamente emitido',
          ],
        },
        note: 'O BSN é emitido através do registo na base de dados da população, seja como residente ou, no caso de estadias curtas, como não residente através de um balcão RNI. Aconselhamo-lo sobre a via adequada à sua situação durante a entrevista inicial.',
        conditions: {
          title: 'O que a câmara municipal lhe vai pedir',
          intro: 'O BSN é a chave que abre todas as outras fechaduras. Quase todos os atrasos que vemos resultam de um dos seis pontos abaixo.',
          items: [
            'O registo é feito na câmara municipal da sua morada e é necessário ter uma morada onde o senhorio permita o registo.',
            'Uma permanência superior a quatro meses implica o registo no BRP. Uma permanência mais curta implica o registo RNI, numa das câmaras municipais designadas.',
            'Leve o seu passaporte, a sua autorização de residência ou MVV quando aplicável, e o seu contrato de arrendamento.',
            'As certidões estrangeiras de nascimento e de casamento têm de ser legalizadas ou ter apostila, e ser traduzidas por um tradutor ajuramentado.',
            'As reuniões têm normalmente de ser marcadas com antecedência e, em Rotterdam, os tempos de espera vão de alguns dias a várias semanas, consoante a época do ano.',
            'Cada membro da família precisa da sua própria marcação e dos seus próprios documentos, incluindo as crianças.',
          ],
        },
        details: {
          title: 'Onde os processos de BSN correm mal',
          items: [
            {
              q: 'Porque é que a legalização é um problema tão grande?',
              a: 'Uma certidão que não tenha sido legalizada no país de emissão não pode ser aceite, e a cadeia passa muitas vezes por um ministério local e depois por uma embaixada neerlandesa. Pode demorar semanas ou meses e não pode ser iniciada quando já se encontra aqui. É a razão mais comum para uma chegada ficar bloqueada, e é a primeira coisa que verificamos.',
            },
            {
              q: 'Posso obter o BSN sem uma morada neerlandesa?',
              a: 'Sim, através do registo RNI para não residentes, disponível em dezanove câmaras municipais designadas. Dá-lhe um BSN para que o processamento salarial e a atividade bancária possam começar, mas não é um registo de residência, pelo que continua a ter de fazer o registo devido assim que tiver a sua morada.',
            },
            {
              q: 'O que acontece logo a seguir à reunião?',
              a: 'O seu BSN é normalmente emitido no momento ou em poucos dias. Depois disso, abre caminho ao pedido de DigiD, à adesão ao seguro de saúde, a uma conta bancária neerlandesa e a um processamento salarial correto. Percorremos essa sequência consigo, em vez de o deixar com um número e uma lista.',
            },
            {
              q: 'Acompanham-me à reunião?',
              a: 'Sim, é esse o propósito do serviço. As reuniões decorrem em neerlandês, os funcionários pedem documentos que não constavam da lista publicada, e ter ao seu lado alguém que sabe a resposta transforma uma segunda reunião em nenhuma segunda reunião.',
            },
          ],
        },
        faq: {
          title: 'Perguntas frequentes',
          items: [
            {
              q: 'Com que rapidez posso obter o BSN depois de chegar?',
              a: 'Com os documentos preparados com antecedência, muitas vezes poucos dias após a chegada; o número é normalmente emitido na própria reunião ou pouco depois. Os verdadeiros atrasos vêm de apostilas em falta e de listas de espera para marcações, que é precisamente o que eliminamos.',
            },
            {
              q: 'Preciso de uma morada permanente para obter o BSN?',
              a: 'Precisa de uma morada onde seja possível registar-se, que pode ser temporária se o proprietário permitir o registo. Se ainda não a tiver, avaliamos a via RNI ou tratamos de uma habitação de curta duração onde o registo seja permitido.',
            },
            {
              q: 'Toda a minha família pode ser registada de uma só vez?',
              a: 'Sim, e vale a pena. Marcamos uma reunião familiar, preparamos todas as certidões com antecedência e garantimos que as crianças ficam corretamente registadas, o que é importante mais tarde para a inscrição na escola e para os cuidados de saúde.',
            },
          ],
        },
        cta: {
          title: 'Obtenha o seu BSN sem voltas nem esperas',
          text: 'Envie-nos a sua data de chegada e teremos prontos a marcação, a documentação e um lugar ao seu lado.',
          label: 'Tratar do meu BSN',
        },
        form: 'relocation',
        image: '/images/bsn-registration.jpg?v=20260731',
        imageAlt: 'Consultora e cliente numa mesa de aconselhamento privado',
        image2: '/images/immigration-documents.jpg?v=20260731',
        image2Alt: 'Pasta de couro e caneta de tinta permanente sobre uma secretária',
      },
      {
        slug: 'municipality-registration-netherlands',
        menuLabel: 'Registo na câmara municipal',
        title: 'Registo na Câmara Municipal nos Países Baixos',
        metaTitle: 'Registo na Câmara Municipal | E & I Expat Services',
        metaDescription: 'Registe-se na sua câmara municipal neerlandesa sem stress. Preparação de documentos, marcação de reuniões e acompanhamento pessoal em todo o processo na gemeente.',
        eyebrow: 'Gemeente',
        intro: [
          'Todos os residentes nos Países Baixos têm de estar registados na sua gemeente, a câmara municipal, e esse registo acompanha-o em todo o lado: impostos, prestações sociais, votação, dísticos de estacionamento, vagas na escola. Se estiver errado, ou se ficar desatualizado após uma mudança, pequenos erros administrativos transformam-se discretamente em problemas reais.',
          'Tratamos de toda a relação com a sua câmara municipal. O primeiro registo quando chega, o novo registo quando muda de morada dentro dos Países Baixos, o cancelamento do registo se partir, e as correções quando os dados não correspondem à realidade. Anos de trabalho junto de embaixadas e consulados ensinaram-nos como pensa a administração neerlandesa, e pomos essa fluência ao serviço no seu balcão local.',
        ],
        cardText: 'Primeiro registo, mudanças de morada e correções na gemeente, tudo tratado por nós.',
        explainer: {
          title: 'O que é o registo na câmara municipal?',
          text: [
            'O registo na câmara municipal inscreve-o na Basisregistratie Personen, o BRP, que é o registo da população neerlandesa. Regista quem é e onde vive, e é o que dá origem ao seu BSN. Todos os níveis da administração neerlandesa consultam esse registo.',
            'É uma obrigação legal com prazo, e não uma formalidade opcional. Regista-se na gemeente da morada onde vive efetivamente e precisa da autorização do senhorio para essa morada, que é o ponto onde os registos falham com mais frequência.',
          ],
        },
        forWho: {
          title: 'Para quem é',
          items: [
            'Recém-chegados que fazem o primeiro registo na base de dados da população',
            'Expatriados que mudam entre cidades neerlandesas e têm de se registar de novo',
            'Residentes cujos dados municipais contêm erros que continuam a causar problemas',
            'Expatriados de partida que precisam de um cancelamento de registo sem falhas',
          ],
        },
        included: {
          title: 'O que está incluído',
          blocks: [
            {
              title: 'O balcão certo, a via certa',
              text: 'As câmaras municipais diferem mais do que seria de esperar. Determinamos onde e como o seu processo deve ser apresentado, incluindo as opções nos centros para expatriados.',
            },
            {
              title: 'Processo documental completo',
              text: 'Comprovativo de morada, documentos de identificação, autorização do arrendamento e certidões estrangeiras reunidos e verificados antes da reunião.',
            },
            {
              title: 'Marcação e presença',
              text: 'Marcamos o horário, explicamos-lhe o que vai acontecer e vamos consigo para traduzir e resolver imprevistos.',
            },
            {
              title: 'Verificação dos dados',
              text: 'Depois verificamos o seu extrato da base de dados, porque um erro no seu nome ou na sua morada hoje é um crédito à habitação recusado amanhã.',
            },
          ],
        },
        process: {
          title: 'Como funciona',
          steps: [
            {
              title: 'Avaliação da situação',
              text: 'Chegada, mudança ou correção? Mapeamos o seu caso e os documentos que a sua gemeente vai pedir.',
            },
            {
              title: 'Processo e marcação',
              text: 'Reunimos o processo e garantimos a marcação mais próxima que seja viável.',
            },
            {
              title: 'Registado e verificado',
              text: 'Concluímos o registo em conjunto e confirmamos que a base de dados mostra exatamente o que deve mostrar.',
            },
          ],
        },
        fees: {
          title: 'Honorários profissionais para o registo na câmara municipal',
          kind: 'fixed',
          amount: 'Investimento a partir de €295',
          includes: [
            'Reunião marcada dentro do prazo de cinco dias previsto na lei',
            'Morada e autorização do senhorio verificadas para que o registo não seja recusado',
            'Acompanhamento à câmara municipal no próprio dia',
            'Confirmação de que o registo no BRP está correto assim que for emitido',
          ],
        },
        conditions: {
          title: 'Regras que apanham as pessoas desprevenidas',
          intro: 'O registo na gemeente acompanha-o em todas as instituições do país, pelo que um erro aqui reaparece em todo o lado.',
          items: [
            'O primeiro registo tem de ser feito no prazo de cinco dias após a chegada, e uma mudança dentro dos Países Baixos no prazo de cinco dias após a mudança.',
            'A mudança de morada tem de ser comunicada à nova câmara municipal, não à anterior.',
            'O registo exige a autorização do senhorio para a morada. Registar-se onde tal é proibido põe em risco o seu arrendamento.',
            'O seu estado civil, a grafia do seu nome e o seu local de nascimento são retirados de certidões legalizadas, e corrigi-los mais tarde é muito mais difícil do que acertar logo à primeira.',
            'Ausentar-se dos Países Baixos por mais de oito meses num ano exige o cancelamento do registo, o que afeta seguros, prestações sociais e autorizações.',
            'Os nacionais de países terceiros levantam normalmente o seu documento de residência no IND, e não na câmara municipal. As duas reuniões são separadas.',
          ],
        },
        details: {
          title: 'Acertar o registo',
          items: [
            {
              q: 'Porque é que a grafia do meu nome é tão importante?',
              a: 'O registo no BRP alimenta o seu banco, a sua entidade empregadora, a administração fiscal, a sua seguradora e o IND. Uma transliteração que difira do seu passaporte numa única letra produz divergências que aparecem meses depois, no pior momento. Verificamos a inscrição em confronto com o seu passaporte antes de o funcionário a gravar.',
            },
            {
              q: 'Conseguem corrigir um registo que já está errado?',
              a: 'Normalmente sim, com os documentos comprovativos certos e um pedido formal de correção. Os erros na data de nascimento, no estado civil e na nacionalidade anterior são os que mais corrigimos, e vale a pena corrigi-los em vez de conviver com eles.',
            },
            {
              q: 'E se o meu senhorio não autorizar o registo?',
              a: 'Nesse caso a morada é um problema, não um incómodo. Verificamos a autorização de registo antes de assinar um contrato e, quando um senhorio recusa depois disso, assumimos a correspondência, porque na maioria das situações de habitação a recusa não tem fundamento legal.',
            },
            {
              q: 'Tenho de cancelar o registo quando partir?',
              a: 'Sim, se partir por mais de oito meses num período de doze meses. Não cancelar o registo deixa-o responsável por prémios de seguro de saúde neerlandês e por impostos locais muito depois de ter saído. Tratamos da saída com o mesmo cuidado com que tratamos da chegada.',
            },
          ],
        },
        faq: {
          title: 'Perguntas frequentes',
          items: [
            {
              q: 'E se o meu senhorio não tiver dado autorização para o registo?',
              a: 'Tem o direito de se registar onde vive efetivamente, e um senhorio não o pode proibir legalmente. Abordamos primeiro o senhorio para resolver a questão de forma amigável e, se for necessário, acompanhamo-lo na via de investigação de morada da câmara municipal.',
            },
            {
              q: 'Mudei-me dentro dos Países Baixos. Tenho mesmo de me registar de novo?',
              a: 'Sim, no prazo de cinco dias após a mudança, e não é uma formalidade. A sua seguradora de saúde, a administração fiscal e a sua entidade empregadora consultam esse registo. Apresentamos a alteração online ou ao balcão e confirmamos que foi processada.',
            },
            {
              q: 'Os meus filhos têm de ir à reunião?',
              a: 'Num primeiro registo, as câmaras municipais querem geralmente ver cada membro da família pessoalmente, incluindo as crianças. Planeamos uma única reunião familiar eficiente para não ter de voltar três vezes.',
            },
          ],
        },
        cta: {
          title: 'Torne a gemeente simples',
          text: 'Seja o que for que a sua câmara municipal lhe peça, já o fizemos antes. Diga-nos a sua situação e considere o assunto tratado.',
          label: 'Tratar do meu registo',
        },
        form: 'relocation',
        image: '/images/municipality-registration.jpg?v=20260731',
        imageAlt: 'Cliente a chegar a um edifício público neerlandês histórico',
        image2: '/images/consultation.jpg?v=20260731',
        image2Alt: 'Consultora e cliente a discutir os passos seguintes',
      },
      {
        slug: 'health-insurance-guidance-netherlands',
        menuLabel: 'Seguro de saúde',
        title: 'Aconselhamento sobre Seguro de Saúde nos Países Baixos',
        metaTitle: 'Seguro de Saúde nos Países Baixos | E & I Expat Services',
        metaDescription: 'O seguro de saúde neerlandês explicado e tratado. Ajudamos expatriados a escolher a apólice certa, a inscrever-se num médico de família e a evitar multas por adesão tardia.',
        eyebrow: 'Saúde',
        intro: [
          'O seguro de saúde neerlandês é obrigatório, excelente e genuinamente confuso. Tem de subscrever uma apólice básica no prazo de quatro meses a contar do início da obrigação de seguro, os prémios e as franquias variam de formas difíceis de comparar a partir do estrangeiro, e falhar o prazo traz multas e prémios retroativos. Entretanto, o site de cada seguradora parte do princípio de que já compreende o sistema.',
          'Explicamos tudo numa conversa honesta: o que o pacote básico cobre sempre, quando vale a pena um seguro complementar para a sua família e como funciona realmente a franquia. Depois ajudamo-lo a aderir, a inscrever-se num médico de família e a saber o que fazer na primeira vez que ficar doente ou que o seu filho ficar doente.',
        ],
        cardText: 'A apólice de saúde neerlandesa certa escolhida, subscrita e explicada em linguagem clara.',
        forWho: {
          title: 'Para quem é',
          items: [
            'Recém-chegados perante o prazo de quatro meses para o seguro',
            'Famílias que ponderam cobertura complementar para dentista, fisioterapia ou necessidades dos filhos',
            'Expatriados sem certeza se o seguro estrangeiro ou o da entidade empregadora ainda se aplica',
            'Quem recebeu uma carta do CAK e não sabe porquê',
          ],
        },
        included: {
          title: 'O que está incluído',
          blocks: [
            {
              title: 'O sistema explicado como deve ser',
              text: 'Pacote básico, franquia, comparticipações próprias, subsídio de saúde: toda a engrenagem explicada uma vez, com clareza, com os seus números.',
            },
            {
              title: 'Comparação de apólices e adesão',
              text: 'Selecionamos as apólices que se adequam à sua família e ao seu orçamento, explicamos honestamente os compromissos e acompanhamo-lo na adesão.',
            },
            {
              title: 'Inscrição no médico de família e na farmácia',
              text: 'Encontramos perto de si um huisarts que aceite novos pacientes, tratamos da sua inscrição e explicamos como funcionam os encaminhamentos para especialistas.',
            },
            {
              title: 'Verificação do subsídio',
              text: 'Se o seu rendimento der direito ao zorgtoeslag, o subsídio mensal de saúde, ajudamo-lo a requerê-lo.',
            },
          ],
        },
        process: {
          title: 'Como funciona',
          steps: [
            {
              title: 'Conversa sobre a cobertura',
              text: 'Avaliamos a sua família, as suas necessidades de saúde e a data de início, e verificamos o que a sua entidade empregadora já oferece.',
            },
            {
              title: 'Escolher e aderir',
              text: 'Escolhe a partir de uma lista curta e clara e nós concluímos a adesão com o seu BSN.',
            },
            {
              title: 'Rede de cuidados montada',
              text: 'Médico de família, dentista e farmácia inscritos, para que o seu primeiro dia de doença seja um incómodo, não uma crise.',
            },
          ],
        },
        fees: {
          title: 'Honorários profissionais para o aconselhamento sobre seguro de saúde',
          kind: 'fixed',
          amount: 'Investimento a partir de €195',
          includes: [
            'A apólice neerlandesa certa identificada para a sua situação e o seu agregado familiar',
            'Pedido preenchido e submetido consigo',
            'Data de início alinhada com a sua chegada para que nunca fique sem seguro',
            'Aconselhamento sobre a franquia, o subsídio de saúde e a escolha do médico de família',
          ],
        },
        note: 'O seguro produz efeitos retroativamente a partir da data em que a obrigação começou, pelo que os prémios são devidos desde essa data mesmo que a adesão seja posterior. Aderir com prontidão não custa nada mais e evita multas.',
        conditions: {
          title: 'Como funciona o sistema neerlandês',
          intro: 'O seguro de saúde neerlandês é obrigatório, privado e sujeito a prazos. Falhar o calendário sai caro de uma forma que surpreende a maioria dos recém-chegados.',
          items: [
            'Quem vive ou trabalha nos Países Baixos tem de subscrever o seguro de saúde básico neerlandês no prazo de quatro meses após o registo.',
            'A cobertura retroage ao seu primeiro dia de residência, pelo que uma adesão tardia gera uma fatura pelos meses entretanto decorridos, mais uma multa.',
            'O pacote básico é definido pelo Estado e é idêntico em todas as seguradoras. Só o preço, o serviço e a cobertura complementar diferem.',
            'Existe uma franquia anual obrigatória definida pelo Estado, que paga antes de a maioria dos cuidados ser reembolsada. O médico de família está isento dela.',
            'Não pode consultar um especialista sem um encaminhamento do médico de família onde está inscrito, exceto em emergências.',
            'Os rendimentos baixos e médios podem dar direito ao zorgtoeslag, um subsídio mensal de saúde atribuído pela administração fiscal.',
          ],
        },
        details: {
          title: 'Escolher bem, não apenas depressa',
          items: [
            {
              q: 'Que cobertura complementar vale realmente a pena?',
              a: 'O dentista para adultos, a fisioterapia para além do mínimo legal e a cobertura de cuidados no estrangeiro são as três que compensam para a maioria dos nossos clientes. As crianças estão cobertas gratuitamente na apólice de um dos pais, incluindo o dentista. Quase tudo o resto é um cálculo pessoal, e fazemo-lo consigo, não por si.',
            },
            {
              q: 'Porque é que não consigo encontrar um médico de família?',
              a: 'As clínicas em Rotterdam e nas cidades maiores fecham regularmente as suas listas, e a inscrição é exigida antes de precisar de cuidados, e não no momento em que deles precisa. Começamos a procura de médico de família na sua primeira semana e sabemos que clínicas da região continuam a aceitar pacientes.',
            },
            {
              q: 'Tenho o regime dos 30 por cento. Muda alguma coisa?',
              a: 'A sua obrigação de seguro não muda. O que pode mudar é o seu direito ao zorgtoeslag, uma vez que o subsídio depende de uma condição de recursos calculada sobre o rendimento tributável. Verificamos isso em vez de o presumir.',
            },
            {
              q: 'E se eu só trabalhar aqui parte do ano?',
              a: 'As situações transfronteiriças e de trabalho rotativo são genuinamente complicadas, e errar significa pagar prémios a dobrar ou ficar sem cobertura nenhuma. Os trabalhadores offshore, os trabalhadores destacados e as pessoas com uma entidade empregadora noutro Estado da UE regem-se por regras diferentes, e analisamos a sua em concreto.',
            },
          ],
        },
        faq: {
          title: 'Perguntas frequentes',
          items: [
            {
              q: 'Tenho um seguro de viagem ou internacional. É suficiente?',
              a: 'Normalmente não. A partir do momento em que vive ou trabalha aqui e está abrangido pelo sistema neerlandês, a apólice básica neerlandesa é legalmente exigida, independentemente de outras coberturas. Verificamos a sua situação específica, incluindo as exceções para determinados destacamentos e para estudantes.',
            },
            {
              q: 'Porque é que preciso de um médico de família antes sequer de estar doente?',
              a: 'O huisarts é a porta de entrada para todos os cuidados de saúde neerlandeses; os hospitais esperam um encaminhamento. As clínicas perto de si podem ter as listas de pacientes fechadas, pelo que inscrever-se cedo, enquanto está saudável, é a melhor decisão de saúde que um recém-chegado pode tomar.',
            },
            {
              q: 'O que acontece se surgir uma questão de saúde fora do horário de expediente?',
              a: 'Os Países Baixos têm um serviço de médico de família fora de horas, o huisartsenpost, para casos urgentes. E os nossos clientes podem sempre escrever-nos na linha pessoal de WhatsApp a qualquer hora; já acompanhámos mais do que um pai preocupado durante a sua primeira febre noturna nos Países Baixos.',
            },
          ],
        },
        cta: {
          title: 'Fique segurado antes que o prazo se encarregue do assunto',
          text: 'Uma conversa e os seus cuidados de saúde neerlandeses ficam escolhidos, subscritos e prontos a usar.',
          label: 'Tratar do meu seguro',
        },
        form: 'relocation',
        image: '/images/health-insurance.jpg?v=20260731',
        imageAlt: 'Cliente e consultora a falar sobre a cobertura de saúde neerlandesa',
        image2: '/images/relocation-settling.jpg?v=20260731',
        image2Alt: 'Consultora a percorrer os passos de instalação com recém-chegados',
      },
      {
        slug: 'school-search-netherlands',
        menuLabel: 'Procura de escola',
        title: 'Procura de escola nos Países Baixos',
        metaTitle: 'Procura de escola nos Países Baixos | E & I Expat Services',
        metaDescription: 'Encontre a escola neerlandesa, internacional ou bilingue certa para os seus filhos. Pré-seleção de escolas, visitas e apoio na inscrição para famílias expatriadas.',
        eyebrow: 'Escolas',
        intro: [
          'Pergunte a pais em processo de mudança o que lhes tira o sono e raramente é o visto. É a escola. Internacional ou neerlandesa? Bilingue? Qual é a dimensão das listas de espera e o que acontece a uma criança de nove anos que não fala neerlandês na sua primeira segunda-feira? Estas perguntas merecem melhores respostas do que um tópico de fórum.',
          'Guiamo-lo pelo panorama real: escolas internacionais, escolas neerlandesas com turmas de acolhimento, programas bilingues e a realidade das listas de espera de cada uma. Selecionamos as escolas que se ajustam ao seu filho, marcamos as visitas e acompanhamo-lo nelas, e conduzimos a documentação de inscrição até à vaga confirmada.',
        ],
        cardText: 'A escola certa para o seu filho, da pré-seleção à inscrição confirmada.',
        forWho: {
          title: 'Para quem é',
          items: [
            'Famílias que escolhem entre o ensino internacional e o neerlandês',
            'Pais de crianças que chegam sem falar neerlandês',
            'Expatriados cuja duração da colocação torna a escolha da escola complicada',
            'Famílias que se mudam a meio do ano letivo e receiam não conseguir vaga',
          ],
        },
        included: {
          title: 'O que está incluído',
          blocks: [
            {
              title: 'Panorama do sistema de ensino',
              text: 'Como funciona o sistema neerlandês, quanto custam as escolas internacionais, como as turmas de acolhimento colmatam a barreira linguística e o que se adequa à duração da sua colocação.',
            },
            {
              title: 'Pré-seleção personalizada de escolas',
              text: 'Escolas selecionadas em função da idade, das línguas e das necessidades do seu filho, ajustadas ao local onde vai viver, com notas honestas sobre cada uma.',
            },
            {
              title: 'Visitas marcadas e acompanhadas',
              text: 'Marcamos as visitas guiadas, preparamos as perguntas que vale a pena fazer e acompanhamo-lo em cada uma.',
            },
            {
              title: 'Da inscrição à confirmação',
              text: 'Formulários de candidatura, registos escolares anteriores e acompanhamento das listas de espera, geridos até o seu filho ter uma vaga confirmada.',
            },
          ],
        },
        process: {
          title: 'Como funciona',
          steps: [
            {
              title: 'Conversa inicial com a família',
              text: 'Falamos sobre os seus filhos, as línguas que falam, as suas necessidades e os seus planos nos Países Baixos.',
            },
            {
              title: 'Pré-seleção e visita',
              text: 'Recebe uma pré-seleção focada e visitamos juntos as escolas promissoras.',
            },
            {
              title: 'Inscrição e início',
              text: 'Concluímos a inscrição e ajudamos o seu filho a chegar a uma escola que já o espera.',
            },
          ],
        },
        fees: {
          title: 'Honorários para uma procura de escola',
          kind: 'fixed',
          amount: 'Investimento a partir de €995',
          includes: [
            'Uma pré-seleção de escolas internacionais, bilingues ou neerlandesas que se ajustam realmente ao seu filho',
            'Listas de espera, prazos de admissão e regras de área de residência verificados antes de escolher',
            'Visitas e apresentações marcadas junto das escolas',
            'Documentação de inscrição preparada e submetida',
          ],
        },
        note: 'A escolha da escola e a escolha da habitação são uma única decisão, não duas; é a morada que determina as opções. Se também tratarmos da sua procura de habitação, planeamos ambas em conjunto.',
        conditions: {
          title: 'O que as famílias devem saber primeiro',
          intro: 'São as vagas escolares, e não a habitação, que normalmente determinam quando uma família se pode mudar. Planeie este ponto antes de tudo o resto.',
          items: [
            'A escolaridade é obrigatória a partir dos cinco anos e a maioria das crianças começa aos quatro.',
            'As escolas internacionais na região de Rotterdam têm vagas limitadas e listas de espera, e os anos de escolaridade mais procurados ficam preenchidos com um ano de antecedência.',
            'As escolas internacionais nos Países Baixos dividem-se em duas categorias: as escolas internacionais neerlandesas subsidiadas, bastante mais baratas mas que exigem um percurso internacional comprovável, e as escolas internacionais privadas.',
            'As crianças que ainda não falam neerlandês passam habitualmente um ano numa nieuwkomersklas antes de entrarem no ensino neerlandês regular.',
            'A inscrição exige normalmente comprovativo de morada e um BSN, o que liga o calendário escolar ao calendário da habitação e do registo.',
            'Aconselhamos sobre escolas e gerimos o processo. Não podemos criar uma vaga onde a escola não tem nenhuma.',
          ],
        },
        details: {
          title: 'Escolher o ensino certo',
          items: [
            {
              q: 'Escola internacional ou escola neerlandesa?',
              a: 'Tudo depende de quanto tempo tenciona ficar. Abaixo de três anos, uma escola internacional preserva a continuidade e o currículo ao qual o seu filho vai regressar. Acima de cinco, uma escola neerlandesa dá-lhe a língua, as amizades e uma adolescência muito mais fácil. Os anos intermédios são uma decisão a sério, e discutimo-la como deve ser em vez de empurrarmos a opção mais cara.',
            },
            {
              q: 'Com que antecedência devemos começar?',
              a: 'Seis a nove meses antes da mudança no caso das escolas internacionais e três meses no caso das escolas neerlandesas. Se já estiver dentro desse prazo, vamos diretamente às escolas que ainda têm margem, que são uma lista diferente da que encontra online.',
            },
            {
              q: 'Quanto custa?',
              a: 'As escolas internacionais neerlandesas subsidiadas custam alguns milhares de euros por ano. As escolas internacionais privadas da região ficam consideravelmente acima disso, e as propinas, a inscrição e os materiais são normalmente faturados em separado. Indicamos o valor anual real de cada escola da sua pré-seleção para que não haja surpresas no segundo mês.',
            },
            {
              q: 'O meu filho vai conseguir com o neerlandês?',
              a: 'As crianças mais novas conseguem quase sempre, e depressa. A nieuwkomersklas existe precisamente para isso, e um ano nela costuma levar a criança ao ponto em que o ensino regular funciona. Para adolescentes perto dos exames, a conta é outra, e somos francos quanto a isso.',
            },
          ],
        },
        faq: {
          title: 'Perguntas frequentes',
          items: [
            {
              q: 'Devemos escolher o ensino internacional ou o neerlandês?',
              a: 'Para colocações de menos de cerca de três anos, as escolas internacionais oferecem continuidade. Para famílias que ficam mais tempo, as escolas neerlandesas com um programa de acolhimento integram muitas vezes as crianças mais depressa e custam bastante menos. Ajudamo-lo a decidir com base nos seus planos, não numa regra geral.',
            },
            {
              q: 'O meu filho não fala neerlandês. Como lidam as escolas neerlandesas com isso?',
              a: 'Muitas regiões têm turmas de acolhimento dedicadas, onde as crianças recebem neerlandês intensivo durante cerca de um ano antes de entrarem nas turmas regulares. A colocação depende da idade e da região, e nós encontramos as opções concretas perto da sua casa.',
            },
            {
              q: 'As listas de espera são mesmo tão más?',
              a: 'Varia enormemente conforme a cidade e a escola. Escolas internacionais muito procuradas podem ter listas longas enquanto uma escola igualmente boa ali perto tem vagas. Candidatar-se cedo e ao conjunto certo de escolas é a maior parte do trabalho, e é isso que gerimos.',
            },
          ],
        },
        cta: {
          title: 'Dê aos seus filhos uma aterragem suave',
          text: 'Fale-nos dos seus filhos e encontramos a escola onde vão prosperar, e depois tratamos da inscrição.',
          label: 'Encontrar a nossa escola',
        },
        form: 'relocation',
        image: '/images/school-search.jpg?v=20260731',
        imageAlt: 'Mãe e filha a chegar a uma escola internacional',
        image2: '/images/family-relocation.jpg?v=20260731',
        image2Alt: 'Família a pedalar ao longo de um canal neerlandês à hora dourada',
      },
      {
        slug: 'settling-in-services-netherlands',
        menuLabel: 'Serviços de instalação',
        title: 'Serviços de instalação nos Países Baixos',
        metaTitle: 'Serviços de instalação, Países Baixos | E & I Expat Services',
        metaDescription: 'Apoio na instalação de expatriados nos Países Baixos: banco, serviços domésticos, telemóvel, transportes, orientação no bairro e as cem pequenas coisas que transformam uma casa numa vida.',
        eyebrow: 'Instalação',
        intro: [
          'A papelada termina e é então que começam as verdadeiras perguntas. Que banco abre uma conta esta semana? Porque existem três tipos de contentor de lixo? Como funciona o sistema de médico de família, onde se compra uma bicicleta que não seja roubada até sexta-feira e o que é, afinal, o eigen risico? Instalar-se são cem pequenos enigmas, e resolvê-los sozinho leva meses.',
          'Nós comprimimos esses meses em semanas. Banco, serviços domésticos, internet, telemóvel, cartões de transporte, o essencial dos seguros e uma orientação a sério pelo seu novo bairro, tratados consigo e explicados à medida que avançamos. É precisamente esta instalação pessoal e prática que leva os nossos clientes a chamar-nos concierge em vez de agência.',
        ],
        cardText: 'Banco, serviços domésticos, transportes e conhecimento do bairro, tratados em semanas e não em meses.',
        forWho: {
          title: 'Para quem é',
          items: [
            'Recém-chegados que querem a vida prática a funcionar nas primeiras semanas',
            'Profissionais ocupados sem tempo para pesquisar fornecedores neerlandeses',
            'Cônjuges e famílias que chegam enquanto o cônjuge que trabalha já está no escritório',
            'Quem se mudou há meses e continua a sentir que só chegou a meio',
          ],
        },
        included: {
          title: 'O que está incluído',
          blocks: [
            {
              title: 'Conta bancária tratada',
              text: 'Ajuda a escolher e a abrir uma conta bancária neerlandesa, além da configuração do iDEAL e das aplicações de pagamento de que o dia a dia por cá depende.',
            },
            {
              title: 'Casa ligada',
              text: 'Contratos de energia, água, internet e telefone comparados, tratados e agendados em função da data de entrada na casa.',
            },
            {
              title: 'Deslocações',
              text: 'Cartões de transporte público OV, aconselhamento na compra de bicicleta, dísticos de estacionamento e, se conduzir, orientação sobre a sua carta e sobre ter carro nos Países Baixos.',
            },
            {
              title: 'Orientação no bairro',
              text: 'Uma visita guiada personalizada à sua zona: o mercado, o bom supermercado, a farmácia, os clubes desportivos, os atalhos que os locais usam.',
            },
            {
              title: 'As pequenas grandes coisas',
              text: 'Calendários de recolha de lixo, criação do DigiD, seguro de responsabilidade civil, opções de creche: os pormenores que ninguém menciona até correrem mal.',
            },
          ],
        },
        process: {
          title: 'Como funciona',
          steps: [
            {
              title: 'Plano de instalação',
              text: 'Listamos aquilo de que o seu agregado precisa, pela ordem que desbloqueia tudo o resto.',
            },
            {
              title: 'Tratar em conjunto',
              text: 'Ao longo de algumas sessões abrimos contas e tratamos de contratos e cartões, explicando cada passo para que mantenha o controlo.',
            },
            {
              title: 'Dia de orientação',
              text: 'Passamos tempo consigo no seu bairro até começar a senti-lo como seu.',
            },
          ],
        },
        fees: {
          title: 'Quanto custa o apoio na instalação',
          kind: 'tailored',
          amount: 'Proposta à medida',
          amountNote: 'A instalação é a parte da mudança que difere de pessoa para pessoa, pelo que o preço corresponde ao que pretende efetivamente ver tratado. Recebe um orçamento fixo após a primeira conversa, e não uma contagem à hora.',
          includes: [
            'Serviços domésticos, internet e impostos municipais tratados em seu nome',
            'Inscrição no médico, no dentista e na farmácia',
            'Banco, DigiD e a burocracia neerlandesa que bloqueia tudo o resto',
            'A orientação prática que transforma uma morada num bairro',
          ],
        },
        conditions: {
          title: 'A ordem pela qual as coisas têm de acontecer',
          intro: 'A administração neerlandesa é uma cadeia. Tentar o passo quatro antes do passo dois é a razão pela qual as chegadas demoram meses em vez de semanas.',
          items: [
            'Primeiro a morada, depois o registo, depois o BSN. Nada de relevante pode ser tratado antes de o BSN existir.',
            'O DigiD, a credencial nacional de acesso, vem a seguir ao BSN e é exigido pela administração fiscal, pela saúde e pela maioria dos serviços públicos.',
            'A maioria dos bancos neerlandeses exige um BSN e comprovativo de morada, embora algumas contas possam ser abertas antes apenas com o passaporte.',
            'O seguro de saúde tem de ser contratado no prazo de quatro meses após o registo e é retroativo à data de chegada.',
            'Os contratos de energia, água e internet ficam em seu nome a partir do dia em que o arrendamento começa, e mudar mais tarde implica prazos de aviso prévio.',
            'A troca de uma carta de condução estrangeira só é possível para alguns países e apenas dentro de um prazo definido após o registo.',
          ],
        },
        details: {
          title: 'As coisas que ninguém lhe conta',
          items: [
            {
              q: 'Que banco devo escolher?',
              a: 'Depende menos do banco do que daquilo que precisa dele. Planos de crédito à habitação, banca para empresas, uma entidade patronal que paga do estrangeiro e família noutra moeda apontam todos para respostas diferentes. Abrimos a conta consigo e garantimos que o iDEAL, o método de pagamento de que metade do país depende, funciona desde o primeiro dia.',
            },
            {
              q: 'Posso usar a minha carta de condução estrangeira?',
              a: 'As cartas da UE e do EEE mantêm-se válidas. As cartas de vários outros países, incluindo alguns estados dos EUA, podem ser trocadas sem novo exame, mas apenas dentro de um prazo limitado após o registo e, em certos casos, só se beneficiar do regime dos 30%. Se falhar esse prazo, terá de fazer o exame neerlandês completo. Verificamos a sua situação desde cedo porque este prazo não perdoa.',
            },
            {
              q: 'Como consigo médico, dentista e farmácia?',
              a: 'Inscreve-se num consultório de médico de família perto da sua morada, e é esse consultório que lhe atribui a farmácia. Ambos enchem, por isso ambos se tratam nas suas primeiras duas semanas. Os dentistas aceitam pacientes particulares diretamente e são mais fáceis, embora os bons no centro também tenham listas.',
            },
            {
              q: 'E a administração fiscal no primeiro ano?',
              a: 'Vale quase sempre a pena entregar a declaração do seu primeiro ano fiscal neerlandês, mesmo quando pensa que não deve nada, porque as declarações do ano de chegada dão frequentemente lugar a reembolso. Somos consultores de relocalização e não consultores fiscais, por isso apresentamo-lo a um consultor que trata de declarações de expatriados, em vez de adivinharmos por si.',
            },
          ],
        },
        faq: {
          title: 'Perguntas frequentes',
          items: [
            {
              q: 'Posso abrir uma conta bancária neerlandesa antes de ter BSN?',
              a: 'Alguns bancos permitem-no e aceitam que forneça o BSN mais tarde; as políticas mudam com frequência. Sabemos como está a situação neste momento e encaminhamo-lo pela via mais rápida, para que o seu salário tenha onde entrar.',
            },
            {
              q: 'O que é o DigiD e preciso mesmo dele?',
              a: 'O DigiD é a sua identidade digital junto do Estado neerlandês: impostos, saúde, subsídios e serviços municipais usam-no todos. Vai precisar dele constantemente, e criamo-lo consigo desde cedo.',
            },
            {
              q: 'Chegámos há meses mas nunca nos instalámos verdadeiramente. Isto ainda é para nós?',
              a: 'Sem dúvida, e é mais comum do que pensa. Verificamos o que falta ou ficou mal configurado, corrigimos e concluímos a chegada para a qual nunca teve tempo.',
            },
          ],
        },
        cta: {
          title: 'Sinta-se em casa mais depressa',
          text: 'Dê-nos algumas semanas e os Países Baixos deixam de ser um país estrangeiro para passarem a ser onde vive.',
          label: 'Ajudem-me a instalar-me',
        },
        form: 'relocation',
        image: '/images/relocation-settling.jpg?v=20260728',
        imageAlt: 'Um recém-chegado a orientar-se no seu novo bairro neerlandês',
        image2: '/images/couple-moving-in.jpg?v=20260731',
        image2Alt: 'Casal com as chaves do seu novo apartamento nos Países Baixos',
      },
      {
        slug: 'airport-pickup-for-expats-netherlands',
        menuLabel: 'Recolha no aeroporto',
        title: 'Recolha no aeroporto para expatriados nos Países Baixos',
        metaTitle: 'Recolha no aeroporto, Países Baixos | E & I Expat Services',
        metaDescription: 'Um acolhimento caloroso em Schiphol ou no aeroporto de Rotterdam: recolha pessoal, transfer até à sua nova casa e um briefing do primeiro dia para que a relocalização comece com calma.',
        eyebrow: 'Chegada',
        intro: [
          'Cada relocalização tem um momento zero: as portas da sala de chegadas abrem-se e a sua nova vida começa com jet lag, bagagem e um país que ainda não conhece. A forma como corre essa primeira hora dá cor a toda a mudança. Não deveria incluir arrastar malas por transbordos de comboio nem explicar uma morada a um taxista à meia-noite.',
          'Esperamo-lo na sala de chegadas, com placa de nome e tudo, e levamo-lo diretamente à porta da sua nova casa. Pelo caminho recebe o essencial do primeiro dia: como funciona a casa, onde fazer as compras de amanhã, o que acontece esta semana. E porque os voos aterram à hora a que aterram, a nossa linha de WhatsApp acompanha-o a toda a hora desde o momento em que levanta voo.',
        ],
        cardText: 'Recebido nas chegadas, levado a casa e preparado para a sua primeira manhã neerlandesa.',
        forWho: {
          title: 'Para quem é',
          items: [
            'Famílias que chegam com crianças, bagagem e sem energia para logística',
            'Quem chega pela primeira vez e quer uma cara conhecida na sala de chegadas',
            'Profissionais que aterram tarde da noite ou em voos de fim de semana',
            'Entidades patronais que querem receber devidamente o seu novo colaborador',
          ],
        },
        included: {
          title: 'O que está incluído',
          blocks: [
            {
              title: 'Acompanhamento do voo',
              text: 'Monitorizamos o seu voo, para que um atraso ou uma aterragem antecipada não alterem nada no seu acolhimento.',
            },
            {
              title: 'Acolhimento pessoal',
              text: 'Um contacto conhecido à sua espera na sala de chegadas de Schiphol, Rotterdam The Hague ou Eindhoven, pronto a ajudar com a bagagem e as crianças.',
            },
            {
              title: 'Transfer direto para casa',
              text: 'Uma viagem confortável até à sua nova casa ou ao apartamento temporário, com cadeirinhas para crianças quando necessário.',
            },
            {
              title: 'Briefing do primeiro dia',
              text: 'Chaves, aquecimento, wifi e eletrodomésticos explicados, um plano para as primeiras compras e uma ideia clara dos compromissos da sua primeira semana.',
            },
          ],
        },
        process: {
          title: 'Como funciona',
          steps: [
            {
              title: 'Indique o seu voo',
              text: 'Envie os dados do voo e a morada; confirmamos o plano e mantemo-nos contactáveis enquanto viaja.',
            },
            {
              title: 'Aterrar e ser recebido',
              text: 'Sai das chegadas e a sua relocalização já está ali à sua espera.',
            },
            {
              title: 'Chegar a casa',
              text: 'Vai dormir numa casa a funcionar, sabendo exatamente como será o dia seguinte.',
            },
          ],
        },
        fees: {
          title: 'Honorários para a recolha no aeroporto',
          kind: 'fixed',
          amount: 'A partir de €395',
          includes: [
            'Um motorista profissional e uma viatura executiva à medida do seu grupo e da bagagem',
            'Voo monitorizado para que os atrasos não lhe custem a reserva',
            'Acolhimento dentro do terminal, não uma mensagem do parque de estacionamento',
            'Transfer direto para a sua morada, hotel ou primeiro compromisso',
          ],
        },
        conditions: {
          title: 'Como funciona o transfer',
          intro: 'Um serviço curto, com poucas condições, todas elas para que ninguém fique numa sala de chegadas sem saber o que fazer.',
          items: [
            'Cobrimos Schiphol, Rotterdam The Hague e Eindhoven, e terminais privados mediante pedido.',
            'Envie o número do voo e nós acompanhamo-lo, para que um atraso altere o nosso horário e não o seu acolhimento.',
            'O acolhimento é dentro do terminal, nas chegadas, e não à porta do aeroporto.',
            'As viaturas são escolhidas em função da dimensão do grupo e da bagagem, incluindo cadeirinhas para crianças quando necessário.',
            'Os transfers fazem-se para qualquer morada na região de Rotterdam e do porto, e para mais longe mediante acordo.',
            'As reservas são confirmadas com pelo menos vinte e quatro horas de antecedência sempre que possível, embora aceitemos alterações de última hora.',
          ],
        },
        details: {
          title: 'A primeira hora neerlandesa',
          items: [
            {
              q: 'O que acontece entre o aeroporto e a porta de casa?',
              a: 'É recebido com o seu nome, tratamos da bagagem e a viagem serve para o briefing que interessa: como funcionam as chaves, onde fica o supermercado mais próximo, o que fazer quanto ao lixo, que aplicação gere os transportes públicos e o que acontece amanhã. A maioria dos clientes considera essa meia hora mais valiosa do que o próprio transfer.',
            },
            {
              q: 'Podem recolher uma família que chega em separado?',
              a: 'Sim. As chegadas repartidas são comuns quando o cônjuge vem mais tarde ou as crianças terminam o período escolar. Coordenamos vários voos e, quando o intervalo é de um ou dois dias, mantemos o mesmo motorista para que haja uma cara conhecida das duas vezes.',
            },
            {
              q: 'A casa está pronta quando chegarmos?',
              a: 'Está, se tivermos sido nós a tratar dela. Como parte de um pacote de relocalização, garantimos que as chaves foram levantadas, que o aquecimento está ligado, que as camas estão utilizáveis e que há café, leite e pão na cozinha. Chegar à meia-noite a um apartamento vazio é uma memória que as pessoas guardam durante anos, e é evitável.',
            },
            {
              q: 'Também tratam das partidas?',
              a: 'Sim, e para clientes que deixam os Países Baixos combinamos isso com a vistoria final, a recuperação da caução e o cancelamento do registo, para que o último dia seja tão bem gerido como o primeiro.',
            },
          ],
        },
        faq: {
          title: 'Perguntas frequentes',
          items: [
            {
              q: 'E se o meu voo aterrar às 2 da manhã?',
              a: 'Então estamos na sala de chegadas às 2 da manhã. As chegadas não cumprem horário de expediente e nós também não; essa promessa está no centro da nossa forma de trabalhar.',
            },
            {
              q: 'Conseguem levar uma família com muita bagagem e um animal de estimação?',
              a: 'Sim. Diga-nos com antecedência quantas pessoas são, quantas malas levam e a dimensão da transportadora, e tratamos de uma viatura que leve tudo, animal incluído.',
            },
            {
              q: 'A recolha é apenas para clientes com um pacote completo de relocalização?',
              a: 'Pode ser reservada isoladamente, embora a maioria dos clientes a combine com o apoio na instalação, para que a primeira semana corra tão bem como a primeira hora. O preço para a sua situação é confirmado na conversa inicial.',
            },
          ],
        },
        cta: {
          title: 'Comece a sua nova vida acompanhado, não perdido',
          text: 'Envie-nos o número do voo e a primeira cara que vir nos Países Baixos será uma cara amiga.',
          label: 'Reservar a minha chegada',
        },
        form: 'relocation',
        image: '/images/relocation-arrival.jpg?v=20260731',
        imageAlt: 'Motorista a receber um cliente num terminal de aviação privada',
        image2: '/images/vip-welcome.jpg?v=20260731',
        image2Alt: 'Carro executivo numa avenida arborizada neerlandesa à hora dourada',
      },
      {
        slug: 'family-relocation-netherlands',
        menuLabel: 'Relocalização familiar',
        title: 'Relocalização Familiar nos Países Baixos',
        metaTitle: 'Relocalização Familiar Países Baixos | E & I Expat Services',
        metaDescription: 'Mude toda a família para os Países Baixos com um único guia pessoal: habitação, escolas, registos, saúde e uma chegada tranquila para cada membro da família.',
        eyebrow: 'Famílias',
        intro: [
          'Mudar-se sozinho é um projeto. Mudar uma família são cinco projetos a decorrer ao mesmo tempo: uma casa que sirva a todos, escolas com vagas reais, registos para cada passaporte do agregado, cuidados de saúde para o bebé e para o adolescente, e um cônjuge cuja carreira e vida social merecem mais do que uma nota de rodapé. Basta soltar um fio para toda a mudança se desfazer.',
          'Nós seguramos todos os fios. Um único guia planeia toda a mudança familiar como um calendário só, ordena as marcações para que nada bloqueie nada, e presta atenção ao lado humano: como as crianças se adaptam, como o cônjuge acompanhante constrói uma vida, como a casa começa a parecer casa. A nossa reputação nesta área foi construída no mundo das embaixadas, onde as colocações familiares são a norma e o fracasso não é uma opção.',
        ],
        cardText: 'Um calendário, um guia e uma chegada tranquila para cada membro da família.',
        forWho: {
          title: 'Para quem é',
          items: [
            'Famílias que se mudam para os Países Baixos por um novo cargo ou colocação',
            'Pais que conciliam prazos escolares com prazos de habitação',
            'Agregados com nacionalidades diversas e documentação diversa',
            'Cônjuges acompanhantes que querem um plano de chegada próprio, e não um plano deixado para o fim',
          ],
        },
        included: {
          title: 'O que está incluído',
          blocks: [
            {
              title: 'Um plano-mestre para a família',
              text: 'Habitação, escolas, registos, seguros e chegada organizados num calendário único, com as dependências tratadas pela ordem certa.',
            },
            {
              title: 'Casa e escola em paralelo',
              text: 'Conduzimos a procura de habitação e a procura de escola como uma só decisão, para que nunca ganhe a casa e perca a vaga na escola.',
            },
            {
              title: 'Registos para todos',
              text: 'BSN e registo municipal para cada membro da família, com as certidões das crianças e as traduções preparadas com antecedência.',
            },
            {
              title: 'Cuidados de saúde para o agregado',
              text: 'Seguro para a família, um médico de família que aceite novos utentes, e cuidados pediátricos e dentários identificados antes de alguém precisar deles.',
            },
            {
              title: 'Integração do cônjuge e da família',
              text: 'Orientação no bairro, clubes, creches, opções de línguas e as apresentações que transformam uma cidade nova numa comunidade.',
            },
          ],
        },
        process: {
          title: 'Como funciona',
          steps: [
            {
              title: 'Conversa inicial com a família',
              text: 'Encontramo-nos com toda a família, por videochamada ou presencialmente, e reunimos as necessidades de cada membro num só plano.',
            },
            {
              title: 'Preparar e garantir',
              text: 'Antes de embarcar, a frente da casa, a frente da escola e a frente da documentação já estão em andamento.',
            },
            {
              title: 'Chegar em conjunto',
              text: 'A chegada, os registos e o início das aulas acontecem no prazo previsto, connosco ao seu lado em cada passo.',
            },
            {
              title: 'Instalar e acompanhar',
              text: 'Mantemo-nos presentes ao longo dos primeiros meses, porque as perguntas não param à porta de casa.',
            },
          ],
        },
        fees: {
          title: 'Quanto custa uma relocalização familiar',
          kind: 'tailored',
          amount: 'Proposta à medida',
          amountNote: 'Não há duas mudanças familiares iguais: o número de filhos, as escolas, a via de visto e o calendário alteram todo o trabalho. Após uma consulta inicial, recebe uma proposta personalizada que abrange toda a chegada.',
          includes: [
            'Um plano que abrange cada membro da família, ordenado pela sequência certa',
            'Procura de habitação construída em torno das escolas e do trajeto diário, não apenas do código postal',
            'Procura de escola, inscrição e apresentações',
            'Todos os registos de todos os membros da família, marcados e acompanhados',
          ],
        },
        conditions: {
          title: 'Como se sequencia uma mudança familiar',
          intro: 'Uma mudança familiar tem mais dependências do que qualquer outra. Estas são as que definem o calendário.',
          items: [
            'Normalmente é a disponibilidade de vagas nas escolas que determina a data da mudança, e não a data de início do trabalho.',
            'Cada membro da família precisa da sua própria marcação de registo e dos seus próprios documentos legalizados, incluindo as crianças.',
            'O titular principal da autorização tem de cumprir o requisito de rendimento para a família acompanhante, atualmente 2.523,96 euros brutos por mês, incluindo o subsídio de férias.',
            'Quando um dos progenitores não se muda, é necessário o consentimento por escrito para que a criança possa mudar-se.',
            'O seguro de saúde é obrigatório para cada membro da família, embora as crianças fiquem cobertas gratuitamente na apólice de um dos progenitores.',
            'O cônjuge que acompanha um trabalhador altamente qualificado tem acesso livre ao mercado de trabalho neerlandês e não necessita de uma autorização de trabalho separada.',
          ],
        },
        details: {
          title: 'O que as famílias nos perguntam',
          items: [
            {
              q: 'Por que ordem devemos fazer as coisas?',
              a: 'Escolas, depois habitação na zona que funciona, depois autorizações e registo, depois a camada prática. Inverter os dois primeiros passos é o erro familiar mais comum e mais caro, porque uma casa bonita a quarenta minutos da única escola com vagas deixa toda a gente infeliz em novembro.',
            },
            {
              q: 'O meu cônjuge abdica de uma carreira para vir. O que é realista?',
              a: 'O mercado de trabalho neerlandês está genuinamente aberto aos cônjuges acompanhantes, sobretudo nos setores de língua inglesa em torno de Rotterdam e de Haia, e não é necessária qualquer autorização de trabalho. O que mais ajuda é um CV em formato neerlandês, compreender como funciona de facto o recrutamento local, e começar antes da mudança em vez de depois. Fazemos as apresentações que estiverem ao nosso alcance.',
            },
            {
              q: 'Como se adaptam as crianças?',
              a: 'Melhor do que os pais esperam, e mais devagar do que os pais desejam. O sistema neerlandês é invulgarmente acolhedor com as crianças recém-chegadas e a nieuwkomersklas funciona. A parte mais difícil costuma ser entre o terceiro e o sexto mês, quando a novidade passa, e ajuda enormemente ter planeado um desporto, música ou um clube antes de precisar disso.',
            },
            {
              q: 'É mesmo possível fazer tudo em paralelo?',
              a: 'Sim, e tem de ser assim. As autorizações, as candidaturas às escolas, a habitação, o registo e o seguro têm cada um o seu tempo de espera, por isso tratamos de todos em simultâneo num único calendário familiar, em vez de um a seguir ao outro. É essa a diferença entre uma mudança que demora dez semanas e uma que demora seis meses.',
            },
          ],
        },
        faq: {
          title: 'Perguntas frequentes',
          items: [
            {
              q: 'Com quanta antecedência deve uma família começar a planear?',
              a: 'Três a seis meses antes da mudança é confortável, sobretudo porque as vagas nas escolas e os arrendamentos com espaço para famílias são o mais escasso. Com menos tempo também é viável; significa apenas que definimos prioridades de forma mais rigorosa desde o primeiro dia.',
            },
            {
              q: 'Também apoiam a parte dos vistos numa mudança familiar?',
              a: 'Sim. O reagrupamento familiar e os vistos de cônjuge são tratados através dos nossos serviços de imigração, e coordenar as duas frentes sob o mesmo teto é precisamente o que mantém uma mudança familiar coerente.',
            },
            {
              q: 'E os nossos filhos que ainda não têm idade escolar?',
              a: 'Nos Países Baixos, as creches têm frequentemente listas de espera mais longas do que as escolas, por isso tratamos o acolhimento de crianças com a mesma urgência: listas restritas, candidaturas e uma explicação do subsídio de creche a que poderá ter direito.',
            },
          ],
        },
        cta: {
          title: 'Mude toda a família com uma única chamada',
          text: 'Diga-nos quem vem e quando, e construímos o plano que deixa toda a gente instalada, com escola e a sorrir.',
          label: 'Planear a nossa mudança familiar',
        },
        form: 'relocation',
        image: '/images/family-relocation.jpg?v=20260731',
        imageAlt: 'Família a andar de bicicleta junto a um canal neerlandês na hora dourada',
        image2: '/images/family-reunification.jpg?v=20260731',
        image2Alt: 'Família reunida numa casa neerlandesa luminosa',
      },
      {
        slug: 'relocation-services-rotterdam',
        menuLabel: 'Relocalização Rotterdam',
        title: 'Serviços de Relocalização em Rotterdam',
        metaTitle: 'Serviços de Relocalização Rotterdam | E & I Expat Services',
        metaDescription: 'Apoio completo de relocalização em Rotterdam por um especialista local: habitação, registos, escolas e instalação, na cidade e na região portuária.',
        eyebrow: 'Rotterdam',
        intro: [
          'Rotterdam recompensa quem chega com um local do seu lado. É uma cidade de trabalho, direta e rápida, com um mercado de habitação que apertou fortemente e uma economia portuária que atrai profissionais de todos os continentes. Aqui, as listas de verificação nacionais de relocalização levam-no apenas até certo ponto; o que conta é conhecer os balcões, os bairros e os ritmos desta cidade.',
          'Este é o nosso território. Somos o especialista de Rotterdam e do seu corredor industrial, do centro da cidade até ao Europoort e à Maasvlakte, e tudo o que tratamos, habitação, registo na gemeente de Rotterdam, escolas, saúde, assenta nessa profundidade local. Recebe o serviço completo de relocalização, afinado com precisão para esta cidade.',
        ],
        cardText: 'O serviço completo de relocalização, afinado para Rotterdam por quem a vive.',
        forWho: {
          title: 'Para quem é',
          items: [
            'Profissionais que começam em empresas de Rotterdam, no porto ou no polo industrial',
            'Famílias que se mudam para Rotterdam e para as localidades vizinhas',
            'Contratações internacionais cujos empregadores querem uma chegada rápida e sem sobressaltos',
            'Expatriados já nos Países Baixos que se mudam para Rotterdam',
          ],
        },
        included: {
          title: 'O que está incluído',
          blocks: [
            {
              title: 'Apoio à habitação em Rotterdam',
              text: 'Uma procura assente no conhecimento ao nível do bairro e em relações com agentes locais, com visitas e análise do contrato incluídas.',
            },
            {
              title: 'Registos tratados localmente',
              text: 'BSN e registo municipal através dos balcões de Rotterdam com que trabalhamos semanalmente, preparados para que uma visita chegue.',
            },
            {
              title: 'Escolas e creches na região',
              text: 'Opções de escolas internacionais e neerlandesas em Rotterdam e nos arredores, ajustadas à sua casa e ao seu trajeto diário.',
            },
            {
              title: 'Instalação na cidade',
              text: 'Banco, transportes, saúde e uma orientação personalizada pelo seu bairro, dos mercados até ao Maas.',
            },
          ],
        },
        process: {
          title: 'Como funciona',
          steps: [
            {
              title: 'Conversa inicial em Rotterdam',
              text: 'Cruzamos o seu local de trabalho, a sua família e o seu calendário com a cidade que conhecemos rua a rua.',
            },
            {
              title: 'Tudo em movimento',
              text: 'Habitação, registos e escolas avançam em paralelo, coordenados por uma só pessoa.',
            },
            {
              title: 'Chegado e a viver',
              text: 'Fica registado, com casa e orientado, e com um número local para contactar sempre que surgir uma dúvida.',
            },
          ],
        },
        fees: {
          title: 'Quanto custa uma relocalização em Rotterdam',
          kind: 'tailored',
          amount: 'Proposta à medida',
          amountNote: 'Serviços concebidos à medida das suas necessidades pessoais. Após uma consulta inicial, receberá uma proposta personalizada com base nos seus objetivos, na sua situação familiar e no nível de apoio que preferir.',
          includes: [
            'Um plano único que abrange imigração, habitação e todos os registos',
            'Um consultor que conhece a cidade e acompanha o seu processo do início ao fim',
            'Marcações agendadas, preparadas e acompanhadas consigo',
            'Apoio que continua depois de as caixas estarem desfeitas',
          ],
        },
        conditions: {
          title: 'O que cobrimos localmente',
          intro: 'Estamos sediados nesta região e trabalhamos nela, o que significa que o nosso aconselhamento é específico e não genérico a nível nacional.',
          items: [
            'Rotterdam e os municípios vizinhos, incluindo Schiedam, Capelle aan den IJssel, Barendrecht, Spijkenisse e o corredor do Europoort.',
            'As marcações de registo em Rotterdam fazem-se com antecedência, com tempos de espera de alguns dias a várias semanas, consoante a época.',
            'A cidade tem zonas de estacionamento com licenças por agregado, e as listas de espera no centro prolongam-se por meses.',
            'As escolas internacionais da região concentram-se em Kralingen e no sul da cidade, e as vagas são limitadas.',
            'As rendas do setor livre começam à volta de 1.200 euros para um T1 e sobem acentuadamente na construção nova virada para o rio.',
            'Os processos fora da nossa região são reencaminhados em vez de aceites. Preferimos encaminhá-lo para a empresa certa a sermos a empresa errada.',
          ],
        },
        details: {
          title: 'Viver em Rotterdam',
          items: [
            {
              q: 'Porquê Rotterdam em vez de Amsterdam?',
              a: 'Espaço, custo e franqueza. Tem materialmente mais casa pelo mesmo dinheiro, um trajeto mais curto para o porto e para o polo industrial, uma população internacional profissional em vez de turística, e uma cidade que está a ser reconstruída em vez de preservada. Amsterdam fica a quarenta minutos quando lhe apetecer.',
            },
            {
              q: 'O inglês é suficiente aqui?',
              a: 'Para o dia a dia e para a maioria dos locais de trabalho, sim. Para a correspondência da câmara municipal, os litígios de arrendamento, as letras pequenas dos seguros e a administração escolar, não, e é precisamente essa lacuna que existimos para colmatar. Aprender neerlandês continua a valer a pena, e indicamos-lhe cursos adequados a adultos que trabalham.',
            },
            {
              q: 'Como é que as pessoas se deslocam?',
              a: 'Bicicleta em primeiro lugar, metro em segundo, carro em último. O metro chega à maior parte da cidade e a grande parte da região, o OV-chipkaart ou o seu cartão bancário cobrem tudo, e o carro só é realmente útil se trabalhar nos terminais ou tiver crianças pequenas a levar em dois sentidos.',
            },
            {
              q: 'Como é a comunidade internacional?',
              a: 'Grande, ativa e espalhada pela região em vez de concentrada num único bairro. Entre o polo portuário, a Universidade Erasmus, o centro médico e o setor criativo, a maioria dos recém-chegados encontra o seu grupo mais depressa do que espera. Fazemos apresentações sempre que podemos, o que para muitos clientes conta mais do que qualquer passo administrativo.',
            },
          ],
        },
        faq: {
          title: 'Perguntas frequentes',
          items: [
            {
              q: 'Trabalham apenas em Rotterdam?',
              a: 'Cobrimos toda a região: Schiedam, Vlaardingen, Capelle, Barendrecht, a Hoeksche Waard e o corredor portuário até Hoek van Holland. Muitas vezes a melhor casa para o seu orçamento fica na localidade ao lado, e dizemos-lho.',
            },
            {
              q: 'A minha entidade empregadora fica na zona portuária. Onde devo viver?',
              a: 'Depende do seu regime de turnos e da sua tolerância à A15. Muitos profissionais do porto vivem no centro e fazem o percurso contra o sentido do trânsito; outros preferem Voorne-Putten ou Westland pela proximidade. Simulamos o seu trajeto real antes de escolher.',
            },
            {
              q: 'Podem trabalhar diretamente com a minha entidade empregadora ou com o departamento de recursos humanos?',
              a: 'Com todo o gosto. Coordenamos regularmente com os recursos humanos as datas de início, os contratos e a documentação, e podemos ser o ponto de contacto único para que o colaborador simplesmente chegue e tudo funcione.',
            },
          ],
        },
        cta: {
          title: 'Chegue a Rotterdam como um local',
          text: 'Uma conversa com quem conhece esta cidade, e a sua mudança deixa de ser um quebra-cabeças.',
          label: 'Começar a minha mudança para Rotterdam',
        },
        form: 'relocation',
        image: '/images/rotterdam.jpg?v=20260728',
        imageAlt: 'Centro de Rotterdam com arquitetura moderna ao longo do Maas',
        image2: '/images/rotterdam-evening.jpg',
        image2Alt: 'Skyline de Rotterdam ao anoitecer',
      },
    ],
    crossLinks: [
      {
        label: 'Relocalização em Europoort',
        path: '/industrial-expat-services/europoort-relocation-services-netherlands',
        text: 'Vai mudar-se por motivos de trabalho para a zona industrial de Europoort? Consulte o nosso serviço dedicado à região portuária.',
      },
    ],
    cta: {
      title: 'Um guia para toda a sua relocalização',
      text: 'Do seu BSN à escola dos seus filhos, uma pessoa que sabe o seu nome trata de tudo e acompanha-o em cada passo.',
      label: 'Iniciar a minha relocalização',
    },
  };
