/* GENERATED by scripts/i18n-strings.mjs. Do not hand-edit.
   pt/vip.ts is a 1:1 structural mirror of en/vip.ts; only leaf strings
   differ. To change structure, change English and re-run the build. */
import type { VipContent } from '../types';

export const vip: VipContent = {
    title: 'Serviços VIP de relocalização',
    metaTitle: 'Pacotes VIP de relocalização e imigração nos Países Baixos | E & I',
    metaDescription: 'Pacotes VIP de relocalização para casais, famílias e empresas que se mudam para os Países Baixos. Imigração, habitação, registos e instalação, orquestrados por uma só pessoa. Cada pacote é orçamentado à medida das suas exigências.',
    eyebrow: 'Serviços VIP',
    intro: [
      'Artistas com calendários de digressão. Atletas entre épocas. Quadros de direção com um único fim de semana livre e fundadores sem nenhum. Os nossos pacotes VIP existem para quem tem uma agenda que não se dobra, para que sejam os Países Baixos a dobrar-se.',
      'Cada pacote é conduzido pessoalmente pela Johanna: marcações concentradas, portas abertas com antecedência e uma linha disponível 24 horas por dia atendida por quem conhece o seu processo, não por um serviço de apoio.',
    ],
    image: '/images/vip-hub.jpg?v=20260731',
    imageAlt: 'Anfitrião a receber um casal que chega de carro a um hotel junto ao canal',
    pricingNote: {
      title: 'Como é definido o preço do VIP',
      text: [
        'Serviços à medida, ajustados às suas exigências pessoais. Após uma primeira consulta, receberá uma proposta personalizada baseada nos seus objetivos, na sua situação familiar e no nível de acompanhamento que preferir.',
        'Essa proposta é um valor fixo para o âmbito acordado. Sem tarifas horárias, sem acrescentos a meio da mudança e sem custo pela consulta de que nasce.',
      ],
    },
    tailored: {
      text: 'Cada pacote é um ponto de partida, não uma ementa fixa. Na primeira consulta adaptamos o âmbito à sua situação, acrescentando o que precisa e retirando o que não precisa.',
      label: 'Falar sobre um pacote à medida',
    },
    packages: [
      {
        slug: 'couple-relocation-immigration-package-netherlands',
        name: 'Pacote VIP Casal',
        tagline: 'Duas vidas, uma chegada sem atritos.',
        metaTitle: 'Pacote de relocalização e imigração para casais nos Países Baixos | E & I',
        metaDescription: 'Pacote completo de relocalização e imigração para casais que se mudam para os Países Baixos: visto de cônjuge, habitação, BSN, seguro, conta bancária e instalação, com acompanhamento pessoal.',
        investment: 'À medida',
        intro: [
          'Mudam-se por uma carreira, por uma empresa ou um pelo outro, e nenhum dos dois tem tempo para se tornar perito em burocracia neerlandesa. O Pacote VIP Casal põe os dois processos numa só mão e ordena tudo para que vistos, casa e registos cheguem pela ordem certa.',
        ],
        included: {
          title: 'O que está incluído',
          items: [
            {
              title: 'Apoio ao visto de cônjuge',
              text: 'Avaliação, preparação e entrega da via de cônjuge, alinhada com a autorização do parceiro que trabalha.',
            },
            {
              title: 'Aconselhamento em imigração',
              text: 'Uma só estratégia para os dois processos, para que nenhum pedido fique à espera do outro.',
            },
            {
              title: 'Apoio na habitação',
              text: 'Uma seleção ajustada à vossa vida, visitas marcadas, contrato revisto antes de assinarem.',
            },
            {
              title: 'Registo BSN',
              text: 'Marcações na câmara municipal agendadas e acompanhadas em conjunto.',
            },
            {
              title: 'Aconselhamento sobre seguro de saúde',
              text: 'A apólice neerlandesa certa, escolhida e ativada a tempo.',
            },
            {
              title: 'Apoio na conta bancária',
              text: 'Uma conta neerlandesa aberta sem o habitual círculo vicioso entre morada e BSN.',
            },
            {
              title: 'Marcações na câmara municipal',
              text: 'Cada registo agendado, preparado e acompanhado.',
            },
            {
              title: 'Apoio à instalação',
              text: 'Serviços, internet, médico, dentista e as pequenas coisas que tornam uma cidade vossa.',
            },
            {
              title: 'Apoio por WhatsApp',
              text: 'Uma linha direta com a Johanna, a qualquer hora, para os dois.',
            },
          ],
        },
        forWho: {
          title: 'Pensado para',
          items: [
            'Casais em que um dos parceiros se muda por trabalho e o outro precisa de uma via de residência',
            'Casais de dupla carreira que chegam com autorizações separadas',
            'Cônjuges que se juntam a quem já trabalha nos Países Baixos',
          ],
        },
        process: {
          title: 'Como decorre',
          steps: [
            {
              title: 'Consulta',
              text: 'Uma conversa sobre a vossa situação, prazos e pontos inegociáveis. Recebem um orçamento fixo.',
            },
            {
              title: 'Preparação',
              text: 'Os dois pedidos preparados em paralelo enquanto selecionamos casas.',
            },
            {
              title: 'Semana da chegada',
              text: 'Registos, banco e seguro concluídos em poucos dias, connosco ao vosso lado.',
            },
            {
              title: 'Instalação',
              text: 'Ficamos em linha até à última caixa aberta e à última conta a funcionar.',
            },
          ],
        },
        justification: {
          title: 'Porque é que os casais o escolhem',
          text: [
            'Tratada em separado, a relocalização de um casal são dois processos de imigração, uma procura de casa num mercado que se move em dias e um mês de marcações em horário de expediente que não têm. Tratada por nós, é um plano e um punhado de assinaturas.',
          ],
        },
        faq: {
          title: 'Perguntas que os casais fazem',
          items: [
            {
              q: 'O meu cônjuge pode trabalhar nos Países Baixos?',
              a: 'Na maioria das autorizações de cônjuge sim, com livre acesso ao mercado de trabalho. Confirmamos a vossa situação exata durante a consulta.',
            },
            {
              q: 'Temos de ser casados?',
              a: 'Não. Os Países Baixos reconhecem relações duradouras nas vias para cônjuges; aconselhamos que provas tornam o processo convincente.',
            },
            {
              q: 'Com que rapidez podemos ficar ambos registados?',
              a: 'Com os documentos preparados antes da chegada, os registos principais concluem-se normalmente na primeira semana.',
            },
          ],
        },
        cta: {
          title: 'Planeiem juntos a vossa chegada',
          text: 'Digam-nos as vossas datas e dir-vos-emos exatamente o que é possível.',
          label: 'Enviar o meu pedido VIP',
        },
        image: '/images/vip-couple.jpg?v=20260728',
        imageAlt: 'Casal na varanda de uma cobertura com vista sobre Roterdão ao anoitecer',
      },
      {
        slug: 'family-relocation-immigration-services-netherlands',
        name: 'Pacote VIP Família',
        tagline: 'Toda a família, com uma aterragem suave.',
        metaTitle: 'Serviços de relocalização e imigração para famílias nos Países Baixos | E & I',
        metaDescription: 'Pacote de relocalização familiar para os Países Baixos: imigração para cada membro da família, habitação, procura de escola, saúde, registos e orientação no bairro, com acompanhamento pessoal.',
        investment: 'À medida',
        badge: 'O mais procurado',
        intro: [
          'Uma relocalização familiar não é uma versão ampliada de uma individual, é outra disciplina. Anos letivos que começam em datas fixas, uma casa que tem de servir a todos, quatro processos no IND em vez de um. Este pacote existe porque acertar nessa sequência é aquilo em que somos melhores.',
        ],
        included: {
          title: 'O que está incluído',
          items: [
            {
              title: 'Aconselhamento em imigração familiar',
              text: 'A autorização de cada membro da família preparada e entregue como um único pedido coordenado.',
            },
            {
              title: 'Apoio na habitação',
              text: 'Casas de dimensão familiar perto das escolas certas, encontradas e negociadas.',
            },
            {
              title: 'Procura de escola',
              text: 'Escolas internacionais e neerlandesas comparadas, visitas marcadas, inscrição tratada antes de as listas fecharem.',
            },
            {
              title: 'Registo BSN para a família',
              text: 'Uma só ida à câmara municipal para todo o agregado, preparada e acompanhada.',
            },
            {
              title: 'Orientação em saúde',
              text: 'Seguro para cada membro, um médico de família e um dentista que aceitem novos utentes.',
            },
            {
              title: 'Marcações na câmara municipal',
              text: 'Agendadas em torno do horário escolar e do vosso dia de trabalho.',
            },
            {
              title: 'Apoio à instalação',
              text: 'Dos serviços aos clubes desportivos, a infraestrutura da vida familiar montada.',
            },
            {
              title: 'Orientação no bairro',
              text: 'Uma apresentação guiada à vossa zona: percursos, parques infantis, supermercados, vida ao fim de semana.',
            },
            {
              title: 'Apoio por WhatsApp',
              text: 'Uma linha para ambos os pais, atendida a qualquer hora.',
            },
          ],
        },
        forWho: {
          title: 'Pensado para',
          items: [
            'Famílias que se mudam por uma colocação em Roterdão ou na região portuária',
            'Pais que precisam de resolver as escolas antes de tudo o resto',
            'Agregados que chegam por reagrupamento familiar a par de uma autorização de trabalho',
          ],
        },
        process: {
          title: 'Como decorre',
          steps: [
            {
              title: 'Consulta',
              text: 'Mapeamos a família: idades, escolas, vias de visto, datas. Recebem um único orçamento fixo.',
            },
            {
              title: 'Primeiro as escolas',
              text: 'A inscrição arranca de imediato, porque são as vagas escolares que fixam os prazos de tudo o resto.',
            },
            {
              title: 'Casa e autorizações',
              text: 'A procura de casa e os pedidos de imigração correm em paralelo.',
            },
            {
              title: 'Chegada',
              text: 'Registos feitos numa só visita, orientação vivida em família, e nós continuamos contactáveis.',
            },
          ],
        },
        justification: {
          title: 'Porque é que as famílias o escolhem',
          text: [
            'O custo de um pacote familiar mede-se contra outro número: o custo de um ano letivo perdido, de um arrendamento perdido para quem foi mais rápido, ou de um pai que passa os primeiros três meses em filas em vez de estar no trabalho e em casa. As famílias dizem-nos que o pacote se pagou nas primeiras duas semanas.',
          ],
        },
        faq: {
          title: 'Perguntas que as famílias fazem',
          items: [
            {
              q: 'Conseguem colocar os nossos filhos numa escola internacional?',
              a: 'Não conseguimos criar vagas que não existem, mas sabemos que escolas têm lugar, como funcionam realmente as suas listas e como apresentar uma candidatura que avance depressa.',
            },
            {
              q: 'Os nossos filhos precisam de autorização própria?',
              a: 'Sim, cada filho precisa de uma autorização de residência. Preparamo-las juntamente com a vossa, para que a família seja aprovada como um todo.',
            },
            {
              q: 'Quanto tempo até a família se sentir instalada?',
              a: 'A papelada demora dias, uma vez preparada. A sensação demora uma estação, e é exatamente esse período que o nosso apoio à instalação cobre.',
            },
          ],
        },
        cta: {
          title: 'Ofereçam à vossa família uma aterragem suave',
          text: 'Falem-nos do vosso agregado e das vossas datas. Desenharemos a chegada em torno do ano letivo.',
          label: 'Enviar o meu pedido VIP',
        },
        image: '/images/vip-family.jpg?v=20260731',
        imageAlt: 'Família a chegar a uma moradia neerlandesa na luz do fim da tarde',
      },
      {
        slug: 'business-relocation-immigration-services-netherlands',
        name: 'Pacote VIP Empresa',
        tagline: 'Fundar, registar, viver. Por esta ordem, depressa.',
        metaTitle: 'Serviços de relocalização e imigração para empresas nos Países Baixos | E & I',
        metaDescription: 'Pacote de relocalização empresarial para os Países Baixos: visto startup ou DAFT, constituição da sociedade e registo na KvK, habitação e instalação para fundadores e quadros, num só plano.',
        investment: 'À medida',
        intro: [
          'Fundadores e quadros de direção que se mudam para os Países Baixos enfrentam duas burocracias ao mesmo tempo: uma para a empresa, outra para a vida à sua volta. Este pacote conduz as duas vias em simultâneo, para que o negócio já esteja a operar enquanto quem o fundou já vive bem, em vez de andar entre um hotel e uma fila de balcão.',
        ],
        included: {
          title: 'O que está incluído',
          items: [
            {
              title: 'Aconselhamento sobre o visto startup',
              text: 'Escolha do facilitador, alinhamento do plano de negócios e entrega do pedido na via startup neerlandesa.',
            },
            {
              title: 'Apoio ao visto DAFT',
              text: 'Para cidadãos dos EUA: a via do Dutch American Friendship Treaty, preparada de ponta a ponta.',
            },
            {
              title: 'Constituição da sociedade',
              text: 'Forma jurídica, escritura e as decisões práticas pelo meio.',
            },
            {
              title: 'Apoio ao registo na KvK',
              text: 'Registo na Câmara de Comércio concluído corretamente logo à primeira.',
            },
            {
              title: 'Apoio na habitação',
              text: 'Uma casa ou um pied-à-terre ajustado à sua base de operações.',
            },
            {
              title: 'Relocalização do empresário',
              text: 'O lado pessoal da mudança ordenado em torno dos prazos da empresa.',
            },
            {
              title: 'Registo BSN',
              text: 'Registo na câmara municipal marcado e acompanhado.',
            },
            {
              title: 'Apoio à instalação',
              text: 'Banco, seguros e a infraestrutura do dia a dia para si e para a sua família.',
            },
            {
              title: 'Aconselhamento no arranque do negócio',
              text: 'Apresentações a contabilistas, notários e à rede local de que vai realmente precisar.',
            },
          ],
        },
        forWho: {
          title: 'Pensado para',
          items: [
            'Fundadores que entram com o visto startup ou pelo tratado DAFT',
            'Quadros de direção que se mudam enquanto constituem uma sociedade neerlandesa',
            'Empresas que deslocam em conjunto pessoas-chave e as suas famílias',
          ],
        },
        process: {
          title: 'Como decorre',
          steps: [
            {
              title: 'Consulta',
              text: 'Planos da empresa e situação pessoal na mesma mesa. Recebe um orçamento fixo e uma sequência.',
            },
            {
              title: 'Duas vias',
              text: 'Visto e constituição da sociedade avançam em paralelo, desbloqueando-se mutuamente no momento certo.',
            },
            {
              title: 'Aterragem',
              text: 'KvK, BSN, banco e casa concluídos numa semana de chegada comprimida.',
            },
            {
              title: 'Operação',
              text: 'O senhor gere a empresa. Nós continuamos a ser quem resolve o que aparecer.',
            },
          ],
        },
        justification: {
          title: 'Porque é que os fundadores o escolhem',
          text: [
            'Mais ninguém no mercado junta o visto, a constituição, a habitação e a família num só trabalho. Montar o mesmo resultado com quatro fornecedores diferentes custa mais, demora mais e deixa-o a si como gestor de projeto. Aqui, o gestor de projeto está incluído.',
          ],
        },
        faq: {
          title: 'Perguntas que os fundadores fazem',
          items: [
            {
              q: 'Visto startup ou DAFT, qual me serve?',
              a: 'O DAFT é exclusivo de cidadãos dos EUA e exige um investimento modesto; o visto startup exige um facilitador reconhecido. Avaliamos ambos face aos seus planos logo na primeira conversa.',
            },
            {
              q: 'Posso registar uma empresa antes de ter morada?',
              a: 'A ordem entre morada, BSN e KvK é exatamente o tipo de armadilha de sequência para que existimos. Organizamos os passos de modo a que nada fique bloqueado.',
            },
            {
              q: 'Trabalham com equipas que se mudam?',
              a: 'Sim. Para relocalizações empresariais de vários colaboradores e das suas famílias construímos um programa conjunto; pergunte-nos pelas condições para empresas.',
            },
          ],
        },
        cta: {
          title: 'Mude o fundador, não apenas a empresa',
          text: 'Conte-nos os seus planos e a sua janela temporal. Responderemos com uma sequência e um orçamento fixo.',
          label: 'Enviar o meu pedido VIP',
        },
        image: '/images/vip-business.jpg?v=20260731',
        imageAlt: 'Executivo a trabalhar no banco traseiro de um carro com motorista',
      },
      {
        slug: 'vip-relocation-concierge',
        name: 'VIP Relocation Concierge',
        tagline: 'Para vidas que não param para se mudar.',
        metaTitle: 'VIP Relocation Concierge nos Países Baixos | E & I',
        metaDescription: 'Relocalização concierge completa nos Países Baixos para artistas, atletas e quadros de direção: uma única visita preparada, todas as marcações alinhadas, dias com motorista e apoio pessoal 24 horas por dia.',
        investment: 'À medida',
        intro: [
          'Um artista entre datas de digressão. Um atleta contratado a meio da época. Um quadro cuja agenda já está planeada para o ano seguinte. O nível concierge comprime uma relocalização no tempo que realmente tem, por vezes um único fim de semana, e trata de tudo o que for possível tratar sem si.',
          'O senhor diz-nos as datas em que pode estar nos Países Baixos. Nós coreografamos o resto à volta delas.',
        ],
        included: {
          title: 'O que está incluído',
          items: [
            {
              title: 'Uma visita preparada',
              text: 'Todas as marcações que a lei exige com a sua presença, alinhadas numa só deslocação: IND, câmara municipal, banco, visitas a imóveis.',
            },
            {
              title: 'Casa antes de aterrar',
              text: 'Uma seleção criteriosa, visitada primeiro em vídeo, para que a sua visita confirme em vez de procurar.',
            },
            {
              title: 'Dias com motorista',
              text: 'Recolha no aeroporto e motorista durante toda a visita.',
            },
            {
              title: 'Imigração, tratada em silêncio',
              text: 'Pedidos preparados, entregues e acompanhados enquanto está noutro lugar.',
            },
            {
              title: 'Família incluída',
              text: 'Cônjuge, filhos, escolas e organização de pessoal, cobertos onde for preciso.',
            },
            {
              title: 'Discrição',
              text: 'Uma forma de trabalhar herdada do mundo das embaixadas. A sua mudança continua a ser assunto seu.',
            },
            {
              title: 'Linha 24 horas',
              text: 'A Johanna, diretamente, em qualquer fuso horário em que esteja.',
            },
          ],
        },
        forWho: {
          title: 'Pensado para',
          items: [
            'Artistas e intérpretes que se mudam entre digressões e produções',
            'Atletas e equipas técnicas que mudam a meio da época',
            'Quadros de direção e figuras públicas que precisam de rapidez e discrição em igual medida',
          ],
        },
        process: {
          title: 'Como decorre',
          steps: [
            {
              title: 'Uma conversa reservada',
              text: 'A sua situação, os seus constrangimentos, as suas datas. Desenhamos a visita e orçamentamo-la a preço fixo.',
            },
            {
              title: 'Tudo preparado',
              text: 'Documentos, entregas, seleções e marcações organizados enquanto continua a sua vida.',
            },
            {
              title: 'A visita',
              text: 'Uma estadia coreografada, normalmente de dois a três dias, com motorista e com a Johanna sempre presentes.',
            },
            {
              title: 'Depois da visita',
              text: 'Concluímos o resto, recebemos as chaves onde for permitido e continuamos disponíveis enquanto chega para ficar.',
            },
          ],
        },
        justification: {
          title: 'O que está realmente a comprar',
          text: [
            'Este nível é orçamentado sobre uma verdade simples: o seu tempo é o recurso mais escasso da mudança. Cada hora que retiramos do seu lado da mesa é uma hora no palco, no campo ou na sala do conselho. É essa a troca, e é em torno dela que a proposta é construída.',
          ],
        },
        faq: {
          title: 'Perguntas que os clientes fazem',
          items: [
            {
              q: 'É mesmo possível tratar de tudo numa só visita?',
              a: 'Quase tudo. A lei neerlandesa exige a sua presença física num pequeno conjunto de marcações; concentramos exatamente essas na sua visita e absorvemos o resto.',
            },
            {
              q: 'Qual é o grau de discrição do processo?',
              a: 'Total. Sem listas de clientes, sem estudos de caso com nomes e, onde for útil, trabalhamos através do seu management ou do seu family office.',
            },
            {
              q: 'E se as minhas datas mudarem?',
              a: 'Os programas construídos em torno de artistas e atletas nascem para ser reconstruídos. Refazemos a coreografia e mantemos os processos em andamento.',
            },
          ],
        },
        cta: {
          title: 'Diga-nos a sua janela',
          text: 'Dê-nos as datas que tem. Mostrar-lhe-emos o que pode acontecer dentro delas.',
          label: 'Enviar um pedido reservado',
        },
        image: '/images/vip-concierge.jpg?v=20260728',
        imageAlt: 'Jato privado com carro à espera ao amanhecer',
      },
    ],
    cta: {
      title: 'Não sabe que pacote lhe serve?',
      text: 'Basta uma conversa para desenhar o certo. Todos os pacotes começam no mesmo passo, uma consulta pessoal.',
      label: 'Marque uma consulta',
    },
  };
