/**
 * Translation harness for the language trees.
 *
 * Every language is a strict 1:1 structural mirror of English (a hard client
 * requirement), which means a language file is fully described by English plus a
 * flat map of translated leaf strings. This script is the two directions of that:
 *
 *   extract  dump every translatable leaf of a language as { "json.path": "text" }
 *   build    write src/content/<lang>/*.ts from English plus such a map
 *
 * Keys listed in KEEP are identity, not prose: slugs, image paths, form kinds and
 * route paths must be byte-identical across languages or the routing breaks.
 *
 * Usage:
 *   node scripts/i18n-strings.mjs extract en > en.json
 *   node scripts/i18n-strings.mjs build it it.json
 *   node scripts/i18n-strings.mjs stats en
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const APP = path.resolve(HERE, '..');
const CONTENT = path.join(APP, 'src', 'content');

/** Never translated: identity and routing values shared by every language. */
const KEEP = new Set(['slug', 'image', 'image2', 'form', 'path', 'key', 'href', 'imageAlt', 'image2Alt']);
/** ...except alt text, which IS prose. Kept out of KEEP explicitly below. */
const ALT = new Set(['imageAlt', 'image2Alt']);

/** The eight content modules that make up one language. */
export const MODULES = ['core', 'immigration', 'housing', 'relocation', 'industrial', 'business', 'vip', 'guides'];

/** Load a language's content as plain data by running it through tsx. */
export function loadLang(lang) {
  const src = `
    import { ${lang} } from ${JSON.stringify(path.join(CONTENT, lang, 'index.ts'))};
    process.stdout.write(JSON.stringify(${lang}));
  `;
  const tmp = path.join(APP, `.i18n-load-${lang}.mts`);
  writeFileSync(tmp, src);
  try {
    const out = execFileSync(path.join(APP, 'node_modules', '.bin', 'tsx'), [tmp], {
      cwd: APP,
      maxBuffer: 64 * 1024 * 1024,
      encoding: 'utf8',
    });
    return JSON.parse(out);
  } finally {
    execFileSync('rm', ['-f', tmp]);
  }
}

/** Walk an object emitting { "a.b.0.c": "leaf string" } for translatable leaves. */
export function extract(node, prefix = '', out = {}) {
  if (typeof node === 'string') {
    out[prefix] = node;
    return out;
  }
  if (Array.isArray(node)) {
    node.forEach((v, i) => extract(v, prefix ? `${prefix}.${i}` : String(i), out));
    return out;
  }
  if (node && typeof node === 'object') {
    for (const [k, v] of Object.entries(node)) {
      if (KEEP.has(k) && !ALT.has(k)) continue;
      extract(v, prefix ? `${prefix}.${k}` : k, out);
    }
  }
  return out;
}

/** Rebuild a full content object from English plus a translation map. */
export function apply(node, map, prefix = '') {
  if (typeof node === 'string') {
    const t = map[prefix];
    return typeof t === 'string' && t.length ? t : node;
  }
  if (Array.isArray(node)) {
    return node.map((v, i) => apply(v, map, prefix ? `${prefix}.${i}` : String(i)));
  }
  if (node && typeof node === 'object') {
    const out = {};
    for (const [k, v] of Object.entries(node)) {
      if (KEEP.has(k) && !ALT.has(k)) {
        out[k] = v;
        continue;
      }
      out[k] = apply(v, map, prefix ? `${prefix}.${k}` : k);
    }
    return out;
  }
  return node;
}

/* ---------------- TS emitter ---------------- */

const q = (s) => "'" + String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";

function emit(v, ind = '  ') {
  if (typeof v === 'string') return q(v);
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);
  if (Array.isArray(v)) {
    if (!v.length) return '[]';
    const inner = v.map((x) => `${ind}  ${emit(x, ind + '  ')},`).join('\n');
    return `[\n${inner}\n${ind}]`;
  }
  const entries = Object.entries(v).filter(([, x]) => x !== undefined);
  if (!entries.length) return '{}';
  const inner = entries.map(([k, x]) => `${ind}  ${k}: ${emit(x, ind + '  ')},`).join('\n');
  return `{\n${inner}\n${ind}}`;
}

const TYPE_OF = {
  core: 'CoreContent',
  immigration: 'SectionContent',
  housing: 'SectionContent',
  relocation: 'SectionContent',
  industrial: 'SectionContent',
  business: 'SectionContent',
  vip: 'VipContent',
  guides: 'GuidesContent',
};

const HEADER = (lang, mod) => `/* GENERATED by scripts/i18n-strings.mjs. Do not hand-edit.
   ${lang}/${mod}.ts is a 1:1 structural mirror of en/${mod}.ts; only leaf strings
   differ. To change structure, change English and re-run the build. */\n`;

export function writeLang(lang, data) {
  const dir = path.join(CONTENT, lang);
  mkdirSync(dir, { recursive: true });
  for (const mod of MODULES) {
    const body = `${HEADER(lang, mod)}import type { ${TYPE_OF[mod]} } from '../types';\n\nexport const ${mod}: ${TYPE_OF[mod]} = ${emit(data[mod])};\n`;
    writeFileSync(path.join(dir, `${mod}.ts`), body);
  }
  const index = `${HEADER(lang, 'index')}import type { SiteContent } from '../types';
${MODULES.map((m) => `import { ${m} } from './${m}';`).join('\n')}

export const ${lang}: SiteContent = {
${MODULES.map((m) => `  ${m},`).join('\n')}
};
`;
  writeFileSync(path.join(dir, 'index.ts'), index);
}

/* ---------------- CLI ---------------- */

const [cmd, lang, file] = process.argv.slice(2);

if (cmd === 'extract') {
  process.stdout.write(JSON.stringify(extract(loadLang(lang)), null, 1));
} else if (cmd === 'stats') {
  const m = extract(loadLang(lang));
  const vals = Object.values(m);
  const chars = vals.reduce((a, s) => a + s.length, 0);
  const words = vals.reduce((a, s) => a + s.split(/\s+/).filter(Boolean).length, 0);
  const bySection = {};
  for (const [k, v] of Object.entries(m)) {
    const top = k.split('.')[0];
    bySection[top] = bySection[top] || { n: 0, chars: 0 };
    bySection[top].n++;
    bySection[top].chars += v.length;
  }
  console.log(`${lang}: ${vals.length} strings, ${words} words, ${chars} chars`);
  for (const [k, v] of Object.entries(bySection).sort((a, b) => b[1].chars - a[1].chars)) {
    console.log(`  ${k.padEnd(14)} ${String(v.n).padStart(5)} strings  ${String(v.chars).padStart(7)} chars`);
  }
} else if (cmd === 'build') {
  const map = JSON.parse(readFileSync(file, 'utf8'));
  const en = loadLang('en');
  writeLang(lang, apply(en, map));
  const total = Object.keys(extract(en)).length;
  const done = Object.keys(map).filter((k) => map[k]).length;
  console.log(`built ${lang}: ${done}/${total} strings translated (${Math.round((100 * done) / total)}%)`);
} else {
  console.error('usage: i18n-strings.mjs extract|stats|build <lang> [map.json]');
  process.exit(1);
}
