// One-shot: appends the client-feedback round of copy to the nl/de dictionaries.
import fs from 'node:fs';

const NL = [
["Our largest programme. Dense, feathery plumes with a strong straight stem, cut at the right stage to travel and open in the vase rather than in the box.","Ons grootste programma. Dichte, veerachtige pluimen op een stevige rechte steel, geknipt op het juiste moment zodat ze onderweg goed blijven en pas in de vaas opengaan, niet in de doos."],
["Order confirmed by Monday flies the same week. Nairobi to Amsterdam is a night flight, and we confirm the delivery day for your destination on the order confirmation rather than quoting a blanket transit time.","Een order dat maandag bevestigd is, vliegt dezelfde week. Nairobi-Amsterdam is een nachtvlucht, en we bevestigen de leverdag voor uw bestemming op de orderbevestiging in plaats van een vaste transittijd voor iedereen te beloven."],
["Flowers required","Gewenste bloemen"],
["Estimated volume","Geschat volume"],
["Stem length / specification","Steellengte / specificatie"],
["Delivery location","Afleverlocatie"],
["Phone","Telefoon"],
["Premium Kenyan summer flowers &amp; foliage | JASM Flowers","Premium Keniaanse zomerbloemen &amp; groen | JASM Flowers"],
["Solidago, eucalyptus and limonium grown in Kenya for professional flower buyers across Europe. Consistent quality, reliable supply, cut to order and graded to your specification.","Solidago, eucalyptus en limonium, geteeld in Kenia voor professionele bloemeninkopers in heel Europa. Constante kwaliteit, betrouwbare levering, op order geknipt en gesorteerd op uw specificatie."],
["Premium Kenyan summer<br>flowers <em>&amp; foliage</em>","Premium Keniaanse zomer<br>bloemen <em>&amp; groen</em>"],
["Consistent quality. Reliable supply. Grown in Kenya for professional flower buyers across Europe, with solidago, eucalyptus and limonium at the heart of the programme.","Constante kwaliteit. Betrouwbare levering. Geteeld in Kenia voor professionele bloemeninkopers in heel Europa, met solidago, eucalyptus en limonium als hart van het programma."],
["Consistent quality. Reliable supply. Grown in Kenya for professional flower buyers across Europe.","Constante kwaliteit. Betrouwbare levering. Geteeld in Kenia voor professionele bloemeninkopers in heel Europa."],
["Summer flowers with a stem worth paying for.","Zomerbloemen met een steel die zijn prijs waard is."],
["&amp; eucalyptus, our core products","&amp; eucalyptus, onze kernproducten"],
["<b>2&ndash;4 &deg;C</b>","<b>2&ndash;4 &deg;C</b>"],
["cold chain, kept unbroken","koelketen, onafgebroken"],
["<b data-cut-left>14:00</b>","<b data-cut-left>14:00</b>"],
["order cut-off, East Africa Time","ordersluiting, Oost-Afrikaanse tijd"],
["Our core products","Onze kernproducten"],
["Solidago and eucalyptus are what we lead with and what we plan the season around. Limonium runs alongside them as an additional core programme product.","Solidago en eucalyptus zijn waar we mee vooropgaan en waar we het seizoen omheen plannen. Limonium loopt daarnaast mee als aanvullend kernproduct in het programma."],
["Solidago grown in Kenya for JASM Flowers","Solidago, geteeld in Kenia voor JASM Flowers"],
["Core product","Kernproduct"],
["Eucalyptus grown in Kenya for JASM Flowers","Eucalyptus, geteeld in Kenia voor JASM Flowers"],
["Limonium grown in Kenya for JASM Flowers","Limonium, geteeld in Kenia voor JASM Flowers"],
["Core programme","Kernprogramma"],
["Additional flowers","Aanvullende bloemen"],
["Available through our grower network and packed on the same airway bill, so you stop paying three freight minimums to build one bouquet.","Beschikbaar via ons telersnetwerk en verpakt op dezelfde vrachtbrief, zodat u niet langer drie vrachtminima betaalt om een boeket op te bouwen."],
["Why European buyers<br>choose JASM","Waarom Europese inkopers<br>voor JASM kiezen"],
["Graded to your specification","Gesorteerd op uw specificatie"],
["Photos before shipment","Foto's voor verzending"],
["How we work","Zo werken we"],
["Five steps, from the plan we agree with you to the box that lands at your cold store.","Vijf stappen, van het plan dat we met u afspreken tot de doos die bij uw koelcel aankomt."],
["Plan","Plannen"],
["Grow","Telen"],
["Harvest &amp; grade","Oogsten &amp; sorteren"],
["Pack &amp; export","Verpakken &amp; exporteren"],
["Deliver","Leveren"],
["You tell us the lines, the lengths and roughly what volume per week. We agree a programme with our growing partners before anything is planted or committed.","U vertelt ons de soorten, de lengtes en ongeveer welk volume per week. We spreken een programma af met onze teeltpartners voordat er iets geplant of vastgelegd wordt."],
["Selected Kenyan growers produce to that plan on our written specification. We stay close to the crop through the season rather than buying whatever is on the floor that week.","Geselecteerde Keniaanse telers produceren volgens dat plan op onze schriftelijke specificatie. We blijven het hele seizoen dicht op het gewas, in plaats van te kopen wat die week toevallig op de vloer ligt."],
["Cut to your order and graded against your spec: stem length, bunch weight, stem count and cut stage, checked before anything is bunched.","Op uw order geknipt en gesorteerd op uw spec: steellengte, bosgewicht, aantal stelen en snijstadium, gecontroleerd voordat er iets gebost wordt."],
["Pre-cooled within the hour, sealed into pre-chilled boxes with your labels, and prepared for export out of Nairobi. Photos of your pallet on request before it moves.","Binnen het uur voorgekoeld, verzegeld in voorgekoelde dozen met uw labels en klaargemaakt voor export vanuit Nairobi. Op verzoek foto's van uw pallet voordat die vertrekt."],
["Flown to Amsterdam or Liege on a reliable, temperature-controlled route and trucked onward to your cold store, with the temperature log travelling with the shipment.","Gevlogen naar Amsterdam of Luik op een betrouwbare, temperatuurbewaakte route en verder gereden naar uw koelcel, met het temperatuurlogboek dat met de zending meereist."],
["<b>Night freighter</b> to Europe","<b>Nachtvracht</b> naar Europa"],
["Kenya to Europe,<br>on a cold chain we control","Kenia naar Europa,<br>in een koelketen die we bewaken"],
["Out of Nairobi to Amsterdam or Liege, then onward across Europe to your cold store. Nothing goes through the Dutch clock, so you skip a day of handling and a margin you were paying for nothing.","Vanuit Nairobi naar Amsterdam of Luik, en van daaruit verder door Europa naar uw koelcel. Er gaat niets via de Nederlandse klok, dus u slaat een dag handling over en een marge waar u niets voor terugkreeg."],
["Pre-cooled within the hour of cutting, sealed into pre-chilled boxes and held at 2 to 4 degrees through the export process, with the temperature logged. We confirm the delivery day for your destination on the order rather than promising the same transit time to everyone.","Binnen het uur na het knippen voorgekoeld, verzegeld in voorgekoelde dozen en op 2 tot 4 graden gehouden gedurende het exportproces, met temperatuurregistratie. We bevestigen de leverdag voor uw bestemming op de order in plaats van iedereen dezelfde transittijd te beloven."],
["Trial order","Proefzending"],
["Start with a trial","Begin met een proefzending"],
["Not ready for a regular programme yet? Start with a trial order and experience our quality, packing and service before moving to a regular supply programme.","Nog niet toe aan een vast programma? Begin met een proefzending en ervaar onze kwaliteit, verpakking en service voordat u overgaat op een vast leveringsprogramma."],
["Request a trial box","Vraag een proefdoos aan"],
["Hello JASM Flowers, I would like to arrange a trial order.","Hallo JASM Flowers, ik wil graag een proefzending regelen."],
["Ask on WhatsApp","Vraag het via WhatsApp"],
["A half box is enough for a first trial","Een halve doos is genoeg voor een eerste proef"],
["Mix up to three lines in one shipment","Combineer tot drie soorten in een zending"],
["Graded to the same written spec as a standing order","Gesorteerd op dezelfde schriftelijke spec als een vast order"],
["Photos of your pallet before it ships","Foto's van uw pallet voordat die verzonden wordt"],
["A Kenyan flower export business connecting selected growers with professional international buyers. Summer flowers, foliage and roses, grown in Kenya for Europe.","Een Keniaans bloemenexportbedrijf dat geselecteerde telers verbindt met professionele internationale inkopers. Zomerbloemen, groen en rozen, geteeld in Kenia voor Europa."],
["About JASM","Over JASM"],
["Our growing partners","Onze teeltpartners"],
["Core","Kern"],
["How flowers get from a Kenyan field to a European cold store: cut to order, pre-cooled within the hour, night freighter from Nairobi to Amsterdam or Liege on an unbroken cold chain.","Hoe bloemen van een Keniaans veld naar een Europese koelcel gaan: op order geknipt, binnen het uur voorgekoeld, nachtvracht van Nairobi naar Amsterdam of Luik in een onafgebroken koelketen."],
["Kenya to Europe,<br>cold the whole way","Kenia naar Europa,<br>de hele weg gekoeld"],
["Day 1, morning","Dag 1, ochtend"],
["On to you","Naar u toe"],
["Delivered","Geleverd"],
["Trucked to you refrigerated, with the temperature log from the whole journey. Your delivery day is confirmed on the order.","Gekoeld naar u toe gereden, met het temperatuurlogboek van de hele reis. Uw leverdag wordt op de order bevestigd."],
["About JASM: Kenyan flower export | JASM Flowers","Over JASM: Keniaanse bloemenexport | JASM Flowers"],
["JASM Flowers is a Kenyan flower export business connecting selected growers with professional international buyers. Quality, consistency, transparency and long-term partnerships.","JASM Flowers is een Keniaans bloemenexportbedrijf dat geselecteerde telers verbindt met professionele internationale inkopers. Kwaliteit, constantheid, transparantie en langdurige partnerschappen."],
["Selected growers,<br>professional buyers","Geselecteerde telers,<br>professionele inkopers"],
["JASM Flowers is a Kenyan flower export business connecting selected growers with professional international buyers.","JASM Flowers is een Keniaans bloemenexportbedrijf dat geselecteerde telers verbindt met professionele internationale inkopers."],
["Quality","Kwaliteit"],
["Consistency","Constantheid"],
["Transparency","Transparantie"],
["Long-term partnerships","Langdurige partnerschappen"],
["We work the other way round. You order from us, our growing partners cut to that order, and the box is built for you. That is one fewer week in transit and a price that reflects the stem rather than the number of people who touched it.","Wij doen het andersom. U bestelt bij ons, onze teeltpartners knippen op dat order en de doos wordt voor u opgebouwd. Dat scheelt een week onderweg en levert een prijs op die over de steel gaat in plaats van over het aantal handen dat eraan zat."],
["We are not a farm and we do not pretend to be one. What we bring is the relationship with the growers, the specification the crop is held to, and the export process that gets it to you in the condition you were promised.","We zijn geen kwekerij en doen ook niet alsof. Wat wij brengen is de relatie met de telers, de specificatie waar het gewas aan gehouden wordt, en het exportproces dat het bij u brengt in de staat die is afgesproken."],
["Our model is working with selected Kenyan growers rather than owning farms. We collaborate closely with them on quality, specifications, harvesting, grading and export preparation, so what leaves the country matches what was agreed.","Ons model is samenwerken met geselecteerde Keniaanse telers in plaats van zelf kwekerijen bezitten. We werken nauw met hen samen aan kwaliteit, specificaties, oogst, sortering en exportvoorbereiding, zodat wat het land verlaat overeenkomt met wat is afgesproken."],
["Selected, not sourced on the day","Geselecteerd, niet op de dag ingekocht"],
["We work with a small group of growers we know, chosen for the crop they are genuinely good at rather than for whatever is cheapest on the floor that week.","We werken met een kleine groep telers die we kennen, gekozen om het gewas waar ze echt goed in zijn en niet om wat die week het goedkoopst op de vloer ligt."],
["Grown to a written specification","Geteeld op een schriftelijke specificatie"],
["Stem length, bunch weight, stem count and cut stage are agreed up front and shared with the grower, so the spec is set before the crop is planted, not argued about after.","Steellengte, bosgewicht, aantal stelen en snijstadium worden vooraf afgesproken en met de teler gedeeld, zodat de spec vaststaat voordat het gewas de grond in gaat en er achteraf niet over gediscussieerd hoeft te worden."],
["Close on quality and export prep","Dicht op kwaliteit en exportvoorbereiding"],
["We stay involved through harvesting, grading and export preparation. If a farm will not take an unannounced visit, we do not buy from it.","We blijven betrokken bij oogst, sortering en exportvoorbereiding. Laat een kwekerij geen onaangekondigd bezoek toe, dan kopen we er niet."],
["Naivasha, around 1,900 m","Naivasha, rond 1.900 m"],
["Lakeside blocks on volcanic soil. The main solidago, limonium and statice ground, and the reason filler volume holds all year.","Percelen aan het meer op vulkanische grond. De belangrijkste grond voor solidago, limonium en statice, en de reden dat het volume aan vulbloemen het hele jaar op peil blijft."],
["Two regions, deliberately","Twee regio's, met opzet"],
["Weather that ruins a crop in Naivasha rarely touches Mount Kenya in the same week, so a standing order does not fail because of one storm.","Weer dat een gewas in Naivasha verwoest, raakt Mount Kenya zelden in dezelfde week, dus een vast order valt niet om door een enkele storm."],
["Buyer enquiry","Inkoopaanvraag"],
["Your business","Uw bedrijf"],
["What you need","Wat u nodig heeft"],
["e.g. 2 full boxes solidago per week","bijv. 2 hele dozen solidago per week"],
["e.g. 60-70 cm, 250 g bunches, tight cut","bijv. 60-70 cm, bossen van 250 g, krap gesneden"],
["Airport or delivery address","Luchthaven of afleveradres"],
["Trial order first","Eerst een proefzending"],
["How we reach you","Hoe we u bereiken"],
["Phone or WhatsApp","Telefoon of WhatsApp"],
["Cut stage, your own grading spec, packaging or labelling requirements...","Snijstadium, uw eigen sorteerspecificatie, eisen aan verpakking of labels..."],
["Core products","Kernproducten"],
["Solidago and eucalyptus, plus limonium","Solidago en eucalyptus, plus limonium"],
["Solidago and eucalyptus are our core products. Limonium runs alongside them as an additional core programme product.","Solidago en eucalyptus zijn onze kernproducten. Limonium loopt daarnaast mee als aanvullend kernproduct in het programma."],
["Additional flowers 1","Aanvullende bloemen 1"],
["Additional flowers 2","Aanvullende bloemen 2"],
["Additional flowers 3","Aanvullende bloemen 3"],
["Additional flowers 4","Aanvullende bloemen 4"],
["Cold chain unbroken at 2 to 4 &deg;C; delivery day confirmed on your order.","Koelketen onafgebroken op 2 tot 4 &deg;C; leverdag bevestigd op uw order."],
["Growing partners","Teeltpartners"],
["Selected Kenyan growers, working to our written specification.","Geselecteerde Keniaanse telers, werkend op onze schriftelijke specificatie."],
];

const DE = [
["Our largest programme. Dense, feathery plumes with a strong straight stem, cut at the right stage to travel and open in the vase rather than in the box.","Unser groesstes Programm. Dichte, federartige Rispen an einem kraeftigen geraden Stiel, im richtigen Stadium geschnitten, damit sie den Transport ueberstehen und in der Vase aufgehen statt in der Kiste."],
["Order confirmed by Monday flies the same week. Nairobi to Amsterdam is a night flight, and we confirm the delivery day for your destination on the order confirmation rather than quoting a blanket transit time.","Eine bis Montag bestaetigte Bestellung fliegt in derselben Woche. Nairobi nach Amsterdam ist ein Nachtflug, und wir bestaetigen den Liefertag fuer Ihr Ziel auf der Auftragsbestaetigung, statt allen dieselbe Transitzeit zu versprechen."],
["Flowers required","Benoetigte Blumen"],
["Estimated volume","Geschaetztes Volumen"],
["Stem length / specification","Stiellaenge / Spezifikation"],
["Delivery location","Lieferort"],
["Phone","Telefon"],
["Premium Kenyan summer flowers &amp; foliage | JASM Flowers","Premium Sommerblumen &amp; Schnittgruen aus Kenia | JASM Flowers"],
["Solidago, eucalyptus and limonium grown in Kenya for professional flower buyers across Europe. Consistent quality, reliable supply, cut to order and graded to your specification.","Solidago, Eukalyptus und Limonium, in Kenia angebaut fuer professionelle Blumeneinkaeufer in ganz Europa. Gleichbleibende Qualitaet, verlaessliche Versorgung, auf Bestellung geschnitten und nach Ihrer Spezifikation sortiert."],
["Premium Kenyan summer<br>flowers <em>&amp; foliage</em>","Premium Sommerblumen aus<br>Kenia <em>&amp; Schnittgruen</em>"],
["Consistent quality. Reliable supply. Grown in Kenya for professional flower buyers across Europe, with solidago, eucalyptus and limonium at the heart of the programme.","Gleichbleibende Qualitaet. Verlaessliche Versorgung. In Kenia angebaut fuer professionelle Blumeneinkaeufer in ganz Europa, mit Solidago, Eukalyptus und Limonium im Zentrum des Programms."],
["Consistent quality. Reliable supply. Grown in Kenya for professional flower buyers across Europe.","Gleichbleibende Qualitaet. Verlaessliche Versorgung. In Kenia angebaut fuer professionelle Blumeneinkaeufer in ganz Europa."],
["Summer flowers with a stem worth paying for.","Sommerblumen mit einem Stiel, der seinen Preis wert ist."],
["&amp; eucalyptus, our core products","&amp; Eukalyptus, unsere Kernprodukte"],
["<b>2&ndash;4 &deg;C</b>","<b>2&ndash;4 &deg;C</b>"],
["cold chain, kept unbroken","Kuehlkette, ohne Unterbrechung"],
["<b data-cut-left>14:00</b>","<b data-cut-left>14:00</b>"],
["order cut-off, East Africa Time","Bestellschluss, ostafrikanische Zeit"],
["Our core products","Unsere Kernprodukte"],
["Solidago and eucalyptus are what we lead with and what we plan the season around. Limonium runs alongside them as an additional core programme product.","Solidago und Eukalyptus stehen bei uns an erster Stelle und um sie herum planen wir die Saison. Limonium laeuft daneben als zusaetzliches Kernprodukt im Programm mit."],
["Solidago grown in Kenya for JASM Flowers","Solidago, in Kenia angebaut fuer JASM Flowers"],
["Core product","Kernprodukt"],
["Eucalyptus grown in Kenya for JASM Flowers","Eukalyptus, in Kenia angebaut fuer JASM Flowers"],
["Limonium grown in Kenya for JASM Flowers","Limonium, in Kenia angebaut fuer JASM Flowers"],
["Core programme","Kernprogramm"],
["Additional flowers","Weitere Blumen"],
["Available through our grower network and packed on the same airway bill, so you stop paying three freight minimums to build one bouquet.","Verfuegbar ueber unser Erzeugernetzwerk und auf demselben Luftfrachtbrief gepackt, damit Sie nicht laenger drei Frachtmindestmengen fuer einen Strauss zahlen."],
["Why European buyers<br>choose JASM","Warum europaeische Einkaeufer<br>sich fuer JASM entscheiden"],
["Graded to your specification","Nach Ihrer Spezifikation sortiert"],
["Photos before shipment","Fotos vor dem Versand"],
["How we work","So arbeiten wir"],
["Five steps, from the plan we agree with you to the box that lands at your cold store.","Fuenf Schritte, vom Plan, den wir mit Ihnen abstimmen, bis zur Kiste, die in Ihrem Kuehlhaus ankommt."],
["Plan","Planen"],
["Grow","Anbauen"],
["Harvest &amp; grade","Ernten &amp; sortieren"],
["Pack &amp; export","Packen &amp; exportieren"],
["Deliver","Liefern"],
["You tell us the lines, the lengths and roughly what volume per week. We agree a programme with our growing partners before anything is planted or committed.","Sie nennen uns die Sorten, die Laengen und ungefaehr das Volumen pro Woche. Wir stimmen ein Programm mit unseren Anbaupartnern ab, bevor etwas gepflanzt oder zugesagt wird."],
["Selected Kenyan growers produce to that plan on our written specification. We stay close to the crop through the season rather than buying whatever is on the floor that week.","Ausgewaehlte kenianische Erzeuger produzieren nach diesem Plan und nach unserer schriftlichen Spezifikation. Wir bleiben die ganze Saison nah an der Kultur, statt zu kaufen, was in der Woche gerade verfuegbar ist."],
["Cut to your order and graded against your spec: stem length, bunch weight, stem count and cut stage, checked before anything is bunched.","Auf Ihre Bestellung geschnitten und nach Ihrer Spezifikation sortiert: Stiellaenge, Bundgewicht, Stielzahl und Schnittstadium, geprueft bevor gebunden wird."],
["Pre-cooled within the hour, sealed into pre-chilled boxes with your labels, and prepared for export out of Nairobi. Photos of your pallet on request before it moves.","Innerhalb einer Stunde vorgekuehlt, in vorgekuehlte Kisten mit Ihren Etiketten verschlossen und fuer den Export aus Nairobi vorbereitet. Auf Wunsch Fotos Ihrer Palette, bevor sie bewegt wird."],
["Flown to Amsterdam or Liege on a reliable, temperature-controlled route and trucked onward to your cold store, with the temperature log travelling with the shipment.","Auf einer verlaesslichen, temperaturgefuehrten Route nach Amsterdam oder Luettich geflogen und weiter zu Ihrem Kuehlhaus gefahren, mit dem Temperaturprotokoll, das mit der Sendung reist."],
["<b>Night freighter</b> to Europe","<b>Nachtfrachter</b> nach Europa"],
["Kenya to Europe,<br>on a cold chain we control","Kenia nach Europa,<br>in einer Kuehlkette, die wir fuehren"],
["Out of Nairobi to Amsterdam or Liege, then onward across Europe to your cold store. Nothing goes through the Dutch clock, so you skip a day of handling and a margin you were paying for nothing.","Aus Nairobi nach Amsterdam oder Luettich und von dort weiter durch Europa zu Ihrem Kuehlhaus. Nichts laeuft ueber die niederlaendische Uhr, Sie sparen also einen Tag Handling und eine Marge, fuer die Sie nichts bekamen."],
["Pre-cooled within the hour of cutting, sealed into pre-chilled boxes and held at 2 to 4 degrees through the export process, with the temperature logged. We confirm the delivery day for your destination on the order rather than promising the same transit time to everyone.","Innerhalb einer Stunde nach dem Schnitt vorgekuehlt, in vorgekuehlte Kisten verschlossen und waehrend des gesamten Exportprozesses bei 2 bis 4 Grad gehalten, mit Temperaturaufzeichnung. Wir bestaetigen den Liefertag fuer Ihr Ziel auf der Bestellung, statt allen dieselbe Transitzeit zu versprechen."],
["Trial order","Probesendung"],
["Start with a trial","Starten Sie mit einer Probesendung"],
["Not ready for a regular programme yet? Start with a trial order and experience our quality, packing and service before moving to a regular supply programme.","Noch nicht bereit fuer ein festes Programm? Starten Sie mit einer Probesendung und erleben Sie unsere Qualitaet, Verpackung und unseren Service, bevor Sie zu einem regelmaessigen Lieferprogramm uebergehen."],
["Request a trial box","Probekiste anfragen"],
["Hello JASM Flowers, I would like to arrange a trial order.","Hallo JASM Flowers, ich moechte gerne eine Probesendung vereinbaren."],
["Ask on WhatsApp","Per WhatsApp fragen"],
["A half box is enough for a first trial","Eine halbe Kiste reicht fuer einen ersten Test"],
["Mix up to three lines in one shipment","Bis zu drei Sorten in einer Sendung kombinieren"],
["Graded to the same written spec as a standing order","Nach derselben schriftlichen Spezifikation sortiert wie ein festes Programm"],
["Photos of your pallet before it ships","Fotos Ihrer Palette vor dem Versand"],
["A Kenyan flower export business connecting selected growers with professional international buyers. Summer flowers, foliage and roses, grown in Kenya for Europe.","Ein kenianisches Blumenexportunternehmen, das ausgewaehlte Erzeuger mit professionellen internationalen Einkaeufern verbindet. Sommerblumen, Schnittgruen und Rosen, in Kenia fuer Europa angebaut."],
["About JASM","Ueber JASM"],
["Our growing partners","Unsere Anbaupartner"],
["Core","Kern"],
["How flowers get from a Kenyan field to a European cold store: cut to order, pre-cooled within the hour, night freighter from Nairobi to Amsterdam or Liege on an unbroken cold chain.","Wie Blumen von einem kenianischen Feld in ein europaeisches Kuehlhaus kommen: auf Bestellung geschnitten, innerhalb einer Stunde vorgekuehlt, Nachtfrachter von Nairobi nach Amsterdam oder Luettich in einer ununterbrochenen Kuehlkette."],
["Kenya to Europe,<br>cold the whole way","Kenia nach Europa,<br>durchgehend gekuehlt"],
["Day 1, morning","Tag 1, morgens"],
["On to you","Weiter zu Ihnen"],
["Delivered","Geliefert"],
["Trucked to you refrigerated, with the temperature log from the whole journey. Your delivery day is confirmed on the order.","Gekuehlt zu Ihnen gefahren, mit dem Temperaturprotokoll der gesamten Reise. Ihr Liefertag wird auf der Bestellung bestaetigt."],
["About JASM: Kenyan flower export | JASM Flowers","Ueber JASM: kenianischer Blumenexport | JASM Flowers"],
["JASM Flowers is a Kenyan flower export business connecting selected growers with professional international buyers. Quality, consistency, transparency and long-term partnerships.","JASM Flowers ist ein kenianisches Blumenexportunternehmen, das ausgewaehlte Erzeuger mit professionellen internationalen Einkaeufern verbindet. Qualitaet, Bestaendigkeit, Transparenz und langfristige Partnerschaften."],
["Selected growers,<br>professional buyers","Ausgewaehlte Erzeuger,<br>professionelle Einkaeufer"],
["JASM Flowers is a Kenyan flower export business connecting selected growers with professional international buyers.","JASM Flowers ist ein kenianisches Blumenexportunternehmen, das ausgewaehlte Erzeuger mit professionellen internationalen Einkaeufern verbindet."],
["Quality","Qualitaet"],
["Consistency","Bestaendigkeit"],
["Transparency","Transparenz"],
["Long-term partnerships","Langfristige Partnerschaften"],
["We work the other way round. You order from us, our growing partners cut to that order, and the box is built for you. That is one fewer week in transit and a price that reflects the stem rather than the number of people who touched it.","Wir machen es umgekehrt. Sie bestellen bei uns, unsere Anbaupartner schneiden auf diese Bestellung, und die Kiste wird fuer Sie gebaut. Das ist eine Woche weniger unterwegs und ein Preis, der den Stiel abbildet statt der Zahl der Haende, die ihn angefasst haben."],
["We are not a farm and we do not pretend to be one. What we bring is the relationship with the growers, the specification the crop is held to, and the export process that gets it to you in the condition you were promised.","Wir sind keine Gaertnerei und geben auch nicht vor, eine zu sein. Was wir einbringen, ist die Beziehung zu den Erzeugern, die Spezifikation, an der die Kultur gemessen wird, und der Exportprozess, der die Ware in dem Zustand zu Ihnen bringt, der zugesagt wurde."],
["Our model is working with selected Kenyan growers rather than owning farms. We collaborate closely with them on quality, specifications, harvesting, grading and export preparation, so what leaves the country matches what was agreed.","Unser Modell ist die Zusammenarbeit mit ausgewaehlten kenianischen Erzeugern, nicht der Besitz eigener Farmen. Wir arbeiten eng mit ihnen an Qualitaet, Spezifikationen, Ernte, Sortierung und Exportvorbereitung, damit das, was das Land verlaesst, dem entspricht, was vereinbart wurde."],
["Selected, not sourced on the day","Ausgewaehlt, nicht tagesaktuell eingekauft"],
["We work with a small group of growers we know, chosen for the crop they are genuinely good at rather than for whatever is cheapest on the floor that week.","Wir arbeiten mit einer kleinen Gruppe von Erzeugern, die wir kennen, ausgewaehlt nach der Kultur, in der sie wirklich gut sind, und nicht nach dem, was in der Woche am guenstigsten ist."],
["Grown to a written specification","Nach schriftlicher Spezifikation angebaut"],
["Stem length, bunch weight, stem count and cut stage are agreed up front and shared with the grower, so the spec is set before the crop is planted, not argued about after.","Stiellaenge, Bundgewicht, Stielzahl und Schnittstadium werden vorab vereinbart und mit dem Erzeuger geteilt, damit die Spezifikation steht, bevor die Kultur gepflanzt wird, und nicht hinterher verhandelt werden muss."],
["Close on quality and export prep","Nah an Qualitaet und Exportvorbereitung"],
["We stay involved through harvesting, grading and export preparation. If a farm will not take an unannounced visit, we do not buy from it.","Wir bleiben bei Ernte, Sortierung und Exportvorbereitung eingebunden. Laesst ein Betrieb keinen unangekuendigten Besuch zu, kaufen wir dort nicht."],
["Naivasha, around 1,900 m","Naivasha, rund 1.900 m"],
["Lakeside blocks on volcanic soil. The main solidago, limonium and statice ground, and the reason filler volume holds all year.","Parzellen am See auf vulkanischem Boden. Der wichtigste Standort fuer Solidago, Limonium und Statice und der Grund, warum das Fuellgruen-Volumen das ganze Jahr haelt."],
["Two regions, deliberately","Zwei Regionen, mit Absicht"],
["Weather that ruins a crop in Naivasha rarely touches Mount Kenya in the same week, so a standing order does not fail because of one storm.","Wetter, das eine Kultur in Naivasha zerstoert, trifft den Mount Kenya selten in derselben Woche, ein festes Programm faellt also nicht wegen eines einzigen Sturms aus."],
["Buyer enquiry","Einkaufsanfrage"],
["Your business","Ihr Unternehmen"],
["What you need","Was Sie brauchen"],
["e.g. 2 full boxes solidago per week","z. B. 2 ganze Kisten Solidago pro Woche"],
["e.g. 60-70 cm, 250 g bunches, tight cut","z. B. 60-70 cm, Bunde zu 250 g, eng geschnitten"],
["Airport or delivery address","Flughafen oder Lieferadresse"],
["Trial order first","Zuerst eine Probesendung"],
["How we reach you","Wie wir Sie erreichen"],
["Phone or WhatsApp","Telefon oder WhatsApp"],
["Cut stage, your own grading spec, packaging or labelling requirements...","Schnittstadium, Ihre eigene Sortierspezifikation, Anforderungen an Verpackung oder Etiketten..."],
["Core products","Kernprodukte"],
["Solidago and eucalyptus, plus limonium","Solidago und Eukalyptus, dazu Limonium"],
["Solidago and eucalyptus are our core products. Limonium runs alongside them as an additional core programme product.","Solidago und Eukalyptus sind unsere Kernprodukte. Limonium laeuft daneben als zusaetzliches Kernprodukt im Programm mit."],
["Additional flowers 1","Weitere Blumen 1"],
["Additional flowers 2","Weitere Blumen 2"],
["Additional flowers 3","Weitere Blumen 3"],
["Additional flowers 4","Weitere Blumen 4"],
["Cold chain unbroken at 2 to 4 &deg;C; delivery day confirmed on your order.","Kuehlkette ununterbrochen bei 2 bis 4 &deg;C; Liefertag auf Ihrer Bestellung bestaetigt."],
["Growing partners","Anbaupartner"],
["Selected Kenyan growers, working to our written specification.","Ausgewaehlte kenianische Erzeuger, die nach unserer schriftlichen Spezifikation arbeiten."],
];

// The German above is written with ae/oe/ue/ss digraphs so the source stays ASCII;
// the dictionary itself is proper German, so they are folded back here. Whole-word
// only: a blanket ue -> ü would turn "tagesaktuell" into nonsense.
const UML = {
  ueber: 'über', Ueber: 'Über', ueberstehen: 'überstehen', uebergehen: 'übergehen',
  fuer: 'für', Kuehlkette: 'Kühlkette', Kuehlhaus: 'Kühlhaus', vorgekuehlt: 'vorgekühlt',
  vorgekuehlte: 'vorgekühlte', gekuehlt: 'gekühlt', Luettich: 'Lüttich', Fuenf: 'Fünf',
  guenstigsten: 'günstigsten', Fuellgruen: 'Füllgrün', Schnittgruen: 'Schnittgrün',
  unangekuendigten: 'unangekündigten', Verfuegbar: 'Verfügbar', geprueft: 'geprüft',
  fuehren: 'führen', temperaturgefuehrten: 'temperaturgeführten',
  zerstoert: 'zerstört', moechte: 'möchte', groesstes: 'größtes', Strauss: 'Strauß',
  verlaesst: 'verlässt', laesst: 'Lässt', Laesst: 'Lässt', laeuft: 'läuft',
  waehrend: 'während', faellt: 'fällt', laenger: 'länger', Haende: 'Hände',
  Gaertnerei: 'Gärtnerei', kraeftigen: 'kräftigen', bestaetigte: 'bestätigte',
  bestaetigen: 'bestätigen', bestaetigt: 'bestätigt',
  Auftragsbestaetigung: 'Auftragsbestätigung', Benoetigte: 'Benötigte',
  Geschaetztes: 'Geschätztes', Stiellaenge: 'Stiellänge', Laengen: 'Längen',
  Blumeneinkaeufer: 'Blumeneinkäufer', Einkaeufer: 'Einkäufer', Qualitaet: 'Qualität',
  ungefaehr: 'ungefähr', ausgewaehlte: 'ausgewählte', ausgewaehlten: 'ausgewählten',
  Ausgewaehlte: 'Ausgewählte', verlaesslichen: 'verlässlichen',
  verlaessliche: 'verlässliche', Verlaessliche: 'Verlässliche',
  Bestaendigkeit: 'Beständigkeit', zusaetzliches: 'zusätzliches',
  regelmaessigen: 'regelmäßigen', niederlaendische: 'niederländische',
  europaeische: 'europäische', kenianische: 'kenianische',
};
const RE = new RegExp(`\\b(${Object.keys(UML).sort((a, b) => b.length - a.length).join('|')})\\b`, 'g');
const de = DE.map(([k, v]) => [k, v.replace(RE, w => UML[w])]);

// Anything still carrying a digraph is either correct German (Erzeuger, aktuell) or a
// word this map missed - print it so the miss is visible rather than silently shipped.
const left = new Set();
for (const [, v] of de) for (const w of v.match(/\b\w*(ae|oe|ue|aeh|ss)\w*\b/g) || []) left.add(w);
console.log('digraphs left for review:', [...left].join(' '));

const HEAD = '\n# --- client feedback round: positioning, growing partners, process, trial, buyer form\n';
for (const [code, rows] of [['nl', NL], ['de', de]]) {
  const f = new URL(`../src/lang/${code}.tsv`, import.meta.url);
  fs.appendFileSync(f, HEAD + rows.map(([k, v]) => `${k}\t${v}`).join('\n') + '\n');
  console.log(`${code}.tsv +${rows.length}`);
}
