// One-shot: appends the 29 Sep copy/structure round to the nl/de dictionaries.
// Run: node tools/_lang2909b.mjs
import fs from 'node:fs';

const P = [
["Small round powder-blue leaves on a fine stem, with the scent the leaf is bought for. Cut at the stage that holds its bloom rather than the stage that fills a box fastest.",
 "Kleine ronde poederblauwe blaadjes aan een fijne steel, met de geur waar het blad om gekocht wordt. Geknipt op het moment dat de waslaag blijft zitten, niet op het moment dat een doos het snelst vol is.",
 "Kleine runde pudrig-blaue Blätter an einem feinen Stiel, mit dem Duft, für den das Blatt gekauft wird. Geschnitten in dem Stadium, in dem der Reif hält, nicht in dem, das eine Kiste am schnellsten füllt."],
["The large rounded coin leaf, on a straighter and heavier stem than Baby Blue. Used where a bouquet needs structure and volume rather than texture.",
 "Het grote ronde muntblad, aan een rechtere en zwaardere steel dan Baby Blue. Voor boeketten die structuur en volume nodig hebben in plaats van textuur.",
 "Das große runde Münzblatt, an einem geraderen und schwereren Stiel als Baby Blue. Für Sträuße, die Struktur und Volumen brauchen statt Textur."],
["Estimated quantity", "Geschatte hoeveelheid", "Geschätzte Menge"],
["Delivery destination", "Afleverbestemming", "Lieferziel"],
["Shipment frequency", "Verzendfrequentie", "Versandfrequenz"],
["Message", "Bericht", "Nachricht"],
["&amp; eucalyptus, our key flowers", "&amp; eucalyptus, onze kernbloemen", "&amp; Eukalyptus, unsere Kernblumen"],
["Our key flowers", "Onze kernbloemen", "Unsere Kernblumen"],
["Solidago and the two eucalyptus lines lead the programme and the season is planned around them.",
 "Solidago en de twee eucalyptuslijnen vormen de kern van het programma; het seizoen wordt daaromheen gepland.",
 "Solidago und die beiden Eukalyptuslinien bilden den Kern des Programms; die Saison wird um sie herum geplant."],
["All 17 lines", "Alle 17 soorten", "Alle 17 Sorten"],
["Key flower", "Kernbloem", "Kernblume"],
["Eucalyptus Baby Blue grown in Kenya for JASM Flowers",
 "Eucalyptus Baby Blue, geteeld in Kenia voor JASM Flowers",
 "Eucalyptus Baby Blue, in Kenia angebaut für JASM Flowers"],
["Eucalyptus Baby Blue", "Eucalyptus Baby Blue", "Eucalyptus Baby Blue"],
["Eucalyptus cinerea", "Eucalyptus cinerea", "Eucalyptus cinerea"],
["Powder blue, Blue green", "Poederblauw, blauwgroen", "Puderblau, Blaugrün"],
["Eucalyptus Silver Dollar grown in Kenya for JASM Flowers",
 "Eucalyptus Silver Dollar, geteeld in Kenia voor JASM Flowers",
 "Eucalyptus Silver Dollar, in Kenia angebaut für JASM Flowers"],
["Eucalyptus Silver Dollar", "Eucalyptus Silver Dollar", "Eucalyptus Silver Dollar"],
["Eucalyptus polyanthemos", "Eucalyptus polyanthemos", "Eucalyptus polyanthemos"],
["Silver green, Grey green", "Zilvergroen, grijsgroen", "Silbergrün, Graugrün"],
["Limonium runs alongside as a core programme line; the rest come through our grower network. All of it packs on the same airway bill, so one bouquet costs one freight minimum.",
 "Limonium loopt mee als vaste programmalijn; de rest komt via ons telersnetwerk. Alles gaat op dezelfde vrachtbrief, dus een boeket kost een vrachtminimum.",
 "Limonium läuft als feste Programmlinie mit; der Rest kommt über unser Erzeugernetz. Alles geht auf denselben Luftfrachtbrief, ein Strauß kostet also ein Frachtminimum."],
["50 cm to 70 cm &middot; 12-18 days", "50 cm tot 70 cm &middot; 12-18 dagen", "50 cm bis 70 cm &middot; 12-18 Tage"],
["From your list<br>to your shipment", "Van uw lijst<br>naar uw zending", "Von Ihrer Liste<br>zu Ihrer Sendung"],
["Five steps, from the mail you send us to the box at your cold store.",
 "Vijf stappen, van de mail die u stuurt tot de doos in uw koelcel.",
 "Fünf Schritte, von der Mail, die Sie schicken, bis zur Kiste in Ihrem Kühlhaus."],
["Tell us what you need", "Vertel ons wat u nodig hebt", "Sagen Sie uns, was Sie brauchen"],
["We check availability", "Wij checken de beschikbaarheid", "Wir prüfen die Verfügbarkeit"],
["You get a quotation", "U krijgt een offerte", "Sie erhalten ein Angebot"],
["We prepare your order", "Wij maken uw order klaar", "Wir bereiten Ihre Bestellung vor"],
["Your flowers ship", "Uw bloemen gaan op transport", "Ihre Blumen gehen auf die Reise"],
["Send the varieties, stem lengths, quantities and where it has to land. A list in a mail is enough to start.",
 "Stuur de soorten, steellengtes, aantallen en waar het moet landen. Een lijstje in een mail is genoeg om te beginnen.",
 "Schicken Sie Sorten, Stiellängen, Mengen und den Zielort. Eine Liste in einer Mail reicht für den Anfang."],
["We go to our growing partners with your specification and confirm what can actually be cut for you, in what volume and from when.",
 "Wij gaan met uw specificatie naar onze telerpartners en bevestigen wat er werkelijk voor u geknipt kan worden, in welk volume en vanaf wanneer.",
 "Wir gehen mit Ihrer Spezifikation zu unseren Erzeugerpartnern und bestätigen, was tatsächlich für Sie geschnitten werden kann, in welcher Menge und ab wann."],
["A written price against the agreed specification, quantity and shipment, so you can compare it with what you pay now.",
 "Een schriftelijke prijs op basis van de afgesproken specificatie, hoeveelheid en zending, zodat u hem kunt vergelijken met wat u nu betaalt.",
 "Ein schriftlicher Preis auf Basis der vereinbarten Spezifikation, Menge und Sendung, damit Sie ihn mit dem vergleichen können, was Sie heute zahlen."],
["Once confirmed we coordinate harvesting, grading, packing and export preparation against that same specification.",
 "Na bevestiging coördineren wij oogst, sortering, verpakking en exportvoorbereiding tegen diezelfde specificatie.",
 "Nach der Bestätigung koordinieren wir Ernte, Sortierung, Verpackung und Exportvorbereitung nach derselben Spezifikation."],
["We book the shipment and keep you posted while it travels. Pallet photos before it leaves, on request.",
 "Wij boeken de zending en houden u op de hoogte terwijl die onderweg is. Palletfoto's voor vertrek, op verzoek.",
 "Wir buchen die Sendung und halten Sie auf dem Laufenden, während sie unterwegs ist. Palettenfotos vor dem Abflug, auf Wunsch."],
["<b>Buying the same lines every week?</b> Talk to us about a weekly or seasonal supply programme and we plan the volume with the grower in advance.",
 "<b>Koopt u elke week dezelfde soorten?</b> Vraag ons naar een wekelijks of seizoensprogramma, dan plannen wij het volume vooraf met de teler.",
 "<b>Kaufen Sie jede Woche dieselben Sorten?</b> Sprechen Sie mit uns über ein wöchentliches oder saisonales Lieferprogramm, dann planen wir das Volumen vorab mit dem Erzeuger."],
["How programmes work", "Hoe programma's werken", "Wie Programme funktionieren"],
["Tell us the lines, the lengths and the volume. We check availability with our growing partners and come back with a written quote, grade, pack and freight included, inside one working day.",
 "Geef ons de soorten, de lengtes en het volume. Wij checken de beschikbaarheid bij onze telerpartners en komen binnen een werkdag terug met een schriftelijke offerte, inclusief sortering, verpakking en vracht.",
 "Nennen Sie uns die Sorten, die Längen und das Volumen. Wir prüfen die Verfügbarkeit bei unseren Erzeugerpartnern und melden uns innerhalb eines Werktages mit einem schriftlichen Angebot, inklusive Sortierung, Verpackung und Fracht."],
["Flower catalogue: 17 lines from Kenya | JASM Flowers",
 "Bloemencatalogus: 17 soorten uit Kenia | JASM Flowers",
 "Blumenkatalog: 17 Sorten aus Kenia | JASM Flowers"],
["17 lines on one airway bill. The specs below are the standard pack; stem length, bunch weight and cut stage can be set to your own programme.",
 "17 soorten op een vrachtbrief. De specificaties hieronder zijn de standaardverpakking; steellengte, bosgewicht en snijstadium kunnen op uw eigen programma worden afgestemd.",
 "17 Sorten auf einem Luftfrachtbrief. Die Angaben unten sind die Standardverpackung; Stiellänge, Bundgewicht und Schnittstadium lassen sich auf Ihr eigenes Programm einstellen."],
["Eucalyptus Baby Blue from JASM Flowers", "Eucalyptus Baby Blue van JASM Flowers", "Eucalyptus Baby Blue von JASM Flowers"],
["Blue green", "Blauwgroen", "Blaugrün"],
["Eucalyptus Silver Dollar from JASM Flowers", "Eucalyptus Silver Dollar van JASM Flowers", "Eucalyptus Silver Dollar von JASM Flowers"],
["Grey green", "Grijsgroen", "Graugrün"],
["Contract growing", "Contractteelt", "Vertragsanbau"],
["Supply programmes,<br>planted in advance", "Leveringsprogramma's,<br>vooraf geplant", "Lieferprogramme,<br>vorab gepflanzt"],
["A one-off order is checked against what our partners already have in the ground. A programme is the other way round: we agree the volume with the grower before the crop goes in, so the stems exist because you asked for them.",
 "Een losse order toetsen we aan wat onze partners al in de grond hebben staan. Een programma werkt andersom: we spreken het volume met de teler af voordat het gewas de grond in gaat, dus de stelen bestaan omdat u erom vroeg.",
 "Eine einzelne Bestellung gleichen wir mit dem ab, was unsere Partner bereits im Boden haben. Ein Programm läuft andersherum: Wir vereinbaren das Volumen mit dem Erzeuger, bevor die Kultur gesetzt wird, die Stiele existieren also, weil Sie danach gefragt haben."],
["Worth doing if you buy the same lines every week or every season. We plan it around the varieties you need, the volume you expect, stem lengths, your quality specification, the months you need cover and how often you want it delivered.",
 "De moeite waard als u elke week of elk seizoen dezelfde soorten koopt. We plannen het rond de soorten die u nodig hebt, het volume dat u verwacht, steellengtes, uw kwaliteitsspecificatie, de maanden waarin u dekking nodig hebt en hoe vaak u wilt laten leveren.",
 "Lohnt sich, wenn Sie jede Woche oder jede Saison dieselben Sorten kaufen. Wir planen es um die Sorten, die Sie brauchen, das erwartete Volumen, Stiellängen, Ihre Qualitätsspezifikation, die Monate, in denen Sie Abdeckung brauchen, und die gewünschte Lieferhäufigkeit."],
["The point is a price and a plan that work at both ends of the chain. A grower who knows the offtake plants better than a grower selling into a spot market.",
 "Het doel is een prijs en een planning die aan beide kanten van de keten werken. Een teler die zijn afzet kent, plant beter dan een teler die op de dagmarkt verkoopt.",
 "Es geht um einen Preis und eine Planung, die an beiden Enden der Kette funktionieren. Ein Erzeuger, der seine Abnahme kennt, plant besser als einer, der auf den Tagesmarkt verkauft."],
["Talk about a programme", "Praat over een programma", "Über ein Programm sprechen"],
["Importers, wholesalers, floral distributors, florists, bouquet producers and retail flower businesses. Europe takes most of the volume; the rest travels further.",
 "Importeurs, groothandels, bloemendistributeurs, bloemisten, boeketmakers en retailbedrijven. Europa neemt het grootste deel van het volume af; de rest reist verder.",
 "Importeure, Großhändler, Blumendistributoren, Floristen, Bouquetbetriebe und Blumeneinzelhandel. Europa nimmt den größten Teil des Volumens ab, der Rest reist weiter."],
["Where we are going: to be the Kenyan supply partner buyers worldwide keep coming back to, on long-term relationships rather than one-off shipments.",
 "Waar we naartoe werken: de Keniaanse leverancier zijn waar inkopers wereldwijd naar terugkeren, op langetermijnrelaties in plaats van losse zendingen.",
 "Wohin wir wollen: der kenianische Lieferpartner sein, zu dem Einkäufer weltweit zurückkommen, auf Basis langfristiger Beziehungen statt einzelner Sendungen."],
["<b>Quality is not only the flower.</b> It is also a specification that says what you are actually getting, accurate information when something changes, and an answer from the same person between the first quotation and the shipment landing.",
 "<b>Kwaliteit is niet alleen de bloem.</b> Het is ook een specificatie die zegt wat u werkelijk krijgt, kloppende informatie als er iets verandert, en antwoord van dezelfde persoon tussen de eerste offerte en de aankomst van de zending.",
 "<b>Qualität ist nicht nur die Blume.</b> Sie ist auch eine Spezifikation, die sagt, was Sie tatsächlich bekommen, verlässliche Information, wenn sich etwas ändert, und eine Antwort von derselben Person zwischen dem ersten Angebot und der Ankunft der Sendung."],
["Send the varieties, stem lengths, quantities, how often you want them and where they have to land. We check availability with our growing partners and come back with a written price inside one working day.",
 "Stuur de soorten, steellengtes, aantallen, hoe vaak u ze wilt en waar ze moeten landen. Wij checken de beschikbaarheid bij onze telerpartners en komen binnen een werkdag terug met een schriftelijke prijs.",
 "Schicken Sie Sorten, Stiellängen, Mengen, die gewünschte Häufigkeit und den Zielort. Wir prüfen die Verfügbarkeit bei unseren Erzeugerpartnern und melden uns innerhalb eines Werktages mit einem schriftlichen Preis."],
["Who you are", "Wie u bent", "Wer Sie sind"],
["e.g. weekly, or a one-off trial", "bijv. wekelijks, of een eenmalige proef", "z. B. wöchentlich oder ein einmaliger Test"],
["17 lines, one airway bill. Stem lengths, bunch and box specs, and month by month availability for the full programme.",
 "17 soorten, een vrachtbrief. Steellengtes, bos- en doosspecificaties en beschikbaarheid per maand voor het hele programma.",
 "17 Sorten, ein Luftfrachtbrief. Stiellängen, Bund- und Kistenangaben sowie die Verfügbarkeit Monat für Monat für das ganze Programm."],
["Full specification, all 17 lines", "Volledige specificatie, alle 17 soorten", "Vollständige Spezifikation, alle 17 Sorten"],
["<b>Eucalyptus Baby Blue</b>", "<b>Eucalyptus Baby Blue</b>", "<b>Eucalyptus Baby Blue</b>"],
["<b>Eucalyptus Silver Dollar</b>", "<b>Eucalyptus Silver Dollar</b>", "<b>Eucalyptus Silver Dollar</b>"],
["Key flowers", "Kernbloemen", "Kernblumen"],
["Solidago, eucalyptus and limonium", "Solidago, eucalyptus en limonium", "Solidago, Eukalyptus und Limonium"],
["Solidago, Eucalyptus Baby Blue and Eucalyptus Silver Dollar are our key flowers. Limonium runs alongside them as a core programme line.",
 "Solidago, Eucalyptus Baby Blue en Eucalyptus Silver Dollar zijn onze kernbloemen. Limonium loopt daarnaast mee als vaste programmalijn.",
 "Solidago, Eucalyptus Baby Blue und Eucalyptus Silver Dollar sind unsere Kernblumen. Limonium läuft daneben als feste Programmlinie mit."],
["Eucalyptus cinerea &middot; Baby Blue", "Eucalyptus cinerea &middot; Baby Blue", "Eucalyptus cinerea &middot; Baby Blue"],
["Eucalyptus polyanthemos &middot; Silver Dollar", "Eucalyptus polyanthemos &middot; Silver Dollar", "Eucalyptus polyanthemos &middot; Silver Dollar"],
];

for (const [code, idx] of [['nl', 1], ['de', 2]]) {
  const f = `src/lang/${code}.tsv`;
  const have = new Set(fs.readFileSync(f, 'utf8').split(/\r?\n/)
    .map(l => l.slice(0, l.indexOf('\t')).trim()).filter(Boolean));
  const add = P.filter(p => !have.has(p[0])).map(p => `${p[0]}\t${p[idx]}`);
  if (add.length) fs.appendFileSync(f, add.join('\n') + '\n');
  console.log(`${code}: +${add.length}`);
}
