import { chromium } from 'playwright';
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
const ROOT=path.resolve(path.dirname(new URL(import.meta.url).pathname).replace(/^\/([A-Za-z]:)/,'$1'),'..');
const DIST=path.join(ROOT,'dist'),OUT=path.join(ROOT,'shots');
const T={'.html':'text/html','.css':'text/css','.js':'text/javascript','.webp':'image/webp','.jpg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml','.woff2':'font/woff2'};
const server=http.createServer((q,r)=>{let p=decodeURIComponent(q.url.split('?')[0]);let f=path.join(DIST,p);if(p.endsWith('/'))f=path.join(f,'index.html');if(!fs.existsSync(f)){r.writeHead(404);return r.end('x')}r.writeHead(200,{'content-type':T[path.extname(f)]||'application/octet-stream'});r.end(fs.readFileSync(f))});
await new Promise(r=>server.listen(0,r));
const base=`http://127.0.0.1:${server.address().port}`;
const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:794,height:1123},deviceScaleFactor:1.6});
const p=await ctx.newPage();
await p.goto(base+'/catalogue-sheet/',{waitUntil:'load'});
await p.evaluate(()=>[...document.images].forEach(i=>{i.loading='eager'}));
await p.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0),null,{timeout:60000});
await p.waitForTimeout(1200);
const pages=await p.$$('.page');
for (const i of [0,1]) await pages[i].screenshot({path:path.join(OUT,'_sheet'+i+'.png')});
await b.close();server.close();
console.log('ok');
