import sharp from 'sharp';
import { readdir, stat, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';

const manifest: Record<string, number[]> = {};

const PUBLIC = path.resolve(process.cwd(), 'public');
const WEBP_QUALITY = 80;
const AVIF_QUALITY = 60;
const WIDTHS = [480, 960, 1600];
const SRC_EXT = /\.(jpe?g|png|webp)$/i;
const LADDER_SUFFIX = /-(?:480|960|1600)\.(?:webp|avif)$/i;
const SKIP = new Set(['favicon-64.png', 'apple-touch-icon.png', 'og.webp']);

function human(size: number): string {
  if (size > 1024 * 1024) return (size / 1024 / 1024).toFixed(2) + ' MB';
  return (size / 1024).toFixed(0) + ' KB';
}

async function processOne(dir: string, file: string) {
  if (LADDER_SUFFIX.test(file) || SKIP.has(file)) return;
  const full = path.join(dir, file);
  const before = (await stat(full)).size;
  const meta = await sharp(full).metadata();
  const srcWidth = meta.width ?? 0;
  if (!srcWidth) return;

  const base = file.replace(SRC_EXT, '');
  const ladder: number[] = [];
  for (const w of WIDTHS) {
    if (w < srcWidth) ladder.push(w);
  }
  ladder.push(Math.min(srcWidth, WIDTHS[WIDTHS.length - 1]));

  const outputs: string[] = [];
  for (const w of ladder) {
    const webpOut = path.join(dir, `${base}-${w}.webp`);
    const avifOut = path.join(dir, `${base}-${w}.avif`);
    const pipeline = sharp(full).rotate().resize({ width: w, withoutEnlargement: true });
    await pipeline.clone().webp({ quality: WEBP_QUALITY, effort: 6, smartSubsample: true }).toFile(webpOut);
    await pipeline.clone().avif({ quality: AVIF_QUALITY, effort: 6 }).toFile(avifOut);
    const wSize = (await stat(webpOut)).size;
    const aSize = (await stat(avifOut)).size;
    outputs.push(`${w}w webp ${human(wSize)} / avif ${human(aSize)}`);
  }
  const rel = path.relative(PUBLIC, full);
  console.log(`  ${rel.padEnd(40)} ${human(before)} -> ${outputs.join('  ')}`);
  await unlink(full);

  // Manifest key: "/path/to/name" (no extension), value: emitted widths sorted asc.
  const relBase = path.posix.join('/', path.relative(PUBLIC, dir).split(path.sep).join('/'), base);
  manifest[relBase] = ladder;
}

async function walk(dir: string): Promise<void> {
  let entries: string[] = [];
  try {
    entries = await readdir(dir);
  } catch {
    return;
  }
  const subdirs: string[] = [];
  const targets: string[] = [];
  for (const e of entries) {
    const full = path.join(dir, e);
    const s = await stat(full);
    if (s.isDirectory()) subdirs.push(full);
    else if (SRC_EXT.test(e) && !LADDER_SUFFIX.test(e) && !SKIP.has(e)) targets.push(e);
  }
  if (targets.length) {
    console.log(`\n${path.relative(PUBLIC, dir) || '.'}: ${targets.length} files`);
    for (const file of targets.sort()) {
      try {
        await processOne(dir, file);
      } catch (err) {
        console.error(`  ! ${file}: ${(err as Error).message}`);
      }
    }
  }
  for (const sub of subdirs) await walk(sub);
}

async function main() {
  await walk(PUBLIC);
  const manifestPath = path.resolve(process.cwd(), 'src/image-manifest.ts');
  const lines = Object.keys(manifest)
    .sort()
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(manifest[k])},`)
    .join('\n');
  await writeFile(
    manifestPath,
    `// Auto-generated by scripts/optimize-images.ts. Do not edit by hand.\nexport const imageWidths: Record<string, readonly number[]> = {\n${lines}\n};\n`,
    'utf8',
  );
  console.log(`\nManifest -> ${path.relative(process.cwd(), manifestPath)} (${Object.keys(manifest).length} entries)`);
  console.log('Done.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
